### ISSUE TITLE
setup() can't take dictionary as keyword arguments

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#1]
Originally reported by: **Anonymous**

----------------------------------------

If I pass a dictionary 
    
    setup_args = {... ,'options' = {'build_exe'=...},'cible'  = [ Executable(...) ]}
    
    setup(**setup_args)
    
It's failed : 
    
    Traceback (most recent call last):
      File "setup.py", line 60, in <module>
        setup(* *setup_args)
      File "C:Python27libsite-packagescx_Freezedist.py", line 359, in setup
        distutils.core.setup(**attrs)
      File "C:Python27libdistutilscore.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "C:Python27libsite-packagescx_Freezedist.py", line 23, in __init__
        distutils.dist.Distribution.__init__(self, attrs)
      File "C:Python27libdistutilsdist.py", line 241, in __init__
        for (command, cmd_options) in options.items():
    AttributeError: 'tuple' object has no attribute 'items'
    

But if I pass cx_freeze specials arguments outside of the dict :

    
    setup(options = {'build_exe'=...},cible=[ Executable(...) ], **setup_args)
    
it's work.

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/1

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anthony Tuininga (Bitbucket: [anthony_tuininga](https://bitbucket.org/anthony_tuininga), GitHub: Unknown)**:

----------------------------------------

I followed your instructions as best as I could and was unable to duplicate your issue. If you can provide the exact source that you used that is causing the problem, that would be appreciated and I'll re-examine the issue. Until then I am going to mark it as invalid.
