### ISSUE TITLE
An attempt was made to load a program with an incorrect format

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#103]
Originally reported by: **Anonymous**

----------------------------------------

When I have PyQT installed I get the following traceback. Without it installed the build completes but fails at runtime as PyQT is not installed.

My system is Win7(32 bit). Python 2.7.8, Pyqt 4.11.1 QT 4.8.3. cx_Freeze 4.3.3.

Do you have any hints as to what is going wrong. I know some else has managed to build this app on a 32 bit windows.

```
#!bash

m encodings.iso2022_jp_ext
m encodings.iso2022_kr
m encodings.iso8859_1
m encodings.iso8859_10
m encodings.iso8859_11
...
m xml.parsers.expat         C:\Python27\lib\xml\parsers\expat.py
m zipimport
m zlib

Missing modules:
? ElementC14N imported from xml.etree.ElementTree
? ElementTree imported from PyQt4.uic.uiparser
? PyQt4.elementtree.ElementTree imported from PyQt4.uic.uiparser
? PyQt4.uic.port_v3.proxy_base imported from PyQt4.uic.Compiler.qtproxies
........
? termios imported from getpass
This is not necessarily a problem - the modules may not be needed on this platfo
rm.

copying C:\Python27\lib\site-packages\PyQt4\QtCore.pyd -> build\exe.win32-2.7\Py
Qt4.QtCore.pyd
.....
copying C:\Python27\lib\site-packages\PyQt4\SSLEAY32.dll -> build\exe.win32-2.7\SSLEAY32.dll
copying C:\Python27\lib\site-packages\PyQt4\QtWebKit.pyd -> build\exe.win32-2.7\PyQt4.QtWebKit.pyd
copying C:\Python27\lib\site-packages\PyQt4\QtWebKit4.dll -> build\exe.win32-2.7\QtWebKit4.dll
copying C:\Python27\lib\site-packages\PyQt4\uic\port_v3\proxy_base.py -> build\exe.win32-2.7\PyQt4.uic.port_v3.proxy_base.py
Traceback (most recent call last):
  File "build.py", line 43, in <module>
    Executable("ngccc-cli.py", base=base, targetName=mangle_target_name("cw-cli")),
  File "C:\Python27\lib\site-packages\cx_Freeze\dist.py", line 362, in setup
    distutils.core.setup(**attrs)
  File "C:\Python27\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python27\lib\distutils\command\build.py", line 127, in run
    self.run_command(cmd_name)
  File "C:\Python27\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python27\lib\site-packages\cx_Freeze\dist.py", line 232, in run
    freezer.Freeze()
  File "C:\Python27\lib\site-packages\cx_Freeze\freezer.py", line 610, in Freeze
    self.compress, self.copyDependentFiles)
  File "C:\Python27\lib\site-packages\cx_Freeze\freezer.py", line 588, in _WriteModules
    self._CopyFile(module.file, target, copyDependentFiles)
  File "C:\Python27\lib\site-packages\cx_Freeze\freezer.py", line 143, in _CopyFile
    for source in self._GetDependentFiles(source):
  File "C:\Python27\lib\site-packages\cx_Freeze\freezer.py", line 263, in _GetDependentFiles
    dependentFiles = cx_Freeze.util.GetDependentFiles(path)
cx_Freeze.util.BindError: (11, 'An attempt was made to load a program with an incorrect format', 'C:\\Python27\\lib\\site-packages\\PyQt4\\uic\\port_v3\\proxy_b
ase.py')

Z:\ngcccbase>

```

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/103

**Comment by anthony-tuininga** [comment]
*Original comment by* **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**:

----------------------------------------

I think this is the same as issue #88. It should be fixed by pull request #56.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anonymous**:

----------------------------------------

I think you are right. Renaming port_v3 folder sidestepped the issue for me. I will check next time I am working on the project. Will close the issue for now.

**Comment by anthony-tuininga** [comment]
*Original comment by* **fabiofz (Bitbucket: [fabiofz](https://bitbucket.org/fabiofz), GitHub: Unknown)**:

----------------------------------------

I see that this has been fixed for some time already, yet, I've just stumbled over this same error... and noted that the currently pip-installable version of cx_Freeze is still 4.3.3 from May... is there some plan for a new release version of cx_Freeze?

Thanks.
