### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'python3.8/site-packages/packaging-20.3.dist-info/__pycache__'

### ISSUE THREAD

**Issue by Erriez** [marcelotduarte/cx_Freeze#1034]
**Describe the bug**
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/src/venv/lib/python3.8/site-packages/packaging-20.3.dist-info/__pycache__'
```

**To Reproduce**
Follow documentation: 
- Installation: https://cx-freeze.readthedocs.io/en/latest/installation.html
- Script: https://cx-freeze.readthedocs.io/en/latest/script.html

```bash
# Install system dependencies
$ sudo apt install python3-virtualenv patchelf

# Setup virtualenv
$ mkdir ~/src
$ cd ~/src
$ virtualenv venv
$ source venv/bin/activate
$ pip install --upgrade cx_Freeze

# Create test Python file
$ echo "print('Hello world!')" > hello.py
$ python hello.py
Hello World!

# Run cx_Freeze as separate command
$ cxfreeze -c hello.py --target-dir dist
Traceback (most recent call last):
  File "/home/user/src/venv/bin/cxfreeze", line 8, in <module>
    sys.exit(main())
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/cli.py", line 262, in main
    freezer.Freeze()
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/freezer.py", line 795, in Freeze
    self.finder: ModuleFinder = self._GetModuleFinder()
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/freezer.py", line 464, in _GetModuleFinder
    finder = ModuleFinder(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 70, in __init__
    self._add_base_modules()
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 82, in _add_base_modules
    self.IncludeModule("traceback")
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 676, in IncludeModule
    module = self._import_module(name, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 257, in _import_module
    module = self._internal_import_module(name, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 347, in _internal_import_module
    module = self._load_module(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 458, in _load_module
    self._scan_code(module.code, module, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 581, in _scan_code
    imported_module = self._import_module(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 257, in _import_module
    module = self._internal_import_module(name, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 347, in _internal_import_module
    module = self._load_module(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 458, in _load_module
    self._scan_code(module.code, module, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 581, in _scan_code
    imported_module = self._import_module(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 257, in _import_module
    module = self._internal_import_module(name, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 347, in _internal_import_module
    module = self._load_module(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 458, in _load_module
    self._scan_code(module.code, module, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 615, in _scan_code
    self._scan_code(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 615, in _scan_code
    self._scan_code(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 581, in _scan_code
    imported_module = self._import_module(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 257, in _import_module
    module = self._internal_import_module(name, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 347, in _internal_import_module
    module = self._load_module(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 458, in _load_module
    self._scan_code(module.code, module, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 615, in _scan_code
    self._scan_code(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 615, in _scan_code
    self._scan_code(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 581, in _scan_code
    imported_module = self._import_module(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 257, in _import_module
    module = self._internal_import_module(name, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 347, in _internal_import_module
    module = self._load_module(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 458, in _load_module
    self._scan_code(module.code, module, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 615, in _scan_code
    self._scan_code(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 581, in _scan_code
    imported_module = self._import_module(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 257, in _import_module
    module = self._internal_import_module(name, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 347, in _internal_import_module
    module = self._load_module(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 458, in _load_module
    self._scan_code(module.code, module, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 581, in _scan_code
    imported_module = self._import_module(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 257, in _import_module
    module = self._internal_import_module(name, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 347, in _internal_import_module
    module = self._load_module(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 458, in _load_module
    self._scan_code(module.code, module, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 615, in _scan_code
    self._scan_code(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 581, in _scan_code
    imported_module = self._import_module(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 257, in _import_module
    module = self._internal_import_module(name, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 347, in _internal_import_module
    module = self._load_module(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 458, in _load_module
    self._scan_code(module.code, module, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 581, in _scan_code
    imported_module = self._import_module(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 257, in _import_module
    module = self._internal_import_module(name, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 321, in _internal_import_module
    self._run_hook("load", module.name, module)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 548, in _run_hook
    method(self, *args)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/hooks.py", line 1229, in load_time
    finder.IncludeModule("_strptime")
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 676, in IncludeModule
    module = self._import_module(name, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 257, in _import_module
    module = self._internal_import_module(name, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 347, in _internal_import_module
    module = self._load_module(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 458, in _load_module
    self._scan_code(module.code, module, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 581, in _scan_code
    imported_module = self._import_module(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 257, in _import_module
    module = self._internal_import_module(name, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 347, in _internal_import_module
    module = self._load_module(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 458, in _load_module
    self._scan_code(module.code, module, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 615, in _scan_code
    self._scan_code(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 581, in _scan_code
    imported_module = self._import_module(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 257, in _import_module
    module = self._internal_import_module(name, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 347, in _internal_import_module
    module = self._load_module(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 458, in _load_module
    self._scan_code(module.code, module, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 615, in _scan_code
    self._scan_code(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 615, in _scan_code
    self._scan_code(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 581, in _scan_code
    imported_module = self._import_module(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 257, in _import_module
    module = self._internal_import_module(name, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 347, in _internal_import_module
    module = self._load_module(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 458, in _load_module
    self._scan_code(module.code, module, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 615, in _scan_code
    self._scan_code(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 581, in _scan_code
    imported_module = self._import_module(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 257, in _import_module
    module = self._internal_import_module(name, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 347, in _internal_import_module
    module = self._load_module(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 458, in _load_module
    self._scan_code(module.code, module, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 581, in _scan_code
    imported_module = self._import_module(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 257, in _import_module
    module = self._internal_import_module(name, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 347, in _internal_import_module
    module = self._load_module(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 458, in _load_module
    self._scan_code(module.code, module, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 590, in _scan_code
    self._ensure_from_list(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 157, in _ensure_from_list
    self._import_module(sub_module_name, deferred_imports, caller)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 257, in _import_module
    module = self._internal_import_module(name, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 347, in _internal_import_module
    module = self._load_module(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 458, in _load_module
    self._scan_code(module.code, module, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 590, in _scan_code
    self._ensure_from_list(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 157, in _ensure_from_list
    self._import_module(sub_module_name, deferred_imports, caller)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 257, in _import_module
    module = self._internal_import_module(name, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 347, in _internal_import_module
    module = self._load_module(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 458, in _load_module
    self._scan_code(module.code, module, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 581, in _scan_code
    imported_module = self._import_module(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 291, in _import_module
    module = self._internal_import_module(name, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 347, in _internal_import_module
    module = self._load_module(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 458, in _load_module
    self._scan_code(module.code, module, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 615, in _scan_code
    self._scan_code(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 615, in _scan_code
    self._scan_code(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 581, in _scan_code
    imported_module = self._import_module(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 257, in _import_module
    module = self._internal_import_module(name, deferred_imports)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 347, in _internal_import_module
    module = self._load_module(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 424, in _load_module
    module = self._add_module(name, file_name=path, parent=parent)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/finder.py", line 107, in _add_module
    module = Module(
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/module.py", line 58, in __init__
    self._cache_dist_info(req_name)
  File "/home/user/src/venv/lib/python3.8/site-packages/cx_Freeze/module.py", line 76, in _cache_dist_info
    shutil.copyfile(str(file.locate()), dist_path)
  File "/usr/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/src/venv/lib/python3.8/site-packages/packaging-20.3.dist-info/__pycache__'
```

**Expected behavior**
No errors.

**Desktop (please complete the following information):**
 - Platform information: Ubuntu Linux 20.04 (Clean installation, all updates of today installed)
 - OS architecture: amd64
 - cx_Freeze version: v6.6:
 - Python version: 3.8:

**Additional context**
Same output when creating a `setup.py` file and running `python setup.py build`.

**Comment by marcelotduarte** [comment]
For me its works! I use ubuntu 20.10 but in CI it is tested in Ubuntu 20.04
In general I use venv to test (python3 -m venv) not virtualenv, but installed it here and tested with your sample (the echo line has a error, but ok). and its works too.
Obviously, my installation is not a clean install.
But I'll create a check to ignore unnecessary directories like pycache. Do you use some option to install python with compiled libraries?

**Comment by Erriez** [comment]
@marcelotduarte Thanks for your fast reply. 

> In general I use venv to test (python3 -m venv) not virtualenv, 

I did not notice any differences.

> Do you use some option to install python with compiled libraries?

I did not install compiled libraries myself, but I'm not 100% if this is done under water via another project.

I've installed a fresh Ubuntu 21.04 in VirtualBox and works out of the box. Same procedure. (I've removed the "!" in the echo)

**Comment by marcelotduarte** [comment]
cx_Freeze 6.7 has just been released.
