### ISSUE TITLE
getting error when running cx_Freeze 

### ISSUE THREAD

**Issue by coolprat999** [marcelotduarte/cx_Freeze#1039]
Hi,

I am running below ansible task but its giving error as below. 

```yaml
- name: check and verify curator dependeancies
  shell: |
     {{ python }} --version
     {{ pip }} --version
     cd  {{ curator_home }}
     {{ python }} setup.py install
```

**Error** - 

```
TASK [curator : check and verify curator dependeancies] ****************************************************************************************************************
fatal: [elasticsearch_1]: FAILED! => {
    "changed": true,
    "cmd": "/root/virtualenv/bin/python3 --version\n/root/virtualenv/bin/pip3 --version\ncd  /opt/curator-5.8.1/\n/root/virtualenv/bin/python3 setup.py install\n",
    "delta": "0:00:00.874014",
    "end": "2021-04-29 20:49:30.602140",
    "rc": 1,
    "start": "2021-04-29 20:49:29.728126"
}

STDOUT:

Python 3.6.8
pip 21.1 from /root/virtualenv/lib64/python3.6/site-packages/pip (python 3.6)
running install
running build
running build_py
creating build
creating build/lib
creating build/lib/curator
copying curator/singletons.py -> build/lib/curator
copying curator/actions.py -> build/lib/curator
copying curator/snapshotlist.py -> build/lib/curator
copying curator/config_utils.py -> build/lib/curator
copying curator/_version.py -> build/lib/curator
copying curator/repomgrcli.py -> build/lib/curator
copying curator/__main__.py -> build/lib/curator
copying curator/utils.py -> build/lib/curator
copying curator/indexlist.py -> build/lib/curator
copying curator/curator_cli.py -> build/lib/curator
copying curator/logtools.py -> build/lib/curator
copying curator/cli.py -> build/lib/curator
copying curator/exceptions.py -> build/lib/curator
copying curator/__init__.py -> build/lib/curator
running egg_info
creating elasticsearch_curator.egg-info
writing elasticsearch_curator.egg-info/PKG-INFO
writing dependency_links to elasticsearch_curator.egg-info/dependency_links.txt
writing entry points to elasticsearch_curator.egg-info/entry_points.txt
writing requirements to elasticsearch_curator.egg-info/requires.txt
writing top-level names to elasticsearch_curator.egg-info/top_level.txt
writing manifest file 'elasticsearch_curator.egg-info/SOURCES.txt'
reading manifest file 'elasticsearch_curator.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'elasticsearch_curator.egg-info/SOURCES.txt'
creating build/lib/curator/cli_singletons
copying curator/cli_singletons/__init__.py -> build/lib/curator/cli_singletons
copying curator/cli_singletons/alias.py -> build/lib/curator/cli_singletons
copying curator/cli_singletons/allocation.py -> build/lib/curator/cli_singletons
copying curator/cli_singletons/close.py -> build/lib/curator/cli_singletons
copying curator/cli_singletons/delete.py -> build/lib/curator/cli_singletons
copying curator/cli_singletons/forcemerge.py -> build/lib/curator/cli_singletons
copying curator/cli_singletons/freeze.py -> build/lib/curator/cli_singletons
copying curator/cli_singletons/object_class.py -> build/lib/curator/cli_singletons
copying curator/cli_singletons/open_indices.py -> build/lib/curator/cli_singletons
copying curator/cli_singletons/replicas.py -> build/lib/curator/cli_singletons
copying curator/cli_singletons/restore.py -> build/lib/curator/cli_singletons
copying curator/cli_singletons/rollover.py -> build/lib/curator/cli_singletons
copying curator/cli_singletons/show.py -> build/lib/curator/cli_singletons
copying curator/cli_singletons/shrink.py -> build/lib/curator/cli_singletons
copying curator/cli_singletons/snapshot.py -> build/lib/curator/cli_singletons
copying curator/cli_singletons/unfreeze.py -> build/lib/curator/cli_singletons
copying curator/cli_singletons/utils.py -> build/lib/curator/cli_singletons
creating build/lib/curator/defaults
copying curator/defaults/__init__.py -> build/lib/curator/defaults
copying curator/defaults/client_defaults.py -> build/lib/curator/defaults
copying curator/defaults/filter_elements.py -> build/lib/curator/defaults
copying curator/defaults/filtertypes.py -> build/lib/curator/defaults
copying curator/defaults/option_defaults.py -> build/lib/curator/defaults
copying curator/defaults/settings.py -> build/lib/curator/defaults
creating build/lib/curator/validators
copying curator/validators/__init__.py -> build/lib/curator/validators
copying curator/validators/actions.py -> build/lib/curator/validators
copying curator/validators/config_file.py -> build/lib/curator/validators
copying curator/validators/filters.py -> build/lib/curator/validators
copying curator/validators/options.py -> build/lib/curator/validators
copying curator/validators/schemacheck.py -> build/lib/curator/validators
running build_exe


STDERR:

/root/virtualenv/lib64/python3.6/site-packages/cx_Freeze/common.py:129: UserWarning: camelCase values is obsolete and will be removed in the next major version -> use the new name 'target_name'
  "camelCase values is obsolete and will be removed in the "
warning: no files found matching 'Changelog.rst'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
warning: no previously-included files matching '*.pyo' found under directory 'curator'
warning: no previously-included files matching '*.pyc' found under directory 'docs'
warning: no previously-included files matching '*.pyo' found under directory 'docs'
warning: no previously-included files matching '*.pyc' found under directory 'test'
warning: no previously-included files matching '*.pyo' found under directory 'test'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'docs/asciidoc/html_docs'
Traceback (most recent call last):
  File "setup.py", line 140, in <module>
    executables = [curator_exe,curator_cli_exe,repomgr_exe]
  File "/root/virtualenv/lib64/python3.6/site-packages/cx_Freeze/dist.py", line 397, in setup
    distutils.core.setup(**attrs)
  File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib64/python3.6/distutils/command/install.py", line 556, in run
    self.run_command('build')
  File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib64/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/root/virtualenv/lib64/python3.6/site-packages/cx_Freeze/dist.py", line 260, in run
    zipExcludePackages=self.zip_exclude_packages,
  File "/root/virtualenv/lib64/python3.6/site-packages/cx_Freeze/freezer.py", line 88, in __init__
    self._VerifyConfiguration()
  File "/root/virtualenv/lib64/python3.6/site-packages/cx_Freeze/freezer.py", line 551, in _VerifyConfiguration
    self.patchelf = Patchelf()
  File "/root/virtualenv/lib64/python3.6/site-packages/cx_Freeze/patchelf.py", line 15, in __init__
    _verify_patchelf()
  File "/root/virtualenv/lib64/python3.6/site-packages/cx_Freeze/patchelf.py", line 52, in _verify_patchelf
    raise ValueError("Cannot find required utility `patchelf` in PATH")
ValueError: Cannot find required utility `patchelf` in PATH
```

I have created  `venv`  (virtualenv) and have set below variables in ansible. 

```
Python 3.6.8
pip 21.1 from /root/virtualenv/lib64/python3.6/site-packages/pip (python 3.6)
```

as i understood its trying to run below script, 

```
# cat setup.py
import os
import re
import sys
from setuptools import setup

# Utility function to read from file.
def fread(fname):
    return open(os.path.join(os.path.dirname(__file__), fname)).read()

def get_version():
    VERSIONFILE="curator/_version.py"
    verstrline = fread(VERSIONFILE).strip()
    vsre = r"^__version__ = ['\"]([^'\"]*)['\"]"
    mo = re.search(vsre, verstrline, re.M)
    if mo:
        VERSION = mo.group(1)
    else:
        raise RuntimeError("Unable to find version string in %s." % (VERSIONFILE,))
    build_number = os.environ.get('CURATOR_BUILD_NUMBER', None)
    if build_number:
        return VERSION + "b{}".format(build_number)
    return VERSION

def get_install_requires():
    res = ['elasticsearch>=7.0.4,<8.0.0' ]
    res.append('urllib3>=1.24.2,<1.25')
    res.append('requests>=2.20.0')
    res.append('boto3>=1.9.142')
    res.append('requests_aws4auth>=0.9')
    res.append('click>=6.7,<7.0')
    res.append('pyyaml==3.13')
    res.append('voluptuous>=0.9.3')
    res.append('certifi>=2019.9.11')
    res.append('six>=1.11.0')
    return res

try:
    ### cx_Freeze ###
    from cx_Freeze import setup, Executable
    try:
        import certifi
        cert_file = certifi.where()
    except ImportError:
        cert_file = ''
    # Dependencies are automatically detected, but it might need
    # fine tuning.


    base = 'Console'

    icon = None
    if os.path.exists('Elastic.ico'):
        icon = 'Elastic.ico'

    curator_exe = Executable(
        "run_curator.py",
        base=base,
        targetName = "curator",
    )
    curator_cli_exe = Executable(
        "run_singleton.py",
        base=base,
        targetName = "curator_cli",
    )
    repomgr_exe = Executable(
        "run_es_repo_mgr.py",
        base=base,
        targetName = "es_repo_mgr",
    )
    buildOptions = dict(
        packages = [],
        excludes = [],
        include_files = [cert_file],
    )

    if sys.platform == "win32":
        curator_exe = Executable(
            "run_curator.py",
            base=base,
            targetName = "curator.exe",
            icon = icon
        )
        curator_cli_exe = Executable(
            "run_singleton.py",
            base=base,
            targetName = "curator_cli.exe",
            icon = icon
        )
        repomgr_exe = Executable(
            "run_es_repo_mgr.py",
            base=base,
            targetName = "es_repo_mgr.exe",
            icon = icon
        )

        msvcrt = 'vcruntime140.dll'
        buildOptions = dict(
            packages = [],
            excludes = [],
            include_files = [cert_file, msvcrt],
            include_msvcr = True,
        )

    setup(
        name = "elasticsearch-curator",
        version = get_version(),
        author = "Elastic",
        author_email = "info@elastic.co",
        description = "Tending your Elasticsearch indices",
        long_description=fread('README.rst'),
        url = "http://github.com/elastic/curator",
        download_url = "https://github.com/elastic/curator/tarball/v" + get_version(),
        license = "Apache License, Version 2.0",
        install_requires = get_install_requires(),
        setup_requires = get_install_requires(),
        keywords = "elasticsearch time-series indexed index-expiry",
        packages = ["curator"],
        include_package_data=True,
        entry_points = {
            "console_scripts" : [
                "curator = curator.cli:cli",
                "curator_cli = curator.curator_cli:main",
                "es_repo_mgr = curator.repomgrcli:repo_mgr_cli",
            ]
        },
        classifiers=[
            "Intended Audience :: Developers",
            "Intended Audience :: System Administrators",
            "License :: OSI Approved :: Apache Software License",
            "Operating System :: OS Independent",
            "Programming Language :: Python",
            "Programming Language :: Python :: 2.7",
            "Programming Language :: Python :: 3.5",
            "Programming Language :: Python :: 3.6",
            "Programming Language :: Python :: 3.7",
        ],
        test_suite = "test.run_tests.run_all",
        tests_require = ["mock", "nose", "coverage", "nosexcover"],
        options = {"build_exe" : buildOptions},
        executables = [curator_exe,curator_cli_exe,repomgr_exe]
    )
    ### end cx_Freeze ###
except ImportError:
    setup(
        name = "elasticsearch-curator",
        version = get_version(),
        author = "Elastic",
        author_email = "info@elastic.co",
        description = "Tending your Elasticsearch indices",
        long_description=fread('README.rst'),
        url = "http://github.com/elastic/curator",
        download_url = "https://github.com/elastic/curator/tarball/v" + get_version(),
        license = "Apache License, Version 2.0",
        install_requires = get_install_requires(),
        keywords = "elasticsearch time-series indexed index-expiry",
        packages = ["curator"],
        include_package_data=True,
        entry_points = {
            "console_scripts" : [
                "curator = curator.cli:cli",
                "curator_cli = curator.curator_cli:main",
                "es_repo_mgr = curator.repomgrcli:repo_mgr_cli",
            ]
        },
        classifiers=[
            "Intended Audience :: Developers",
            "Intended Audience :: System Administrators",
            "License :: OSI Approved :: Apache Software License",
            "Operating System :: OS Independent",
            "Programming Language :: Python",
            "Programming Language :: Python :: 2.7",
            "Programming Language :: Python :: 3.5",
            "Programming Language :: Python :: 3.6",
            "Programming Language :: Python :: 3.7",
        ],
        test_suite = "test.run_tests.run_all",
        tests_require = ["mock", "nose", "coverage", "nosexcover"]
    )
```

I have installed below packages under `venv` in offline way. (no internet). Not sure if  `cx-Freeze ` is too latest compare to other packages and causing any issue.

```
# pip3 list
Package               Version
--------------------- ----------
APScheduler           3.6.3
attrs                 19.3.0
aws-requests-auth     0.4.2
blist                 1.3.6
boto3                 1.12.38
botocore              1.15.38
certifi               2020.4.5.1
cffi                  1.14.0
chardet               3.0.4
chardet2              2.0.3
click                 7.1.2
configparser          5.0.0
croniter              0.3.31
cryptography          3.4.7
cx-Freeze             6.6
defusedxml            0.6.0
docopt                0.6.2
docutils              0.15.2
elastalert            0.2.1
elasticsearch         7.12.0
elasticsearch7        7.6.0
envparse              0.2.0
exotel                0.1.5
future                0.18.2
idna                  2.9
importlib-metadata    4.0.1
itsdangerous          1.1.0
Jinja2                2.11.3
jira                  1.0.14
jmespath              0.9.5
jsonschema            2.6.0
MarkupSafe            1.1.1
mock                  4.0.2
oauthlib              3.1.0
pbr                   5.4.5
pip                   21.1
pycparser             2.20
PyJWT                 1.7.1
pyrsistent            0.16.0
PySocks               1.7.1
PyStaticConfiguration 0.10.4
python-dateutil       2.6.1
python-magic          0.4.15
pytz                  2019.3
PyYAML                3.13
requests              2.23.0
requests-aws4auth     1.0.0
requests-oauthlib     1.3.0
requests-toolbelt     0.9.1
s3transfer            0.3.3
setuptools            39.2.0
six                   1.14.0
stomp.py              6.0.0
texttable             1.6.2
thehive4py            1.6.0
twilio                6.0.0
typing-extensions     3.7.4.3
tzlocal               2.0.0
urllib3               1.25.8
voluptuous            0.11.7
Werkzeug              1.0.1
wheel                 0.34.2
zipp                  3.1.0
```
Can some please tell what is causing this issue?

Thanks,

**Comment by marcelotduarte** [comment]
> ValueError: Cannot find required utility `patchelf` in PATH

Please check the docs: https://cx-freeze.readthedocs.io/en/latest/installation.html#requirement-for-linux

**Comment by coolprat999** [comment]
I am not able to find patchelf rpm package for Redhat Linux.

**Comment by marcelotduarte** [comment]
It has for centos7, there must be for redhat.
https://centos.pkgs.org/7/epel-x86_64/patchelf-0.12-1.el7.x86_64.rpm.html

**Comment by coolprat999** [comment]
Thanks for your reply. I wil check again and confirm.

I am not sure if its really centos site.

**Comment by marcelotduarte** [comment]
The site is not centos site, but it show how to install using fedoraproject site:
Install Howto

    Download latest epel-release rpm from

    http://download-ib01.fedoraproject.org/pub/epel/7/x86_64/

    Install epel-release rpm:

    # rpm -Uvh epel-release*rpm

    Install patchelf rpm package:

    # yum install patchelf

**Comment by marcelotduarte** [comment]
Please confirm the method, so I can update the docs.

**Comment by coolprat999** [comment]
Currently I removed the `cx-freeze` as its only used for binary package creation as per below. I will let you know once I tired. 

May be till then you can put `patchelf` package installation as optional step if someone sees same issue.

https://github.com/elastic/curator/issues/1601#issuecomment-829570830

**Comment by marcelotduarte** [comment]
Documentation updated to inform how to install patchelf from sources.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.7 has just been released.
