### ISSUE TITLE
The 'flask-compress' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by europa502** [marcelotduarte/cx_Freeze#1041]
App crashes when I include flask-compress-

```
Traceback (most recent call last):
  File "C:\Users\menonAbhijit\AppData\Local\Programs\Python\Python39\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 81, in run
    module.run()
  File "C:\Users\menonAbhijit\AppData\Local\Programs\Python\Python39\lib\site-packages\cx_Freeze\initscripts\Console.py", line 36, in run
    exec(code, m.__dict__)
  File "strata.py", line 1, in <module>
  File "C:\Users\menonAbhijit\AppData\Local\Programs\Python\Python39\lib\site-packages\dash_core_components\__init__.py", line 6, in <module>
    import dash as _dash
  File "C:\Users\menonAbhijit\AppData\Local\Programs\Python\Python39\lib\site-packages\dash\__init__.py", line 5, in <module>
    from .dash import Dash, no_update  # noqa: F401,E402
  File "C:\Users\menonAbhijit\AppData\Local\Programs\Python\Python39\lib\site-packages\dash\dash.py", line 53, in <module>
    _flask_compress_version = parse_version(get_distribution("flask-compress").version)
  File "C:\Users\menonAbhijit\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 480, in get_distribution
    dist = get_provider(dist)
  File "C:\Users\menonAbhijit\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 356, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "C:\Users\menonAbhijit\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 899, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Users\menonAbhijit\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 785, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'flask-compress' distribution was not found and is required by the application

```
I'm using python 3.9 with cx_freeze 6.6.

This is the line that throws out error -
https://github.com/plotly/dash/blob/597dc22c86de97530fb9b0a9bd9f7876bd0d7601/dash/dash.py#L53
I went through this [issue](https://github.com/marcelotduarte/cx_Freeze/issues/438), but the merge made wasn't helpful. I had to end up the [workaround](https://github.com/marcelotduarte/cx_Freeze/issues/438#issuecomment-472954154) instead.

I tried adding 'flask_compress' in packages as well as includes, but I still got the error. 
Then I tried to add 'flask-compress' in those sections, but I encountered import error while building the app
At first, I thought it was because of pkg_resources checking for flask_compress and since its canonical name is different sometimes(Flask-Compress or flask-compress), maybe that would be causing the issue. But when I built the app with python3.6 it worked perfectly. I didn't require that workaround. 

I raised an issue in [dash](https://github.com/plotly/dash/issues/1606), but now I'm thinking maybe it is not their fault.
Furthermore, while going through the documentation, I realized that cx_freeze is experimental for python 3.9, and maybe that's why this problem exists.

**Comment by marcelotduarte** [comment]
Please try it with the new beta release.
cx_Freeze 6.7b8 has just been released.
pip install cx-Freeze==6.7b8

**Comment by marcelotduarte** [comment]
cx_Freeze 6.7 has just been released.

**Comment by europa502** [comment]
The issue is fixed. Thanks!!
