### ISSUE TITLE
[Bug]  ELF load command address/offset not properly aligned

### ISSUE THREAD

**Issue by mcauto** [marcelotduarte/cx_Freeze#1048]
I install pacakage after bdist_rpm.

example project: https://github.com/mcauto/cx-freeze-bdist-rpm-example

```bash
# host
$ git clone https://github.com/mcauto/cx-freeze-bdist-rpm-example
$ cd cx-freeze-bdist-rpm-example
$ docker-compose up --build -d
$ docker exec -it build-test_app_1 bash
# in docker
$ python setup.py bdist_rpm
$ rpm -ivh dist/*.rpm
```

Then occur error message below.
because of `paramiko`

```bash
sh-4.2# build_test
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/cx_Freeze/initscripts/__startup__.py", line 81, in run
    module.run()
  File "/usr/local/lib/python3.9/site-packages/cx_Freeze/initscripts/Console.py", line 36, in run
    exec(code, m.__dict__)
  File "build_test/__main__.py", line 1, in <module>
    from build_test.hello import hello
  File "<frozen zipimport>", line 259, in load_module
  File "/code/build/bdist.linux-x86_64/rpm/BUILD/build_test-0.0.1/build_test/hello.py", line 1, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/site-packages/paramiko/transport.py", line 89, in <module>
    from paramiko.dsskey import DSSKey
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/site-packages/paramiko/dsskey.py", line 37, in <module>
    from paramiko.pkey import PKey
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/site-packages/paramiko/pkey.py", line 31, in <module>
    import bcrypt
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/site-packages/bcrypt/__init__.py", line 25, in <module>
    from . import _bcrypt  # type: ignore
ImportError: /usr/local/lib/build_test-0.0.1/lib/_cffi_backend.cpython-39-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned
```

**Comment by marcelotduarte** [comment]
**Desktop (please complete the following information):**
 - Platform information (e.g. Ubuntu Linux 16.04):
 - OS architecture (e.g. amd64):
 - cx_Freeze version [e.g. 6.6]:
 - Python version [e.g. 3.9]:

**Comment by mcauto** [comment]
> **Desktop (please complete the following information):**

Here !

* Platform information (e.g. Ubuntu Linux 16.04): centos 7 (with docker)
* OS architecture (e.g. amd64): x86_64
* cx_Freeze version [e.g. 6.6]: 6.6
* Python version [e.g. 3.9]: 3.9

**Comment by marcelotduarte** [comment]
I looked at your example, over the top, I don't have time to test it now. However, I see that you use a version of python compiled from sources, so I believe that some configuration options are missing (line 15 of the Dockerfile). Use:
configure --enable-shared
Maybe you need to add --enable-ipv6 if use some networking
And the flag:
LDFLAGS_NODIST="-Wl,-rpath,/usr/local/lib"
If you have some other error.
Try it out!

**Comment by marcelotduarte** [comment]
Do you have success?

**Comment by mcauto** [comment]
I cant solve it..

I try it like below.
however, same error occurs.

```dockerfile
...
RUN tar xJvf Python-3.9.5.tar.xz \
    && cd Python-3.9.5 \
    && ./configure --enable-shared --enable-ipv6
RUN cd Python-3.9.5 \
    && LDFLAGS_NODIST="-Wl,-rpath,/usr/local/lib" make \
    && make altinstall
...
```

```bash
sh-4.2# build_test
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/cx_Freeze/initscripts/__startup__.py", line 81, in run
    module.run()
  File "/usr/local/lib/python3.9/site-packages/cx_Freeze/initscripts/Console.py", line 36, in run
    exec(code, m.__dict__)
  File "build_test/__main__.py", line 1, in <module>
    from build_test.hello import hello
  File "<frozen zipimport>", line 259, in load_module
  File "/code/build/bdist.linux-x86_64/rpm/BUILD/build_test-0.0.1/build_test/hello.py", line 1, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/site-packages/paramiko/transport.py", line 89, in <module>
    from paramiko.dsskey import DSSKey
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/site-packages/paramiko/dsskey.py", line 37, in <module>
    from paramiko.pkey import PKey
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/site-packages/paramiko/pkey.py", line 31, in <module>
    import bcrypt
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/site-packages/bcrypt/__init__.py", line 25, in <module>
    from . import _bcrypt  # type: ignore
ImportError: /usr/local/lib/build_test-0.0.1/lib/_cffi_backend.cpython-39-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned
```

**Comment by marcelotduarte** [comment]
```
...
&& ./configure --enable-shared --enable-ipv6 LDFLAGS_NODIST="-Wl,-rpath,/usr/local/lib" \
&& make
...
```

**Comment by marcelotduarte** [comment]
Do you get this project running in this image? There are some issues to run a py39 in centos7.
In [manylinux](https://github.com/pypa/manylinux) they solve them.
But, the shared library isn't included.
So, if you use: FROM quay.io/pypa/manylinux2014_x86_64
You'll get an error.

I had preliminary work with manylinux2010 (centos6) but you can adapt to use manylinux2014 (centos7).
See https://github.com/marcelotduarte/cx_Freeze/tree/develop/ci
https://github.com/marcelotduarte/cx_Freeze/blob/develop/ci/build-manylinux2010.sh
https://github.com/marcelotduarte/cx_Freeze/blob/develop/ci/build-manylinux-create.sh

**Comment by mcauto** [comment]
I use CentOS 7(+python3.9) on-premise server in production.

I try it, then i get an error.
Could you push your docker image(manylinux-freeze) on docker hub?
 
```dockerfile
# https://github.com/pypa/manylinux
FROM quay.io/pypa/manylinux2014_x86_64
COPY requirements.txt requirements.txt
```

<details> <summary> python3.9 -m install -r requirements.txt </summary>

```bash
Installing collected packages: cx-freeze
    Running setup.py install for cx-freeze ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_bkrfu6z/cx-freeze_c851ee3ebfbb4cabad3e02bae3465dcb/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_bkrfu6z/cx-freeze_c851ee3ebfbb4cabad3e02bae3465dcb/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-7duxfrih/install-record.txt --single-version-externally-managed --compile --install-headers /opt/_internal/cpython-3.9.5/include/python3.9/cx-freeze
         cwd: /tmp/pip-install-_bkrfu6z/cx-freeze_c851ee3ebfbb4cabad3e02bae3465dcb/
    Complete output (40 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.9
    creating build/lib.linux-x86_64-3.9/cx_Freeze
    copying cx_Freeze/finder.py -> build/lib.linux-x86_64-3.9/cx_Freeze
    copying cx_Freeze/cli.py -> build/lib.linux-x86_64-3.9/cx_Freeze
    copying cx_Freeze/macdist.py -> build/lib.linux-x86_64-3.9/cx_Freeze
    copying cx_Freeze/__main__.py -> build/lib.linux-x86_64-3.9/cx_Freeze
    copying cx_Freeze/setupwriter.py -> build/lib.linux-x86_64-3.9/cx_Freeze
    copying cx_Freeze/common.py -> build/lib.linux-x86_64-3.9/cx_Freeze
    copying cx_Freeze/windist.py -> build/lib.linux-x86_64-3.9/cx_Freeze
    copying cx_Freeze/darwintools.py -> build/lib.linux-x86_64-3.9/cx_Freeze
    copying cx_Freeze/dist.py -> build/lib.linux-x86_64-3.9/cx_Freeze
    copying cx_Freeze/freezer.py -> build/lib.linux-x86_64-3.9/cx_Freeze
    copying cx_Freeze/__init__.py -> build/lib.linux-x86_64-3.9/cx_Freeze
    copying cx_Freeze/executable.py -> build/lib.linux-x86_64-3.9/cx_Freeze
    copying cx_Freeze/winversioninfo.py -> build/lib.linux-x86_64-3.9/cx_Freeze
    copying cx_Freeze/winmsvcr.py -> build/lib.linux-x86_64-3.9/cx_Freeze
    copying cx_Freeze/exception.py -> build/lib.linux-x86_64-3.9/cx_Freeze
    copying cx_Freeze/patchelf.py -> build/lib.linux-x86_64-3.9/cx_Freeze
    copying cx_Freeze/module.py -> build/lib.linux-x86_64-3.9/cx_Freeze
    copying cx_Freeze/hooks.py -> build/lib.linux-x86_64-3.9/cx_Freeze
    creating build/lib.linux-x86_64-3.9/cx_Freeze/initscripts
    copying cx_Freeze/initscripts/ConsoleSetLibPath.py -> build/lib.linux-x86_64-3.9/cx_Freeze/initscripts
    copying cx_Freeze/initscripts/SharedLib.py -> build/lib.linux-x86_64-3.9/cx_Freeze/initscripts
    copying cx_Freeze/initscripts/__startup__.py -> build/lib.linux-x86_64-3.9/cx_Freeze/initscripts
    copying cx_Freeze/initscripts/SharedLibSource.py -> build/lib.linux-x86_64-3.9/cx_Freeze/initscripts
    copying cx_Freeze/initscripts/Console.py -> build/lib.linux-x86_64-3.9/cx_Freeze/initscripts
    running build_ext
    creating build/temp.linux-x86_64-3.9
    creating build/temp.linux-x86_64-3.9/source
    creating build/temp.linux-x86_64-3.9/source/bases
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/opt/_internal/cpython-3.9.5/include/python3.9 -c source/bases/Console.c -o build/temp.linux-x86_64-3.9/source/bases/Console.o
    creating build/lib.linux-x86_64-3.9/cx_Freeze/bases
    gcc -pthread build/temp.linux-x86_64-3.9/source/bases/Console.o -L/opt/_internal/cpython-3.9.5/lib/python3.9/config-3.9-x86_64-linux-gnu -lpython3.9 -o build/lib.linux-x86_64-3.9/cx_Freeze/bases/Console -Xlinker -export-dynamic -lcrypt -lpthread -ldl -lutil -lm -lm -s -Wl,-rpath,$ORIGIN/lib -Wl,-rpath,$ORIGIN/../lib
    /opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: cannot find -lpython3.9
    collect2: error: ld returned 1 exit status
    error: command '/opt/rh/devtoolset-9/root/usr/bin/gcc' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_bkrfu6z/cx-freeze_c851ee3ebfbb4cabad3e02bae3465dcb/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_bkrfu6z/cx-freeze_c851ee3ebfbb4cabad3e02bae3465dcb/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-7duxfrih/install-record.txt --single-version-externally-managed --compile --install-headers /opt/_internal/cpython-3.9.5/include/python3.9/cx-freeze Check the logs for full command output.
```

</details>

**Comment by marcelotduarte** [comment]
> I try it, then i get an error.

Like I said.

> Could you push your docker image(manylinux-freeze) on docker hub?

The reserved space for open source is github registry for instance is 500MB. The image is about 900MB.

But you can produce it.

Install docker with buildx
(
if your system do not have it, you can use:
curl -fsSL https://get.docker.com/ | sh
sudo usermod -aG docker $USER
and restart
)

Clone manylinux
Clone develop branch of cx_Freeze: `git clone -b develop https://github.com/marcelotduarte/cx_Freeze.git`
create a venv and go to the cx_Freeze directory
edit ci/build-manylinux2010.sh to comment the lines
./build-manylinux-run.sh
./build-manylinux-tests.sh
run:
`./ci/build-manylinux2010.sh`

Dockerfile:
```
FROM manylinux2010_x86_64

RUN yum install -y rpm-build

RUN ln -s /usr/local/bin/python3.9 /usr/local/bin/python3

RUN python3 -m pip install --upgrade git+https://github.com/marcelotduarte/cx_Freeze.git

WORKDIR /code
COPY requirements.txt requirements.txt
RUN python3 -m pip install -r requirements.txt

# cython import
#RUN pip install -U \
#    git+https://github.com/marcelotduarte/cx_Freeze.git@main 

COPY setup.py setup.py
COPY build_test build_test
RUN set -ex \
    && python3 setup.py build_exe --silent bdist_rpm
RUN rpm -ivh dist/*.rpm

CMD ["build_test"]
```

**Comment by mcauto** [comment]
I have an error when I use POLICY=manylinux2014 and python3.9....

```bash
#30 86.02 mv -f $depbase.Tpo $depbase.Po
#30 178.1 g++: fatal error: Killed signal terminated program as
#30 178.1 compilation terminated.
#30 178.2 make[2]: *** [Doxygen/javadoc.o] Error 1
#30 178.2 make[2]: Leaving directory `/swig-4.0.2/Source'
#30 178.2 make[1]: *** [all] Error 2
#30 178.2 make[1]: Leaving directory `/swig-4.0.2/Source'
#30 178.3 make: *** [source] Error 2
------
Dockerfile:84
--------------------
  83 |     COPY build_scripts/build-swig.sh /build_scripts/
  84 | >>> RUN export SWIG_ROOT=swig-4.0.2 && \
  85 | >>>     export SWIG_HASH=d53be9730d8d58a16bf0cbd1f8ac0c0c3e1090573168bfa151b01eb47fa906fc && \
  86 | >>>     export SWIG_DOWNLOAD_URL=https://sourceforge.net/projects/swig/files/swig/${SWIG_ROOT} && \
  87 | >>>     export PCRE_ROOT=pcre-8.44 && \
  88 | >>>     export PCRE_HASH=aecafd4af3bd0f3935721af77b889d9024b2e01d96b58471bd91a3063fb47728 && \
  89 | >>>     export PCRE_DOWNLOAD_URL=https://ftp.pcre.org/pub/pcre && \
  90 | >>>     manylinux-entrypoint /build_scripts/build-swig.sh
  91 |
--------------------
error: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c export SWIG_ROOT=swig-4.0.2 &&     export SWIG_HASH=d53be9730d8d58a16bf0cbd1f8ac0c0c3e1090573168bfa151b01eb47fa906fc &&     export SWIG_DOWNLOAD_URL=https://sourceforge.net/projects/swig/files/swig/${SWIG_ROOT} &&     export PCRE_ROOT=pcre-8.44 &&     export PCRE_HASH=aecafd4af3bd0f3935721af77b889d9024b2e01d96b58471bd91a3063fb47728 &&     export PCRE_DOWNLOAD_URL=https://ftp.pcre.org/pub/pcre &&     manylinux-entrypoint /build_scripts/build-swig.sh]: exit code: 2
```

**Comment by mcauto** [comment]
Thank you kindful explain!

but I get an error. 
when I install build_test.rpm (build on `manylinux2010_x86_64`) on centos 7 

```bash
# centos 7
drwxr-xr-x  2 root root     4096 Jun  1 01:56 .
drwxr-xr-x 12 root root     4096 Nov 13  2020 ..
-rw-r--r--  1 root root     3469 Jun  1 01:56 build_test-0.0.1-1.src.rpm
-rw-r--r--  1 root root 10330108 Jun  1 01:56 build_test-0.0.1-1.x86_64.rpm
-rw-r--r--  1 root root     1284 Jun  1 01:56 build_test-0.0.1.tar.gz
-rw-r--r--  1 root root  1461436 Jun  1 01:56 build_test-debuginfo-0.0.1-1.x86_64.rpm
[root@3d94eacf9197 src]# rpm -ivh *.rpm
error: Failed dependencies:
        libffi.so.5()(64bit) is needed by build_test-0.0.1-1.x86_64
        liblzma.so.0()(64bit) is needed by build_test-0.0.1-1.x86_64
Updating / installing...
   1:build_test-0.0.1-1               ################################# [100%]
[root@3d94eacf9197 src]#
```

```bash
# manylinux2010_x86_64
$ exec /opt/_internal/cpython-3.9.5/bin/build_test
ImportError: /opt/_internal/cpython-3.9.5/lib/build_test-0.0.1/lib/_cffi_backend.cpython-39-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned
```

**Comment by marcelotduarte** [comment]
I get it running with more changes:
in setup.py add "bin_path_includes": "/usr/lib64", to options build_exe
in requirements change to cffi==1.13.2 (Why? https://foss.heptapod.net/pypy/cffi/-/issues/432)
Dockerfile:
```
# docker build -t build-test-rpm
# docker run --rm build-test-rpm
FROM manylinux2010_x86_64 as builder

RUN yum install -y rpm-build libffi-devel

RUN ln -s /usr/local/bin/python3.9 /usr/local/bin/python3

WORKDIR /code
COPY requirements.txt requirements.txt
RUN python3 -m pip install -r requirements.txt

COPY setup.py setup.py
COPY build_test build_test
RUN set -ex \
    && python3 setup.py bdist_rpm

FROM centos:7
COPY --from=builder /code/dist/*.rpm /dist/
RUN rpm -ivh dist/*.rpm
USER nobody:nobody
ENTRYPOINT ["/opt/_internal/cpython-3.9.5/bin/build_test"]
```

**Comment by marcelotduarte** [comment]
Deo, I get success without changing the setup and requirements. 
There are four issues:
1) --enable-shared (using my modified manylinx solves this)
2) corruption by patchelf in the libffi dependency
3) corruption by strip in rpmbuild (using strip) in the cffi extension
Check the PR for more details.
4) failed dependencies - use `bdist_rpm --no-autoreq`

Dockerfile:
```
# docker build -t build-test-rpm .
# docker run --rm build-test-rpm
FROM manylinux2010_x86_64 as builder

RUN yum install -y rpm-build
# libffi-devel openssl-devel

RUN ln -s /opt/_internal/cpython-3.9.5/bin/python3.9 /usr/local/bin/python3
RUN ln -s /opt/_internal/cpython-3.9.5/bin/pip3.9 /usr/local/bin/pip

WORKDIR /code
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN pip uninstall -y cx-freeze && \
    pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@develop

COPY setup.py setup.py
COPY build_test build_test
RUN set -ex && \
    python3 setup.py bdist_rpm --no-autoreq
RUN ls -l build/bdist*/rpm/*/* || true
RUN ldd /opt/_internal/cpython-3.9.5/lib/python3.9/site-packages/_cffi_backend.cpython-39-x86_64-linux-gnu.so
RUN patchelf --print-soname --print-rpath --print-needed --debug /opt/_internal/cpython-3.9.5/lib/python3.9/site-packages/_cffi_backend.cpython-39-x86_64-linux-gnu.so

FROM centos:7
COPY --from=builder /code/dist/* /dist/
COPY --from=builder /usr/local/bin/patchelf /usr/local/bin/patchelf
RUN rpm -ivh dist/build_test-0.0.1-1.x86_64.rpm
RUN ls -l -h /opt/_internal/cpython-3.9.5/lib/build_test-0.0.1
RUN ldd /opt/_internal/cpython-3.9.5/lib/build_test-0.0.1/lib/*.so* | grep -i -B 1 "not a dynamic executable" || true
RUN patchelf --print-soname --print-rpath --print-needed --debug /opt/_internal/cpython-3.9.5/lib/build_test-0.0.1/lib/_cffi_backend.cpython-39-x86_64-linux-gnu.so
USER nobody:nobody
RUN /opt/_internal/cpython-3.9.5/lib/build_test-0.0.1/build_test
CMD ["/opt/_internal/cpython-3.9.5/lib/build_test-0.0.1/build_test"]
```

**Comment by mcauto** [comment]
Awesome! It's works!

Unfortunately, I was faced with other problems...
When I add ldap3 dependency. 
Occur error blow.😨
Could you help me one more..? plz

```bash
pip install ldap3
```

```
# build_test/hello.py
import paramiko
import ldap3
def hello():
    print("hello")
```

```
ImportError libffi.so.5: cannot open shared object file: No such file or directory
```

<details> <summary> log </summary> 

```bash
 => ERROR [stage-1 8/8] RUN /opt/_internal/cpython-3.9.5/lib/build_test-0.0.1/build_test                                                                                                                                             1.0s
------
 > [stage-1 8/8] RUN /opt/_internal/cpython-3.9.5/lib/build_test-0.0.1/build_test:
#27 0.922 Traceback (most recent call last):
#27 0.922   File "/opt/_internal/cpython-3.9.5/lib/python3.9/site-packages/cx_Freeze/initscripts/__startup__.py", line 81, in run
#27 0.924   File "/opt/_internal/cpython-3.9.5/lib/python3.9/site-packages/cx_Freeze/initscripts/Console.py", line 36, in run
#27 0.924   File "build_test/__main__.py", line 1, in <module>
#27 0.924   File "<frozen zipimport>", line 259, in load_module
#27 0.924   File "/code/build/bdist.linux-x86_64/rpm/BUILD/build_test-0.0.1/build_test/hello.py", line 2, in <module>
#27 0.925   File "<frozen zipimport>", line 259, in load_module
#27 0.925   File "/opt/_internal/cpython-3.9.5/lib/python3.9/site-packages/ldap3/__init__.py", line 141, in <module>
#27 0.925   File "<frozen zipimport>", line 259, in load_module
#27 0.925   File "/opt/_internal/cpython-3.9.5/lib/python3.9/site-packages/ldap3/core/connection.py", line 38, in <module>
#27 0.925   File "<frozen zipimport>", line 259, in load_module
#27 0.925   File "/opt/_internal/cpython-3.9.5/lib/python3.9/site-packages/ldap3/extend/__init__.py", line 29, in <module>
#27 0.925   File "<frozen zipimport>", line 259, in load_module
#27 0.925   File "/opt/_internal/cpython-3.9.5/lib/python3.9/site-packages/ldap3/extend/microsoft/dirSync.py", line 27, in <module>
#27 0.925   File "<frozen zipimport>", line 259, in load_module
#27 0.925   File "/opt/_internal/cpython-3.9.5/lib/python3.9/site-packages/ldap3/protocol/microsoft.py", line 26, in <module>
#27 0.925   File "<frozen zipimport>", line 259, in load_module
#27 0.925   File "/opt/_internal/cpython-3.9.5/lib/python3.9/ctypes/__init__.py", line 8, in <module>
#27 0.925 ImportError: libffi.so.5: cannot open shared object file: No such file or directory
```

</details>

**Comment by marcelotduarte** [comment]
In this specific case, use "bin_includes": "libffi.so.5"
```
    options={
        "build_exe":{
            "zip_include_packages": ["*"],
            "zip_exclude_packages": [],
            "includes": [],
            "silent": True,
            "bin_includes": "libffi.so.5",
        }
    },
```

**Comment by mcauto** [comment]
Thank you. It's works!   
close issue.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.7 has just been released.
