### ISSUE TITLE
Pythonnet initialization issue

### ISSUE THREAD

**Issue by pcbt** [marcelotduarte/cx_Freeze#1049]
This issue is a continuation of #658. The problem is still on with the following setup:

Python 3.8.10 (official python not a conda version)
cx_freeze 6.6
W10 Version 1909 (OS Build 18363.1500)
system: amd64

I tried with another W10 pc and error code is the same:

```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Python.Runtime.Runtime.InitializePlatformData()
   at Python.Runtime.Runtime.Initialize(Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.InitExt()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at clrModule.PyInit_clr()
```

**Comment by bsztr** [comment]
Hi, 

Python 3.7
Cx_Freeze 6.6
OS build 19042.985

I have the same issue when initialising clr. Tried sample project, with import clr and print to terminal and got the same error. 
_Pyinstaller does the job without any issues._ 

Silly question, but maybe this is something to do with setting up the config file? I simply added "clr" in the packages section.

**Any suggestion would be much appreciated.**  

BUILD FOLDER:

27/05/2021  14:49    <DIR>          dict
27/05/2021  14:49    <DIR>          DLLs
27/05/2021  14:49    <DIR>          lib
27/06/2018  14:00            59,032 python3.dll
27/06/2018  14:00         3,844,760 python37.dll
27/06/2018  13:05         1,731,744 tcl86t.dll
27/05/2021  14:48           113,664 testing.exe
27/06/2018  13:05         1,480,352 tk86t.dll
27/06/2018  13:02            89,752 VCRUNTIME140.dll

```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Python.Runtime.Runtime.InitializePlatformData()
   at Python.Runtime.Runtime.Initialize(Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.InitExt()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at clrModule.PyInit_clr()
```

**Comment by marcelotduarte** [comment]
I rested my sample and it works!
I need that you expand my sample or try to point me in the direction of the error.

Windows 10 Pro
Version 20H2
SO 19042.928
Windows Feature Experience Pack 120.2212.551.0

My pip list (in a virtual environment):
```
Package            Version
------------------ -------
cx-Freeze          6.6
cx-Logging         3.0
importlib-metadata 4.4.0
pip                21.1.2
pycparser          2.20
pythonnet          2.5.2
setuptools         57.0.0
zipp               3.4.1
```
My sample consists of 3 files:
```
# setup.py
from cx_Freeze import setup, Executable

base = "Console"

executables = [
    Executable("test.py", base=base),
    Executable("test2.py", base=base),
]

setup(
    name="test",
    version="1.0",
    description="test",
    options={"build_exe": {"silent": True, "include_msvcr": True}},
    executables=executables,
)
```
```
# test.py
import platform

import clr

if __name__ == "__main__":
    print(platform.system())
    print(platform.machine())
    input("Press ENTER")
```
```
# test2.py
import platform

import clr
from System import String
from System.Collections import *

clr.AddReference("System.Windows.Forms")
from System.Windows.Forms import Form

if __name__ == "__main__":
    print(platform.system())
    print(platform.machine())
    print(Form)
    print(String)
    input("Press ENTER")
```
Result:
![pnet](https://user-images.githubusercontent.com/12752334/120254914-43338c00-c261-11eb-8432-bbaa83b75e06.png)

https://github.com/marcelotduarte/cx_Freeze/issues/658#issuecomment-633187364

**Comment by marcelotduarte** [comment]
@pcbt @bsztr 
I add a PR #1088 with samples (3 demo) from pythonnet that are more complex than my 2 tests.
For me they build and run.
https://github.com/marcelotduarte/cx_Freeze/tree/main/cx_Freeze/samples/pythonnet-demo
This is a image of the first test that I did.
![pnet2](https://user-images.githubusercontent.com/12752334/120438745-20d06a00-c358-11eb-8412-edd636534b63.png)

**Comment by pcbt** [comment]
Hi @marcelotduarte , 

I tried to run the examples, they run normally. Maybe there is something wrong with the assembly file I want to import in my script. Is there a way to debug executable?

KR
Batuhan A.

**Comment by marcelotduarte** [comment]
To test with messages on command line, modify the setup.py as:
```
import sys
from cx_Freeze import setup, Executable

base = None

executables = [
    Executable("helloform.py", icon="python-clear.ico", base=base),
    Executable("splitter.py", icon="python-clear.ico", base=base),
    Executable("wordpad.py", icon="python-clear.ico", base=base),
]

setup(
    name="pythonnet demos",
    version="0.1",
    description="https://github.com/pythonnet/pythonnet/tree/master/demo",
    executables=executables,
)

```

**Comment by marcelotduarte** [comment]
> Maybe there is something wrong with the assembly file I want to import in my script.

Try to change one script to add your import....

> Is there a way to debug executable?

You can put breakpoint() in py37+ (It is still valid when running the executable).

**Comment by marcelotduarte** [comment]
@pcbt @bsztr A bug described in #1304 and reproducible with #1333 (with uses pythonnet) should be the cause of this issue.
[cx_Freeze 6.10](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.10) has just been released.
Can you check if this has been resolved?
