### ISSUE TITLE
Freezing with homebrewed PyQt4 on OS X

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#109]
Originally reported by: **Michka Popoff (Bitbucket: [iMichka](https://bitbucket.org/iMichka), GitHub: [iMichka](https://github.com/iMichka))**

----------------------------------------

Hi

Freezing with PyQt4 on OS X is not working. I am using PyQt4 installed through homebrew. Here is the error, with only a PyQt4 QtCore and QtGui import:

```
#!python

mbp-de-michka:test michkapopoff$ cxfreeze main.py --target-dir build/
copying /usr/local/lib/python2.7/site-packages/cx_Freeze/bases/Console -> build/main
copying /usr/local/Frameworks/Python.framework/Versions/2.7/Python -> build/Python
writing zip file build/main

  Name                      File
  ----                      ----
P PyQt4                     /usr/local/lib/python2.7/site-packages/PyQt4/__init__.py
m PyQt4.QtCore              /usr/local/lib/python2.7/site-packages/PyQt4/QtCore.so
m PyQt4.QtGui               /usr/local/lib/python2.7/site-packages/PyQt4/QtGui.so
m StringIO                  
m UserDict                  
m __builtin__               
m __main__                  main.py
m _abcoll                   
m _codecs                   
m _codecs_cn                /usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_codecs_cn.so
m _codecs_hk                /usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_codecs_hk.so
m _codecs_iso2022           /usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_codecs_iso2022.so
m _codecs_jp                /usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_codecs_jp.so
m _codecs_kr                /usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_codecs_kr.so
m _codecs_tw                /usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_codecs_tw.so
m _multibytecodec           /usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_multibytecodec.so
m _struct                   /usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_struct.so
m _warnings                 
m _weakref                  
m _weakrefset               
m abc                       
m base64                    
m binascii                  /usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/binascii.so
m bz2                       /usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/bz2.so
m codecs                    
m copy                      
m copy_reg                  
m cx_Freeze__init__         /usr/local/lib/python2.7/site-packages/cx_Freeze/initscripts/Console.py
P encodings                 
m encodings.aliases         
m encodings.ascii           
m encodings.base64_codec    
m encodings.big5            
m encodings.big5hkscs       
m encodings.bz2_codec       
m encodings.charmap         
m encodings.cp037           
m encodings.cp1006          
m encodings.cp1026          
m encodings.cp1140          
m encodings.cp1250          
m encodings.cp1251          
m encodings.cp1252          
m encodings.cp1253          
m encodings.cp1254          
m encodings.cp1255          
m encodings.cp1256          
m encodings.cp1257          
m encodings.cp1258          
m encodings.cp424           
m encodings.cp437           
m encodings.cp500           
m encodings.cp720           
m encodings.cp737           
m encodings.cp775           
m encodings.cp850           
m encodings.cp852           
m encodings.cp855           
m encodings.cp856           
m encodings.cp857           
m encodings.cp858           
m encodings.cp860           
m encodings.cp861           
m encodings.cp862           
m encodings.cp863           
m encodings.cp864           
m encodings.cp865           
m encodings.cp866           
m encodings.cp869           
m encodings.cp874           
m encodings.cp875           
m encodings.cp932           
m encodings.cp949           
m encodings.cp950           
m encodings.euc_jis_2004    
m encodings.euc_jisx0213    
m encodings.euc_jp          
m encodings.euc_kr          
m encodings.gb18030         
m encodings.gb2312          
m encodings.gbk             
m encodings.hex_codec       
m encodings.hp_roman8       
m encodings.hz              
m encodings.idna            
m encodings.iso2022_jp      
m encodings.iso2022_jp_1    
m encodings.iso2022_jp_2    
m encodings.iso2022_jp_2004 
m encodings.iso2022_jp_3    
m encodings.iso2022_jp_ext  
m encodings.iso2022_kr      
m encodings.iso8859_1       
m encodings.iso8859_10      
m encodings.iso8859_11      
m encodings.iso8859_13      
m encodings.iso8859_14      
m encodings.iso8859_15      
m encodings.iso8859_16      
m encodings.iso8859_2       
m encodings.iso8859_3       
m encodings.iso8859_4       
m encodings.iso8859_5       
m encodings.iso8859_6       
m encodings.iso8859_7       
m encodings.iso8859_8       
m encodings.iso8859_9       
m encodings.johab           
m encodings.koi8_r          
m encodings.koi8_u          
m encodings.latin_1         
m encodings.mac_arabic      
m encodings.mac_centeuro    
m encodings.mac_croatian    
m encodings.mac_cyrillic    
m encodings.mac_farsi       
m encodings.mac_greek       
m encodings.mac_iceland     
m encodings.mac_latin2      
m encodings.mac_roman       
m encodings.mac_romanian    
m encodings.mac_turkish     
m encodings.mbcs            
m encodings.palmos          
m encodings.ptcp154         
m encodings.punycode        
m encodings.quopri_codec    
m encodings.raw_unicode_escape 
m encodings.rot_13          
m encodings.shift_jis       
m encodings.shift_jis_2004  
m encodings.shift_jisx0213  
m encodings.string_escape   
m encodings.tis_620         
m encodings.undefined       
m encodings.unicode_escape  
m encodings.unicode_internal 
m encodings.utf_16          
m encodings.utf_16_be       
m encodings.utf_16_le       
m encodings.utf_32          
m encodings.utf_32_be       
m encodings.utf_32_le       
m encodings.utf_7           
m encodings.utf_8           
m encodings.utf_8_sig       
m encodings.uu_codec        
m encodings.zlib_codec      
m errno                     
m exceptions                
m genericpath               
m imp                       
m itertools                 /usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/itertools.so
m linecache                 
m os                        
m posix                     
m posixpath                 
m pwd                       
m quopri                    
m repr                      
m sip                       /usr/local/lib/python2.7/site-packages/sip.so
m stat                      
m stringprep                
m struct                    
m sys                       
m traceback                 
m types                     
m unicodedata               /usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/unicodedata.so
m warnings                  
m weakref                   
m zipimport                 
m zlib                      /usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/zlib.so

Missing modules:
? _emx_link imported from os
? cStringIO imported from encodings.quopri_codec, encodings.uu_codec, quopri
? ce imported from os
? getopt imported from base64, quopri
? nt imported from os
? ntpath imported from os
? org.python.core imported from copy
? os.path imported from os
? os2 imported from os
? os2emxpath imported from os
? re imported from base64, encodings.idna, posixpath, warnings
? riscos imported from os
? riscosenviron imported from os
? riscospath imported from os
? subprocess imported from os
This is not necessarily a problem - the modules may not be needed on this platform.

copying /usr/local/lib/python2.7/site-packages/PyQt4/QtCore.so -> build/PyQt4.QtCore.so
copying /usr/local/opt/pyqt/lib/python2.7/site-packages/PyQt4/libQtCore.dylib -> build/libQtCore.dylib
Traceback (most recent call last):
  File "/usr/local/bin/cxfreeze", line 5, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/cx_Freeze/main.py", line 188, in main
    freezer.Freeze()
  File "/usr/local/lib/python2.7/site-packages/cx_Freeze/freezer.py", line 605, in Freeze
    self._FreezeExecutable(executable)
  File "/usr/local/lib/python2.7/site-packages/cx_Freeze/freezer.py", line 197, in _FreezeExecutable
    exe.copyDependentFiles, scriptModule)
  File "/usr/local/lib/python2.7/site-packages/cx_Freeze/freezer.py", line 588, in _WriteModules
    self._CopyFile(module.file, target, copyDependentFiles)
  File "/usr/local/lib/python2.7/site-packages/cx_Freeze/freezer.py", line 145, in _CopyFile
    self._CopyFile(source, target, copyDependentFiles)
  File "/usr/local/lib/python2.7/site-packages/cx_Freeze/freezer.py", line 137, in _CopyFile
    shutil.copyfile(source, target)
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/usr/local/opt/pyqt/lib/python2.7/site-packages/PyQt4/libQtCore.dylib'
```

List of files in the site-packages/PyQt4 folder:

```
#!python

-r--r--r--+  1 michkapopoff  admin    12784  6 aoû 08:45 Qt.so
-r--r--r--+  1 michkapopoff  admin  2626680  6 aoû 08:45 QtCore.so
-r--r--r--+  1 michkapopoff  admin   312196  6 aoû 08:45 QtDeclarative.so
-r--r--r--+  1 michkapopoff  admin   415832  6 aoû 08:45 QtDesigner.so
-r--r--r--+  1 michkapopoff  admin  8628604  6 aoû 08:45 QtGui.so
-r--r--r--+  1 michkapopoff  admin   137532  6 aoû 08:45 QtHelp.so
-r--r--r--+  1 michkapopoff  admin   163312  6 aoû 08:45 QtMultimedia.so
-r--r--r--+  1 michkapopoff  admin   783232  6 aoû 08:45 QtNetwork.so
-r--r--r--+  1 michkapopoff  admin   317548  6 aoû 08:45 QtOpenGL.so
-r--r--r--+  1 michkapopoff  admin   226008  6 aoû 08:45 QtScript.so
-r--r--r--+  1 michkapopoff  admin    33772  6 aoû 08:45 QtScriptTools.so
-r--r--r--+  1 michkapopoff  admin   348168  6 aoû 08:45 QtSql.so
-r--r--r--+  1 michkapopoff  admin   118876  6 aoû 08:45 QtSvg.so
-r--r--r--+  1 michkapopoff  admin    45312  6 aoû 08:45 QtTest.so
-r--r--r--+  1 michkapopoff  admin   494948  6 aoû 08:45 QtWebKit.so
-r--r--r--+  1 michkapopoff  admin   355856  6 aoû 08:45 QtXml.so
-r--r--r--+  1 michkapopoff  admin   190856  6 aoû 08:45 QtXmlPatterns.so
-r--r--r--+  1 michkapopoff  admin     1111  6 aoû 08:45 __init__.py
-r--r--r--+  1 michkapopoff  admin   445972  6 aoû 08:45 phonon.so
-r--r--r--   1 michkapopoff  staff    14476  6 aoû 08:36 pyqtconfig.py
drwxr-xr-x+ 15 michkapopoff  admin      510  6 aoû 08:45 uic
```

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/109

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Closing due to inactivity.
