### ISSUE TITLE
Error: can't find module 'google' after freezing.

### ISSUE THREAD

**Issue by kiflowb777** [marcelotduarte/cx_Freeze#1094]
After freezing my script with cx_freeze I get:
```can't find module 'google'```

I use:
```cxfreeze -O -OO --target-dir=FREEZE_PROJECT --include-modules="tensorflow,numpy,google" --target-name="project.exe" project.py```

**Desktop (please complete the following information):**
 - Platform information (e.g. Ubuntu Linux 16.04): Windows 10
 - OS architecture: 64 bit
 - cx_Freeze version: 6.6
 - Python version [e.g. 3.9]: 3.6.1
 - TensorFlow: 2.5.0
 - Numpy: 1.19.5

**Comment by kiflowb777** [comment]
```
ERROR	can't find module 'google'	__main__:36
Traceback (most recent call last):
  File "project.py", line 19, in <module>
  File "D:\PROJECT\initialize.py", line 15, in initialize_p
    import tensorflow as tf
  File ".\lib\tensorflow\__init__.py", line 41, in <module>
    ^ZOIRO OXEI
  File ".\lib\tensorflow\python\__init__.py", line 40, in <module>
  File ".\lib\tensorflow\python\eager\context.py", line 32, in <module>
  File ".\lib\tensorflow\core\framework\function_pb2.py", line 7, in <module>
    
zipimport.ZipImportError: can't find module 'google'
ERROR	can't find module 'google'	__main__:37
```

**Comment by marcelotduarte** [comment]
What is result of pip list?

In advance, there is no google package. google is a namespace package, so there are packages like: google.core.api, google.cloud.storage, etc
What is the traceback if you remove the include-modules?

**Comment by kiflowb777** [comment]
```
PS C:\python36\Scripts> .\pip.exe list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
absl-py (0.11.0)
appdirs (1.4.4)
astor (0.7.1)
astroid (2.2.4)
astunparse (1.6.3)
atomicwrites (1.4.0)
attrs (20.3.0)
backports.weakref (1.0.post1)
bleach (3.1.0)
cached-property (1.5.2)
cachetools (4.2.0)
certifi (2020.12.5)
chardet (4.0.0)
colorama (0.4.1)
coverage (4.5.2)
cx-Freeze (6.6)
cx-Logging (3.0)
cycler (0.10.0)
dataclasses (0.8)
decorator (4.4.2)
distlib (0.3.1)
filelock (3.0.12)
flatbuffers (1.12)
gast (0.4.0)
google-api-core (1.30.0)
google-api-python-client (2.8.0)
google-auth (1.24.0)
google-auth-httplib2 (0.1.0)
google-auth-oauthlib (0.4.2)
google-pasta (0.2.0)
googleapis-common-protos (1.53.0)
grpcio (1.34.1)
h5py (3.1.0)
html5lib (1.0.1)
httplib2 (0.19.1)
idna (2.10)
imageio (2.9.0)
imgaug (0.2.6)
importlib-metadata (4.5.0)
importlib-resources (5.0.0)
iniconfig (1.1.1)
isort (4.3.11)
joblib (0.13.2)
Keras-Applications (1.0.8)
keras-nightly (2.5.0.dev2021032900)
Keras-Preprocessing (1.1.2)
kiwisolver (1.0.1)
lazy-object-proxy (1.4.2)
Markdown (3.0.1)
matplotlib (3.0.3)
mccabe (0.6.1)
mock (2.0.0)
numpy (1.19.5+mkl)
oauthlib (3.1.0)
olefile (0.46)
opencv-python (4.5.1.48)
opt-einsum (3.3.0)
packaging (20.4)
pbr (5.1.3)
Pillow (6.1.0)
pip (9.0.1)
pipdeptree (2.0.0)
pluggy (0.13.1)
protobuf (3.14.0)
psutil (5.6.3)
py (1.9.0)
py-cpuinfo (5.0.0)
pyasn1 (0.4.8)
pyasn1-modules (0.2.8)
pycryptodome (3.7.3)
pylint (2.3.1)
pyparsing (2.4.7)
pytest (6.1.2)
python-dateutil (2.8.0)
pytz (2018.9)
PyWavelets (1.1.1)
PyYAML (3.13)
requests (2.25.1)
requests-oauthlib (1.3.0)
rsa (4.7)
scikit-image (0.17.2)
scikit-learn (0.21.3)
scipy (1.3.1)
setuptools (57.0.0)
six (1.15.0)
tensorboard (2.5.0)
tensorboard-data-server (0.6.1)
tensorboard-plugin-wit (1.8.0)
tensorflow-estimator (2.5.0)
tensorflow-gpu (2.5.0)
termcolor (1.1.0)
Theano (1.0.4)
tifffile (2020.9.3)
toml (0.10.2)
typed-ast (1.3.1)
typing-extensions (3.10.0.0)
unittest-xml-reporting (2.2.1)
uritemplate (3.0.1)
urllib3 (1.26.2)
virtualenv (20.3.1)
webencodings (0.5.1)
Werkzeug (0.14.1)
wheel (0.36.2)
wrapt (1.12.1)
zipp (3.4.1)
You are using pip version 9.0.1, however version 21.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

**Comment by kiflowb777** [comment]
When remove the include-modules the traceback is the same.

After freezing TensorFlow cannot find ```google.protobuf``` in "C:\python36\Lib\site-packages\tensorflow\core\framework\function_pb2.py":

function_pb2.py file head:
```python
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/framework/function.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)
```

But google directory exists in freeze target:
```D:\FREEZE_PROJECT\lib\google\protobuf```

**Comment by marcelotduarte** [comment]
use --packages=google.protobuf then.

**Comment by kiflowb777** [comment]
Now I get:
```
2021-06-11T15:55:40.591+0200	ERROR	can't find module 'google'	__main__:36
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 81, in run
    module.run()
  File "c:\python36\lib\site-packages\cx_Freeze\initscripts\Console.py", line 36, in run
    exec(code, m.__dict__)
  File "project.py", line 11, in <module>
zipimport.ZipImportError: can't find module 'google'
```

 "project.py", line 11 is:
```import google.protobuf```

**Comment by jpeg13** [comment]
I used to have a similar issue using `protobuf` and used to solve it by manually adding an empty `__init__.py` file into the `google` directory ("namespace package"). The issue disappeared at the time I moved from Python 3.6 to 3.8, however I've never checked if there was a causality.
@kiflowb777
> You are using pip version 9.0.1, however version 21.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

You should consider following this advice, it might also play a role here.

**Comment by marcelotduarte** [comment]
> The issue disappeared at the time I moved from Python 3.6 to 3.8,

Probably at the same time we support namespaces automatically in v 6.2.

>>    You are using pip version 9.0.1, however version 21.1.2 is available.
> >   You should consider upgrading via the 'python -m pip install --upgrade pip' command.
>
> You should consider following this advice, it might also play a role here.
I agree. Update the pip and reinstall the google packages to update the metadata.

Can you provide a minimal sample to reproduce the error, then I can make hooks for it.

**Comment by marcelotduarte** [comment]
Oh, and try to use the new beta version: pip install cx-freeze==6.7b4

**Comment by jpeg13** [comment]
> > The issue disappeared at the time I moved from Python 3.6 to 3.8,
> 
> Probably at the same time we support namespaces automatically in v 6.2.

Good point, I actually also changed cx_Freeze from 6.0 to 6.2 in the same commit, the causality is thus probably there.

**Comment by marcelotduarte** [comment]
@kiflowb777 cx_Freeze 6.7b5 has just been released.
pip install cx-Freeze==6.7b5

Try it out and give me feedback.

**Comment by kiflowb777** [comment]
Thanks, 

To solve the issue I:
- updated pip to newest version (9.0.1 -> 21.1.2)
- added empty ```__init__.py``` in ```google``` module directory,
- moved ```google``` directory form ```D:\FROZEN_TARGET\lib\google``` to ```D:\FROZEN_TARGET\google```

and now everything works.

**Comment by kiflowb777** [comment]
> 
> 
> @kiflowb777 cx_Freeze 6.7b5 has just been released.
> pip install cx-Freeze==6.7b5
> 
> Try it out and give me feedback.

The problem still exists, only applying those three actions I mentioned in the previous post helped.

**Comment by marcelotduarte** [comment]
@kiflowb777 I had a simple test, please check if it runs for you:
```
import tensorflow as tf

print(">>>> tensorflow version", tf.__version__)

tf.add(1, 2).numpy()
hello = tf.constant('Hello, TensorFlow!')
print(hello.numpy())
```
It is simple but sufficient to load all imports like protobuf and others.
It works for me since cx-freeze 6.3 (but I tested it only with python 3.8)
Now I tested with python 3.9
To build: cxfreeze hello.py

**Comment by marcelotduarte** [comment]
Tested with 3.6 in windows (using tensorflow-cpu because is in a Virtualbox).
![tf-36-win](https://user-images.githubusercontent.com/12752334/122179066-8c88fb80-ce5d-11eb-9159-67a1789d8d3b.png)

**Comment by kiflowb777** [comment]
Please try add: ```import google.protobuf``` to python script e.g.:
```python
import tensorflow as tf
import google.protobuf

print(">>>> tensorflow version", tf.__version__)

tf.add(1, 2).numpy()
hello = tf.constant('Hello, TensorFlow!')
print(hello.numpy())
```

And then freeze.

**Comment by marcelotduarte** [comment]
File: hello.py
```
import tensorflow as tf
import google.protobuf as gp

print("tensorflow", tf)
print(">>>> tensorflow version", tf.__version__)
print("google.protobuf", gp)
print(">>>> tensorflow version", gp.__version__)

tf.add(1, 2).numpy()
hello = tf.constant('Hello, TensorFlow!')
print(hello.numpy())
```
Using a command like your, but without the incorrect include google (google is not a module, nor a package, it is a namespace):
cxfreeze -O -OO --target-dir=FREEZE_PROJECT --target-name="project" hello.py
Result:
```
(3664) C:\Testes\tf>python -VV
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)]

(3664) C:\Testes\tf>cxfreeze --version
cxfreeze 6.6 Copyright (c) 2020-2021 Marcelo Duarte. All rights reserved.
Copyright (c) 2007-2020 Anthony Tuininga. All rights reserved. Copyright (c)
2001-2006 Computronix Corporation. All rights reserved.

(3664) C:\Testes\tf>FREEZE_PROJECT\project.exe
tensorflow <module 'tensorflow' from 'C:\\Testes\\tf\\FREEZE_PROJECT\\lib\\tensorflow\\__init__.pyc'>
>>>> tensorflow version 2.5.0
google.protobuf <module 'google.protobuf' from 'C:\\Testes\\tf\\FREEZE_PROJECT\\lib\\library.zip\\google\\protobuf\\__init__.pyc'>
>>>> google.protobuf version 3.17.3
2021-06-18 20:25:05.255142: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
b'Hello, TensorFlow!'

(3664) C:\Testes\tf>

```
Note:
I'm using cx-freeze 6.6 to prove that it runs, but with cx-freeze 6.7b6 the result is better for a real use of numpy+mkl

**Comment by kiflowb777** [comment]
With newest cx-freeze this simple code in ```hello.py``` works for me, but when I try freeze my bigger project I notice that there are some differences in ```library.zip```
The ```compiler``` and ```util``` directories are missing from the ```library.zip/google/protobuf/``` directory.

**Comment by kiflowb777** [comment]
WinMerge report (Directories google_1 and google_2 were extracted from the library.zip package):

```
Compare D:\Tests\tf\google_1 with D:\Tests\tf\google_2
20.06.2021 18:54:15
Filename,Folder,Comparison result,Left Date,Right Date,Extension

auth,,,  20.06.2021 18:35:40,* 20.06.2021 18:35:41,
oauth2,,,  20.06.2021 18:35:40,* 20.06.2021 18:35:41,
protobuf,,,  20.06.2021 18:35:41,* 20.06.2021 18:35:42,
__init__.pyc,,Binary files are different,  18.06.2021 19:37:26,* 18.06.2021 20:03:42,pyc
```

```
Compare D:\Tests\tf\google_1\protobuf with D:\Tests\tf\google_2\protobuf
20.06.2021 18:56:00
Filename,Folder,Comparison result,Left Date,Right Date,Extension

compiler,,Right only: D:\Tests\tf\google_2\protobuf,  ,* 20.06.2021 18:35:42,
internal,,,  20.06.2021 18:35:41,* 20.06.2021 18:35:42,
pyext,,,  20.06.2021 18:35:41,* 20.06.2021 18:35:42,
util,,Right only: D:\Tests\tf\google_2\protobuf,  ,* 20.06.2021 18:35:42,
__init__.pyc,,Binary files are different,  18.06.2021 17:54:52,* 18.06.2021 20:03:43,pyc
any_pb2.pyc,,Binary files are different,  18.06.2021 17:54:52,* 18.06.2021 20:03:43,pyc
api_pb2.pyc,,Right only: D:\Tests\tf\google_2\protobuf,  ,* 18.06.2021 20:03:43,pyc
descriptor.pyc,,Binary files are different,  18.06.2021 17:54:52,* 18.06.2021 20:03:43,pyc
descriptor_database.pyc,,Binary files are different,  18.06.2021 17:54:52,* 18.06.2021 20:03:43,pyc
descriptor_pb2.pyc,,Binary files are different,  18.06.2021 17:54:52,* 18.06.2021 20:03:43,pyc
descriptor_pool.pyc,,Binary files are different,  18.06.2021 17:54:52,* 18.06.2021 20:03:43,pyc
duration_pb2.pyc,,Right only: D:\Tests\tf\google_2\protobuf,  ,* 18.06.2021 20:03:43,pyc
empty_pb2.pyc,,Right only: D:\Tests\tf\google_2\protobuf,  ,* 18.06.2021 20:03:43,pyc
field_mask_pb2.pyc,,Right only: D:\Tests\tf\google_2\protobuf,  ,* 18.06.2021 20:03:43,pyc
json_format.pyc,,Binary files are different,  18.06.2021 17:54:52,* 18.06.2021 20:03:43,pyc
message.pyc,,Binary files are different,  18.06.2021 17:54:52,* 18.06.2021 20:03:43,pyc
message_factory.pyc,,Binary files are different,  18.06.2021 17:54:52,* 18.06.2021 20:03:43,pyc
proto_builder.pyc,,Right only: D:\Tests\tf\google_2\protobuf,  ,* 18.06.2021 20:03:43,pyc
reflection.pyc,,Binary files are different,  18.06.2021 17:54:52,* 18.06.2021 20:03:43,pyc
service.pyc,,Right only: D:\Tests\tf\google_2\protobuf,  ,* 18.06.2021 20:03:43,pyc
service_reflection.pyc,,Right only: D:\Tests\tf\google_2\protobuf,  ,* 18.06.2021 20:03:43,pyc
source_context_pb2.pyc,,Right only: D:\Tests\tf\google_2\protobuf,  ,* 18.06.2021 20:03:43,pyc
struct_pb2.pyc,,Binary files are different,  18.06.2021 17:54:52,* 18.06.2021 20:03:43,pyc
symbol_database.pyc,,Binary files are different,  18.06.2021 17:54:52,* 18.06.2021 20:03:43,pyc
text_encoding.pyc,,Binary files are different,  18.06.2021 17:54:52,* 18.06.2021 20:03:43,pyc
text_format.pyc,,Binary files are different,  18.06.2021 17:54:52,* 18.06.2021 20:03:43,pyc
timestamp_pb2.pyc,,Binary files are different,  18.06.2021 17:54:52,* 18.06.2021 20:03:43,pyc
type_pb2.pyc,,Right only: D:\Tests\tf\google_2\protobuf,  ,* 18.06.2021 20:03:43,pyc
wrappers_pb2.pyc,,Binary files are different,  18.06.2021 17:54:52,* 18.06.2021 20:03:43,pyc
```

**Comment by kiflowb777** [comment]
To reproduce the issue with missing files and dirs in ```google``` module please make two files:


```python
# hello_tf.py:
from import_tf import initialize_tensorflow
initialize_tensorflow()
```


```python
# import_tf.py:
def initialize_tensorflow():
    import tensorflow as tf
    print(tf.__version__)
```

And then after freezing you can see that the "library.zip/google/protobuf/" directory is missing files and folders (e.g. ```compiler```, ```utils```, etc.).


Tested on version 6.7b6

**Comment by marcelotduarte** [comment]
For me, this works with 6.7b8.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.7 has just been released.
pip install --upgrade cx_Freeze
Assuming this has been resolved.
If you had issues please open a new issue.
