### ISSUE TITLE
ModuleNotFoundError: No module named 'skimage.feature._orb_descriptor_positions'

### ISSUE THREAD

**Issue by kiflowb777** [marcelotduarte/cx_Freeze#1101]
```
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 81, in run
    module.run()
  File "c:\python36\lib\site-packages\cx_Freeze\initscripts\Console.py", line 36, in run
    exec(code, m.__dict__)
  File "E:\Work\project\start.py", line 15, in <module>
    import albumentations as A
  File "c:\python36\lib\site-packages\albumentations\__init__.py", line 10, in <module>
    from .imgaug.transforms import *
  File "c:\python36\lib\site-packages\albumentations\imgaug\transforms.py", line 1, in <module>
    import imgaug as ia
  File "c:\python36\lib\site-packages\imgaug\__init__.py", line 3, in <module>
    from . import augmenters
  File "c:\python36\lib\site-packages\imgaug\augmenters\__init__.py", line 10, in <module>
    from .segmentation import *
  File "c:\python36\lib\site-packages\imgaug\augmenters\segmentation.py", line 21, in <module>
    from skimage import segmentation, measure
  File "c:\python36\lib\site-packages\skimage\segmentation\__init__.py", line 2, in <module>
    from .active_contour_model import active_contour
  File "c:\python36\lib\site-packages\skimage\segmentation\active_contour_model.py", line 5, in <module>
    from ..filters import sobel
  File "c:\python36\lib\site-packages\skimage\filters\__init__.py", line 18, in <module>
    from .ridges import (meijering, sato, frangi, hessian)
  File "c:\python36\lib\site-packages\skimage\filters\ridges.py", line 18, in <module>
    from ..feature.corner import hessian_matrix, hessian_matrix_eigvals
  File "c:\python36\lib\site-packages\skimage\feature\__init__.py", line 23, in <module>
    from .orb import ORB
  File "c:\python36\lib\site-packages\skimage\feature\orb.py", line 12, in <module>
    from .orb_cy import _orb_loop
  File "skimage\feature\orb_cy.pyx", line 13, in init skimage.feature.orb_cy
ModuleNotFoundError: No module named 'skimage.feature._orb_descriptor_positions'
2021-06-11T17:14:18.870+0200	ERROR	No module named 'skimage.feature._orb_descriptor_positions'	__main__:37a
```

The _orb_descriptor_positions.py/pyc file is missing from the freezed_project/lib/skimage/feature directory

**Desktop (please complete the following information):**
 - Platform information (e.g. Ubuntu Linux 16.04): Windows 10
 - OS architecture (e.g. amd64): 64 bit
 - cx_Freeze version : 6.6
 - Python version : 3.6.1

**Comment by kiflowb777** [comment]
Similar issue on Stack: https://stackoverflow.com/questions/63956604/cxfreeze-modulenotfounderror-no-module-named-skimage-feature-orb-descriptor

**Comment by marcelotduarte** [comment]
include the module with includes=['skimage.feature._orb_descriptor_positions'] in build_exe_options

**Comment by marcelotduarte** [comment]
I updated the hooks, so you do need to use includes.
cx_Freeze 6.7b5 has just been released.
pip install cx-Freeze==6.7b5

Try it out and confirm.

**Comment by kiflowb777** [comment]
> 
> 
> include the module with includes=['skimage.feature._orb_descriptor_positions'] in build_exe_options

That didn't help, but the pip update did. (9.0.1 ->21.1.2)

**Comment by kiflowb777** [comment]
> 
> 
> I updated the hooks, so you do need to use includes.
> cx_Freeze 6.7b5 has just been released.
> pip install cx-Freeze==6.7b5
> 
> Try it out and confirm.

With the newest version of module ```pip``` it works (21.1.2), but with the old one (9.0.1) the problem still exists.

**Comment by marcelotduarte** [comment]
With the new version of pip or with the new version of cx-freeze?
Is with pip 21 and cx-freeze 6.6 works?
Or with pip 21 and cx-freeze 6.7b5 that works?

**Comment by kiflowb777** [comment]
> 
> 
> With the new version of pip or with the new version of cx-freeze?
> Is with pip 21 and cx-freeze 6.6 works?
> Or with pip 21 and cx-freeze 6.7b5 that works?

- cx_Freeze 6.6 + pip 21.1.2 - works,
- cx_Freeze 6.7b5 + pip 21.1.2 - works,
- cx_Freeze 6.6 + pip 9.0.1 - doesn't works,
- cx_Freeze 6.7b5 + pip 9.0.1 - doesn't works,

**Comment by marcelotduarte** [comment]
@kiflowb777  Probably the 6.6 with includes and 6.7b5 can be without includes right?

**Comment by kiflowb777** [comment]
Yes, I try with simple script
```python
# hello_sk.py
import albumentations as a
print(a.__version__)
```
and freeze it with:
```batch
set ROOT=%~dp0
set PYTHON_RAW_PATH=C:\pythons\python361_raw
set PYTHON_PATH=%ROOT%\skvenv

if exist %PYTHON_PATH% rmdir /S /Q %PYTHON_PATH%
%PYTHON_RAW_PATH%\python -m venv %PYTHON_PATH%

set PYTHON_EXE=%PYTHON_PATH%\Scripts\python

"%PYTHON_EXE%" -m pip install albumentations==0.4.5
"%PYTHON_EXE%" -m pip install scikit-image==0.17.2

"%PYTHON_EXE%" -m pip install --upgrade pip
"%PYTHON_EXE%" -m pip install cx-Freeze==6.6

"%PYTHON_EXE%" -m pip list

set CXFREEZE_PATH=%PYTHON_PATH%\Scripts\cxfreeze.exe
echo "%CXFREEZE_PATH%"
"%CXFREEZE_PATH%" -O -OO --target-dir=SK_TEST --target-name="hello_sk.exe" hello_sk.py > freeze.log
```
and then I get:
```batch
ModuleNotFoundError: No module named 'skimage.feature._orb_descriptor_positions'
```

but if I freeze this project with command
```batch
"%CXFREEZE_PATH%" -O -OO --target-dir=SK_TEST --include-modules="skimage.feature._orb_descriptor_positions"  --target-name="hello_sk.exe" hello_sk.py > freeze.log
```
it works.

With cx-Freeze==6.7b6 both works, with and without ```--include-modules="skimage.feature._orb_descriptor_positions"```

**Comment by marcelotduarte** [comment]
cx_Freeze 6.7 has just been released.
pip install --upgrade cx_Freeze
