### ISSUE TITLE
Freezing progress report

### ISSUE THREAD

**Issue by antirotor** [marcelotduarte/cx_Freeze#1133]
**Feature proposal**

This is certainly not that much important feature, but it would be nice to have some progress report for the freezing process. We have cx_freeze wrapped in shell script along with other tasks, its output is redirected to log file. Freezing process can take sometimes minutes and without scrolling output lines visible directly in the console it is difficult to see what's going on.

Simple option that can be turned on can then print into cx_freeze output progress string that can be parsed. So the output will look for example like:

```
Progress: 0%
running build
running build_exe
creating directory build\exe.win-amd64-3.7
copying C:\Python37\python37.dll -> build\exe.win-amd64-3.7\python37.dll
copying C:\Python37\python3.dll -> build\exe.win-amd64-3.7\python3.dll
copying E:\projects\pype\pype-3\.venv\lib\site-packages\cx_Freeze\bases\Win32GUI.exe -> build\exe.win-amd64-3.7\openpype_gui.exe
Stamped: build\exe.win-amd64-3.7\openpype_gui.exe
copying E:\projects\pype\pype-3\.venv\lib\site-packages\cx_Freeze\bases\Console.exe -> build\exe.win-amd64-3.7\openpype_console.exe
Stamped: build\exe.win-amd64-3.7\openpype_console.exe
writing zip file build\exe.win-amd64-3.7\lib\library.zip
Progress: 10%
...
```

This could be enabled by adding `report_progress` option to **build** and/or **build_exe** commands. It could be controlled by `progress_step` to configure how often this progress should be printed.

I am willing to make PR for this. What do you think about it?

**Comment by marcelotduarte** [comment]
A PR is acceptable.
I'm in doubt about the name of the option, but it should be in build_exe.
@cainesi Would you like to give your opinion?

**Comment by cainesi** [comment]
Maybe "percentage_progress"?

But I am not sure how this would work as a percentage.   It seems very complicated to determine what percentage of the way along the job is. E.g., halfway through the Freezer.run(), you don't necessarily know that you're halfway through the freeze. (And you also don't know whether build_exe is going to be followed by some other command that will take additional time and need to be factored into calculating an overall percentage -- but maybe you just care about the freeze itself?)

I suppose what you could do is report the total number of files copied so far?

**Comment by marcelotduarte** [comment]
>  It seems very complicated to determine what percentage of the way along the job

I agree. The ModuleFinder searches recursively.
In the Freeze, can count the detected modules in write_modules.

**Comment by kovar-ursa** [comment]
I either have the same or a related issue. 

I'm trying to build an app on MacOS that uses QT5.

I am running cx-freeze==6.7b4

My setup.py looks like:

`import sys
from cx_Freeze import setup, Executable

# Dependencies are automatically detected, but it might need fine tuning.
# "packages": ["os"] is used as example only
build_exe_options = {"packages": ["PyQt5.QtCore","PyQt5.QtGui", "PyQt5.QtWidgets"], "excludes": ["tkinter"]}

# base="Win32GUI" should be used only for Windows GUI app
base = None
if sys.platform == "win32":
    base = "Win32GUI"

setup(
    name = "UVANDA",
    version = "0.1",
    description = "URSA UAS/CUAS UI application!",
    options = {"build_exe": build_exe_options},
    executables = [Executable("UVANDA", base=base)]
)`

If I build normally and try to run the application, I get:

`Praha:exe.macosx-10.9-x86_64-3.9 kovar$ ./UVANDA 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cx_Freeze/initscripts/__startup__.py", line 81, in run
    module.run()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cx_Freeze/initscripts/Console.py", line 36, in run
    exec(code, m.__dict__)
  File "UVANDA", line 14, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/Users/kovar/work/UVANDA/URSA/UVANDA/Gui/UApplication.py", line 18, in <module>
    from URSA.UVANDA.Windows.UAboutWindow import UAboutWindow
  File "<frozen zipimport>", line 259, in load_module
  File "/Users/kovar/work/UVANDA/URSA/UVANDA/Windows/UAboutWindow.py", line 21, in <module>
    from URSA.UVANDA.Gui.UWindow import UWindow
  File "<frozen zipimport>", line 259, in load_module
  File "/Users/kovar/work/UVANDA/URSA/UVANDA/Gui/UWindow.py", line 20, in <module>
    from PyQt5.QtCore import Qt
ImportError: dlopen(/Users/kovar/work/UVANDA/build/exe.macosx-10.9-x86_64-3.9/lib/PyQt5/QtCore.so, 2): Library not loaded: @loader_path/../../../MacOS/../Frameworks/QtCore.framework/QtCore
  Referenced from: /Users/kovar/work/UVANDA/build/exe.macosx-10.9-x86_64-3.9/lib/PyQt5/QtCore.so
  Reason: image not found`

If I build with bdist_dmg it seg faults in QTCore:

`Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000008
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [46878]

VM Regions Near 0x8:
--> 
    __TEXT                      109659000-10965d000    [   16K] r-x/r-x SM=COW  /Users/*/UVANDA-0.1.app/Contents/MacOS/UVANDA

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.apple.CoreFoundation      	0x00007fff2052e73e _CFGetNonObjCTypeID + 10
1   com.apple.CoreFoundation      	0x00007fff2040a080 CFBundleCopyBundleURL + 14
2   QtCore                        	0x0000000109d7a6ec QLibraryInfo::location(QLibraryInfo::LibraryLocation) + 1260
3   QtCore                        	0x0000000109d7a93e QLibraryInfo::location(QLibraryInfo::LibraryLocation) + 1854
4   QtCore                        	0x0000000109ec8296 0x109d64000 + 1458838`

An aside: Why do we need to do `codesign --remove-signature Python` and is that requirement documented? 

Thank you very much.

**Comment by marcelotduarte** [comment]
@kovar-ursa your comment is out of topic. Please comment on the correct issue.
