### ISSUE TITLE
distorm3 related problem

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#115]
Originally reported by: **Anonymous**

----------------------------------------

Hi,
I am not able to run a program that uses distorm3 lib. This package tries to dynamic load .dll-s, and I included them, but no success.

Thanks

Doing a simple example:
## t.py ##

```
#!python


import distorm3, os, sys
print 'hello'
```

and my setup script is like this:

```
#!python


import sys
from cx_Freeze import setup, Executable

binincludes = ['distorm3.dll']
binpaths = ['.']

includefiles = ['distorm3.dll']

exe = Executable(
    script="t.py",
    )

setup(
    name = "blab",
    version = "0.1",
    options = {"build_exe": {'copy_dependent_files':True, 'create_shared_zip':True, 'bin_includes':binincludes, 'bin_path_includes':binpaths, 'include_files':includefiles, 'packages':["distorm3"]}},
    executables = [exe]
    )

```

## Executing t.exe: ##

```
#!python

Traceback (most recent call last):
File "C:\Programs\Python27-amd64\lib\site-packages\cx_freeze-4.3.3-py2.7-win-amd64.egg\cx_Freeze\initscripts\Console.py", line 27, in <module>
exec(code, m.dict)
File "t.py", line 1, in <module>
File "C:\Programs\Python27-amd64\lib\site-packages\distorm3__init__.py", line 47, in <module>
raise ImportError("Error loading the diStorm dynamic library (or cannot load library into process).")
ImportError: Error loading the diStorm dynamic library (or cannot load library into process).


## distorm3 code looks like this ##
```

```
#!python



# Guess the DLL filename and load the library.
_distorm_path = split(__file__)[0]
potential_libs = ['distorm3.dll', 'libdistorm3.dll', 'libdistorm3.so', 'libdistorm3.dylib']
lib_was_found = False
for i in potential_libs:
    try:
        _distorm_file = join(_distorm_path, i)
        _distorm = cdll.LoadLibrary(_distorm_file)
        lib_was_found = True
    except OSError:
        pass

if lib_was_found == False:
    raise ImportError("Error loading the diStorm dynamic library (or cannot load library into process).")
```

So, distorm3 tries to load the .dll from here:
\testetest\build\exe.win-amd64-2.7\library.zip\distorm3\distorm3.dll

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/115

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Closing due to inactivity.
