### ISSUE TITLE
TypeError: gen_id() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by Dennis-Asamoah** [marcelotduarte/cx_Freeze#1184]
**Describe the bug**
the command "python setup.py bdist_msi"  gives this error  "TypeError: gen_id() takes 2 positional arguments but 3 were given". However when i use python setup.py build it builds successfully

**To Reproduce**

in the setup.py
#########################################################
```
import sys
from cx_Freeze import setup, Executable

base = None
if sys.platform == "win32":
    base = "Win32GUI"

build_exe={"packages":["PySide2","numpy","cv2","cryptography","psutil"],
"include_files":["saved_videos/","be.ico","settings.png","persist1.pickle","coco.names","nn.txt","froz.txt","eng.txt"]
}

executables = [
    Executable("main.py", base=base,icon="be.ico",shortcutDir="Desktop")
]

setup(
    name="Be",
    version="0.2",
    description="Sample cx_Freeze PySide2 script",
    options={"build_exe":build_exe},
    executables=executables
)
```
############################################
and run "python setup.py bdist_msi"

**Expected behavior**
 an msi installer output  

**Desktop Info
 - Platform information (windows 8.1):
 - OS architecture (e.g. 64bit):
 - cx_Freeze version [ 6.7]:
 - Python version [ 3.7 32bit]:

**Comment by marcelotduarte** [comment]
I cannot reproduce this issue. Can you put more information?
- if your installation is from python.org, conda, etc.
- complete traceback

**Comment by Dennis-Asamoah** [comment]
Installation is from python.org . Also i only encountered the problem in  version cx-freeze 6.7.
The other version (version 6.6) works without any error with the same setup.py .

**Comment by marcelotduarte** [comment]
Can you put a complete traceback?

**Comment by Dennis-Asamoah** [comment]
```
Traceback (most recent call last):
  File "setup.py", line 98, in <module>
    executables=executables
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\cx_Freeze\dist.py",  line 437, in setup
    distutils.core.setup(**attrs)
  File "C:\Program Files (x86)\Python37-32\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Program Files (x86)\Python37-32\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Program Files (x86)\Python37-32\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\cx_Freeze\windist.py", line 968, in run
    self.add_files()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\cx_Freeze\windist.py", line 326, in add_files
    keyfile=file,
  File "C:\Program Files (x86)\Python37-32\lib\msilib\__init__.py", line 276, in start_component
    keyid = self.cab.gen_id(self.absolute, keyfile)
TypeError: gen_id() takes 2 positional arguments but 3 were given
```

**Comment by marcelotduarte** [comment]
Can you test for me with the previous beta versions, I believe that the bug was introduced between 6.7b1 6.7b or 6.7b3 but I release 8 betas.
To install beta:
pip install cx_Freeze==6.7b1 

Test and put the traceback if necessary (see the previous comment edited).

**Comment by Dennis-Asamoah** [comment]
i tested 6.7b1,6.7b2....6.7b8(all the 6.7betas) and they all gave the same error .

Traceback (most recent call last):
  File "setup.py", line 98, in <module>
    executables=executables
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\cx_Freeze\dist.py",
 line 434, in setup
    distutils.core.setup(**attrs)
  File "C:\Program Files (x86)\Python37-32\lib\distutils\core.py", line 148, in
setup
    dist.run_commands()
  File "C:\Program Files (x86)\Python37-32\lib\distutils\dist.py", line 966, in
run_commands
    self.run_command(cmd)
  File "C:\Program Files (x86)\Python37-32\lib\distutils\dist.py", line 985, in
run_command
    cmd_obj.run()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\cx_Freeze\windist.p
y", line 968, in run
    self.add_files()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\cx_Freeze\windist.p
y", line 326, in add_files
    keyfile=file,
  File "C:\Program Files (x86)\Python37-32\lib\msilib\__init__.py", line 276, in
 start_component
    keyid = self.cab.gen_id(self.absolute, keyfile)
TypeError: gen_id() takes 2 positional arguments but 3 were given

*************************************************************************************************************
then i tested  6.8b1 and it gave me the below error:

Traceback (most recent call last):
  File "setup.py", line 98, in <module>
    executables=executables
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\cx_Freeze\dist.py",
 line 437, in setup
    distutils.core.setup(**attrs)
  File "C:\Program Files (x86)\Python37-32\lib\distutils\core.py", line 148, in
setup
    dist.run_commands()
  File "C:\Program Files (x86)\Python37-32\lib\distutils\dist.py", line 966, in
run_commands
    self.run_command(cmd)
  File "C:\Program Files (x86)\Python37-32\lib\distutils\dist.py", line 985, in
run_command
    cmd_obj.run()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\cx_Freeze\windist.p
y", line 925, in run
    self.run_command("build")
  File "C:\Program Files (x86)\Python37-32\lib\distutils\cmd.py", line 313, in r
un_command
    self.distribution.run_command(command)
  File "C:\Program Files (x86)\Python37-32\lib\distutils\dist.py", line 985, in
run_command
    cmd_obj.run()
  File "C:\Program Files (x86)\Python37-32\lib\distutils\command\build.py", line
 135, in run
    self.run_command(cmd_name)
  File "C:\Program Files (x86)\Python37-32\lib\distutils\cmd.py", line 313, in r
un_command
    self.distribution.run_command(command)
  File "C:\Program Files (x86)\Python37-32\lib\distutils\dist.py", line 985, in
run_command
    cmd_obj.run()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\cx_Freeze\dist.py",
 line 305, in run
    freezer.Freeze()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\cx_Freeze\freezer.p
y", line 609, in Freeze
    self._write_modules(filename, self.finder)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\cx_Freeze\freezer.p
y", line 489, in _write_modules
    print("Removing", folder_to_remove + "...")
TypeError: unsupported operand type(s) for +: 'WindowsPath' and 'str'

**Comment by marcelotduarte** [comment]
6.8b1 has this bug. 
Between version 6.6 (April 14) and 6.7b1 (May 23), there are five PR to this module. But I think that the offending is the first (see PR #1032) because introduces a new comparison.
Do you use some bdis_msi option?

**Comment by Cimbali** [comment]
I think the issue is an msilib that’s not up to date, no? It should look like this, not like `keyid = self.cab.gen_id(self.absolute, keyfile)` which causes the error

https://github.com/python/cpython/blob/c174eafc33999b9e773a5ea9561ad38886f1a0e6/Lib/msilib/__init__.py#L275-L277

This was fixed 2 years ago, see https://github.com/python/cpython/commit/c8d5bf6c3fa09b43f6a5ee779d493d251dbcc53c

**Comment by marcelotduarte** [comment]
@Dennis-Asamoah What is the version of python 3.7? You should upgrade to 3.7.4 or up (3.7.9 is the last with an installer).
Please report
Thanks @Cimbali

**Comment by Dennis-Asamoah** [comment]
Ok thanks @marcelotduarte and @Cimbali . 
Please i  want to ask if there is a way to run the setup once only on a single pc ,after which the setup cannot run on any other pc, or a way to automatically delete the setup after it finishes installing .

**Comment by marcelotduarte** [comment]
I did not understand your question. Are you looking for a way to protect the installation, for example, against piracy?

So to confirm the issue: What is your installed version of python 3.7?

**Comment by Dennis-Asamoah** [comment]
My python  version is 3.7.2.    

Yes to prevent against piracy. I want the software created to run only on one single pc. Meaning after installation, is there a way to prevent the .msi from being run on other pc after the first installation on an initial pc.  In other words the .msi becomes unusable after using it only once .I would be happy if you help me.

**Comment by marcelotduarte** [comment]
This is off-topic. You should find some package or a method to license your program.
msi is modifiable and not protected. See https://stackoverflow.com/questions/56969925/how-to-protect-msi-against-modification

**Comment by Cimbali** [comment]
I think the only thing you can do with msi is add signatures, and I don’t know how you’d do that with `cx_Freeze`. You certainly can’t delete the installer (and then what? users could copy the file before installing, no? Or get it again from where they got it from?) − on the contrary I think windows often keeps a copy of the installer in some system directory to know how to *un*install. 

But that’s indeed unrelated to the bug.

**Comment by marcelotduarte** [comment]
> the only thing you can do with msi is add signatures, and I don’t know how you’d do that with `cx_Freeze`

In #203 has a method

**Comment by Dennis-Asamoah** [comment]
@Cimbali  and @marcelotduarte ,
 thank you guys

**Comment by marcelotduarte** [comment]
Documentation updated: https://cx-freeze.readthedocs.io/en/latest/setup_script.html#cmdoption-arg-extensions
