### ISSUE TITLE
Unsupported operand types() for +: `PosixPath' and 'str'

### ISSUE THREAD

**Issue by bartoszek** [marcelotduarte/cx_Freeze#1189]
I'm experiencing an issue when trying to use `cx_Freeze:6.8b1` against `python:3.9.6` on ArchLinux.

When packaging `freezer.py` complains about: `TypeError: unsupported operand type(s) for +: 'PosixPath' and 'str'`
```py
Traceback (most recent call last):
  File "/build/meshroom-git/src/meshroom/setup.py", line 130, in <module>
    setup(
  File "/usr/lib/python3.9/site-packages/cx_Freeze/dist.py", line 437, in setup
    distutils.core.setup(**attrs)
  File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.9/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.9/site-packages/cx_Freeze/dist.py", line 305, in run
    freezer.Freeze()
  File "/usr/lib/python3.9/site-packages/cx_Freeze/freezer.py", line 609, in Freeze
    self._write_modules(filename, self.finder)
  File "/usr/lib/python3.9/site-packages/cx_Freeze/freezer.py", line 489, in _write_modules
    print("Removing", folder_to_remove + "...")
TypeError: unsupported operand type(s) for +: 'PosixPath' and 'str'
```

`cx_Freeze:3.7` works fine with a small tweak back ported from `cx_Freeze:3.8b1`: https://github.com/marcelotduarte/cx_Freeze/commit/030dd1177c7b7019fb753cd62d0548763805f31c

**Comment by marcelotduarte** [comment]
This was already fixed in the main branch.
If you have a C compiler, you can use it:
pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@main

**Comment by bartoszek** [comment]
Thanks, will check and report if working.

**Comment by marcelotduarte** [comment]
[cx_Freeze 6.8b2](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.8b2) has just been released.
Please, try it out and report.
pip install cx-Freeze==6.8b2

**Comment by marcelotduarte** [comment]
pip install cx-Freeze==6.8b4

**Comment by marcelotduarte** [comment]
cx_Freeze 6.8 has just been released.
pip install --upgrade cx_Freeze
Assuming this has been resolved.
If you had issues please open a new issue.
