### ISSUE TITLE
cx_Freeze.freezer.ConfigError: no file named sys (for module boto.compat.sys)

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#121]
Originally reported by: **Anonymous**

----------------------------------------

This error occurs trying to freeze an app using boto 2.32 or higher.  The boto.compat module is the source of the error, and I suspect that it is the local vendored.six module that is providing Python 2/3 compatibility.  I googled up a number of folks having the same issue trying to freeze apps with panda or scapy which also import boto.

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/121

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anonymous**:

----------------------------------------

Traceback?

**Comment by anthony-tuininga** [comment]
*Original comment by* **Scott Leerssen (Bitbucket: [sleerssen](https://bitbucket.org/sleerssen), GitHub: [sleerssen](https://github.com/sleerssen))**:

----------------------------------------


```
#!python

Traceback (most recent call last):
  File "setup.py", line 47, in <module>
    executables = executables
  File "/build/lib/python2.7/site-packages/cx_Freeze/dist.py", line 362, in setup
    distutils.core.setup(**attrs)
  File "/build/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/build/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/build/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/build/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/build/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/build/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/build/lib/python2.7/site-packages/cx_Freeze/dist.py", line 232, in run
    freezer.Freeze()
  File "/build/lib/python2.7/site-packages/cx_Freeze/freezer.py", line 610, in Freeze
    self.compress, self.copyDependentFiles)
  File "/build/lib/python2.7/site-packages/cx_Freeze/freezer.py", line 510, in _WriteModules
    module.Create(finder)
  File "/build/lib/python2.7/site-packages/cx_Freeze/freezer.py", line 746, in Create
    module.file, module.name)
cx_Freeze.freezer.ConfigError: no file named sys (for module boto.compat.sys)

```

**Comment by anthony-tuininga** [comment]
*Original comment by* **Scott Leerssen (Bitbucket: [sleerssen](https://bitbucket.org/sleerssen), GitHub: [sleerssen](https://github.com/sleerssen))**:

----------------------------------------

I think I managed to hack around the problem by adding the following to the build options in setup.py:


```
#!python

    excludes = ["boto.compat"],
    zip_includes = [
        (os.path.join(os.environ['CX_FREEZE_PYTHON_BACKING'], 'boto/compat.py'),
         "boto/compat.py")
        ],
    packages = [ # product specific stuff removed
                "boto.vendored",
                "email",                          # used by boto
                "email.mime",                     # used by boto
                ],
```

The CX_FREEZE_PYTHON_BACKING is simply an environment variable that points to where the boto sources live.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**:

----------------------------------------

See also issue #99, which I think is essentially the same problem.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Brandon King (Bitbucket: [kingb](https://bitbucket.org/kingb), GitHub: [kingb](https://github.com/kingb))**:

----------------------------------------

I documented my answer for bypassing this problem on [stackoverflow](http://stackoverflow.com/questions/23094751/cx-freeze-fails-to-create-exe-with-pandas-library/27514272#27514272).

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Closing due to inactivity. 
If you had issues please re-open.
