### ISSUE TITLE
ImportError: DLL load failed while importing _multiarray_umath

### ISSUE THREAD

**Issue by jekoie** [marcelotduarte/cx_Freeze#1213]
I use `cx_Freeze` to freeze python app, it run my PC　work well, But when I copy to my friend PC, it run errors?

```console
C:\Users\IPC\Desktop\t\exe.win32-3.8>PLC-Log.exe
Traceback (most recent call last):
  File "D:\python38_x32\lib\site-packages\numpy\core\__init__.py", line 22, in <module>
  File "D:\python38_x32\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
  File "D:\python38_x32\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
ImportError: DLL load failed while importing _multiarray_umath: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python38_x32\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 104, in run
  File "D:\python38_x32\lib\site-packages\cx_Freeze\initscripts\Console.py", line 15, in run
  File "main.py", line 14, in <module>
  File "D:\python38_x32\lib\site-packages\numpy\__init__.py", line 150, in <module>
  File "D:\python38_x32\lib\site-packages\numpy\core\__init__.py", line 48, in <module>
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "C:\Users\IPC\Desktop\t\exe.win32-3.8\PLC-Log.exe"
  * The NumPy version is: "1.21.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: 找不到指定的模块。


C:\Users\IPC\Desktop\t\exe.win32-3.8>
```

**Comment by marcelotduarte** [comment]
**Desktop (please complete the following information):**
 - Platform information (e.g. Ubuntu Linux 16.04): Windows
 - OS architecture (e.g. amd64): 
 - cx_Freeze version [e.g. 6.6]:
 - Python version [e.g. 3.9]:

Your python version in from python.org, anaconda, etc?
numpy and numpy+mkl works well with cx-freeze 6.7 but the anaconda version works better with 6.8b3
Are you using msvcrt option?
https://cx-freeze.readthedocs.io/en/latest/faq.html#microsoft-visual-c-redistributable-package

**Comment by marcelotduarte** [comment]
cx_Freeze 6.8 has just been released.
Closing due to lack of information.
If you had issues please open a new issue.
