### ISSUE TITLE
ImportError: DLL load failed while importing QtCore ?

### ISSUE THREAD

**Issue by jekoie** [marcelotduarte/cx_Freeze#1253]
Hi, I write a very simple app, but cx_Freeze can't freeze it?

```console
Traceback (most recent call last):
  File "D:\python38\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 104, in run
    module_init.run(name + "__main__")
  File "D:\python38\lib\site-packages\cx_Freeze\initscripts\Console.py", line 15, in run
    exec(code, module_main.__dict__)
  File "main.py", line 1, in <module>
ImportError: DLL load failed while importing QtCore: 找不到指定的模块。
```

**lib folder**
![image](https://user-images.githubusercontent.com/6836400/134663822-9dcd00c0-39ec-401a-b779-feea2f01c9eb.png)

** build_exe_options **
```python
build_exe_options = {
    'include_files': [os.path.join(sys.prefix, "python3.dll"), os.path.join(sys.prefix, "vcruntime140.dll")],
    "packages": ["PyQt5", "numpy", "multiprocessing"],
    'excludes': [
        'IPython', 'jupyter_client', 'ipykernel', 'jedi', 'jinjia2', 'jupyter_core', 'nbconvert',
        'ipython_genutils', 'nbformat', 'notebook', 'faker', "asyncio", "email", "lib2to3", "tkinter",
        "sqlite3", "test", "win32com", "PySide6", "cffi", "unittest", "mypy", "pandas", "setuptools"
    ],
    'include_msvcr': True,
    "no_compress": False,
}
```

**Code**
```python
from PyQt5.QtCore import QCoreApplication, QTimer, QStandardPaths
import multiprocessing as mp
import logging
from openpyxl import Workbook
from openpyxl.chart import (LineChart,Reference)

import json
import os
import numpy as np
import datetime
import shutil
import psutil

def main_here():pass

if __name__ == "__main__":
    app = QCoreApplication([])

    main_here()

    timer = QTimer()
    timer.setInterval(1000)
    timer.timeout.connect(lambda: print("abc") )
    timer.start()

    app.exec()

```

**Comment by marcelotduarte** [comment]
python 3.8.10
pip install pyqt5 openpyxl numpy psutil
cxfreeze test.py
build and run
and build and run with the following setup.py
```

import sys
from cx_Freeze import setup, Executable

# base="Win32GUI" should be used only for Windows GUI app
base = None
#if sys.platform == "win32":
#    base = "Win32GUI"

build_exe_options = {
    "excludes": [
        'IPython', 'jupyter_client', 'ipykernel', 'jedi', 'jinjia2', 'jupyter_core', 'nbconvert',
        'ipython_genutils', 'nbformat', 'notebook', 'faker', "asyncio", "email", "lib2to3", "tkinter",
        "sqlite3", "test", "win32com", "PySide6", "cffi", "unittest", "mypy", "pandas", "setuptools"
    ],
    'include_msvcr': True,
}

executables = [Executable("test.py", base=base)]

setup(
    name="test",
    version="0.1",
    description="test",
    options={
        "build_exe": build_exe_options,
    },
    executables=executables,
)
```

**Comment by marcelotduarte** [comment]
Does the [pyqt5 sample](https://github.com/marcelotduarte/cx_Freeze/tree/main/cx_Freeze/samples/pyqt5) build and run for you?

**Comment by jekoie** [comment]
Update to lastest version the problem disappear.

**Comment by Laaettr** [comment]
This issue has returned for me in v7.1.1. I was able to resolve it by downgrading to v7.0.0 of cx_Freeze. Running Python 3.11 in a conda environment on a Windows 10 OS

**Comment by marcelotduarte** [comment]
@Laaettr Can you test the latest development build?
`pip install --force --no-cache --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`

**Comment by marcelotduarte** [comment]
[Release 7.2.0](https://github.com/marcelotduarte/cx_Freeze/releases/tag/7.2.0) is out!
[Documentation](https://cx-freeze.readthedocs.io)
