### ISSUE TITLE
bdist_dmg stops with TypeError of subprocess.py

### ISSUE THREAD

**Issue by ehki** [marcelotduarte/cx_Freeze#1269]
**Describe the bug**

`bdist_dmg` option stops with following error:
```
...
creating build/dist/test_dist-0.1.app/Contents/Frameworks
copying build/test_dist-0.1.app/Contents/Info.plist -> build/dist/test_dist-0.1.app/Contents
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    setup(
  File "/Users/username/opt/miniconda3/envs/cxtest/lib/python3.8/site-packages/cx_Freeze/dist.py", line 447, in setup
    setuptools.setup(**attrs)
  File "/Users/username/opt/miniconda3/envs/cxtest/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/Users/username/opt/miniconda3/envs/cxtest/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/username/opt/miniconda3/envs/cxtest/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/username/opt/miniconda3/envs/cxtest/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/username/opt/miniconda3/envs/cxtest/lib/python3.8/site-packages/cx_Freeze/macdist.py", line 104, in run
    self.execute(self.buildDMG, ())
  File "/Users/username/opt/miniconda3/envs/cxtest/lib/python3.8/distutils/cmd.py", line 335, in execute
    util.execute(func, args, msg, dry_run=self.dry_run)
  File "/Users/username/opt/miniconda3/envs/cxtest/lib/python3.8/distutils/util.py", line 303, in execute
    func(*args)
  File "/Users/username/opt/miniconda3/envs/cxtest/lib/python3.8/site-packages/cx_Freeze/macdist.py", line 90, in buildDMG
    if subprocess.call(("hdiutil", createargs)) != 0:
  File "/Users/username/opt/miniconda3/envs/cxtest/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Users/username/opt/miniconda3/envs/cxtest/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/username/opt/miniconda3/envs/cxtest/lib/python3.8/subprocess.py", line 1639, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
TypeError: expected str, bytes or os.PathLike object, not list
```

**To Reproduce**
- Compile sample (cx_Freeze/samples/distutils) with `python setup.py bdist_dmg` command.

**Expected behavior**

Successful build of .dmg file.

**Desktop (please complete the following information):**
 - Platform information (e.g. Ubuntu Linux 16.04): Mac OS X 11.4
 - OS architecture (e.g. amd64): arm64
 - cx_Freeze version [e.g. 6.6]: 6.8.1
 - Python version [e.g. 3.9]: 3.8.12

**Additional context**

This issue can be solved by changing lines 89-92 of `macdist.py` from
```
    # Create the dmg
    if subprocess.call(("hdiutil", createargs)) != 0:
        raise OSError("creation of the dmg failed")
```
to
```
    # Create the dmg
    # if subprocess.call(("hdiutil", createargs)) != 0:
    if subprocess.call(createargs) != 0:
        raise OSError("creation of the dmg failed")
```

**Comment by ehki** [comment]
Oh, this is a duplication of #1260 and already solved...

**Comment by marcelotduarte** [comment]
[cx_Freeze 6.8.2](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.8.2) has just been released.
pip install --upgrade cx_Freeze

**Comment by ehki** [comment]
Thanks, cx_Freeze is a really good tool.
