### ISSUE TITLE
Executable with Simple Dash Example Fails

### ISSUE THREAD

**Issue by KarthikAbiram** [marcelotduarte/cx_Freeze#1273]
First off, I would like to thank the developers for their efforts in providing us with this essential building tool :)

**Describe the bug**
Used cx_Freeze on the [dash example](https://dash.plotly.com/layout). When launching the built executable, it results in below error:
```
D:\Python\dash_with_cx_freeze\build\exe.win32-3.7>dash_example.exe
Traceback (most recent call last):
  File "C:\Users\karthik.abiram\.virtualenvs\dash_with_cx_freeze-CUQpB3_U\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 113, in run
    module_init.run(name + "__main__")
  File "C:\Users\karthik.abiram\.virtualenvs\dash_with_cx_freeze-CUQpB3_U\Lib\site-packages\cx_Freeze\initscripts\Console.py", line 15, in run
    exec(code, module_main.__dict__)
  File "dash_example.py", line 4, in <module>
  File "C:\Users\karthik.abiram\.virtualenvs\dash_with_cx_freeze-CUQpB3_U\lib\site-packages\dash\__init__.py", line 5, in <module>
    from .dash import Dash, no_update  # noqa: F401,E402
  File "C:\Users\karthik.abiram\.virtualenvs\dash_with_cx_freeze-CUQpB3_U\lib\site-packages\dash\dash.py", line 66, in <module>
    _flask_compress_version = parse_version(get_distribution("flask-compress").version)
  File "C:\Users\karthik.abiram\.virtualenvs\dash_with_cx_freeze-CUQpB3_U\lib\site-packages\pkg_resources\__init__.py", line 466, in get_distribution
    dist = get_provider(dist)
  File "C:\Users\karthik.abiram\.virtualenvs\dash_with_cx_freeze-CUQpB3_U\lib\site-packages\pkg_resources\__init__.py", line 342, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "C:\Users\karthik.abiram\.virtualenvs\dash_with_cx_freeze-CUQpB3_U\lib\site-packages\pkg_resources\__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Users\karthik.abiram\.virtualenvs\dash_with_cx_freeze-CUQpB3_U\lib\site-packages\pkg_resources\__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'flask-compress' distribution was not found and is required by the application
```

**To Reproduce**
I am attaching the example code, which reproduces the issue.
[dash_with_cx_freeze.zip](https://github.com/marcelotduarte/cx_Freeze/files/7452471/dash_with_cx_freeze.zip)
This includes the pipfile and pipfile.lock, which specifies the version of the packages being used.
Build command used:
`cxfreeze -c dash_example.py`

**Desktop (please complete the following information):**
 - Windows 10 64-bit
 - cx_Freeze version: 6.8.1
 - Python version:  3.7
 - Dash: 2.0.0
 - Pandas: 1.3.4

**Additional context**
Tried Python 3.9 as well and faced the same issue.
[dash_with_cx_freeze.zip](https://github.com/marcelotduarte/cx_Freeze/files/7452471/dash_with_cx_freeze.zip)

Relates to https://github.com/marcelotduarte/cx_Freeze/issues/1041. 
Creating a new ticket since the above one is closed as per this [suggestion](https://twitter.com/dan_abramov/status/992773032325341184?lang=en), which makes sense.

Any help on this would be greatly useful :)

**Comment by marcelotduarte** [comment]
[cx_Freeze 6.8.4](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.8.4) has just been released.
pip install --upgrade cx_Freeze
Assuming this has been resolved.
If you had issues please open a new issue.
