### ISSUE TITLE
Unknown module loader on MacOS

### ISSUE THREAD

**Issue by heinermann** [marcelotduarte/cx_Freeze#1284]
I'm encountering what seems like an obscure error in a Github Actions mac build. I don't know what to make of it, or whether it's a regression since an older version of cx_freeze doesn't encounter this error.

```txt
running build
running build_exe
Traceback (most recent call last):
  File "/Users/runner/work/PyMS/PyMS/setup.py", line 53, in <module>
    setup(
  File "/Users/runner/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/site-packages/cx_Freeze/dist.py", line 447, in setup
    setuptools.setup(**attrs)
  File "/Users/runner/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/Users/runner/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/runner/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/runner/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/runner/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/Users/runner/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/runner/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/runner/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/site-packages/cx_Freeze/dist.py", line 317, in run
    freezer.Freeze()
  File "/Users/runner/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/site-packages/cx_Freeze/freezer.py", line 618, in Freeze
    self._freeze_executable(executable)
  File "/Users/runner/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/site-packages/cx_Freeze/freezer.py", line 206, in _freeze_executable
    finder.IncludeFile(exe.main_script, exe.main_module_name)
  File "/Users/runner/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/site-packages/cx_Freeze/finder.py", line 658, in IncludeFile
    module = self._load_module(name, str(path), deferred_imports)
  File "/Users/runner/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/site-packages/cx_Freeze/finder.py", line 447, in _load_module
    raise ImportError(f"Unknown module loader in {path}", name=name)
ImportError: Unknown module loader in PyAI.pyw
```

- Source: https://github.com/heinermann/PyMS/tree/bundle
- Python: CPython 3.9.8
- [Environment](https://github.com/actions/virtual-environments#available-environments): macOS 10.15 (macos-latest)
- cx_freeze: 6.6.0 and 6.8.2
- Action failure with cx_freeze 6.8.2: https://github.com/heinermann/PyMS/runs/4261678315
- Action failure with cx_freeze 6.6.0: https://github.com/heinermann/PyMS/runs/4261883605

This issue doesn't happen in cx_freeze 6.4.2 ([this build](https://github.com/heinermann/PyMS/runs/4261606509), fails for other reasons unrelated to this issue).

cx_freeze 6.5 gives a [different error](https://github.com/heinermann/PyMS/runs/4261934181), `ImportError: No module named 'PyAI__main__'` which may or may not be related.

**Comment by marcelotduarte** [comment]
> ImportError: Unknown module loader in PyAI.pyw

.pyw is specific to Windows. If you rename it to .py it will be recognized.

**Comment by marcelotduarte** [comment]
The finder module was rewritten based on importlib.machinery rules. I must add support for this extension to emulate the previous behavior.

**Comment by heinermann** [comment]
> > ImportError: Unknown module loader in PyAI.pyw
> 
> .pyw is specific to Windows. If you rename it to .py it will be recognized.

Thanks, this fixed my issue.

**Comment by marcelotduarte** [comment]
For the other error, DarwinException, You can try to use python setup.py bdist_mac instead of build in cx_Freeze 6.8.2

**Comment by marcelotduarte** [comment]
[cx_Freeze 6.9](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.9) has just been released.
pip install --upgrade cx_Freeze
