### ISSUE TITLE
4.3.1 does not run correctly when installed using easy_install

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#13]
Originally reported by: **Anonymous**

----------------------------------------

I use Ubuntu 12.10 (I have both 32b & 64b versions and the problem seem present with both)

ged@vbox-ubuntu-12:~/devel/liam2/trunk/src/ > python setup.py build
running build
running build_ext
skipping 'groupby.c' Cython extension (up-to-date)
running build_exe
Traceback (most recent call last):
  File "setup.py", line 47, in <module>
    executables=[Executable("main.py")])
  File "/usr/local/lib/python2.7/dist-packages/cx_Freeze-4.3.1-py2.7-linux-x86_64.egg/cx_Freeze/dist.py", line 365, in setup
    distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/dist-packages/cx_Freeze-4.3.1-py2.7-linux-x86_64.egg/cx_Freeze/dist.py", line 234, in run
    metadata = metadata)
  File "/usr/local/lib/python2.7/dist-packages/cx_Freeze-4.3.1-py2.7-linux-x86_64.egg/cx_Freeze/freezer.py", line 104, in __init__
    self._VerifyConfiguration()
  File "/usr/local/lib/python2.7/dist-packages/cx_Freeze-4.3.1-py2.7-linux-x86_64.egg/cx_Freeze/freezer.py", line 466, in _VerifyConfiguration
    self._GetInitScriptFileName()
  File "/usr/local/lib/python2.7/dist-packages/cx_Freeze-4.3.1-py2.7-linux-x86_64.egg/cx_Freeze/freezer.py", line 311, in _GetInitScriptFileName
    raise ConfigError("no initscript named %s", name)
cx_Freeze.freezer.ConfigError: no initscript named Console

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/13

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
