### ISSUE TITLE
Dash + Pywebview | Cx_Freeze exe combination throws "System.Reflection.TargetInvocationException"

### ISSUE THREAD

**Issue by rms4698** [marcelotduarte/cx_Freeze#1333]
**Describe the bug**
Hi team, I am using Dash + Pywebview combination to create web app using python. This works in local & when I tried to build an EXE using CX_freeze & when I run the exe it throws the following error
```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary 2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary 2.TryGetValue(TKey key, TValue& value)
   at Python.Runtime.Runtime.InitializePlatformData()
   at Python.Runtime.Runtime.Initialize(Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable 1 args, Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.InitExt()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at clrModule.PyInit_clr()
```

**To Reproduce**
This error can be reproduced by creating exe for the following python code.

```
import dash
from dash import html
from threading import Thread
import webview

app = dash.Dash(__name__)
app.layout = html.Div("Hi")

if __name__ == "__main__":
    def run_app():
        app.run_server(debug=False)
    t = Thread(target=run_app)
    t.daemon = True
    t.start()
    window = webview.create_window("App", "http://127.0.0.1:8050/")
    webview.start(debug=False)
```

**Expected behavior**
I would like the EXE to run without any issues since the same piece of code works without EXE.

**Desktop (please complete the following information):**
 - Platform information :Windows 10
 - OS architecture : 64-bit operating system, x64-based processor
 - cx_Freeze version : 6.9
 - Python version : 3.8
 - OS build : 19042.1415

**Additional context**
I have tried Dash + CX freeze & it works also Pywebview + CX freeze and that also works. The above error is coming only if I have Dash + Pywebview + CX freeze.

Also, I referred https://github.com/marcelotduarte/cx_Freeze/issues/1049 where someone had similar issue and I ran those test scripts they run perfectly.  Also when I try to create exe using pyinstaller, that also works. But I prefer CX_freeze than pyinstaller because of it's cleaner structure.  Any inputs would be greatly helpful. Thanks. (I have attached a folder to recreate the issue).
[app.zip](https://github.com/marcelotduarte/cx_Freeze/files/7821273/app.zip)

**Comment by marcelotduarte** [comment]
[cx_Freeze 6.10](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.10) has just been released.

**Comment by rms4698** [comment]
Thanks a lot for update.
