### ISSUE TITLE
Cannot package jsonschema

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#136]
Originally reported by: **Ian Bell (Bitbucket: [ibell](https://bitbucket.org/ibell), GitHub: [ibell](https://github.com/ibell))**

----------------------------------------

Cross-posted to jsonschema issues, but here is the problem:

cx_Freeze cannot package jsonschema, and I was wondering whether you had any experience with this.

A simple minimal working example:
```
import sys
from cx_Freeze import setup, Executable

build_exe_options = {"packages": ["os"], "excludes": ["tkinter"]}

setup(  name = "test",
        version = "0.0",
        description = "My GUI application!",
        options = {"build_exe": build_exe_options},
        executables = [Executable("test.py")])
```
where the contents of ``test.py`` are simply
```
import jsonschema
```
I get the traceback:
```
running build
running build_exe
copying C:\Users\ihb\AppData\Local\Continuum\Miniconda\lib\site-packages\cx_Freeze\bases\Console.exe -> build\exe.win-amd64-2.7\test.exe
copying C:\Users\ihb\AppData\Local\Continuum\Miniconda\python27.dll -> build\exe.win-amd64-2.7\python27.dll
Stamped: build\exe.win-amd64-2.7\test
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    executables = [Executable("test.py")])
  File "C:\Users\ihb\AppData\Local\Continuum\Miniconda\lib\site-packages\cx_Freeze\dist.py", line 362, in setup
    distutils.core.setup(**attrs)
  File "C:\Users\ihb\AppData\Local\Continuum\Miniconda\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Users\ihb\AppData\Local\Continuum\Miniconda\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Users\ihb\AppData\Local\Continuum\Miniconda\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Users\ihb\AppData\Local\Continuum\Miniconda\lib\distutils\command\build.py", line 127, in run
    self.run_command(cmd_name)
  File "C:\Users\ihb\AppData\Local\Continuum\Miniconda\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "C:\Users\ihb\AppData\Local\Continuum\Miniconda\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Users\ihb\AppData\Local\Continuum\Miniconda\lib\site-packages\cx_Freeze\dist.py", line 232, in run
    freezer.Freeze()
  File "C:\Users\ihb\AppData\Local\Continuum\Miniconda\lib\site-packages\cx_Freeze\freezer.py", line 626, in Freeze
    self.compress, self.copyDependentFiles)
  File "C:\Users\ihb\AppData\Local\Continuum\Miniconda\lib\site-packages\cx_Freeze\freezer.py", line 526, in _WriteModules
    module.Create(finder)
  File "C:\Users\ihb\AppData\Local\Continuum\Miniconda\lib\site-packages\cx_Freeze\freezer.py", line 762, in Create
    module.file, module.name)
cx_Freeze.freezer.ConfigError: no file named sys (for module collections.sys)
```

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/136

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anthony Tuininga (Bitbucket: [anthony_tuininga](https://bitbucket.org/anthony_tuininga), GitHub: Unknown)**:

----------------------------------------

Corrected by commit https://bitbucket.org/anthony_tuininga/cx_freeze/commits/c580734d42274df3080679cfb637b4dd475f2fa0

cx_Freeze was attempting a relative import of a builtin module and incorrectly considering it an extension found within a package.
