### ISSUE TITLE
4.3.1 fails to run on ubuntu 64b

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#14]
Originally reported by: **Gaëtan de Menten (Bitbucket: [gdementen](https://bitbucket.org/gdementen), GitHub: [gdementen](https://github.com/gdementen))**

----------------------------------------

I use Ubuntu 12.10. cx_Freeze seem to work fine on Ubuntu 32b (when installed manually using "sudo python setup.py install") but not on Ubuntu 64b

    :::bash
    ged@vbox-ubuntu-12:~/devel/liam2/trunk/src/ > python setup.py build
    running build
    running build_ext
    skipping 'groupby.c' Cython extension (up-to-date)
    running build_exe
    Traceback (most recent call last):
      File "setup.py", line 47, in <module>
        executables=[Executable("main.py")])
      File "/usr/local/lib/python2.7/dist-packages/cx_Freeze/dist.py", line 365, in setup
      File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python2.7/dist-packages/cx_Freeze/dist.py", line 235, in run
      File "/usr/local/lib/python2.7/dist-packages/cx_Freeze/freezer.py", line 567, in Freeze
    ImportError: No module named util

    ged@vbox-ubuntu-12:~/devel/liam2/trunk/src/ > cd /usr/local/lib/python2.7/dist-packages/cx_Freeze/
    ged@vbox-ubuntu-12:/usr/local/lib/python2.7/dist-packages/cx_Freeze/ > echo $PYTHONPATH 
    .:/home/ged/devel/sqlalchemy/trunk/lib:/home/ged/devel/elixir/trunk:
    ged@vbox-ubuntu-12:/usr/local/lib/python2.7/dist-packages/cx_Freeze/ > python
    Python 2.7.3 (default, Sep 26 2012, 21:51:14) 
    [GCC 4.7.2] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import util
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: No module named util
    >>> 
    ged@vbox-ubuntu-12:/usr/local/lib/python2.7/dist-packages/cx_Freeze/ > cd ~/devel/cx_Freeze-4.3.1/build/lib.linux-x86_64-2.7/cx_Freeze/
    ged@vbox-ubuntu-12:~/devel/cx_Freeze-4.3.1/build/lib.linux-x86_64-2.7/cx_Freeze/ > ls
    bases  dist.py  finder.py  freezer.py  hooks.py  __init__.py  macdist.py  main.py  setupwriter.py  util.so  windist.py
    ged@vbox-ubuntu-12:~/devel/cx_Freeze-4.3.1/build/lib.linux-x86_64-2.7/cx_Freeze/ > python 
    Python 2.7.3 (default, Sep 26 2012, 21:51:14) 
    [GCC 4.7.2] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import util
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    SystemError: dynamic module not initialized properly
    >>> 

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/14

**Comment by anthony-tuininga** [comment]
*Original comment by* **Gaëtan de Menten (Bitbucket: [gdementen](https://bitbucket.org/gdementen), GitHub: [gdementen](https://github.com/gdementen))**:

----------------------------------------

Here is the log file I got when installing cx_Freeze:

    sudo python setup.py install > install.log

I hope it helps debug the problem.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Gaëtan de Menten (Bitbucket: [gdementen](https://bitbucket.org/gdementen), GitHub: [gdementen](https://github.com/gdementen))**:

----------------------------------------

ok, I found what the problem was. It was simply bad permissions on util.so (it was 770 instead of 755). There was another permission problem for bases but that one was trivial to solve since the error message actually include "permission denied". All this time wasted for that. grrr... Anyway, now I am unsure whether this is caused by my particular setup or if it is actually a problem in cx_Freeze setup.py.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**:

----------------------------------------

If you've got time, can you grab a clean download of the source, and recompile it to see if the problem reappears? On my 32 bit Ubuntu system, util.so is generated with mode 775.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Closing due to inactivity. 
If you had issues please re-open.
