### ISSUE TITLE
cx_freeze has problems with gtk

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#147]
Originally reported by: **Anonymous**

----------------------------------------

Hi there,

see the attached minimal code example. When I run

$ python minimal-gdk-problem.py,

everything works.
If I do

$ python setup.py build_exe

$ build\exe.win-amd64-2.7\minimal-gdk-problem.exe

I get a popup titled

cx_Freeze: Python error in main script

saying

Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
    exec(code, m.__dict__)
  File "minimal-gdk-problem.py", line 5, in <module>
    window =  gtk.Window(gtk.WINDOW_TOPLEVEL)
AttributeError: 'module' object has no attribute 'Window'

Environment:
Win7, Python 2.7, 64bit, Anaconda distribution, 
pygtk from http://www.lfd.uci.edu/~gohlke/pythonlibs/#pygtk, 
GTK from http://www.gtk.org/download/win64.php

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/147

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Closing due to inactivity. 
If you had issues please re-open.
