### ISSUE TITLE
Running frozen app with Python 3.5 (No module named '_frozen_importlib_external')

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#156]
Originally reported by: **Aivar Annamaa (Bitbucket: [aivarannamaa](https://bitbucket.org/aivarannamaa), GitHub: [aivarannamaa](https://github.com/aivarannamaa))**

----------------------------------------

After freezing a Tkinter program in Windows 7 with Python 3.5 32bit and running it, I got following error

```
#!none

Traceback (most recent call last):
  File "X:\Python35-x32\lib\importlib\_bootstrap.py", line 1140, in _install
  File "X:\Python35-x32\lib\importlib\_bootstrap.py", line 969, in _find_and_load
  File "X:\Python35-x32\lib\importlib\_bootstrap.py", line 956, in _find_and_load_unlocked
ImportError: No module named '_frozen_importlib_external'
Fatal Python error: Py_Initialize: importlib install failed

Current thread 0x000004f4 (most recent call first):

```

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/156

**Comment by anthony-tuininga** [comment]
*Original comment by* **Julien Duponchelle (Bitbucket: [jduponchelle](https://bitbucket.org/jduponchelle), GitHub: Unknown)**:

----------------------------------------

I got the same issue on OSX

**Comment by anthony-tuininga** [comment]
*Original comment by* **Julien Duponchelle (Bitbucket: [jduponchelle](https://bitbucket.org/jduponchelle), GitHub: Unknown)**:

----------------------------------------

The code from _bootstrap.py:

```
#!python

def _install(sys_module, _imp_module):
    """Install importlib as the implementation of import."""
    _setup(sys_module, _imp_module)

    sys.meta_path.append(BuiltinImporter)
    sys.meta_path.append(FrozenImporter)

    global _bootstrap_external
    import _frozen_importlib_external
    _bootstrap_external = _frozen_importlib_external
    _frozen_importlib_external._install(sys.modules[__name__])
```

I think the issue is the import cx_freeze can't see the import and will not embed the package _frozen_importlib_external.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Julien Duponchelle (Bitbucket: [jduponchelle](https://bitbucket.org/jduponchelle), GitHub: Unknown)**:

----------------------------------------

I can fix the crash by modifying finder.py:

After

```
#!python

        if sys.version_info[:2] >= (3, 4):
            # We need this, because collections gets loaded (via traceback),
            # and a partially frozen package causes problems.
            self.IncludeModule("collections.abc")
```

Add

```
#!python

        if sys.version_info[:2] >= (3,5):
            self.IncludeModule("importlib.abc")
```

But after that it doesn't work and doesn't found my main module.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Julien Duponchelle (Bitbucket: [jduponchelle](https://bitbucket.org/jduponchelle), GitHub: Unknown)**:

----------------------------------------

The main module not found is specific to our code because we use a custom initscript. 

I will make a PR for the current issue.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Julien Duponchelle (Bitbucket: [jduponchelle](https://bitbucket.org/jduponchelle), GitHub: Unknown)**:

----------------------------------------

PR opened:
https://bitbucket.org/anthony_tuininga/cx_freeze/pull-requests/82/python-35-compatibility/diff

**Comment by anthony-tuininga** [comment]
*Original comment by* **Julien Duponchelle (Bitbucket: [jduponchelle](https://bitbucket.org/jduponchelle), GitHub: Unknown)**:

----------------------------------------

I also backport the fix for the 4.x branch
https://bitbucket.org/anthony_tuininga/cx_freeze/pull-requests/83/python-35-compatibility-for-cx_freeze-4x/diff

**Comment by anthony-tuininga** [comment]
*Original comment by* **Antoine Martin (Bitbucket: [totaam](https://bitbucket.org/totaam), GitHub: [totaam](https://github.com/totaam))**:

----------------------------------------

4 months without any activity - does this mean cx_freeze is no longer maintained? 3.5 is current.

**Comment by anthony-tuininga** [comment]
*Original comment by* **jean-patrick francoia (Bitbucket: [jean_patrick_francoia](https://bitbucket.org/jean_patrick_francoia), GitHub: Unknown)**:

----------------------------------------

I don't know if it's no longer maintained, but the pypi version is clearly outdated, a lot of patches are not included in the packaged. Including this one. I had to manually apply patches, while bugs are long known and patched.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Aivar Annamaa (Bitbucket: [aivarannamaa](https://bitbucket.org/aivarannamaa), GitHub: [aivarannamaa](https://github.com/aivarannamaa))**:

----------------------------------------

I was able to use cx_freeze repository version with Python 3.5

**Comment by anthony-tuininga** [comment]
*Original comment by* **Antoine Martin (Bitbucket: [totaam](https://bitbucket.org/totaam), GitHub: [totaam](https://github.com/totaam))**:

----------------------------------------

@aivarannamaa: thanks, that's good to know.
It would be a lot easier if there was a supported release, so we can just pip install it and get on with more productive things.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anthony Tuininga (Bitbucket: [anthony_tuininga](https://bitbucket.org/anthony_tuininga), GitHub: Unknown)**:

----------------------------------------

All, cx_Freeze is not dead, it's just "resting". :-) Honestly, the new version should have been out months ago but there is one matter that needs to be resolved yet and one enhancement that needs to be completed and I simply haven't found the time yet. :-( Coming soon, really!

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anthony Tuininga (Bitbucket: [anthony_tuininga](https://bitbucket.org/anthony_tuininga), GitHub: Unknown)**:

----------------------------------------

I've just checked in a change to deal with the issues I was experiencing with Python 3.5. Now that that is out of the way I can deal with the final enhancement -- that of supporting packages being stored outside of the zip files in order to avoid incompatibilities with certain packages.

**Comment by anthony-tuininga** [comment]
*Original comment by* **sazearte (Bitbucket: [sazearte](https://bitbucket.org/sazearte), GitHub: [sazearte](https://github.com/sazearte))**:

----------------------------------------

I have this error too.

I'm in windows 7 64bits, with python3.5 64 bits.
I try to use your fix but not work with me.

I downloaded with version: http://www.lfd.uci.edu/~gohlke/pythonlibs/#cx_freeze
cx_Freeze-4.3.4-cp35-none-win_amd64.whl

Have you solution ?

**Comment by anthony-tuininga** [comment]
*Original comment by* **Sebastian Krause (Bitbucket: [sekrause](https://bitbucket.org/sekrause), GitHub: [sekrause](https://github.com/sekrause))**:

----------------------------------------

Since the current development version works fine with Python 3.5, but nobody has created an easily installable release for everyone to use, I've done just that and published some pre-built binary Python Wheels of the cx_Freeze 5.0 development version: https://github.com/sekrause/cx_Freeze-Wheels

**Comment by anthony-tuininga** [comment]
*Original comment by* **timeyyy (Bitbucket: [timeyyy](https://bitbucket.org/timeyyy), GitHub: [timeyyy](https://github.com/timeyyy))**:

----------------------------------------

i get the same error with python3.4

**Comment by anthony-tuininga** [comment]
*Original comment by* **Diogo Pereira (Bitbucket: [diogocp](https://bitbucket.org/diogocp), GitHub: [diogocp](https://github.com/diogocp))**:

----------------------------------------

@anthony_tuininga It's been six months since you fixed Python 3.5 compatibility. It would be great if you could just make a release, even without the other planned enhancements.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Sebastian Krause (Bitbucket: [sekrause](https://bitbucket.org/sekrause), GitHub: [sekrause](https://github.com/sekrause))**:

----------------------------------------

I completely agree to just create a 5.0 release with what you have now. The repository of unofficial Windows Wheels I mentioned above has turned out to be quite popular and so far I haven't heard any complaints, so people are already using cx_Freeze 5.0 with Python 3.5 on Windows anyway. An official release on PyPI with pre-built Wheels for Windows would make things so much easier for everyone.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anthony Tuininga (Bitbucket: [anthony_tuininga](https://bitbucket.org/anthony_tuininga), GitHub: Unknown)**:

----------------------------------------

You make a good point. I'll give up trying to integrate the last set of changes and call those 5.1 instead. I am gone for the next two weeks, though, so it will have to wait until I return. My apologies for the lengthy delay!

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anthony Tuininga (Bitbucket: [anthony_tuininga](https://bitbucket.org/anthony_tuininga), GitHub: Unknown)**:

----------------------------------------

The cx_Freeze 5.0 release has FINALLY been made. Apologies for the delay!
