### ISSUE TITLE
ssl issue with python 3.10 and latest cx freeze

### ISSUE THREAD

**Issue by jony89** [marcelotduarte/cx_Freeze#1582]
**Describe the bug**

**To Reproduce**
my setup py is:

```
from cx_Freeze import setup, Executable

# Dependencies are automatically detected, but it might need
# fine tuning.
build_exe_options = {"packages": ["httpx", "ssl"], "excludes": []}

base = None

executables = [Executable("./src/app/app.py", base=base)]

"""include the file of the package from python/anaconda installation """
include_files = [""]

setup(
    name="**",
    version="0.2.2",
    description="",
    options={"build_exe": build_exe_options},
    executables=executables,
)
```

then I ran:

` python setup.py build`

**Expected behavior**
when I try to run the `build/app` file I get an unclear exception

**Screenshots**
```
Traceback (most recent call last):
  File "/python3.10/site-packages/cx_Freeze/initscripts/__startup__.py", line 120, in run
    module_init.run(name + "__main__")
  File "/python3.10/site-packages/cx_Freeze/initscripts/Console.py", line 16, in run
    exec(code, module_main.__dict__)
  File "src/app/app.py", line 2, in <module>
  File "/__init__.py", line 1, in <module>
    from .app import commands_app
  File "/app.py", line 3, in <module>
    from app.commands.get_commands import get_app
  File "/commands/get_commands.py", line 1, in <module>
    from app.services.controller_api import ControllerAPI
  File "/services/controller_api.py", line 2, in <module>
    from **.async_client_httpx import APIClient
  File "/python3.10/site-packages/**/async_client_httpx.py", line 5, in <module>
    import httpx
  File "/python3.10/site-packages/httpx/__init__.py", line 2, in <module>
    from ._api import delete, get, head, options, patch, post, put, request, stream
  File "/python3.10/site-packages/httpx/_api.py", line 4, in <module>
    from ._client import Client
  File "/python3.10/site-packages/httpx/_client.py", line 9, in <module>
    from ._auth import Auth, BasicAuth, FunctionAuth
  File "/python3.10/site-packages/httpx/_auth.py", line 10, in <module>
    from ._models import Request, Response
  File "/python3.10/site-packages/httpx/_models.py", line 10, in <module>
    from ._content import ByteStream, UnattachedStream, encode_request, encode_response
  File "/python3.10/site-packages/httpx/_content.py", line 18, in <module>
    from ._multipart import MultipartStream
  File "/python3.10/site-packages/httpx/_multipart.py", line 7, in <module>
    from ._types import (
  File "/python3.10/site-packages/httpx/_types.py", line 5, in <module>
    import ssl
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: dlopen(**/lib/_ssl.cpython-310-darwin.so, 2): Library not loaded: @loader_path/../lib/libssl.1.1.dylib
  Referenced from: **/lib/_ssl.cpython-310-darwin.so
  Reason: image not found
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

```

## env

mac big sur 11.4
 - cx_Freeze version [e.g. 6.11]: 6.11.1
 - Python version [e.g. 3.10]: 3.10.2

**Comment by marcelotduarte** [comment]
Can you test with the development version?

To install the latest development build:

`pip install --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`

If you are using conda, use:

`conda install -y --no-channel-priority -S -c https://marcelotduarte.github.io/packages/conda cx_Freeze`

**Comment by marcelotduarte** [comment]
> then I ran:
> 
> ` python setup.py build`

Another possibility is to try with:
`python setup.py bdist_mac`

**Comment by marcelotduarte** [comment]
I made a patch. Please test and give me feedback. See more: https://github.com/marcelotduarte/cx_Freeze/issues/1548#issuecomment-1617572177

**Comment by marcelotduarte** [comment]
[Release 6.15.3](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.15.3) is out!
