### ISSUE TITLE
cannot install cx_freeze with pip3 (python 3.4 x64 under ubuntu 14.04 x64)

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#159]
Originally reported by: **Marcio Marchini (Bitbucket: [sglebs](https://bitbucket.org/sglebs), GitHub: [sglebs](https://github.com/sglebs))**

----------------------------------------

After having the problem #153, I had this error:

```
(und2s101)marcio@marcio-virtual-machine:~/git/und2s101$ paver build_linux---> pavement.build_linux
Requirement already satisfied (use --upgrade to upgrade): cx-Freeze in /home/marcio/venvs/und2s101/lib/python3.4/site-packages/cx_Freeze-5.0-py3.4-linux-x86_64.egg
Cleaning up...
Traceback (most recent call last):
  File "/home/marcio/venvs/und2s101/bin/cxfreeze", line 5, in <module>
    pkg_resources.run_script('cx-Freeze==5.0', 'cxfreeze')
  File "/home/marcio/venvs/und2s101/lib/python3.4/site-packages/pkg_resources.py", line 488, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/marcio/venvs/und2s101/lib/python3.4/site-packages/pkg_resources.py", line 1354, in run_script
    execfile(script_filename, namespace, namespace)
  File "/home/marcio/venvs/und2s101/lib/python3.4/site-packages/pkg_resources.py", line 55, in execfile
    exec(compile(open(fn).read(), fn, 'exec'), globs, locs)
  File "/home/marcio/venvs/und2s101/lib/python3.4/site-packages/cx_Freeze-5.0-py3.4-linux-x86_64.egg/EGG-INFO/scripts/cxfreeze", line 5, in <module>
    main()
  File "/home/marcio/venvs/und2s101/lib/python3.4/site-packages/cx_Freeze-5.0-py3.4-linux-x86_64.egg/cx_Freeze/main.py", line 176, in main
    silent = options.silent)
  File "/home/marcio/venvs/und2s101/lib/python3.4/site-packages/cx_Freeze-5.0-py3.4-linux-x86_64.egg/cx_Freeze/freezer.py", line 144, in __init__
    self._VerifyConfiguration()
  File "/home/marcio/venvs/und2s101/lib/python3.4/site-packages/cx_Freeze-5.0-py3.4-linux-x86_64.egg/cx_Freeze/freezer.py", line 451, in _VerifyConfiguration
    executable._VerifyConfiguration(self)
  File "/home/marcio/venvs/und2s101/lib/python3.4/site-packages/cx_Freeze-5.0-py3.4-linux-x86_64.egg/cx_Freeze/freezer.py", line 604, in _VerifyConfiguration
    self._GetInitScriptFileName()
  File "/home/marcio/venvs/und2s101/lib/python3.4/site-packages/cx_Freeze-5.0-py3.4-linux-x86_64.egg/cx_Freeze/freezer.py", line 624, in _GetInitScriptFileName
    self.initScript = get_resource_file_path("initscripts", name, ".py")
  File "/home/marcio/venvs/und2s101/lib/python3.4/site-packages/cx_Freeze-5.0-py3.4-linux-x86_64.egg/cx_Freeze/freezer.py", line 99, in get_resource_file_path
    if os.path.isabs(name):
  File "/home/marcio/venvs/und2s101/lib/python3.4/posixpath.py", line 63, in isabs
    return s.startswith(sep)
AttributeError: 'NoneType' object has no attribute 'startswith'
(und2s101)marcio@marcio-virtual-machine:~/git/und2s101$ ^C
```

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/159

**Comment by anthony-tuininga** [comment]
*Original comment by* **Marcio Marchini (Bitbucket: [sglebs](https://bitbucket.org/sglebs), GitHub: [sglebs](https://github.com/sglebs))**:

----------------------------------------

I had a similar problem under Windows after patching for #153.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Tim Kacprowski (Bitbucket: [tim_kacprowski](https://bitbucket.org/tim_kacprowski), GitHub: Unknown)**:

----------------------------------------

same here.
patched the source via 'if True' hack, now     if os.path.isabs(name):
  File "/usr/lib/python2.7/posixpath.py", line 61, in isabs
    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'

i'm on ubunut 14.04, using python 2.7

**Comment by anthony-tuininga** [comment]
*Original comment by* **Walker Inman (Bitbucket: [swinman](https://bitbucket.org/swinman), GitHub: [swinman](https://github.com/swinman))**:

----------------------------------------

this is happening for me as well: ubuntu 14.04, python 3.4

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anthony Tuininga (Bitbucket: [anthony_tuininga](https://bitbucket.org/anthony_tuininga), GitHub: Unknown)**:

----------------------------------------

Fixed by
https://bitbucket.org/anthony_tuininga/cx_freeze/commits/a69936ec621ceb936c535dc09c2fc5c1ae25aae6
