### ISSUE TITLE
ImportError: cannot import name 'nonlin' from partially initialized module 'scipy.optimize' (most likely due to a circular import) ([...]\lib\scipy\optimize\__init__.pyc)

### ISSUE THREAD

**Issue by gergely-elias** [marcelotduarte/cx_Freeze#1598]
**Describe the bug**
Frozen version of our project raises an ImportError at the start. The unfrozen version does not suffer from similar problems.
I suspect the source of the problem must be one of these two dependencies: numpy==1.23.2, scikit-image==0.19.3
Project name redacted in the stacktrace below.

```
Traceback (most recent call last):
  File "[...]\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 113, in run
    module_init.run(name + "__main__")
  File "[...]\Lib\site-packages\cx_Freeze\initscripts\Console.py", line 15, in run
    exec(code, module_main.__dict__)
  File "[...].py", line 1, in <module>
  File "[...].py", line 8, in <module>
    from skimage.transform import resize
  File "[...]\lib\site-packages\skimage\transform\__init__.py", line 4, in <module>
    from .radon_transform import (radon, iradon, iradon_sart,
  File "[...]\lib\site-packages\skimage\transform\radon_transform.py", line 6, in <module>
    from ._warps import warp
  File "[...]\lib\site-packages\skimage\transform\_warps.py", line 9, in <module>
    from ..measure import block_reduce
  File "[...]\lib\site-packages\skimage\measure\__init__.py", line 6, in <module>
    from ._polygon import approximate_polygon, subdivide_polygon
  File "[...]\lib\site-packages\skimage\measure\_polygon.py", line 2, in <module>
    from scipy import signal
  File "[...]\lib\site-packages\scipy\__init__.py", line 211, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
  File "[...]\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "[...]\lib\site-packages\scipy\signal\__init__.py", line 323, in <module>
    from ._filter_design import *
  File "[...]\lib\site-packages\scipy\signal\_filter_design.py", line 16, in <module>
    from scipy import special, optimize, fft as sp_fft
  File "[...]\lib\site-packages\scipy\__init__.py", line 211, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
  File "[...]\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "[...]\lib\site-packages\scipy\optimize\__init__.py", line 428, in <module>
    from . import (
ImportError: cannot import name 'nonlin' from partially initialized module 'scipy.optimize' (most likely due to a circular import) 
```
I tried `--packages=llvmlite.binding` based on what I found on StackOverflow, but it didn't help.

**Desktop (please complete the following information):**
 - Platform information (e.g. Ubuntu Linux 22.04): Windows 10
 - OS architecture (e.g. amd64): x64
 - cx_Freeze version [e.g. 6.11]: 6.11.1
 - Python version [e.g. 3.10]: 3.9.7

I'm happy to contribute, but will definitely need some guidance with that.
Thanks!

**Comment by marcelotduarte** [comment]
Probably you must use:
--packages=scipy.optimize or --packages=scipy

**Comment by gergely-elias** [comment]
none of these seem to work unfortunately

**Comment by marcelotduarte** [comment]
Can you make a simple sample to reproduce the error?

**Comment by gergely-elias** [comment]
It looks like reorganizing the imports resolved my problem. Thanks for the help!
