### ISSUE TITLE
No module named 'shiboken2.shiboken2'

### ISSUE THREAD

**Issue by EuphoricCatface** [marcelotduarte/cx_Freeze#1679]
**Describe the bug**
When trying to run a frozen PySide2 app, the application errors out with `ModuleNotFoundError: No module named 'shiboken2.shiboken2'`

```
PySide2/__init__.py: Unable to import shiboken2 from /home/pi/pyside2_cxfreeze_test/build/exe.linux-armv7l-3.9/lib/library.zip, /home/pi/pyside2_cxfreeze_test/build/exe.linux-armv7l-3.9/lib
Traceback (most recent call last):
  File "/home/pi/pyside2_cxfreeze_test/venv-arm/lib/python3.9/site-packages/cx_Freeze/initscripts/__startup__.py", line 138, in run
    module_init.run(name + "__main__")
  File "/home/pi/pyside2_cxfreeze_test/venv-arm/lib/python3.9/site-packages/cx_Freeze/initscripts/console.py", line 16, in run
    exec(code, module_main.__dict__)  # pylint: disable=exec-used
  File "test.py", line 1, in <module>
  File "/usr/lib/python3/dist-packages/PySide2/__init__.py", line 107, in <module>
    _setupQtDirectories()
  File "/usr/lib/python3/dist-packages/PySide2/__init__.py", line 58, in _setupQtDirectories
    import shiboken2
  File "/usr/lib/python3/dist-packages/shiboken2/__init__.py", line 27, in <module>
    from .shiboken2 import *
ModuleNotFoundError: No module named 'shiboken2.shiboken2'
```

**To Reproduce**
Create a simple pyside2 example  
Freeze the application with `cxfreeze main.py`  
Run the frozen application

**Expected behavior**
The application runs a simple blank dialog

**Desktop (please complete the following information):**
 - Platform information (e.g. Ubuntu Linux 22.04): Raspberry Pi OS 2022-09-22
 - OS architecture (e.g. amd64): ARM 32bit environment
 - cx_Freeze version [e.g. 6.11]: 6.12.0 - 6.13.1
 - Python version [e.g. 3.10]: 3.9.2

**Additional context**
PySide2 5.15.2 was installed with apt, and then the venv was created with `--system-site-packages` option, because PySide2 is not available on PyPi for ARM 32bit environment.  
I was able to make it work after downgrading cx_Freeze to 6.11.1, so I think it might be a regression problem.

**Comment by marcelotduarte** [comment]
Can you test with the sample? https://github.com/marcelotduarte/cx_Freeze/tree/main/samples/pyside2
To build: `python setup.py build`

**Comment by EuphoricCatface** [comment]
I'm getting the same error
```
PySide2/__init__.py: Unable to import shiboken2 from /home/pi/cxfreeze/cx_Freeze/samples/pyside2/build/exe.linux-armv7l-3.9/lib/library.zip, /home/pi/cxfreeze/cx_Freeze/samples/pyside2/build/exe.linux-armv7l-3.9/lib
Traceback (most recent call last):
  File "/home/pi/cxfreeze/cx_Freeze/samples/pyside2/venv-arm/lib/python3.9/site-packages/cx_Freeze/initscripts/__startup__.py", line 138, in run
    module_init.run(name + "__main__")
  File "/home/pi/cxfreeze/cx_Freeze/samples/pyside2/venv-arm/lib/python3.9/site-packages/cx_Freeze/initscripts/console.py", line 16, in run
    exec(code, module_main.__dict__)  # pylint: disable=exec-used
  File "test_pyside2.py", line 5, in <module>
  File "/usr/lib/python3/dist-packages/PySide2/__init__.py", line 107, in <module>
    _setupQtDirectories()
  File "/usr/lib/python3/dist-packages/PySide2/__init__.py", line 58, in _setupQtDirectories
    import shiboken2
  File "/usr/lib/python3/dist-packages/shiboken2/__init__.py", line 27, in <module>
    from .shiboken2 import *
ModuleNotFoundError: No module named 'shiboken2.shiboken2'
```

EDIT: In this case, cx_Freeze 6.11.1 fails with a different error
```
Traceback (most recent call last):
  File "/home/pi/cxfreeze/cx_Freeze/samples/pyside2/venv-arm/lib/python3.9/site-packages/cx_Freeze/initscripts/__startup__.py", line 120, in run
    module_init.run(name + "__main__")
  File "/home/pi/cxfreeze/cx_Freeze/samples/pyside2/venv-arm/lib/python3.9/site-packages/cx_Freeze/initscripts/Console.py", line 16, in run
    exec(code, module_main.__dict__)
  File "test_pyside2.py", line 5, in <module>
    from PySide2.QtCore import Qt
  File "/usr/lib/python3/dist-packages/PySide2/__init__.py", line 112, in <module>
  File "shibokensupport/__feature__.py", line 142, in _import
ModuleNotFoundError: No module named 'PySide2.QtCore'
```
The sample runs fine when not frozen.

EDIT2: with `cxfreeze test_pyside2.py` and `cx_Freeze==6.11.1`, the frozen binary works fine.

**Comment by marcelotduarte** [comment]
Can you test with [latest version](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.14.7)?

**Comment by Stewie055** [comment]
> Can you test with [latest version](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.14.7)?

6.15 still has the bug. Cx_Freeze==6.11.1 works fine for me.

I compared the packed shiboken2 files using these two version  and find the difference.

shiboken2  when using cx_freeze version 6.11.1. It works find.

```
│  concrt140.dll
│  msvcp140.dll
│  msvcp140_1.dll
│  msvcp140_2.dll
│  msvcp140_codecvt_ids.dll
│  shiboken2.abi3.dll
│  shiboken2.abi3.lib
│  shiboken2.pyd
│  ucrtbase.dll
│  vcamp140.dll
│  vccorlib140.dll
│  vcomp140.dll
│  vcruntime140.dll
│  vcruntime140_1.dll
│  __init__.pyc
```
shiboken2  when using cx_freeze version   6.15. It raises ModuleNotFoundError.
```
│  shiboken2.abi3.dll
│  shiboken2.abi3.lib
│  shiboken2.pyd
│  __init__.pyc
```
It seems that there are some vcruntime and msvc dll missing under  version 6.15

**Comment by marcelotduarte** [comment]
[Release 6.15.3](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.15.3) is out!

I used the sample: https://github.com/marcelotduarte/cx_Freeze/tree/main/samples/pyside2
I tested with this version in Linux Ubuntu w/ Python 3.10.6 and Windows w/ Python 3.10.11
It works!

Please check that in setup.py it is using "zip_include_packages": ["PySide2"]

Please, give me feedback.

**Comment by marcelotduarte** [comment]
@Aaron1992 

You can test the patch in the latest development build:
`pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`

**Comment by marcelotduarte** [comment]
[Release 6.15.8](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.15.8) is out!
