### ISSUE TITLE
Unable to freeze pythonnet using cx_freeze in Ubuntu

### ISSUE THREAD

**Issue by nitishsharma25** [marcelotduarte/cx_Freeze#1683]
**Describe the bug**
Freezd application using pythonnet is failing during execution. It is working fine locally without freezing.
Project Code attached and freezd application attached below.

**Error Logs:** 

Failed to initialize pythonnet: System.TypeInitializationException: The type initializer for 'Delegates' threw an exception.
 ---> Python.Runtime.BadPythonDllException: Runtime.PythonDLL was not set or does not point to a supported Python runtime DLL. See https://github.com/pythonnet/pythonnet#embedding-python-in-net
 ---> System.MissingMethodException: Failed to load symbol Py_Main: ./test: undefined symbol: Py_Main
   at Python.Runtime.Platform.PosixLoader.GetFunction(IntPtr dllHandle, String name) in /tmp/build-via-sdist-dq4gmg3h/pythonnet-3.0.1/src/runtime/Native/LibraryLoader.cs:line 85
   at Python.Runtime.Runtime.Delegates.GetFunctionByName(String functionName, IntPtr libraryHandle) in /tmp/build-via-sdist-dq4gmg3h/pythonnet-3.0.1/src/runtime/Runtime.Delegates.cs:line 296
   --- End of inner exception stack trace ---
   at Python.Runtime.Runtime.Delegates.GetFunctionByName(String functionName, IntPtr libraryHandle) in /tmp/build-via-sdist-dq4gmg3h/pythonnet-3.0.1/src/runtime/Runtime.Delegates.cs:line 300
   at Python.Runtime.Runtime.Delegates..cctor() in /tmp/build-via-sdist-dq4gmg3h/pythonnet-3.0.1/src/runtime/Runtime.Delegates.cs:line 38
   --- End of inner exception stack trace ---
   at Python.Runtime.Runtime.Delegates.get_PyGILState_Ensure() in /tmp/build-via-sdist-dq4gmg3h/pythonnet-3.0.1/src/runtime/Runtime.Delegates.cs:line 319
   at Python.Runtime.Runtime.PyGILState_Ensure() in /tmp/build-via-sdist-dq4gmg3h/pythonnet-3.0.1/src/runtime/Runtime.cs:line 751
   at Python.Runtime.PythonEngine.AcquireLock() in /tmp/build-via-sdist-dq4gmg3h/pythonnet-3.0.1/src/runtime/PythonEngine.cs:line 479
   at Python.Runtime.Py.GILState..ctor() in /tmp/build-via-sdist-dq4gmg3h/pythonnet-3.0.1/src/runtime/Py.cs:line 27
   at Python.Runtime.Py.GIL() in /tmp/build-via-sdist-dq4gmg3h/pythonnet-3.0.1/src/runtime/Py.cs:line 13
   at Python.Runtime.Loader.Initialize(IntPtr data, Int32 size) in /tmp/build-via-sdist-dq4gmg3h/pythonnet-3.0.1/src/runtime/Loader.cs:line 26
   at Python.Runtime.Runtime.Delegates.get_PyGILState_Ensure() in /tmp/build-via-sdist-dq4gmg3h/pythonnet-3.0.1/src/runtime/Runtime.Delegates.cs:line 319
   at Python.Runtime.Runtime.PyGILState_Ensure() in /tmp/build-via-sdist-dq4gmg3h/pythonnet-3.0.1/src/runtime/Runtime.cs:line 751
   at Python.Runtime.PythonEngine.AcquireLock() in /tmp/build-via-sdist-dq4gmg3h/pythonnet-3.0.1/src/runtime/PythonEngine.cs:line 479
   at Python.Runtime.Py.GILState..ctor() in /tmp/build-via-sdist-dq4gmg3h/pythonnet-3.0.1/src/runtime/Py.cs:line 27
   at Python.Runtime.Py.GIL() in /tmp/build-via-sdist-dq4gmg3h/pythonnet-3.0.1/src/runtime/Py.cs:line 13
   at Python.Runtime.Loader.Initialize(IntPtr data, Int32 size) in /tmp/build-via-sdist-dq4gmg3h/pythonnet-3.0.1/src/runtime/Loader.cs:line 26Traceback (most recent call last):
  File "__startup__.py", line 138, in run
  File "console.py", line 16, in run
  File "test.py", line 9, in <module>
  File "pythonnet/__init__.py", line 144, in load
RuntimeError: Failed to initialize Python.Runtime.dll

**To Reproduce**
1. Untar the project file
2. Goto project root
3. run ./build-linux.sh (This install the dotnet runtime required to run test.py file)

**Expected behavior**
The application should work after freezing with cx_frze. It is working with pyinstaller.

**Screenshots**

**Desktop (please complete the following information):**
 - Platform information: Ubuntu 22.04.1
 - OS architecture: amd64
 - cx_Freeze version: 6.13.1
 - Python version: 3.10.6

**Additional context**
test.py file contains the application logic.
**Source Code:** 
[pythonnet-app.tar.gz](https://github.com/marcelotduarte/cx_Freeze/files/10003300/pythonnet-app.tar.gz)

**Comment by rishky1001** [comment]
Hi @marcelotduarte,

I am facing the same problem with cx_freeze.
Can you help in resolving this?

**Comment by marcelotduarte** [comment]
Install cx_Freeze with:
`pip install --no-binary=cx_Freeze cx_Freeze`

**Comment by rishky1001** [comment]
Thanks @marcelotduarte,
It is working with the above solution.

Can you also help me understand why it was not working with the whl?

**Comment by marcelotduarte** [comment]
pythonnet uses a shared lib to connect to python. Using manylinux wheels this is not available.

**Comment by marcelotduarte** [comment]
[Release 6.15.3](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.15.3) is out!

Can you test the two options with the most recent version and give me feedback?
