### ISSUE TITLE
PYSNMP - Error after freezing

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#169]
Originally reported by: **Anonymous**

----------------------------------------

Dear All,

I am facing an issue with an application I wrote, I have no issues while running it normaly, but then once frozen, it's impossible to get it to initialize the pySnmp cmdGen : 

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
    exec(code, m.__dict__)
  File "main.py", line 137, in <module>
  File "main.py", line 123, in init
  File "C:\Users\nicolas.pfefferle\Desktop\VQueue\snmp_schedule.py", line 106, in start_snmp
    start_snmp_task(snmp_config[0], snmp_config[1], int(snmp_config[2]), snmp_config[3], int(snmp_config[4]), int(snmp_config[5]))

  File "C:\Users\nicolas.pfefferle\Desktop\VQueue\snmp_schedule.py", line 82, in start_snmp_task
    task = task_snmp(target, port, oids, community, delay, trace)
  File "C:\Users\nicolas.pfefferle\Desktop\VQueue\snmp_schedule.py", line 23, in __init__
    self.cmdGen = cmdgen.CommandGenerator()
  File "C:\Python27\lib\site-packages\pysnmp\entity\rfc3413\oneliner\cmdgen.py", line 161, in __init__
    self.snmpEngine = snmpEngine or SnmpEngine()
  File "C:\Python27\lib\site-packages\pysnmp\entity\engine.py", line 83, in __init__
    snmpEngineMaxMessageSize, = self.msgAndPduDsp.mibInstrumController.mibBuilder.importSymbols('__SNMP-FRAMEWORK-MIB', 'snmpEngin
eMaxMessageSize')
  File "C:\Python27\lib\site-packages\pysnmp\smi\builder.py", line 372, in importSymbols
    'No module %s loaded at %s' % (modName, self)
pysnmp.smi.error.MibNotFoundError: No module __SNMP-FRAMEWORK-MIB loaded at <pysnmp.smi.builder.MibBuilder instance at 0x02D519E0>

Does anyone ever had a similar issue ? or is PYSNMP know to be incompatible with Cx_Freeze ?

Thanks to all!

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/169

**Comment by marcelotduarte** [comment]
Assuming this has been resolved.
If you had issues please re-open.
