### ISSUE TITLE
Python 3.4 OSX 10.9 cx_freeze 5.0 update breaks

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#171]
Originally reported by: **Franco C (Bitbucket: [francoc](https://bitbucket.org/francoc), GitHub: [francoc](https://github.com/francoc))**

----------------------------------------

Hello,
just updated my ports and cx_freeze (via manual setup.py build/install) and I cannot freeze applications that froze perfectly before updates. It is likely a simple mistake on my part, yet I fail to understand what I did wrong. 

Example: the matplotlib sample in source https://bitbucket.org/anthony_tuininga/cx_freeze/src/aebc9c32615c14137c948c521a8d91562559237c/cx_Freeze/samples/matplotlib/?at=default

Traceback:

```
#!shell

sudo python setup.py bdist_mac
running bdist_mac
running build
running build_exe
Traceback (most recent call last):
  File "setup.py", line 34, in <module>
    options=options
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cx_Freeze-5.0-py3.4-macosx-10.9-x86_64.egg/cx_Freeze/dist.py", line 337, in setup
    distutils.core.setup(**attrs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cx_Freeze-5.0-py3.4-macosx-10.9-x86_64.egg/cx_Freeze/macdist.py", line 232, in run
    self.run_command('build')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/command/build.py", line 126, in run
    self.run_command(cmd_name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cx_Freeze-5.0-py3.4-macosx-10.9-x86_64.egg/cx_Freeze/dist.py", line 206, in run
    metadata = metadata)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cx_Freeze-5.0-py3.4-macosx-10.9-x86_64.egg/cx_Freeze/freezer.py", line 144, in __init__
    self._VerifyConfiguration()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cx_Freeze-5.0-py3.4-macosx-10.9-x86_64.egg/cx_Freeze/freezer.py", line 451, in _VerifyConfiguration
    executable._VerifyConfiguration(self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cx_Freeze-5.0-py3.4-macosx-10.9-x86_64.egg/cx_Freeze/freezer.py", line 605, in _VerifyConfiguration
    self._GetBaseFileName()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cx_Freeze-5.0-py3.4-macosx-10.9-x86_64.egg/cx_Freeze/freezer.py", line 618, in _GetBaseFileName
    self.base = get_resource_file_path("bases", name, ext)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cx_Freeze-5.0-py3.4-macosx-10.9-x86_64.egg/cx_Freeze/freezer.py", line 99, in get_resource_file_path
    if os.path.isabs(name):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/posixpath.py", line 63, in isabs
    return s.startswith(sep)
AttributeError: 'NoneType' object has no attribute 'startswith'


```

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/171

**Comment by anthony-tuininga** [comment]
*Original comment by* **inso (Bitbucket: [inso](https://bitbucket.org/inso), GitHub: [inso](https://github.com/inso))**:

----------------------------------------

Same problem on linux.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Raven King (Bitbucket: [HystericalLich](https://bitbucket.org/HystericalLich), GitHub: Unknown)**:

----------------------------------------

The same issue in linux with python3.5. Also occurs with trivial programs such as:
```
#!python

print('hello world')
```

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Closing due to inactivity. 
If you had issues please re-open.
