### ISSUE TITLE
After freezing missing libtcl8.6.dylib, libtk8.6.dylib and SSL error

### ISSUE THREAD

**Issue by Wathfea** [marcelotduarte/cx_Freeze#1710]
**Describe the bug**
Hello everyone,

First here is my setup.py:

```
import os
import sys
import certifi
from cx_Freeze import setup, Executable


PYTHON_INSTALL_DIR = os.path.dirname(os.path.dirname(os.__file__))

# Adding files
build_exe_options = {
    "include_files": [
        "resources",
        (certifi.where(), 'cacert.pem'),
        os.path.join(PYTHON_INSTALL_DIR, 'libtcl8.6.dylib'),
        os.path.join(PYTHON_INSTALL_DIR, 'libtk8.6.dylib')
    ],
    "includes": ["tkinter"],
}

os.environ["REQUESTS_CA_BUNDLE"] = os.path.join(os.getcwd(), "cacert.pem")
os.environ['TCL_LIBRARY'] = os.path.join(os.getcwd(), 'libtcl8.6.dylib')
os.environ['TK_LIBRARY'] = os.path.join(os.getcwd(), 'libtk8.6.dylib')


base = None
if sys.platform == "win32":
    base = "Win32GUI"

# Targets
mac = Executable(
    "affy.py",
    base=base,
    icon="logo-affy.ico",
    target_name="Affybot",
)

setup(
    name="Affybot",
    version="1.0",
    description="Description",
    author="David Perlusz",
    options={
        "build_exe": build_exe_options
    },
    executables=[mac],
)

```

I would like to freeze a tkinter gui application. 
After when the build is success I encountered a strange problem.
When I start the application from the build/Affybot.app the app starts, but not working properly. 

When I wanted to check what is the problem and see a bit more I tried to start the app from the build/exe.macosx-10.9-x86_64-3.9/Affybot in console and I got the following error:

```
Traceback (most recent call last):
  File "/Users/davidperlusz/code/affy/.venv/lib/python3.9/site-packages/cx_Freeze/initscripts/__startup__.py", line 138, in run
    module_init.run(name + "__main__")
  File "/Users/davidperlusz/code/affy/.venv/lib/python3.9/site-packages/cx_Freeze/initscripts/console.py", line 16, in run
    exec(code, module_main.__dict__)  # pylint: disable=exec-used
  File "affy.py", line 3, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: dlopen(/Users/davidperlusz/code/affy/build/exe.macosx-10.9-x86_64-3.9/lib/_tkinter.cpython-39-darwin.so, 0x0002): Library not loaded: @loader_path/../lib/libtcl8.6.dylib
  Referenced from: <94CE77B6-5CAD-3C3A-AC13-34A8B8F01541> /Users/davidperlusz/code/affy/build/exe.macosx-10.9-x86_64-3.9/lib/_tkinter.cpython-39-darwin.so
  Reason: tried: '/Users/davidperlusz/code/affy/build/exe.macosx-10.9-x86_64-3.9/lib/../lib/libtcl8.6.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS@loader_path/../lib/libtcl8.6.dylib' (no such file), '/Users/davidperlusz/code/affy/build/exe.macosx-10.9-x86_64-3.9/lib/../lib/libtcl8.6.dylib' (no such file), '/usr/local/lib/libtcl8.6.dylib' (no such file), '/usr/lib/libtcl8.6.dylib' (no such file, not in dyld cache)
```
  
  I found these missing files in the exe.macosx-10.9-x86_64-3.9 folder and I copied them to usr/local/lib manually. 
  This solved the above error, but I'm prety sure this is not the good working way. 
  
  Also it isn't solved all of my problems. The app now starts but when I try to make a request from it I got an other error:
  
  Can't connect to HTTPS URL because the SSL module is not available.

Please can you help me with this? Thank you so much

**Comment by marcelotduarte** [comment]
I made a patch. Please test and give me feedback. See more: https://github.com/marcelotduarte/cx_Freeze/issues/1548#issuecomment-1617572177

**Comment by marcelotduarte** [comment]
[Release 6.15.3](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.15.3) is out!
