### ISSUE TITLE
Problem in freezing the lxml: Type Error encode() argument 1 must be string

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#172]
Originally reported by: **Anonymous**

----------------------------------------

Hi,

I have written a sample script for freezing the lxml on centos 7 platform with following versions

Python version is 2.7.10
cx_freeze version is 4.3.4
lxml is 3.5

Following is the error while running the exe. If I run the sample script in python shell, its working fine.

Traceback (most recent call last):
File "/usr/local/python/2.7.10/lib/python2.7/site-packages/cx_Freeze/initscripts/Console.py", line 27, in 
File "hpcsd.py", line 3, in 
File "/root/workspace/voyage/cs/hpcsbuild/common.py", line 75, in 
File "/root/workspace/voyage/cs/hpcsbuild/ui/server.py", line 33, in 
File "/root/workspace/voyage/cs/hpcsbuild/util/cert.py", line 24, in 
File "/root/workspace/voyage/cs/hpcsbuild/util/config.py", line 23, in 
File "/usr/local/python/2.7.10/lib/python2.7/site-packages/bubbles/dobject.py", line 31, in 
File "/usr/local/python/2.7.10/lib/python2.7/site-packages/bubbles/xmlimpl.py", line 36, in 
File "ExtensionLoader_lxml_etree.py", line 22, in 
File "ExtensionLoader_lxml_etree.py", line 14, in bootstrap
File "src/lxml/lxml.etree.pyx", line 169, in init lxml.etree (src/lxml/lxml.etree.c:229940)
TypeError: encode() argument 1 must be string without null bytes, not unicode

My setup.py file is as follows:

from cx_Freeze import setup, Executable
copyDependentFiles=True
silent = True
includes = ["lxml","lxml._elementpath","collections"]
path=[]
setup(
name = "foobar",
version = "0.5",
description = "foobar-Description",
options = {
"build_exe": {
"includes": includes , }
},

    executables = [Executable("test.py")]
)
Kindly guide me to solve this issue.

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/172

**Comment by marcelotduarte** [comment]
PR #604
