### ISSUE TITLE
FileNotFoundError when try to freeze project with albumentations and scikit-learn modules

### ISSUE THREAD

**Issue by bw7715** [marcelotduarte/cx_Freeze#1723]
**Describe the bug**
An error occurs after freezing:
```python
FileNotFoundError: Could not find module 'C:\Projects\python_projects\cx_freeze_issues\sklearn_libs\out\lib\sklearn\.libs\vcomp140.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

**To Reproduce**
project.py:
```python
import albumentations as A
print(A.__version__)
```

requirements.txt:
```
cx-Freeze
albumentations==1.2.0
qudida==0.0.4
scikit-learn==1.1.1
scipy==1.8.1
```

Freezer script:
```bash
set WORKSPACE=%~dp0
set FREEZER_EXE_PATH="%WORKSPACE%\venv\Scripts\cxfreeze.exe"
set TARGET_DIR=out
set TARGET_NAME=project_out.exe
set PACKAGES=albumentations,qudida,scipy,sklearn
set PROJECT_SOURCE_PY_PATH=project.py

%FREEZER_EXE_PATH% -O -OO --target-dir=%TARGET_DIR% --target-name=%TARGET_NAME% --packages=%PACKAGES% %PROJECT_SOURCE_PY_PATH%
```

Output of frozen project's exe:
```bash
PS C:\Projects\python_projects\cx_freeze_issues\sklearn_libs\out> .\project_out.exe
Traceback (most recent call last):
  File "C:\Projects\python_projects\cx_freeze_issues\sklearn_libs\venv\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 138, in run
    module_init.run(name + "__main__")
  File "C:\Projects\python_projects\cx_freeze_issues\sklearn_libs\venv\Lib\site-packages\cx_Freeze\initscripts\console.py", line 16, in run
    exec(code, module_main.__dict__)  # pylint: disable=exec-used
  File "project.py", line 1, in <module>
  File "C:\Projects\python_projects\cx_freeze_issues\sklearn_libs\venv\lib\site-packages\albumentations\__init__.py", line 5, in <module>
    from .augmentations import *
  File "C:\Projects\python_projects\cx_freeze_issues\sklearn_libs\venv\lib\site-packages\albumentations\augmentations\__init__.py", line 7, in <module>
    from .domain_adaptation import *
  File "C:\Projects\python_projects\cx_freeze_issues\sklearn_libs\venv\lib\site-packages\albumentations\augmentations\domain_adaptation.py", line 6, in <module>
    from qudida import DomainAdapter
  File "C:\Projects\python_projects\cx_freeze_issues\sklearn_libs\venv\lib\site-packages\qudida\__init__.py", line 6, in <module>
    from sklearn.decomposition import PCA
  File "C:\Projects\python_projects\cx_freeze_issues\sklearn_libs\venv\lib\site-packages\sklearn\__init__.py", line 80, in <module>
    from . import _distributor_init  # noqa: F401
  File "C:\Projects\python_projects\cx_freeze_issues\sklearn_libs\venv\lib\site-packages\sklearn\_distributor_init.py", line 23, in <module>
    WinDLL(op.abspath(vcomp140_dll_filename))
  File "C:\Program Files\Python39\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Projects\python_projects\cx_freeze_issues\sklearn_libs\out\lib\sklearn\.libs\vcomp140.dll' (or one of its dependencies). Try using the full path with constructor syntax.
PS C:\Projects\python_projects\cx_freeze_issues\sklearn_libs\out>
```

**Desktop (please complete the following information):**
 - Platform information: Windows 10
 - OS architecture (e.g. amd64): 64bit
 - cx_Freeze version [e.g. 6.11]: 6.13.1
 - Python version [e.g. 3.10]: 3.9.13

**Additional context**

**Comment by bw7715** [comment]
In \lib\sklearn\.libs\  .libs directory in empty.

**Comment by bw7715** [comment]
Sorry, I didn't notice that there is similar issue: https://github.com/marcelotduarte/cx_Freeze/issues/1706

I try to:
```
pip install --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze --upgrade
```

and run again the Freezer Script, but the problem still exists.

**Comment by bw7715** [comment]
```
PS C:\Projects\python_projects\cx_freeze_issues\sklearn_libs\venv\Scripts> .\python.exe -m pip list
Package                Version
---------------------- -----------
albumentations         1.2.0
contourpy              1.0.6
cx-Freeze              6.14.0.dev1
cx-Logging             3.1.0
cycler                 0.11.0
fonttools              4.38.0
imageio                2.23.0
importlib-metadata     5.2.0
joblib                 1.2.0
kiwisolver             1.4.4
lief                   0.12.3
matplotlib             3.6.2
networkx               2.8.8
numpy                  1.24.0
opencv-python-headless 4.6.0.66
packaging              22.0
Pillow                 9.3.0
pip                    22.3.1
pyparsing              3.0.9
python-dateutil        2.8.2
PyWavelets             1.4.1
PyYAML                 6.0
qudida                 0.0.4
scikit-image           0.18.3
scikit-learn           1.1.1
scipy                  1.8.1
setuptools             65.6.3
six                    1.16.0
threadpoolctl          3.1.0
tifffile               2022.10.10
typing_extensions      4.4.0
wheel                  0.38.4
zipp                   3.11.0
```

**Comment by marcelotduarte** [comment]
Duplicate of #1706
Please check the setup.py at https://github.com/marcelotduarte/cx_Freeze/issues/1706#issuecomment-1359004612
In command line cxfreeze use --include-msvcr because sklearn already include some msvcr files.

**Comment by bw7715** [comment]
Thanks you, with ```--include-msvcr``` and develop version works.

```python
cx-Freeze          6.14.0.dev1
```
