### ISSUE TITLE
FileNotFoundError when try to freeze Shapely module.

### ISSUE THREAD

**Issue by bw7715** [marcelotduarte/cx_Freeze#1724]
**Describe the bug**
There is an error when try to freeze project with Shapely module.
```python
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Projects\\python_projects\\cx_freeze_issues\\shapely_libs\\out\\lib\\Shapely.libs'
```

**To Reproduce**
requirements.txt:
```
cx-Freeze
shapely==1.8.4
```

Python project:
```python
import shapely.geometry

box = shapely.geometry.box(0, 0, 100, 100)
print(box)
```

Freezer script
```bash
set WORKSPACE=%~dp0
set FREEZER_EXE_PATH="%WORKSPACE%venv\Scripts\cxfreeze.exe"
set TARGET_DIR=out
set TARGET_NAME=project_out.exe
set PACKAGES=shapely
set PROJECT_SOURCE_PY_PATH=project.py

%FREEZER_EXE_PATH% -O -OO --target-dir=%TARGET_DIR% --target-name=%TARGET_NAME% --packages=%PACKAGES% %PROJECT_SOURCE_PY_PATH%
```

Frozen project's exe:
```bash
PS C:\Projects\python_projects\cx_freeze_issues\shapely_libs\out> .\project_out.exe
Traceback (most recent call last):
  File "C:\Projects\python_projects\cx_freeze_issues\shapely_libs\venv\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 138, in run
    module_init.run(name + "__main__")
  File "C:\Projects\python_projects\cx_freeze_issues\shapely_libs\venv\Lib\site-packages\cx_Freeze\initscripts\console.py", line 16, in run
    exec(code, module_main.__dict__)  # pylint: disable=exec-used
  File "project.py", line 1, in <module>
  File "C:\Projects\python_projects\cx_freeze_issues\shapely_libs\venv\lib\site-packages\shapely\__init__.py", line 29, in <module>
    _delvewheel_init_patch_0_0_23()
  File "C:\Projects\python_projects\cx_freeze_issues\shapely_libs\venv\lib\site-packages\shapely\__init__.py", line 14, in _delvewheel_init_patch_0_0_23
    os.add_dll_directory(libs_dir)
  File "C:\Program Files\Python39\lib\os.py", line 1111, in add_dll_directory
    cookie = nt._add_dll_directory(path)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Projects\\python_projects\\cx_freeze_issues\\shapely_libs\\out\\lib\\Shapely.libs'
```

**Desktop (please complete the following information):**
 - Platform information (e.g. Ubuntu Linux 22.04): Windows 10
 - OS architecture (e.g. amd64): 64 bit
 - cx_Freeze version [e.g. 6.11]: 6.13.1
 - Python version [e.g. 3.10]: 3.9.13

**Additional context**

**Comment by bw7715** [comment]
The 'Shapely.libs' exists but this is a directory, not a file.

![image](https://user-images.githubusercontent.com/92443349/209362287-268fee5d-1a66-4405-80a6-ace356d16ac9.png)

**Comment by marcelotduarte** [comment]
To test the development version:

`pip install --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze --upgrade`

**Comment by bw7715** [comment]
Thanks you with development version it works.

```python
PS C:\Projects\python_projects\cx_freeze_issues\shapely_libs\out> .\project_out.exe
POLYGON ((100 0, 100 100, 0 100, 0 0, 100 0))
```

```python
PS C:\Projects\python_projects\cx_freeze_issues\shapely_libs\venv\Scripts> .\python.exe -m pip list
Package            Version
------------------ -----------
cx-Freeze          6.14.0.dev1
cx-Logging         3.1.0
importlib-metadata 5.2.0
lief               0.12.3
packaging          22.0
pip                22.3.1
setuptools         65.6.3
Shapely            1.8.4
wheel              0.38.4
zipp               3.11.0
```
