### ISSUE TITLE
ImportError: libcblas.so

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#177]
Originally reported by: **Anonymous**

----------------------------------------

Hi everyone, I have a little problem. I bundled a program with cx_freeze (on Linux and windows), and distributed it to my users. The window version works fine, but not the linux version. The linux version works fine on my system, but not on the computer of one of my users. He reported:

```
Traceback (most recent call last): File "/usr/lib/python3.5/site-packages/cx_Freeze/initscripts/Console.py", line 27, in <module> File "/tmp/tmpxlqv8g3n/scripts/gui.py", line 29, in <module> File "/usr/lib/python3.5/importlib/_bootstrap.py", line 969, in _find_and_load File "/usr/lib/python3.5/importlib/_bootstrap.py", line 958, in _find_and_load_unlocked File "/usr/lib/python3.5/importlib/_bootstrap.py", line 664, in _load_unlocked File "/usr/lib/python3.5/importlib/_bootstrap.py", line 634, in _load_backward_compatible File "/home/djipey/informatique/python/ChemBrows/predictor.py", line 9, in <module> File "/usr/lib/python3.5/importlib/_bootstrap.py", line 969, in _find_and_load File "/usr/lib/python3.5/importlib/_bootstrap.py", line 944, in _find_and_load_unlocked File "/usr/lib/python3.5/importlib/_bootstrap.py", line 222, in _call_with_frames_removed File "/usr/lib/python3.5/importlib/_bootstrap.py", line 969, in _find_and_load File "/usr/lib/python3.5/importlib/_bootstrap.py", line 958, in _find_and_load_unlocked File "/usr/lib/python3.5/importlib/_bootstrap.py", line 664, in _load_unlocked File "/usr/lib/python3.5/importlib/_bootstrap.py", line 634, in _load_backward_compatible File "/usr/lib/python3.5/site-packages/sklearn/__init__.py", line 57, in <module> File "/usr/lib/python3.5/importlib/_bootstrap.py", line 969, in _find_and_load File "/usr/lib/python3.5/importlib/_bootstrap.py", line 958, in _find_and_load_unlocked File "/usr/lib/python3.5/importlib/_bootstrap.py", line 664, in _load_unlocked File "/usr/lib/python3.5/importlib/_bootstrap.py", line 634, in _load_backward_compatible File "/usr/lib/python3.5/site-packages/sklearn/base.py", line 8, in <module> File "/usr/lib/python3.5/importlib/_bootstrap.py", line 969, in _find_and_load File "/usr/lib/python3.5/importlib/_bootstrap.py", line 958, in _find_and_load_unlocked File "/usr/lib/python3.5/importlib/_bootstrap.py", line 664, in _load_unlocked File "/usr/lib/python3.5/importlib/_bootstrap.py", line 634, in _load_backward_compatible File "/usr/lib/python3.5/site-packages/numpy/__init__.py", line 180, in <module> File "/usr/lib/python3.5/importlib/_bootstrap.py", line 1016, in _handle_fromlist File "/usr/lib/python3.5/importlib/_bootstrap.py", line 222, in _call_with_frames_removed File "/usr/lib/python3.5/importlib/_bootstrap.py", line 969, in _find_and_load File "/usr/lib/python3.5/importlib/_bootstrap.py", line 958, in _find_and_load_unlocked File "/usr/lib/python3.5/importlib/_bootstrap.py", line 664, in _load_unlocked File "/usr/lib/python3.5/importlib/_bootstrap.py", line 634, in _load_backward_compatible File "/usr/lib/python3.5/site-packages/numpy/add_newdocs.py", line 13, in <module> File "/usr/lib/python3.5/importlib/_bootstrap.py", line 969, in _find_and_load File "/usr/lib/python3.5/importlib/_bootstrap.py", line 958, in _find_and_load_unlocked File "/usr/lib/python3.5/importlib/_bootstrap.py", line 664, in _load_unlocked File "/usr/lib/python3.5/importlib/_bootstrap.py", line 634, in _load_backward_compatible File "/usr/lib/python3.5/site-packages/numpy/lib/__init__.py", line 8, in <module> File "/usr/lib/python3.5/importlib/_bootstrap.py", line 969, in _find_and_load File "/usr/lib/python3.5/importlib/_bootstrap.py", line 958, in _find_and_load_unlocked File "/usr/lib/python3.5/importlib/_bootstrap.py", line 664, in _load_unlocked File "/usr/lib/python3.5/importlib/_bootstrap.py", line 634, in _load_backward_compatible File "/usr/lib/python3.5/site-packages/numpy/lib/type_check.py", line 11, in <module> File "/usr/lib/python3.5/importlib/_bootstrap.py", line 969, in _find_and_load File "/usr/lib/python3.5/importlib/_bootstrap.py", line 944, in _find_and_load_unlocked File "/usr/lib/python3.5/importlib/_bootstrap.py", line 222, in _call_with_frames_removed File "/usr/lib/python3.5/importlib/_bootstrap.py", line 969, in _find_and_load File "/usr/lib/python3.5/importlib/_bootstrap.py", line 958, in _find_and_load_unlocked File "/usr/lib/python3.5/importlib/_bootstrap.py", line 664, in _load_unlocked File "/usr/lib/python3.5/importlib/_bootstrap.py", line 634, in _load_backward_compatible File "/usr/lib/python3.5/site-packages/numpy/core/__init__.py", line 14, in <module> File "/usr/lib/python3.5/importlib/_bootstrap.py", line 1016, in _handle_fromlist File "/usr/lib/python3.5/importlib/_bootstrap.py", line 222, in _call_with_frames_removed File "/usr/lib/python3.5/importlib/_bootstrap.py", line 969, in _find_and_load File "/usr/lib/python3.5/importlib/_bootstrap.py", line 958, in _find_and_load_unlocked File "/usr/lib/python3.5/importlib/_bootstrap.py", line 664, in _load_unlocked File "/usr/lib/python3.5/importlib/_bootstrap.py", line 634, in _load_backward_compatible File "ExtensionLoader_numpy_core_multiarray.py", line 22, in <module> File "ExtensionLoader_numpy_core_multiarray.py", line 14, in __bootstrap__ File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic File "/usr/lib/python3.5/importlib/_bootstrap.py", line 693, in _load File "/usr/lib/python3.5/importlib/_bootstrap.py", line 666, in _load_unlocked File "/usr/lib/python3.5/importlib/_bootstrap.py", line 577, in module_from_spec File "/usr/lib/python3.5/importlib/_bootstrap_external.py", line 903, in create_module File "/usr/lib/python3.5/importlib/_bootstrap.py", line 222, in _call_with_frames_removed ImportError: libcblas.so: cannot open shared object file: No such file or directory

```

Do you have an idea about where the problem comes from ?

I don't have access to his computer, so that's all I can provide. Maybe I should include the numpy package of my setup.py ?

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/177

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Closing due to inactivity.
