### ISSUE TITLE
AttributeError: 'WindowsPath' object has no attribute 'write'

### ISSUE THREAD

**Issue by bw7715** [marcelotduarte/cx_Freeze#1777]
**Describe the bug**
When try to freeze a project I get an error:

```python
...
This is not necessarily a problem - the modules may not be needed on this platform.

Traceback (most recent call last):
  File "C:\\python_projects\cx_freeze_issues\p36_project\venv\lib\site-packages\cx_Freeze\freezer.py", line 580, in _write_modules
    outfile.writestr(zinfo, data)
  File "C:\python36\lib\zipfile.py", line 1645, in writestr
    with self.open(zinfo, mode='w') as dest:
  File "C:\python36\lib\zipfile.py", line 1349, in open
    return self._open_to_write(zinfo, force_zip64=force_zip64)
  File "C:\python36\lib\zipfile.py", line 1462, in _open_to_write
    self.fp.write(zinfo.FileHeader(zip64))
  File "C:\python36\lib\zipfile.py", line 721, in write
    n = self.fp.write(data)
AttributeError: 'WindowsPath' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\python_projects\cx_freeze_issues\p36_project\venv\Scripts\cxfreeze.exe\__main__.py", line 7, in <module>
  File "C:\python_projects\cx_freeze_issues\p36_project\venv\lib\site-packages\cx_Freeze\cli.py", line 370, in main
    freezer.Freeze()
  File "C:\python_projects\cx_freeze_issues\p36_project\venv\lib\site-packages\cx_Freeze\freezer.py", line 633, in Freeze
    self._write_modules(library_zip, finder)
  File "C:\python_projects\cx_freeze_issues\p36_project\venv\lib\site-packages\cx_Freeze\freezer.py", line 605, in _write_modules
    outfile.write(source_path, target_path.as_posix())
  File "C:\python36\lib\zipfile.py", line 1144, in __exit__
    self.close()
  File "C:\python36\lib\zipfile.py", line 1668, in close
    self._write_end_record()
  File "C:\python36\lib\zipfile.py", line 1770, in _write_end_record
    self.fp.write(endrec)
  File "C:\python36\lib\zipfile.py", line 721, in write
    n = self.fp.write(data)
AttributeError: 'WindowsPath' object has no attribute 'write'
```

**To Reproduce**
Simple Python project script:
```python
import sys
print(sys.version)
```

Freezer bat script:
```bash
set WORKSPACE=%~dp0

set SCRIPTS_DIRPATH=%WORKSPACE%\venv\Scripts
set PYTHON_EXE_PATH="%SCRIPTS_DIRPATH%\python.exe"
set FREEZER_EXE_PATH="%SCRIPTS_DIRPATH%\cxfreeze.exe"
set TARGET_DIR=out
set TARGET_NAME=project_out.exe
set PROJECT_SOURCE_PY_PATH=project.py

%FREEZER_EXE_PATH% -O -OO --include-msvcr --target-dir=%TARGET_DIR% --target-name=%TARGET_NAME% %PROJECT_SOURCE_PY_PATH%
```

**Desktop (please complete the following information):**
 - Platform information (e.g. Ubuntu Linux 22.04): Windows 10
 - OS architecture (e.g. amd64): 64bit
 - cx_Freeze version: 6.13.1
 - Python version: 3.6.1

**Additional context**
```
python.exe -m pip list
Package            Version
------------------ -------
cx-Freeze          6.13.1
cx-Logging         3.0
importlib-metadata 4.8.3
lief               0.12.3
packaging          21.3
pip                21.3.1
pyparsing          3.0.7
setuptools         59.6.0
typing_extensions  4.1.1
wheel              0.37.1
zipp               3.6.0
```

**Comment by bw7715** [comment]
With cx_Freeze 6.7 this simple project works after freeze,
this error appears with 6.8 or newer.

**Comment by marcelotduarte** [comment]
1) Python 3.6 is EOL
2) This is a bug in Python, fixed in 3.6.2 (https://bugs.python.org/issue28231)
3) I Tested with 3.6.8 and it is ok.

**Comment by marcelotduarte** [comment]
6.13.2

**Comment by bw7715** [comment]
> 6.13.2

Thank you, now everything works.
