### ISSUE TITLE
PyTorch: Error loading "...\cudnn_adv_infer64_8.dll" or one of its dependencies.

### ISSUE THREAD

**Issue by bw7715** [marcelotduarte/cx_Freeze#1787]
**Describe the bug**
When I try to run frozen project with PyTorch module and CUDA 11.7 then I get an error:

```python
PS C:\projects\out> .\project_out.exe
Traceback (most recent call last):
  File "C:\projects\venv\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 139, in run
    module_init.run(name + "__main__")
  File "C:\projects\venv\Lib\site-packages\cx_Freeze\initscripts\console.py", line 18, in run
    exec(code, module_main.__dict__)  # pylint: disable=exec-used
  File "project.py", line 1, in <module>
  File "C:\projects\venv\lib\site-packages\torch\__init__.py", line 128, in <module>
    raise err
OSError: [WinError 127] The specified procedure could not be found. Error loading "C:\projects\out\lib\torch\lib\cudnn_adv_infer64_8.dll" or one of its dependencies.
PS C:\projects\out>
```

**To Reproduce**
Project file:
```python
# project.py
import torch
print(f"PyTorch: version={torch.version.__version__}, cuda={torch.version.cuda}")
```

Freezer script:
```bash
set WORKSPACE=%~dp0

set SCRIPTS_DIRPATH=%WORKSPACE%\venv\Scripts
set PYTHON_EXE_PATH="%SCRIPTS_DIRPATH%\python.exe"
set FREEZER_EXE_PATH="%SCRIPTS_DIRPATH%\cxfreeze.exe"
set TARGET_DIR=out
set TARGET_NAME=project_out.exe
set PACKAGES=torch
set PROJECT_SOURCE_PY_PATH=project.py

%FREEZER_EXE_PATH% -O -OO --include-msvcr --target-dir=%TARGET_DIR% --target-name=%TARGET_NAME% --packages=%PACKAGES% %PROJECT_SOURCE_PY_PATH% > cx_freeze_log.txt
```

PIP requirements:
```python
--find-links https://download.pytorch.org/whl/cu117/torch_stable.html

cx-Freeze
torch==1.13.1+cu117
torchvision==0.14.1+cu117
```

PIP list:
```python
.\python.exe -m pip list
Package            Version
------------------ ------------
certifi            2022.12.7
charset-normalizer 3.0.1
cx-Freeze          6.14.4
cx-Logging         3.1.0
idna               3.4
lief               0.12.3
numpy              1.24.2
Pillow             9.4.0
pip                23.0.1
requests           2.28.2
setuptools         66.1.1
torch              1.13.1+cu117
torchvision        0.14.1+cu117
typing_extensions  4.5.0
urllib3            1.26.14
```

**Desktop (please complete the following information):**
 - Platform information: Windows 10
 - OS architecture: 64bit
 - cx_Freeze version: 6.14.4
 - Python version: 3.9.13

**Additional context**

**Comment by bw7715** [comment]
With cx_Freeze-6.15.0.dev1 I get an error during freezing process:

```python
C:\projects>"C:\projects\\venv\Scripts\cxfreeze.exe" -O -OO --include-msvcr --target-dir=out --target-name=project_out.exe --packages=torch project.py  1>cx_freeze_log.txt
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\projects\venv\Scripts\cxfreeze.exe\__main__.py", line 7, in <module>
  File "C:\projects\venv\lib\site-packages\cx_Freeze\cli.py", line 372, in main
    freezer.freeze()
  File "C:\projects\venv\lib\site-packages\cx_Freeze\freezer.py", line 675, in freeze
    self._write_modules(library_zip, finder)
  File "C:\projects\venv\lib\site-packages\cx_Freeze\freezer.py", line 565, in _write_modules
    self._copy_package_data(module, target_package_dir)
  File "C:\projects\venv\lib\site-packages\cx_Freeze\freezer.py", line 221, in _copy_package_data
    copy_tree(source_dir, target_dir, excludes)
  File "C:\projects\venv\lib\site-packages\cx_Freeze\freezer.py", line 207, in copy_tree
    copy_tree(source_subdir, target, excludes_subdir)
  File "C:\projects\venv\lib\site-packages\cx_Freeze\freezer.py", line 207, in copy_tree
    copy_tree(source_subdir, target, excludes_subdir)
  File "C:\projects\venv\lib\site-packages\cx_Freeze\freezer.py", line 207, in copy_tree
    copy_tree(source_subdir, target, excludes_subdir)
  File "C:\projects\venv\lib\site-packages\cx_Freeze\freezer.py", line 200, in copy_tree
    if source.is_dir():
  File "C:\Program Files\Python39\lib\pathlib.py", line 1439, in is_dir
    return S_ISDIR(self.stat().st_mode)
  File "C:\Program Files\Python39\lib\pathlib.py", line 1232, in stat
    return self._accessor.stat(self)
OSError: [WinError 4393] The tag present in the reparse point buffer is invalid: 'C:\\projects\\venv\\lib\\site-packages\\torch\\include\\torch\\csrc\\lazy'
```

**Comment by bw7715** [comment]
The 'lib' dir is missing in frozen project. When I copy it (C:\projects\out\lib\torch\lib) then I get an error, after start frozen exe:
```python
PS C:\projects\out> .\project_out.exe
sys.executable: C:\projects\out\project_out.exe
sys.path: ['C:\\projects\\out\\lib\\library.zip', 'C:\\projects\\out\\lib']
Traceback (most recent call last):
  File "<frozen zipimport>", line 259, in load_module
  File "C:\projects\venv\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 10, in <module>
    import string
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Program Files\Python39\lib\string.py", line 52, in <module>
    import re as _re
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Program Files\Python39\lib\re.py", line 124, in <module>
    import enum
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Program Files\Python39\lib\enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
ModuleNotFoundError: No module named 'types'
PS C:\projects\out>
```

**Comment by bw7715** [comment]
If I use ```--packages=torch,torchvision,typing_extensions``` and after freezeing copy and overwite everything from venv to ```frozen_out\lib\torch\lib``` then this small project work after freezing.

**Comment by marcelotduarte** [comment]
Continuation of #1704 
I'll take a look.
The dev1 that you used have a experimental patch. I removed it. Can you test with it (install first) to check if that is gone? (Not the issue w/ pytorch).

**Comment by bw7715** [comment]
Now with dev version I get the same error:
```python
OSError: [WinError 127] The specified procedure could not be found. Error loading "...\_build\out\lib\torch\lib\cudnn_adv_infer64_8.dll" or one of its dependencies.
```

```
certifi            2022.12.7
charset-normalizer 3.0.1
cx-Freeze          6.15.0.dev1
cx-Logging         3.1.0
idna               3.4
lief               0.12.3
numpy              1.24.2
Pillow             9.4.0
pip                22.0.4
requests           2.28.2
setuptools         66.1.1
torch              1.13.1+cu117
torchvision        0.14.1+cu117
typing_extensions  4.5.0
urllib3            1.26.14
```

**Comment by marcelotduarte** [comment]
With cxfreeze project.py fails for me in torch init line 218.
With --packages=torch it builds and run.
But I do not have the CONDA_PATH variables. Can you remove them in a cmd with set CUDA_PATH_V11_7= and test?

**Comment by marcelotduarte** [comment]
[Release 6.14.5](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.14.5)
