### ISSUE TITLE
Problem with initscript

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#182]
Originally reported by: **Ian Bell (Bitbucket: [ibell](https://bitbucket.org/ibell), GitHub: [ibell](https://github.com/ibell))**

----------------------------------------

I am having problems with the default initScript.

For instance, with this simple file, 

```
#!python

import matplotlib.pyplot as plt
plt.plot([1,2,3],[3,4,5])
plt.show()
```

I try to run ``cxfreeze test.py`` (after applying the fix of https://bitbucket.org/anthony_tuininga/cx_freeze/pull-requests/69/install-cxfreeze-command-line-wrapper-for/diff), and I get

```
C:\Users\Belli\Desktop\cxtest>python "C:\Miniconda\Scripts\\cxfreeze" test.py
Traceback (most recent call last):
  File "C:\Miniconda\Scripts\\cxfreeze", line 4, in <module>
    __import__('pkg_resources').run_script('cx-Freeze==5.0', 'cxfreeze')
  File "C:\Miniconda\lib\site-packages\setuptools-20.2.2-py2.7.egg\pkg_resources\__init__.py", line 726, in run_script

  File "C:\Miniconda\lib\site-packages\setuptools-20.2.2-py2.7.egg\pkg_resources\__init__.py", line 1484, in run_script

  File "c:\miniconda\lib\site-packages\cx_freeze-5.0-py2.7-win-amd64.egg\EGG-INFO\scripts\cxfreeze", line 5, in <module>
    main()
  File "C:\Miniconda\lib\site-packages\cx_freeze-5.0-py2.7-win-amd64.egg\cx_Freeze\main.py", line 176, in main
    silent = options.silent)
  File "C:\Miniconda\lib\site-packages\cx_freeze-5.0-py2.7-win-amd64.egg\cx_Freeze\freezer.py", line 144, in __init__
    self._VerifyConfiguration()
  File "C:\Miniconda\lib\site-packages\cx_freeze-5.0-py2.7-win-amd64.egg\cx_Freeze\freezer.py", line 451, in _VerifyConfiguration
    executable._VerifyConfiguration(self)
  File "C:\Miniconda\lib\site-packages\cx_freeze-5.0-py2.7-win-amd64.egg\cx_Freeze\freezer.py", line 604, in _VerifyConfiguration
    self._GetInitScriptFileName()
  File "C:\Miniconda\lib\site-packages\cx_freeze-5.0-py2.7-win-amd64.egg\cx_Freeze\freezer.py", line 624, in _GetInitScriptFileName
    self.initScript = get_resource_file_path("initscripts", name, ".py")
  File "C:\Miniconda\lib\site-packages\cx_freeze-5.0-py2.7-win-amd64.egg\cx_Freeze\freezer.py", line 99, in get_resource_file_path
    if os.path.isabs(name):
  File "C:\Miniconda\lib\ntpath.py", line 58, in isabs
    s = splitdrive(s)[1]
  File "C:\Miniconda\lib\ntpath.py", line 115, in splitdrive
    if len(p) > 1:
TypeError: object of type 'NoneType' has no len()
```

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/182

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anthony Tuininga (Bitbucket: [anthony_tuininga](https://bitbucket.org/anthony_tuininga), GitHub: Unknown)**:

----------------------------------------

Fixed by
https://bitbucket.org/anthony_tuininga/cx_freeze/commits/a69936ec621ceb936c535dc09c2fc5c1ae25aae6
