### ISSUE TITLE
Packaged app cannot locate .so file at right depth in /lib

### ISSUE THREAD

**Issue by spadavec** [marcelotduarte/cx_Freeze#1833]
**Describe the bug**
I'm packaging my app which runs to completion, but when I attempt to execute the app within `/dist`, `xgboost` claims it can't find a relevant .so file in `/lib`:

```bash
Traceback (most recent call last):
  File "/home/spadavec/miniconda3/envs/EDC/lib/python3.8/site-packages/cx_Freeze/initscripts/__startup__.py", line 139, in run
    module_init.run(name + "__main__")
  File "/home/spadavec/miniconda3/envs/EDC/lib/python3.8/site-packages/cx_Freeze/initscripts/console.py", line 18, in run
    exec(code, module_main.__dict__)  # pylint: disable=exec-used
  File "app.py", line 22, in <module>
  File "/home/spadavec/miniconda3/envs/EDC/lib/python3.8/site-packages/xgboost/__init__.py", line 7, in <module>
    from . import collective, dask, rabit
  File "/home/spadavec/miniconda3/envs/EDC/lib/python3.8/site-packages/xgboost/collective.py", line 12, in <module>
    from .core import _LIB, _check_call, c_str, py_str, from_pystr_to_cstr
  File "/home/spadavec/miniconda3/envs/EDC/lib/python3.8/site-packages/xgboost/core.py", line 264, in <module>
    _LIB = _load_lib()
  File "/home/spadavec/miniconda3/envs/EDC/lib/python3.8/site-packages/xgboost/core.py", line 189, in _load_lib
    lib_paths = find_lib_path()
  File "/home/spadavec/miniconda3/envs/EDC/lib/python3.8/site-packages/xgboost/libpath.py", line 68, in find_lib_path
    raise XGBoostLibraryNotFound(msg)
xgboost.libpath.XGBoostLibraryNotFound: Cannot find XGBoost Library in the candidate path.  List of candidates:
- lib/libxgboost.so
XGBoost Python package path: /home/spadavec/itx/esprit-de-corps/src/flask/dist/lib/xgboost
sys.prefix: 
See: https://xgboost.readthedocs.io/en/latest/build.html for installing XGBoost.

```

 However, the file it is looking for is in `/lib/xgboost/lib/libxgboost.so`. Is this a bug? Or is there a way to make sure the .so files in /lib aren't put in multiple folders?

**Desktop (please complete the following information):**
 - Platform information : Ubuntu Linux 18.04:
 - OS architecture is amd64:
 - cx_Freeze version : 6.14.6:
 - Python version : 3.8:

**Comment by spadavec** [comment]
This appears to be a conda conflict issue. Creating a new env with no packages installed allowed this to run as expected.
