### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by bw7715** [marcelotduarte/cx_Freeze#1872]
**Describe the bug**
Random error that sometimes occurs when freezing a project.

```python
Freezing command: '[WindowsPath('C:/project/venv/Scripts/cxfreeze.exe'), '-O', '-OO', '--include-msvcr', '--target-dir=C:\\project\\output_freezer', '--target-name=project.exe', '--packages=albumentations,torch,torchvision,typing_extensions,scipy,sklearn,imageio,PIL,qudida,cv2,shapely', '--excludes=xmlrunner', WindowsPath('c:/project/project.py')]'	deployment.build.freezer:79
21:58:35  Traceback (most recent call last):
21:58:35    File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
21:58:35      return _run_code(code, main_globals, None,
21:58:35    File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
21:58:35      exec(code, run_globals)
21:58:35    File "C:\project\venv\Scripts\cxfreeze.exe\__main__.py", line 7, in <module>
21:58:35    File "C:\project\venv\lib\site-packages\cx_Freeze\cli.py", line 372, in main
21:58:35      freezer.Freeze()
21:58:35    File "C:\project\venv\lib\site-packages\cx_Freeze\freezer.py", line 653, in Freeze
21:58:35      finder: ModuleFinder = self._get_module_finder()
21:58:35    File "C:\project\venv\lib\site-packages\cx_Freeze\freezer.py", line 361, in _get_module_finder
21:58:35      finder.include_package(name)
21:58:35    File "C:\project\venv\lib\site-packages\cx_Freeze\finder.py", line 769, in include_package
21:58:35      module = self._import_module(name, deferred_imports)
21:58:35    File "C:\project\venv\lib\site-packages\cx_Freeze\finder.py", line 285, in _import_module
21:58:35      module = self._internal_import_module(name, deferred_imports)
21:58:35    File "C:\project\venv\lib\site-packages\cx_Freeze\finder.py", line 377, in _internal_import_module
21:58:35      module = self._load_module(
21:58:35    File "C:\project\venv\lib\site-packages\cx_Freeze\finder.py", line 444, in _load_module
21:58:35      self._load_module_code(module, loader, deferred_imports)
21:58:35    File "C:\project\venv\lib\site-packages\cx_Freeze\finder.py", line 483, in _load_module_code
21:58:35      self._run_hook("load", module.name, module)
21:58:35    File "C:\project\venv\lib\site-packages\cx_Freeze\finder.py", line 612, in _run_hook
21:58:35      method(self, *args)
21:58:35    File "C:\project\venv\lib\site-packages\cx_Freeze\hooks\torch.py", line 42, in load_torch
21:58:35      finder.include_package("torch.distributions")
21:58:35    File "C:\project\venv\lib\site-packages\cx_Freeze\finder.py", line 769, in include_package
21:58:35      module = self._import_module(name, deferred_imports)
21:58:35    File "C:\project\venv\lib\site-packages\cx_Freeze\finder.py", line 285, in _import_module
21:58:35      module = self._internal_import_module(name, deferred_imports)
21:58:35    File "C:\project\venv\lib\site-packages\cx_Freeze\finder.py", line 377, in _internal_import_module
21:58:35      module = self._load_module(
21:58:35    File "C:\project\venv\lib\site-packages\cx_Freeze\finder.py", line 444, in _load_module
21:58:35      self._load_module_code(module, loader, deferred_imports)
21:58:35    File "C:\project\venv\lib\site-packages\cx_Freeze\finder.py", line 490, in _load_module_code
21:58:35      self._scan_code(module.code, module, deferred_imports)
21:58:35    File "C:\project\venv\lib\site-packages\cx_Freeze\finder.py", line 653, in _scan_code
21:58:35      imported_module = self._import_module(
21:58:35    File "C:\project\venv\lib\site-packages\cx_Freeze\finder.py", line 319, in _import_module
21:58:35      module = self._internal_import_module(name, deferred_imports)

...  About 2,000 lines repeating the same output

21:58:35    File "C:\project\venv\lib\site-packages\cx_Freeze\finder.py", line 444, in _load_module
21:58:35      self._load_module_code(module, loader, deferred_imports)
21:58:35    File "C:\project\venv\lib\site-packages\cx_Freeze\finder.py", line 490, in _load_module_code
21:58:35      self._scan_code(module.code, module, deferred_imports)
21:58:35    File "C:\project\venv\lib\site-packages\cx_Freeze\finder.py", line 689, in _scan_code
21:58:35      self._scan_code(
21:58:35    File "C:\project\venv\lib\site-packages\cx_Freeze\finder.py", line 689, in _scan_code
21:58:35      self._scan_code(
21:58:35    File "C:\project\venv\lib\site-packages\cx_Freeze\finder.py", line 653, in _scan_code
21:58:35      imported_module = self._import_module(
21:58:35    File "C:\project\venv\lib\site-packages\cx_Freeze\finder.py", line 319, in _import_module
21:58:35      module = self._internal_import_module(name, deferred_imports)
21:58:35    File "C:\project\venv\lib\site-packages\cx_Freeze\finder.py", line 377, in _internal_import_module
21:58:35      module = self._load_module(
21:58:35    File "C:\project\venv\lib\site-packages\cx_Freeze\finder.py", line 439, in _load_module
21:58:35      module = self._add_module(
21:58:35    File "C:\project\venv\lib\site-packages\cx_Freeze\finder.py", line 118, in _add_module
21:58:35      module = Module(name, path, file_name, parent)
21:58:35    File "C:\project\venv\lib\site-packages\cx_Freeze\module.py", line 148, in __init__
21:58:35      self.update_distribution(name)
21:58:35    File "C:\project\venv\lib\site-packages\cx_Freeze\module.py", line 167, in update_distribution
21:58:35      distribution = DistributionCache.from_name(name)
21:58:35    File "C:\project\venv\lib\site-packages\cx_Freeze\module.py", line 43, in from_name
21:58:35      distribution = super().from_name(name)
21:58:35    File "C:\project\venv\lib\site-packages\setuptools\_vendor\importlib_metadata\__init__.py", line 381, in from_name
21:58:35      return next(cls.discover(name=name))
21:58:35    File "C:\project\venv\lib\site-packages\setuptools\_vendor\importlib_metadata\__init__.py", line 400, in <genexpr>
21:58:35      resolver(context) for resolver in cls._discover_resolvers()
21:58:35    File "C:\project\venv\lib\site-packages\setuptools\_vendor\importlib_metadata\__init__.py", line 731, in find_distributions
21:58:35      found = self._search_paths(context.name, context.path)
21:58:35    File "C:\project\venv\lib\site-packages\setuptools\_vendor\importlib_metadata\__init__.py", line 737, in _search_paths
21:58:35      prepared = Prepared(name)
21:58:35    File "C:\project\venv\lib\site-packages\setuptools\_vendor\importlib_metadata\__init__.py", line 692, in __init__
21:58:35      self.normalized = self.normalize(name)
21:58:35    File "C:\project\venv\lib\site-packages\setuptools\_vendor\importlib_metadata\__init__.py", line 700, in normalize
21:58:35      return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
21:58:35    File "C:\Program Files\Python39\lib\re.py", line 210, in sub
21:58:35      return _compile(pattern, flags).sub(repl, string, count)
21:58:35  RecursionError: maximum recursion depth exceeded
```

**To Reproduce**

cmd:
```bash
  C:/project/venv/Scripts/cxfreeze.exe -O -OO --include-msvcr  --target-dir=C:\\project\\output_freezer  --target-name=project.exe  --packages=albumentations,torch,torchvision,typing_extensions,scipy,sklearn,imageio,PIL,qudida,cv2,shapely  --excludes=xmlrunner  c:/project/project.py
```

requirements.txt:
```
--find-links https://download.pytorch.org/whl/cu118/torch_stable.html

albumentations==1.3.0
cx-Freeze==6.14.7
cx-Logging==3.1.0
imageio==2.26.1
numpy==1.24.2
onnx==1.13.1
opencv-python==4.7.0.72
opencv-python-headless==4.7.0.72
Pillow==9.4.0
qudida==0.0.4
scikit-image==0.20.0
scikit-learn==1.2.2
scipy==1.9.1
shapely==2.0.1
torch==2.0.0+cu118
torchvision==0.15.1+cu118
typing_extensions==4.5.0
```

**Desktop (please complete the following information):**
 - Platform information: Windows 10
 - OS architecture: 64bit
 - cx_Freeze version: 6.14.7
 - Python version: 3.9

**Comment by marcelotduarte** [comment]
Upgrade to 6.14.9 and give me feedback.

**Comment by bw7715** [comment]
I upgraded to 6.14.9 version and ran the freeze process several times in loop. 
It is better but about 1 in 10 times this error occurs.

**Comment by bw7715** [comment]
It seems that (at random times) the cx-Freeze module starts compressing PyTorch, then finds modules like OpenCV, NumPy, SciPy, etc. which causes it to recursively descent several hundred modules deep, resulting in a large amount of recursion that may cause errors.

Additionally, module doesn't check for in .git which could case problems users who rely on this version control system. But it does check .svn and CVS
![image](https://user-images.githubusercontent.com/92443349/233091317-410f857d-97aa-4864-8134-72720e43f893.png)

**Comment by bw7715** [comment]
Maybe adding `sys.setrecursionlimit(10000)` in __init__() in 'ModuleFinder' fix the issue ?

**Comment by marcelotduarte** [comment]
What is the minimum project.py to reproduce this error?
I don't have time to look at this right now. I think your observation about 'module doesn't check for in .git' is interesting, but it will make sense in a project with .git and not in torch which is installed via pip and does not have .git in the installation. But we can put a check in that code just in case.

**Comment by bw7715** [comment]
I have project with a lot of .py files (about 250k lines of code in 2k files).
But project.py has about 100 lines of code (where most lines are imports of other .py scripts).

**Comment by bw7715** [comment]
Maybe to reproduce this error try recursion with small limit, e.g.:
```python
sys.setrecursionlimit(10)
```

**Comment by marcelotduarte** [comment]
I make a patch to fix https://github.com/marcelotduarte/cx_Freeze/issues/1872#issuecomment-1514757670
You can test the patch in the latest development build:
`pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`

Please test. If the issue with recursion persists, I'll use sys.setrecursionlimit in https://github.com/marcelotduarte/cx_Freeze/blob/main/cx_Freeze/cli.py

**Comment by bw7715** [comment]
Thank you.

I have run the build process dozens of times but the problem sometimes occurs, although rarely.

**Comment by bw7715** [comment]
I try freeze with 6.15.0 version but problem still occur. Please add sys.setrecursionlimit in CLI.

**Comment by bw7715** [comment]
I start to debug this problem and I noticed that sometimes I get an error:
`ImportError: No module named 'scipy.interpolate.interpnd'`

```python
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\project\venv\Scripts\cxfreeze.exe\__main__.py", line 7, in <module>
  File "E:\project\venv\lib\site-packages\cx_Freeze\cli.py", line 348, in main
    freezer: Freezer = Freezer(
  File "E:\project\venv\lib\site-packages\cx_Freeze\freezer.py", line 729, in __init__
    Freezer.__init__(self, *args, **kwargs)
  File "E:\project\venv\lib\site-packages\cx_Freeze\freezer.py", line 118, in __init__
    self.finder: ModuleFinder = self._get_module_finder()
  File "E:\project\venv\lib\site-packages\cx_Freeze\freezer.py", line 372, in _get_module_finder
    finder.include_package(name)
  File "E:\project\venv\lib\site-packages\cx_Freeze\finder.py", line 769, in include_package
    self._import_all_sub_modules(module, deferred_imports)
  File "E:\project\venv\lib\site-packages\cx_Freeze\finder.py", line 246, in _import_all_sub_modules
    self._import_all_sub_modules(
  File "E:\project\venv\lib\site-packages\cx_Freeze\finder.py", line 240, in _import_all_sub_modules
    raise ImportError(
ImportError: No module named 'scipy.interpolate.interpnd'
```

**Comment by bw7715** [comment]
`ImportError: No module named 'scipy.interpolate._cubic'`

**Comment by marcelotduarte** [comment]
> I try freeze with 6.15.0 version but problem still occur. Please add sys.setrecursionlimit in CLI.

You can test the patch in the latest development build:
`pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`

> `ImportError: No module named 'scipy.interpolate._cubic'`

Please open a new issue about scipy, with version information, that I'll make a hook for it.

**Comment by bw7715** [comment]
It seems that the patch you provided has likely resolved the problem, as I have been testing it for a week without any occurrences. 
Could you include this fix in the next release version?

Although the problem was difficult to reproduce due to its random nature I will inform if the issue occurs in the future.

Thank you for you attention and support.

**Comment by bw7715** [comment]
> 
> > `ImportError: No module named 'scipy.interpolate._cubic'`
> 
> Please open a new issue about scipy, with version information, that I'll make a hook for it.

Link to the issue: https://github.com/marcelotduarte/cx_Freeze/issues/1894
