### ISSUE TITLE
fails to import pyreadstat (missing implicit dependencies)

### ISSUE THREAD

**Issue by gdementen** [marcelotduarte/cx_Freeze#1873]
**Describe the bug**

Program throws a traceback after being frozen by cxfreeze

**To Reproduce**

* Execute :
```bash
> pip install pyreadstat
```

* Create file 'cxfreeze_pyreadstat.py' with :
```python
import pyreadstat

print("hello")
```
* Execute :
```bash
> python cxfreeze_pyreadstat.py
hello
> cxfreeze cxfreeze_pyreadstat.py --target-dir cxdist
> cd cxdist
> cxfreeze_pyreadstat.exe
```
```python
Traceback (most recent call last):
  File "[myenvpath]\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 135, in run
    module_init.run(name + "__main__")
  File "[myenvpath]\Lib\site-packages\cx_Freeze\initscripts\console.py", line 18, in run
    exec(code, module_main.__dict__)  # pylint: disable=exec-used
  File "cxfreeze_pyreadstat.py", line 1, in <module>
  File "[myenvpath]\lib\site-packages\pyreadstat\__init__.py", line 17, in <module>
    from .pyreadstat import read_sas7bdat, read_xport, read_dta, read_sav, read_por, read_sas7bcat
  File "pyreadstat\pyreadstat.pyx", line 1, in init pyreadstat.pyreadstat
  File "pyreadstat\_readstat_parser.pyx", line 30, in init pyreadstat._readstat_parser
ModuleNotFoundError: No module named 'pandas'
```

* Update file 'cxfreeze_pyreadstat.py' with :
```python
import pandas
import pyreadstat

print("hello")
```
* Execute :
```bash
> python cxfreeze_pyreadstat.py
hello
> cxfreeze cxfreeze_pyreadstat.py --target-dir cxdist
> cd cxdist
> cxfreeze_pyreadstat.exe
```
```python
Traceback (most recent call last):
  File "[myenvpath]\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 135, in run
    module_init.run(name + "__main__")
  File "[myenvpath]\Lib\site-packages\cx_Freeze\initscripts\console.py", line 18, in run
    exec(code, module_main.__dict__)  # pylint: disable=exec-used
  File "cxfreeze_pyreadstat.py", line 2, in <module>
  File "[myenvpath]\lib\site-packages\pyreadstat\__init__.py", line 17, in <module>
    from .pyreadstat import read_sas7bdat, read_xport, read_dta, read_sav, read_por, read_sas7bcat
  File "pyreadstat\pyreadstat.pyx", line 35, in init pyreadstat.pyreadstat
ModuleNotFoundError: No module named 'worker'
```

**Expected behavior**

Display "hello" (as above)

**Desktop (please complete the following information):**
 - Windows 10
 - OS architecture: amd64
 - cx_Freeze 6.14.9 (installed via pip)
 - Python 3.10.10

**Comment by marcelotduarte** [comment]
To this basic test, use `--includes=pandas,pyreadstat.worker`
For a more complete project, if this fail, use `--includes=pandas --packages=pyreadstat`
I need feedback to add a hook in the next version to automate this.

**Comment by gdementen** [comment]
Sorry for not replying sooner (I am not actually using cx-freeze these days but wanted to compare the output of cx-freeze for my program with the one from Nuitka and stumbled on this issue) and I thought just reporting the issue would be useful but I needed to push to production, so delayed my comparison & reply. Thanks for fixing it even without input from my part. I will test my full program whenever I find the time to 😉.

**Comment by marcelotduarte** [comment]
You can test the patch in the latest development build:
`pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`
