### ISSUE TITLE
Binary with import to tempfile fails to run Linux 64bit

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#188]
Originally reported by: **Aviv Ben-Yosef (Bitbucket: [abyx](https://bitbucket.org/abyx), GitHub: [abyx](https://github.com/abyx))**

----------------------------------------

cx-Freeze 4.3.4, python 2.7.10, building on Ubuntu.

I have this file:

```python
import tempfile
print "Hello"
```

And this setup.py file:

```python
from cx_Freeze import setup, Executable
setup(name='foo', version='0.1', options={'build_exe': {}}, executables=[Executable('foo.py', base=None)])
```

Running `python setup.py build` and then the new executable results in this error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/cx_Freeze/initscripts/Console.py", line 27, in <module>
    exec(code, m.__dict__)
  File "foo.py", line 1, in <module>
    import tempfile
  File "/usr/local/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/usr/local/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: /tmp/build/exe.linux-x86_64-2.7/_io.so: undefined symbol: _PyErr_ReplaceException
```

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/188

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Closing due to inactivity.
