### ISSUE TITLE
ImportError: No module named 'scipy.interpolate.interpnd'

### ISSUE THREAD

**Issue by bw7715** [marcelotduarte/cx_Freeze#1894]
**Describe the bug**

I encountered an issues while freezing my project using the cx-Freeze module. The problem is probably connected with a RecursionError which can be found at https://github.com/marcelotduarte/cx_Freeze/issues/1872

I encountered two errors:
`ImportError: No module named 'scipy.interpolate._cubic'`
`ImportError: No module named 'scipy.interpolate.interpnd'`

Traceback:
```python
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\project\venv\Scripts\cxfreeze.exe\__main__.py", line 7, in <module>
  File "E:\project\venv\lib\site-packages\cx_Freeze\cli.py", line 348, in main
    freezer: Freezer = Freezer(
  File "E:\project\venv\lib\site-packages\cx_Freeze\freezer.py", line 729, in __init__
    Freezer.__init__(self, *args, **kwargs)
  File "E:\project\venv\lib\site-packages\cx_Freeze\freezer.py", line 118, in __init__
    self.finder: ModuleFinder = self._get_module_finder()
  File "E:\project\venv\lib\site-packages\cx_Freeze\freezer.py", line 372, in _get_module_finder
    finder.include_package(name)
  File "E:\project\venv\lib\site-packages\cx_Freeze\finder.py", line 769, in include_package
    self._import_all_sub_modules(module, deferred_imports)
  File "E:\project\venv\lib\site-packages\cx_Freeze\finder.py", line 246, in _import_all_sub_modules
    self._import_all_sub_modules(
  File "E:\project\venv\lib\site-packages\cx_Freeze\finder.py", line 240, in _import_all_sub_modules
    raise ImportError(
ImportError: No module named 'scipy.interpolate.interpnd'
```

**Desktop (please complete the following information):**
 - Platform information (e.g. Ubuntu Linux 22.04): Windows 10
 - OS architecture (e.g. amd64): 64bit
 - cx_Freeze version [e.g. 6.11]: 6.15.0
 - Python version [e.g. 3.10]: 3.9

**Comment by marcelotduarte** [comment]
You can test the patch in the latest development build:
`pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`

If it works I'll release a bugfix version.

**Comment by bw7715** [comment]
Thank you, I tested the patch and everything works.

**Comment by marcelotduarte** [comment]
[Release 6.15.1](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.15.1)
