### ISSUE TITLE
DLL load error with pandas 2.1.0

### ISSUE THREAD

**Issue by VegarS** [marcelotduarte/cx_Freeze#2026]
**Describe the bug**
Freezing applications no longer works with latest pandas version 2.1.0.

**To Reproduce**
- Create virtual env with latest cx_Freeze and pandas (2.1.0)
- Build pandas sample from cx_Freeze repository
- Run generated exe file

**Expected behavior**
Sample should work without errors.

**Screenshots**
```
Traceback (most recent call last):
  File "C:\Users\vegarst\Downloads\cxfreezeenv\env\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 124, in run
    module_init.run(name + "__main__")
  File "C:\Users\vegarst\Downloads\cxfreezeenv\env\Lib\site-packages\cx_Freeze\initscripts\console.py", line 16, in run
    exec(code, module_main.__dict__)
  File "test_pandas.py", line 4, in <module>
  File "C:\Users\vegarst\Downloads\cxfreezeenv\env\Lib\site-packages\pandas\__init__.py", line 59, in <module>
    from pandas.core.api import (
  File "C:\Users\vegarst\Downloads\cxfreezeenv\env\Lib\site-packages\pandas\core\api.py", line 47, in <module>
    from pandas.core.groupby import (
  File "C:\Users\vegarst\Downloads\cxfreezeenv\env\Lib\site-packages\pandas\core\groupby\__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "C:\Users\vegarst\Downloads\cxfreezeenv\env\Lib\site-packages\pandas\core\groupby\generic.py", line 67, in <module>
    from pandas.core.frame import DataFrame
  File "C:\Users\vegarst\Downloads\cxfreezeenv\env\Lib\site-packages\pandas\core\frame.py", line 142, in <module>
    from pandas.core.generic import (
  File "C:\Users\vegarst\Downloads\cxfreezeenv\env\Lib\site-packages\pandas\core\generic.py", line 187, in <module>
    from pandas.core.window import (
  File "C:\Users\vegarst\Downloads\cxfreezeenv\env\Lib\site-packages\pandas\core\window\__init__.py", line 1, in <module>
    from pandas.core.window.ewm import (
  File "C:\Users\vegarst\Downloads\cxfreezeenv\env\Lib\site-packages\pandas\core\window\ewm.py", line 11, in <module>
    import pandas._libs.window.aggregations as window_aggregations
ImportError: DLL load failed while importing aggregations: Module not found.
```

**Desktop (please complete the following information):**
 - Platform information: Windows 10
 - OS architecture: amd64
 - cx_Freeze version: 6.15.6
 - Python version: 3.11.5

**Comment by marcelotduarte** [comment]
You can test the patch in the latest development build:
`pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`
For conda-forge the command is:
`conda install -y --no-channel-priority -S -c https://marcelotduarte.github.io/packages/conda cx_Freeze`

**Comment by marcelotduarte** [comment]
[Release 6.15.7](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.15.7) is out!
