### ISSUE TITLE
conda env: ImportError: Missing required dependencies ['numpy']

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#205]
Originally reported by: **Phaebz (Bitbucket: [phaebz](https://bitbucket.org/phaebz), GitHub: [phaebz](https://github.com/phaebz))**

----------------------------------------

Steps to reproduce:

* set up the conda environment:
```
conda create -n cxfreeze_numpy python=2.7
conda install -n cxfreeze_numpy pandas
```

*  Install latest cxfreeze

```
activate cxfreeze_numpy
[cxfreeze_numpy] pip install -U https://bitbucket.org/anthony_tuininga/cx_freeze/get/tip.zip
```

* freeze it
```
[cxfreeze_numpy] python setup.py build
```

* run
```
build\exe.win-amd64-2.7\pandas_test.exe
```

Errors to 
```
Traceback (most recent call last):
  File "D:\Miniconda\envs\cxfreeze_numpy\lib\site-packages\cx_Freeze\initscripts\Console.py", line 21, in <module>
    exec(code, m.__dict__)
  File "pandas_test.py", line 1, in <module>
  File "D:\Miniconda\envs\cxfreeze_numpy\lib\site-packages\pandas\__init__.py", line 18, in <module>
    raise ImportError("Missing required dependencies {0}".format(missing_dependencies))
ImportError: Missing required dependencies ['numpy']
```

setup.py
```
from cx_Freeze import setup, Executable

# Dependencies are automatically detected, but it might need fine tuning.
build_exe_options = {'packages': ['pandas', 'numpy'],
                     'include_msvcr': True,
                     }

setup(name='cxfreeze_numpy',
      version='0.1',
      description='asdf',
      options={'build_exe': build_exe_options},
      executables=[Executable('pandas_test.py')])
```

pandas_test.py
```
#!python
import pandas as pd

pd.DataFrame()
```

Am I missing something in setup.py? Can you reproduce?

Detailed versions:
```
cx-freeze                 5.0                       <pip>
mkl                       11.3.3                        1
numpy                     1.11.1                   py27_1
pandas                    0.18.1              np111py27_0
pip                       8.1.2                    py27_0
python                    2.7.12                        0
python-dateutil           2.5.3                    py27_0
pytz                      2016.6.1                 py27_0
setuptools                27.2.0                   py27_0
six                       1.10.0                   py27_0
vs2008_runtime            9.00.30729.1                  2
wheel                     0.29.0                   py27_0
```

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/205

**Comment by anthony-tuininga** [comment]
*Original comment by* **Phaebz (Bitbucket: [phaebz](https://bitbucket.org/phaebz), GitHub: [phaebz](https://github.com/phaebz))**:

----------------------------------------

The log from `python setup.py build` in which numpy is found as a package

**Comment by anthony-tuininga** [comment]
*Original comment by* **Phaebz (Bitbucket: [phaebz](https://bitbucket.org/phaebz), GitHub: [phaebz](https://github.com/phaebz))**:

----------------------------------------

Nevermind. Although I've reproduced this several times, my environment must have been borked up. It is working now.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Phaebz (Bitbucket: [phaebz](https://bitbucket.org/phaebz), GitHub: [phaebz](https://github.com/phaebz))**:

----------------------------------------

Reopening since I had an environment (which had numpy) active when I tested it again... So please ignore my previous comment.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Alexander Stepanov (Bitbucket: [alexander_stepanov__](https://bitbucket.org/alexander_stepanov__), GitHub: Unknown)**:

----------------------------------------

some dll is missing. At pandas_test.py append 
```
#!python

import numpy 
```
before importing pandas.
now i have this error 
```
#!python

ImportError: libcblas.so: cannot open shared object file: No such file or directory
```

**Comment by inu1255** [comment]
in my issue 
I already add `"numpy"` in `includes`,But it still 
```
ImportError: Missing required dependencies ['numpy']
```
I solve it by
1. insert `import numpy` on the top of main.py for test
`python setup.py build`: error `no module named "_methods"`
2. add "_methods" in `include`,
`python setup.py build`: error `cx_Freeze can't find "_methods"`
3. I find "_methods" in `site-packages/numpy/core/` and copy it to `build/exe.win32-2.7/numpy/core/`,
build and run and it works.

For some reason cx_Freeze miss copy some submodule of numpy,In my case sqlalchemy.sql.default_comparator is miss too

**Comment by pedroartigas** [comment]
I have a better solution. Instead of step #2 and #3 add:

numpy.core._methods

To the list of includes

**Comment by Icadan** [comment]
I had the same problem and it looked like cx_freeze don't copy the _methods.pyc file

like @inu1255  said: 
find _methods in site-packages/numpy/core/   and then you should compile it with py_compile
after you compile it you just have to copy it in the build/exe.win32-2.7/numpy/core/ file

**Comment by kaif15** [comment]
I am having the same issue. I tried both the solutions recommended by @pedroartigas and @Icadan however the issue remained. This is only happening when running on another machine since numpy is being found at the searched location on the compile machine.
![572e7e5cde1799e41054ef94854323bd04b4097eab09cdf242 pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/12616052/32134481-14edd572-bc10-11e7-9a4e-82256557d434.png)

EDIT: I fixed it by uninstalling both Pandas and Numpy and reinstalling them. My setup.py looks like this now. 
`#Include the template and static folders as well as the required dlls for the tcl and tk libraries
include_files = [ 'templates/',
                  'static/',
                  'Add to build/tcl86t.dll',
                  'Add to build/tk86t.dll']

#Exclude unnecessary packages
excludes = ["scipy", "notebook", "babel", "PyQt5", "matplotlib", "mpl-data", "test", "sqlalchemy"]

#Include undetected packages
build_exe_options = {"packages": ["asyncio", "tkinter", "numpy.core._methods", "numpy"],
                     "includes": ["asyncio.compat", "jinja2", "jinja2.ext", "lxml._elementpath", "numpy.core._methods", "numpy", "tkinter"],
                     "excludes": excludes,
                     "include_files": include_files}

#Add option to allow for GUI
base = None
if sys.platform == 'win32':
    base = 'Win32GUI'

executables = [
    Executable(script = 'Automaton.py', base=base)
]

setup(name = 'Automaton',
      version = '0.1',
      description = 'MTB Server for File Parsing',
      options = {"build_exe": build_exe_options},
      executables = executables
      )
`

**Comment by Pechi77** [comment]
Hi, Why do we need to install python2.7, can't we run the same on python 3.6 ? I created my python script in 3.6 version.

**Comment by anthony-tuininga** [comment]
It looks like this problem could be resolved by creating a hook. Can one of you who originally had this problem and found a solution provide one?

**Comment by Pechi77** [comment]
I solved it. I copied _method from numpy>core  to build and it's working perfectly.

Thank you.

**Comment by nisarahamedk** [comment]
I am having these issue even after trying all things mentioned above. Does anyone have a solid fix for this?

**Comment by ramondepieri** [comment]
Hi guys, have some news about this problem? I´m with this issue and nothing seems to fix them.

**Comment by GauravBorade** [comment]
could anyone please give me the full path of build

**Comment by GauravBorade** [comment]
i cant found 
build/exe.win32-2.7/numpy/core/

**Comment by sharonsowmya** [comment]
@GauravBorade have you found a solution?

**Comment by GauravBorade** [comment]
I reinstalled it and then installed libraries like tensorflow using pip

**Comment by kurt-rhee** [comment]
I get:

```
ImportError: Unable to import required dependencies:
numpy: DLL load failed: The specified module could not be found.
```

When trying to freeze a program with pandas, is this the same issue or something different?

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.

**Comment by Cristiano2132** [comment]
Hello,
I'm using python 3.7.6 and the new version of cx-Freeze. I checked the error with the pandas package, the simple fact of importing the package into the application generates an error. Cx-Freze compiles without errors but the generated application does not open.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.2 has just been released with namespace detection. Please, try it.
I see an issue with numpy 1.18.3 to 1.19 and pillow 7.x, and I'm investigating.
For now, it has a workaround.
pip install "numpy<1.18.3" "pillow<7"

**Comment by marcelotduarte** [comment]
@Cristiano2132 Can you try cx-freeze 6.2 with the workaround?

If you have a C compiler, you can test the development version:
`pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@develop`

**Comment by marcelotduarte** [comment]
cx_Freeze 6.3 has just been released.
Closing due to inactivity. 
If you had issues please re-open.
