### ISSUE TITLE
ImportError: DLL load failed with Numpy 1.26.0

### ISSUE THREAD

**Issue by bw7715** [marcelotduarte/cx_Freeze#2061]
**Describe the bug**
An error occurs when try to run frozen project with Numpy 1.26.0

```python
C:\Project\Test\tools>..\_build\_output_freezer\project.exe
Traceback (most recent call last):
  File "C:\Project\Test\_build\venv\lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "C:\Project\Test\_build\venv\lib\site-packages\numpy\core\multiarray.py", line 10, in <module>
    from . import overrides
  File "C:\Project\Test\_build\venv\lib\site-packages\numpy\core\overrides.py", line 8, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed while importing _multiarray_umath: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Project\Test\_build\venv\lib\site-packages\numpy\__init__.py", line 158, in <module>
    from numpy.__config__ import show as show_config
  File "C:\Project\Test\_build\venv\lib\site-packages\numpy\__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "C:\Project\Test\_build\venv\lib\site-packages\numpy\core\__init__.py", line 50, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "C:\Project\Test\_build\_output_freezer\project.exe"
  * The NumPy version is: "1.26.0"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: The specified module could not be found.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Project\Test\_build\venv\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 124, in run
    module_init.run(name + "__main__")
  File "C:\Project\Test\_build\venv\Lib\site-packages\cx_Freeze\initscripts\console.py", line 16, in run
    exec(code, module_main.__dict__)
  File "C:\Project\Test\prject.py", line 2, in <module>
    import torch
  File "C:\Project\Test\_build\venv\lib\site-packages\torch\__init__.py", line 934, in <module>
    from .storage import _StorageBase, TypedStorage, _LegacyStorage, UntypedStorage, _warn_typed_storage_removal
  File "C:\Project\Test\_build\venv\lib\site-packages\torch\storage.py", line 12, in <module>
    import numpy as np
  File "C:\Project\Test\_build\venv\lib\site-packages\numpy\__init__.py", line 163, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
```

**To Reproduce**
Freeze a project with newest Numpy.

**Desktop (please complete the following information):**
 - Platform information: Windows 10
 - OS architecture (e.g. amd64): 64 bit
 - cx_Freeze version: 6.15.7
 - Python version: 3.9
 - Numpy: 1.26.0

**Comment by marcelotduarte** [comment]
PR #2058 fix this.
You can test the patch in the latest development build:
`pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`
For conda-forge the command is:
`conda install -y --no-channel-priority -S -c https://marcelotduarte.github.io/packages/conda cx_Freeze`

**Comment by marcelotduarte** [comment]
[Release 6.15.8](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.15.8) is out!

**Comment by bw7715** [comment]
Thank you, it works now :)
