### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy.core._exceptions' with numpy 1.26.0 and cx_Freeze 6.15.8

### ISSUE THREAD

**Issue by jpeg13** [marcelotduarte/cx_Freeze#2068]
**Describe the bug**
An error occurs when trying to run an executable created with cx_Freeze 6.15.8 from a script using numpy 1.26.0.

```
Traceback (most recent call last):
  File "C:\Code\test\matplotlib_sample\venv\lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "C:\Code\test\matplotlib_sample\venv\lib\site-packages\numpy\core\multiarray.py", line 10, in <module>
    from . import overrides
  File "C:\Code\test\matplotlib_sample\venv\lib\site-packages\numpy\core\overrides.py", line 8, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._exceptions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Code\test\matplotlib_sample\venv\lib\site-packages\numpy\__init__.py", line 144, in <module>
    from numpy.__config__ import show as show_config
  File "C:\Code\test\matplotlib_sample\venv\lib\site-packages\numpy\__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "C:\Code\test\matplotlib_sample\venv\lib\site-packages\numpy\core\__init__.py", line 50, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "C:\Code\test\matplotlib_sample\build\exe.win-amd64-3.10\matplotlib_eg.exe"
  * The NumPy version is: "1.26.0"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._exceptions'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Code\test\matplotlib_sample\venv\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 124, in run
    module_init.run(name + "__main__")
  File "C:\Code\test\matplotlib_sample\venv\Lib\site-packages\cx_Freeze\initscripts\console.py", line 16, in run
    exec(code, module_main.__dict__)
  File "matplotlib_eg.py", line 3, in <module>
    from matplotlib.backends.backend_wxagg import (
  File "C:\Code\test\matplotlib_sample\venv\lib\site-packages\matplotlib\__init__.py", line 169, in <module>
    import numpy
  File "C:\Code\test\matplotlib_sample\venv\lib\site-packages\numpy\__init__.py", line 149, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
```

**To Reproduce**
Freeze the matplotlib sample with numpy 1.26.0 and cx_Freeze 6.15.8 and run the executable.

**Expected behavior**
The frozen executable runs without error.

**Desktop:**
Windows 10
```
$ python -VV
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
$ venv/Scripts/python -m pip list
Package         Version
--------------- -------
contourpy       1.1.1
cx-Freeze       6.15.8
cx-Logging      3.1.0
cycler          0.11.0
fonttools       4.42.1
kiwisolver      1.4.5
lief            0.13.2
matplotlib      3.8.0
numpy           1.26.0
packaging       23.1
Pillow          10.0.1
pip             23.0.1
pyparsing       3.1.1
python-dateutil 2.8.2
setuptools      65.5.0
six             1.16.0
wheel           0.41.2
wxPython        4.2.1
```

**Comment by mariasabba** [comment]
I am having the same issue. Already installed older versions from numpy trying to solve it, in and outside venv, nothing helped.

**Comment by marcelotduarte** [comment]
The fix 5188877ceddf104cc3abafd0eb5e32ce61853610
I usually run tests on the development version and do backport. But as I developed a new method of identifying imports using stubs, I could remove an include_packages (which could not be removed in the backport).
I will release this correction soon.

**Comment by jpeg13** [comment]
> I am having the same issue. Already installed older versions from numpy trying to solve it, in and outside venv, nothing helped.

@mariasabba numpy 1.25.2 with cx_Freeze 6.15.7 works for me.

**Comment by jpeg13** [comment]
@marcelotduarte Thank you, I've tested the fix locally, I confirm it works on my setup.

**Comment by mariasabba** [comment]
@marcelotduarte even aplying this line of code to import numpy explicitly, it didn't work. But @jpeg13 solution worked perfectly. Thank you!!

**Comment by marcelotduarte** [comment]
@mariasabba
Are you using some option like zip_include_packages?
If you use packages=["numpy"] it works?

**Comment by marcelotduarte** [comment]
[Release 6.15.9](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.15.9) is out!

Can you test and give feedback?

Also, can you test the development version?
`pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`
For conda-forge the command is:
`conda install -y --no-channel-priority -S -c https://marcelotduarte.github.io/packages/conda cx_Freeze`

**Comment by jpeg13** [comment]
I confirm that the release 6.15.9 and the development version 6.16.0.dev9 work (using pip). Thank you for your work!
