### ISSUE TITLE
Linux and PyTorch 2.1.0 - RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by bw7715** [marcelotduarte/cx_Freeze#2088]
**Describe the bug**
An error occurs when try to freeze a project with PyTorch 2.1.0 on Linux. 
On Windows freezing works. 
With previous PyTorch 2.0.1 freezing works on Windows and Linux.

```python
Freezing command: '['/home/user1/Desktop/work/project/_build/venv/bin/cxfreeze', '-O', '-OO', '--include-msvcr', '--target-dir=/home/user1/Desktop/work/project/_build/output', '--target-name=project', '--include-path=/home/user1/Desktop/work/project', '--packages=torch,torchvision,typing_extensions', ' PosixPath('/home/user1/Desktop/work/project/project1.py')]'	
Traceback (most recent call last):
  File "/home/user1/Desktop/work/project/_build/venv/lib/python3.9/site-packages/cx_Freeze/module.py", line 172, in in_file_system
    return self.parent.in_file_system
  File "/home/user1/Desktop/work/project/_build/venv/lib/python3.9/site-packages/cx_Freeze/module.py", line 172, in in_file_system
    return self.parent.in_file_system
  File "/home/user1/Desktop/work/project/_build/venv/lib/python3.9/site-packages/cx_Freeze/module.py", line 172, in in_file_system
    return self.parent.in_file_system
  [Previous line repeated 997 more times]
RecursionError: maximum recursion depth exceeded
```

**Desktop (please complete the following information):**
 - Platform information: Ubuntu 22.04.3 LTS
 - OS architecture (e.g. amd64): 64bit
 - cx_Freeze version: 6.15.9
 - Python version: 3.9

**Comment by marcelotduarte** [comment]
You can test the patch in the latest development build:
`pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`
For conda-forge the command is:
`conda install -y --no-channel-priority -S -c https://marcelotduarte.github.io/packages/conda cx_Freeze`

**Comment by bw7715** [comment]
I have tried with the cx-Freeze 6.16.0.dev9 version but still get the same error.

**Comment by marcelotduarte** [comment]
I have used a minimal sample:
```
import torch

print("torch", torch.__version__)
```

Can you provide a better minimal sample?

**Comment by bw7715** [comment]
With the simple sample you provided, freezing works. I will try to prepare code to reproduce the error.

I added `print(self.parent)` in the place when the error occurs:

`venv/lib/python3.9/site-packages/cx_Freeze/module.py`
```python
    @property
    def in_file_system(self) -> int:
        """Returns a value indicating where the module/package will be stored:
        0. in a zip file (not directly in the file system)
        1. in the file system, package with modules and data
        2. in the file system, only detected modules.
        """
        print(self.parent)
        if self.parent is not None:
            return self.parent.in_file_system
        if self.path is None or self.file is None:
            return 0
        return self._in_file_system
```

And the print output is:
```
<Module name='triton._C.libtriton.triton._C.libtriton.triton._C.libtriton.triton._C.libtriton.triton._C.libtriton.triton._C.libtriton.triton._C.libtriton.triton._C.libtriton', file=PosixPath('/home/user1/Desktop/work/venv/lib/python3.9/site-packages/triton/_C/libtriton.so')>
```

**Comment by marcelotduarte** [comment]
With 6.15.9 I detected this module triton as the error, so I made the [fix](https://github.com/marcelotduarte/cx_Freeze/pull/2090/files#diff-1b7b1790c2021276354bf6c14bf3eb1422ed4c128ebb61b0b3eaff0f9d09acbdR13).

The changes in 'torch' are because I found other issues.

**Comment by bw7715** [comment]
Thank you, how can I check these changes? Because version 6.16.0.dev9 does not have them.

**Comment by marcelotduarte** [comment]
v6.16.0.dev has the changes. Maybe pip is using a cached version. Force the installation:

`pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze --force --no-cache`

**Comment by bw7715** [comment]
Thank you, I try with this and now I get an error with frozen project:

```python
Traceback (most recent call last):
  File "/home/user1/Desktop/work/project1/venv/lib/python3.9/site-packages/cx_Freeze/initscripts/__startup__.py", line 132, in run
    module_init.run(name + "__main__")
  File "/home/user1/Desktop/work/project1/venv/lib/python3.9/site-packages/cx_Freeze/initscripts/console.py", line 16, in run
    exec(code, module_main.__dict__)
  File "/home/user1/Desktop/work/project1/project1.py", line 31, in <module>
    import triton
  File "/home/user1/Desktop/work/project1/venv/lib/python3.9/site-packages/triton/__init__.py", line 8, in <module>
    from .runtime import (
  File "/home/user1/Desktop/work/project1/venv/lib/python3.9/site-packages/triton/runtime/__init__.py", line 1, in <module>
    from .autotuner import (Autotuner, Config, Heuristics, OutOfResources, autotune,
  File "/home/user1/Desktop/work/project1/venv/lib/python3.9/site-packages/triton/runtime/autotuner.py", line 7, in <module>
    from ..testing import do_bench
ModuleNotFoundError: No module named 'triton.testing'
```

**Comment by marcelotduarte** [comment]
I updated the patch. Please, try again. 
Force the installation:
`pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze --force --no-cache`

**Comment by bw7715** [comment]
Ok, currently with this simple sample it works:
```python
import torch

print("torch", torch.__version__)
``` 


but if I try with this:
```python
import triton

print("triton", triton.__version__)
```
I get this error:
```python
Traceback (most recent call last):
  File "/home/user1/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/cx_Freeze/initscripts/__startup__.py", line 132, in run
    module_init.run(name + "__main__")
  File "/home/user1/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/cx_Freeze/initscripts/console.py", line 16, in run
    exec(code, module_main.__dict__)
  File "/home/user1/PycharmProjects/pythonProject/project1.py", line 2, in <module>
    import triton
  File "/home/user1/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/triton/__init__.py", line 8, in <module>
    from .runtime import (
  File "/home/user1/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/triton/runtime/__init__.py", line 1, in <module>
    from .autotuner import (Autotuner, Config, Heuristics, OutOfResources, autotune,
  File "/home/user1/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/triton/runtime/autotuner.py", line 7, in <module>
    from ..testing import do_bench
  File "/home/user1/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/triton/testing.py", line 7, in <module>
    from ._C.libtriton.triton import runtime
ModuleNotFoundError: No module named 'triton._C'
```

**Comment by marcelotduarte** [comment]
I updated the patch. Please try again.

**Comment by bw7715** [comment]
Thank you, now it works :)

**Comment by marcelotduarte** [comment]
[Release 6.15.10](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.15.10) is out!
