### ISSUE TITLE
cx_freeze doesn't work

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#210]
Originally reported by: **Anonymous**

----------------------------------------

Hi Anthony,

always thanks for your kindness.
I'm having a problem that cx_freeze.
I'm having a pythoncom problem like URL below.

http://stackoverflow.com/questions/40782069/cx-freeze-importerror-no-module-named-pythoncom/40880303#40880303

I copied hooks.py into cx_freeze folder and built it.
build works fine and there was no pythoncom error.
but...I got another error in main script.

Can you help me out?

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/210

**Comment by anthony-tuininga** [comment]
*Original comment by* **jpid (Bitbucket: [jpid](https://bitbucket.org/jpid), GitHub: [jpid](https://github.com/jpid))**:

----------------------------------------

I'm using win7(64bit) with python3.5 
cx_freeze 5.0
plz help me.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anthony Tuininga (Bitbucket: [anthony_tuininga](https://bitbucket.org/anthony_tuininga), GitHub: Unknown)**:

----------------------------------------

The module you are using is generated and is loaded dynamically. You'll need to ensure that cx_Freeze finds it. You can put the import statement directly in your code or include it in the includes in your setup.py.

**Comment by anthony-tuininga** [comment]
*Original comment by* **jpid (Bitbucket: [jpid](https://bitbucket.org/jpid), GitHub: [jpid](https://github.com/jpid))**:

----------------------------------------

@anthony_tuininga 

I already put in import statement in to setup.py. 
I'm not stupid..

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anthony Tuininga (Bitbucket: [anthony_tuininga](https://bitbucket.org/anthony_tuininga), GitHub: Unknown)**:

----------------------------------------

I wasn't implying that you were stupid. If you got that from my comment, my apologies. Are you able to provide a complete sample that demonstrates the problem? That includes a setup.py and a script that fails with the error you are getting? I can try it and figure out what the problem is then.

**Comment by anthony-tuininga** [comment]
*Original comment by* **jpid (Bitbucket: [jpid](https://bitbucket.org/jpid), GitHub: [jpid](https://github.com/jpid))**:

----------------------------------------

hi, anthony,

here is my codes with build and cx_freeze folder in site-packages.
I did downgrade 3.5 to 3.4 because cx_freeze didn't work.
I tried it more than 1 week to build but didn't work..
I know you can solve this problem and appreciated it.

Thank you for your help.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Harald Hanöfner (Bitbucket: [HarryH](https://bitbucket.org/HarryH), GitHub: [HarryH](https://github.com/HarryH))**:

----------------------------------------

I compared the built zipfiles between the py 2.7 (with cx_Freeze 4.3.4) and py 3.5 (with cx_Freeze 5.0) environment. The difference is, that after freezing within the py 3.5 environment the files "pythoncom.pyc" and "pywintypes.pyc" are missing in the resulting "python35.zip". If I add the files manually to the zipfile the freezed app works well.

But I can't discover why the files aren't added to the zipfile with cx_Freeze 5.0 and python 3.5? But maybe this information will help Anthony to find the problem...

**Comment by anthony-tuininga** [comment]
*Original comment by* **Harald Hanöfner (Bitbucket: [HarryH](https://bitbucket.org/HarryH), GitHub: [HarryH](https://github.com/HarryH))**:

----------------------------------------

Today I checked the code again and I found the problem in freezer.py

Here is the code piece from cx_Freeze 4.3.4, line 557-560:

```
#!python


baseFileName, ext = os.path.splitext(fileName)
if baseFileName != module.name and module.name != "zlib":
    if "." in module.name:
        fileName = module.name + ext
```
And here is the code piece from cx_Freeze 5.0, line 543-545:

```
#!python


if "." in module.name:
    baseFileName, ext = os.path.splitext(fileName)
    fileName = module.name + ext
```

The if-query in the new code ignores adding the "pythoncom.pyc" and "pywintypes.pyc".

If I replace the code in freezer.py V5.0 with the code from V4.3.4 my apps works as they should - without pythoncom error.

I don't no if this replacement is correct for all cases. My insight in the cx_freeze code is to shallow, but I think Anthony can estimate it and maybe it can be an approach for a patch.

**Comment by anthony-tuininga** [comment]
*Original comment by* **jpid (Bitbucket: [jpid](https://bitbucket.org/jpid), GitHub: [jpid](https://github.com/jpid))**:

----------------------------------------

@HarryH 
Thanks harald, let me check the code.
and I'll let you know :)

**Comment by anthony-tuininga** [comment]
*Original comment by* **jpid (Bitbucket: [jpid](https://bitbucket.org/jpid), GitHub: [jpid](https://github.com/jpid))**:

----------------------------------------

@HarryH 
well..this doesn't work :(
I agree with you that Anthony can be an approach for a patch ASAP.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Harald Hanöfner (Bitbucket: [HarryH](https://bitbucket.org/HarryH), GitHub: [HarryH](https://github.com/HarryH))**:

----------------------------------------

Oh, sorry I didn't see that Anthony already built a patch mentioned at this address => http://stackoverflow.com/questions/40744692/import-error-when-using-cx-freeze-with-pythoncom#40880303. This patch works fine - pythoncom dependencies are copied correct.

So, my patch above is now decrepitly. Please ignore it.

@jpid
I think your problem above isn't really a pythoncom "error". I found a very [hopefully] useful article for you => http://stackoverflow.com/questions/26907177/ensuredispatch-error-when-using-cx-freeze-for-making-exe

Please see especially the last post there. Maybe it will eliminate your problem.

What also helped on my machine was to replace 

```
#!python

win32.gencache.EnsureDispatch('excel.Application')
```
with

```
#!python

win32.Dispatch('excel.Application')
```

**Comment by anthony-tuininga** [comment]
*Original comment by* **jpid (Bitbucket: [jpid](https://bitbucket.org/jpid), GitHub: [jpid](https://github.com/jpid))**:

----------------------------------------

@HarryH 
Thank you for helping me Harald,
unfortunately, It didn't work for me.
I got another error message.
==============================================================
2016-12-07 13:45:18,711 INFO: Imported existing <module 'comtypes.gen' from 'D:\Master\dist\.\comtypes\gen\__init__.pyc'>
2016-12-07 13:45:18,721 INFO: Using writeable comtypes cache directory: 
'D:\Master\dist\comtypes\gen'
2016-12-07 13:45:18,721 INFO: Could not import comtypes.gen._944DE083_8FB8_45CF_BCB7_C477ACB2F897_0_1_0: No module named _944DE083_8FB8_45CF_BCB7_C477ACB2F897_0_1_0
2016-12-07 13:45:18,782 INFO: Could not import comtypes.gen._00020430_0000_0000_C000_000000000046_0_2_0: No module named _00020430_0000_0000_C000_000000000046_0_2_0
2016-12-07 13:45:18,832 INFO: Could not import comtypes.gen.stdole: No module named stdole
2016-12-07 13:45:18,931 INFO: Could not import comtypes.gen.UIAutomationClient: No module named UIAutomationClient
Traceback (most recent call last):
  File "M1001_CommonCode.py", line 34, in <module>
  File "win32com\client\dynamic.pyc", line 527, in __getattr__
    
AttributeError: excel.Application.Workbooks

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anthony Tuininga (Bitbucket: [anthony_tuininga](https://bitbucket.org/anthony_tuininga), GitHub: Unknown)**:

----------------------------------------

The original issue (pythoncom) was already solved. An additional issue (__main__) was just solved which may have an impact on this. In any case, I used the code provided and it worked correctly in Python 3.5 -- at least up until the point where it starts trying to process specific files which don't exist on my system!

**Comment by anthony-tuininga** [comment]
*Original comment by* **jpid (Bitbucket: [jpid](https://bitbucket.org/jpid), GitHub: [jpid](https://github.com/jpid))**:

----------------------------------------

@anthony_tuininga
Your code is not updated yet~
I don't see the updated code anywhere

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anthony Tuininga (Bitbucket: [anthony_tuininga](https://bitbucket.org/anthony_tuininga), GitHub: Unknown)**:

----------------------------------------

The code was pushed to the repository. A new release has not been made yet but I hope to do that soon.
