### ISSUE TITLE
KeyError: 'IMPORT_STAR'

### ISSUE THREAD

**Issue by calendulish** [marcelotduarte/cx_Freeze#2117]
```
2023-10-30T06:38:34.4924240Z   Traceback (most recent call last):
2023-10-30T06:38:34.4938385Z     File "C:\hostedtoolcache\windows\Python\3.12.0\x64\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
2023-10-30T06:38:34.4940501Z       main()
2023-10-30T06:38:34.4942067Z     File "C:\hostedtoolcache\windows\Python\3.12.0\x64\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
2023-10-30T06:38:34.4946018Z       json_out['return_val'] = hook(**hook_input['kwargs'])
2023-10-30T06:38:34.4946938Z                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-30T06:38:34.4948760Z     File "C:\hostedtoolcache\windows\Python\3.12.0\x64\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
2023-10-30T06:38:34.4950279Z       return hook(config_settings)
2023-10-30T06:38:34.4950769Z              ^^^^^^^^^^^^^^^^^^^^^
2023-10-30T06:38:34.4952406Z     File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-hxrey49h\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
2023-10-30T06:38:34.4954566Z       return self._get_build_requires(config_settings, requirements=['wheel'])
2023-10-30T06:38:34.4955438Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-30T06:38:34.4957083Z     File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-hxrey49h\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
2023-10-30T06:38:34.4958545Z       self.run_setup()
2023-10-30T06:38:34.4960019Z     File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-hxrey49h\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
2023-10-30T06:38:34.4961355Z       exec(code, locals())
2023-10-30T06:38:34.4961854Z     File "<string>", line 203, in <module>
2023-10-30T06:38:34.4963344Z     File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-hxrey49h\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
2023-10-30T06:38:34.4964683Z       return distutils.core.setup(**attrs)
2023-10-30T06:38:34.4965286Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-30T06:38:34.4966828Z     File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-hxrey49h\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 147, in setup
2023-10-30T06:38:34.4968207Z       _setup_distribution = dist = klass(attrs)
2023-10-30T06:38:34.4968851Z                                    ^^^^^^^^^^^^
2023-10-30T06:38:34.4970323Z     File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-hxrey49h\overlay\Lib\site-packages\setuptools\dist.py", line 303, in __init__
2023-10-30T06:38:34.4971658Z       _Distribution.__init__(self, dist_attrs)
2023-10-30T06:38:34.4973188Z     File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-hxrey49h\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 283, in __init__
2023-10-30T06:38:34.4974561Z       self.finalize_options()
2023-10-30T06:38:34.4976035Z     File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-hxrey49h\overlay\Lib\site-packages\setuptools\dist.py", line 679, in finalize_options
2023-10-30T06:38:34.4977720Z       for ep in sorted(loaded, key=by_order):
2023-10-30T06:38:34.4978286Z                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-30T06:38:34.4979747Z     File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-hxrey49h\overlay\Lib\site-packages\setuptools\dist.py", line 678, in <lambda>
2023-10-30T06:38:34.4981098Z       loaded = map(lambda e: e.load(), filtered)
2023-10-30T06:38:34.4981719Z                              ^^^^^^^^
2023-10-30T06:38:34.4982704Z     File "C:\hostedtoolcache\windows\Python\3.12.0\x64\Lib\importlib\metadata\__init__.py", line 205, in load
2023-10-30T06:38:34.4983908Z       module = import_module(match.group('module'))
2023-10-30T06:38:34.4984561Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-30T06:38:34.4985600Z     File "C:\hostedtoolcache\windows\Python\3.12.0\x64\Lib\importlib\__init__.py", line 90, in import_module
2023-10-30T06:38:34.4986793Z       return _bootstrap._gcd_import(name[level:], package, level)
2023-10-30T06:38:34.4987538Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-30T06:38:34.4988347Z     File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
2023-10-30T06:38:34.4989270Z     File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
2023-10-30T06:38:34.4992081Z     File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
2023-10-30T06:38:34.4993194Z     File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
2023-10-30T06:38:34.4994210Z     File "<frozen importlib._bootstrap_external>", line 994, in exec_module
2023-10-30T06:38:34.4995285Z     File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
2023-10-30T06:38:34.4997066Z     File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-hxrey49h\overlay\Lib\site-packages\cx_Freeze\__init__.py", line 12, in <module>
2023-10-30T06:38:34.4998466Z       from .command.build_exe import BuildEXE as build_exe
2023-10-30T06:38:34.5000135Z     File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-hxrey49h\overlay\Lib\site-packages\cx_Freeze\command\build_exe.py", line 13, in <module>
2023-10-30T06:38:34.5001574Z       from cx_Freeze.freezer import Freezer
2023-10-30T06:38:34.5003084Z     File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-hxrey49h\overlay\Lib\site-packages\cx_Freeze\freezer.py", line 30, in <module>
2023-10-30T06:38:34.5004359Z       from .finder import ModuleFinder
2023-10-30T06:38:34.5005821Z     File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-hxrey49h\overlay\Lib\site-packages\cx_Freeze\finder.py", line 33, in <module>
2023-10-30T06:38:34.5007184Z       IMPORT_STAR = opcode.opmap["IMPORT_STAR"]
2023-10-30T06:38:34.5007835Z                     ~~~~~~~~~~~~^^^^^^^^^^^^^^^
2023-10-30T06:38:34.5008419Z   KeyError: 'IMPORT_STAR'
2023-10-30T06:38:34.5008896Z   [end of output]
```

**Desktop (please complete the following information):**
 - Platform information (e.g. Ubuntu Linux 22.04): Windows 11
 - OS architecture (e.g. amd64): amd64
 - cx_Freeze version [e.g. 6.11]: 6.15.10
 - Python version [e.g. 3.10]: 3.12

**Additional context**
it's working fine on python 3.11 but not on python 3.12
not sure how to debug

**Comment by marcelotduarte** [comment]
Duplicate of #1921 

cx_Freeze 6.15.x and dependencies (cx_Logging, Lief) are not declared compatible with Python 3.12 and do not provide wheels.

But, you can test the latest development build:
`pip install --force --no-cache --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`
For conda-forge the command is:
`conda install -y --no-channel-priority -S -c https://marcelotduarte.github.io/packages/conda cx_Freeze`

**Comment by calendulish** [comment]
thank you
the development build is working fine
