### ISSUE TITLE
cx_freeze keeps looking in python/libs, not in compiled libs

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#214]
Originally reported by: **Anonymous**

----------------------------------------

I `cx_freeze`d a Python program (moved from cx_freeze 4.3.4 to 5.0), and I have a problem that apparently cx_freeze keeps looking for the libs it needs in Python's (Anaconda's) directory, instead of looking for it in the directory of the executable it produced.

The current error I'm getting is the following, as I'm using `multiprocessing`:

    Traceback (most recent call last):
      File "D:\Anaconda3\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
        __import__(name + "__init__")
      File "D:\Anaconda3\lib\site-packages\cx_Freeze\initscripts\Console.py", line 21, in <module>
        scriptModule = __import__(moduleName)
      File "Main.py", line 4, in <module>
      File "D:\Anaconda3\lib\multiprocessing\__init__.py", line 16, in <module>
        from . import context
      File "D:\Anaconda3\lib\multiprocessing\context.py", line 5, in <module>
        from . import process
    ImportError: cannot import name 'process'

The directory you see up there is my Python installation!!!! Why is it looking there? Now in the frozen program, if I go to: `myFrozenProgram/multiprocessing/`, I find a file called `Process.pyc`!

My setup script is the following. It's a little more complicated than usual because I add custom dlls from numpy because of a problem that happened in the past. Also the TCL part I added due to an error with tcl:

    import sys
    import os
    import json
    import glob
    from cx_Freeze import setup, Executable
    from GUI.Meta import *
    import os

    PythonPath = os.path.split(sys.executable)[0] #get python path

    os.environ['TCL_LIBRARY'] = os.path.join(PythonPath,"tcl","tcl8.6")
    os.environ['TK_LIBRARY']  = os.path.join(PythonPath,"tcl","tk8.6")

    mkl_files_json_file = glob.glob(os.path.join(PythonPath, "conda-meta","mkl-[!service]*.json"))[0] #json files that has mkl files list (exclude the "service" file)
    with open(mkl_files_json_file) as file:
        mkl_files_json_data = json.load(file)

    numpy_mkl_dlls = mkl_files_json_data["files"] #get the list of files from the json data file

    np_dlls_fullpath = list(map(lambda currPath: os.path.join(PythonPath,currPath),numpy_mkl_dlls)) #get the full path of these files

    includefiles = [("GUI/icon.png","GUI/icon.png") + np_dlls_fullpath
    target = Executable("Main.py",
                        #base = "Win32GUI",
                        icon = "GUI/icon.ico",
                        targetName="MyProg.exe")

    setup(
        name = "My program",
        version = SOFTWARE_VERSION,
        description = "Program",
        options = {'build_exe': {'include_files':includefiles, 'includes': ["sip","re","atexit","PyQt5.QtCore","PyQt5.QtGUI","PyQt5.QtWidgets","multiprocessing"]}},
        executables = [target])

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/214

**Comment by anthony-tuininga** [comment]
*Original comment by* **Graham Jones (Bitbucket: [grahamrjuk](https://bitbucket.org/grahamrjuk), GitHub: [grahamrjuk](https://github.com/grahamrjuk))**:

----------------------------------------

I have the same issue and have spent a little time looking at it.

In the multiprocessing sub-folder in my build folder (in my case ```build/exe.win-amd64-3.5/multiprocessing```) the "process" module is ```Process.pyc```

The import command in ```context``` is using lower case to import ```process```.

If I rename ```Process.pyc``` to ```process.pyc``` then the software runs successfully.

I think the directory seen in the trace is a red-herring - this is the folder it was in when built. What is displayed there can be altered by the ```replace_paths``` option.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Graham Jones (Bitbucket: [grahamrjuk](https://bitbucket.org/grahamrjuk), GitHub: [grahamrjuk](https://github.com/grahamrjuk))**:

----------------------------------------

Further, when the software is built, I see these lines:

```
...
P multiprocessing           C:\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\multiprocessing\__init__.py
m multiprocessing.Process   C:\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\multiprocessing\Process.py
m multiprocessing.connection C:\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\multiprocessing\connection.py
m multiprocessing.context   C:\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\multiprocessing\context.py
P multiprocessing.dummy     C:\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\multiprocessing\dummy\__init__.py
m multiprocessing.dummy.connection C:\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\multiprocessing\dummy\connection.py
m multiprocessing.forkserver C:\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\multiprocessing\forkserver.py
m multiprocessing.heap      C:\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\multiprocessing\heap.py
m multiprocessing.managers  C:\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\multiprocessing\managers.py
m multiprocessing.pool      C:\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\multiprocessing\pool.py
m multiprocessing.popen_fork C:\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\multiprocessing\popen_fork.py
m multiprocessing.popen_forkserver C:\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\multiprocessing\popen_forkserver.py
m multiprocessing.popen_spawn_posix C:\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\multiprocessing\popen_spawn_posix.py
m multiprocessing.popen_spawn_win32 C:\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\multiprocessing\popen_spawn_win32.py
m multiprocessing.process   C:\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\multiprocessing\process.py
...
```

Note the second and the last lines of the output - both copy the ```process``` sub-module, first with the name capitalised, the second lower-case.

The original file in the Python installation is lower-case, so this seems to be something cx_Freeze is doing when freezing the software.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Samer Afach (Bitbucket: [samerafach](https://bitbucket.org/samerafach), GitHub: [samerafach](https://github.com/samerafach))**:

----------------------------------------

@grahamrjuk Thank you very much for this information. Actually, the funny part is that I tried this before, and "thought" it didn't work, because after that, I also got the same error but with `QtGui` doesn't exist (and I oversaw it), for the exact same reason, because the file was named `QtGUI.pyd`. I renamed that to `QtGui.pyd` and that fixed "that" problem. Now I got a new problem right after those renames, for which maybe I have to start a new topic, but I'll post it here too.

After renaming these files, I start my executable and I get... NOTHING! Yes, absolutely nothing. The terminal starts, and nothing is printed there, and the program exits with code 0... Any idea what that is, or even how to debug that?

**Comment by anthony-tuininga** [comment]
*Original comment by* **Graham Jones (Bitbucket: [grahamrjuk](https://bitbucket.org/grahamrjuk), GitHub: [grahamrjuk](https://github.com/grahamrjuk))**:

----------------------------------------

@samerafach Your other problem could be related to #211 - you can't use ```if __name__ == '__main__':``` anymore. I think it is also discussed in the mail-list.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Samer Afach (Bitbucket: [samerafach](https://bitbucket.org/samerafach), GitHub: [samerafach](https://github.com/samerafach))**:

----------------------------------------

@grahamrjuk Oh, thank you very much! You exactly pointed out what the problem was. It works fine now.

I automated the renames of `Process.pyc` and `QtGUI.pyd` in my setup script, and it works fine now. I'm wondering, is this supposed to be fixed in the future?

**Comment by anthony-tuininga** [comment]
*Original comment by* **Graham Jones (Bitbucket: [grahamrjuk](https://bitbucket.org/grahamrjuk), GitHub: [grahamrjuk](https://github.com/grahamrjuk))**:

----------------------------------------

I am building Windows msi installers and can't see any easy way around this problem. The module would need renaming between the build stage and the creation of the installer.
(Note the subject of this issue is technically incorrect now - we know the problem is the incorrect module names in the frozen build, not the folder used to find modules) .

**Comment by anthony-tuininga** [comment]
*Original comment by* **Samer Afach (Bitbucket: [samerafach](https://bitbucket.org/samerafach), GitHub: [samerafach](https://github.com/samerafach))**:

----------------------------------------

I made the renames in my `setup.py` script with no exception handling. This guarantees that if this gets fixed in the future, it'll throw an error and make me realize that this is fixed. I think this is possible for me because I don't use the automated MSI installer; I use NSIS and create my own installer.

About the wrong topic name, I don't see an edit option... I would change the title if I could... Sorry!

**Comment by anthony-tuininga** [comment]
*Original comment by* **Graham Jones (Bitbucket: [grahamrjuk](https://bitbucket.org/grahamrjuk), GitHub: [grahamrjuk](https://github.com/grahamrjuk))**:

----------------------------------------

~~As a quick and dirty fix I add a line after line 399 of finder.py doing:~~
```
            path = os.path.normcase(path)
```
~~My application then works, however there is every chance this will break something else without proper consideration of a sensible solution.~~

That fix doesn't work anymore (I knew it was quick and dirty).

The problem is that some modules do ```from multiprocessing import Process``` and the module code is in a file with the name ```process.py```. cx_Freeze is then told the module is in ```multiprocessing/Process.py``` on a non-case-sensitive OS such as Windows. The problem then comes on execution when the real import of the ```process``` module can't open ```Process.pyc```

**Comment by anthony-tuininga** [comment]
The problem is that the multiprocessing package has both Process (class) and process (submodule) but the imp.find_module() function on Windows finds both of them as submodules! I have pushed a change to cx_Freeze that tells it to ignore multiprocessing.Process. You can see more details on pull request #241 .
