### ISSUE TITLE
cx_Freeze with Python 3.6.0rc1

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#215]
Originally reported by: **Aaron Mildenstein (Bitbucket: [theuntergeek](https://bitbucket.org/theuntergeek), GitHub: Unknown)**

----------------------------------------

I'm trying to freeze my project, which works great with the recent 5.0 dev release in Python 3.5.2, but not with the most recent 3.6.0rc1 release.  I thought I'd get a leg up and test early.  My results are as follows:

```
#!python

[vagrant@localhost curator_source]$ python3.6 setup.py build_exe
running build_exe
Traceback (most recent call last):
  File "setup.py", line 124, in <module>
    executables = [curator_exe,curator_cli_exe,repomgr_exe]
  File "/home/vagrant/.local/lib/python3.6/site-packages/cx_Freeze/dist.py", line 337, in setup
    distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/vagrant/.local/lib/python3.6/site-packages/cx_Freeze/dist.py", line 207, in run
    freezer.Freeze()
  File "/home/vagrant/.local/lib/python3.6/site-packages/cx_Freeze/freezer.py", line 544, in Freeze
    self.finder = self._GetModuleFinder()
  File "/home/vagrant/.local/lib/python3.6/site-packages/cx_Freeze/freezer.py", line 322, in _GetModuleFinder
    self.path, self.replacePaths)
  File "/home/vagrant/.local/lib/python3.6/site-packages/cx_Freeze/finder.py", line 150, in __init__
    self._AddBaseModules()
  File "/home/vagrant/.local/lib/python3.6/site-packages/cx_Freeze/finder.py", line 161, in _AddBaseModules
    self.IncludeModule("traceback")
  File "/home/vagrant/.local/lib/python3.6/site-packages/cx_Freeze/finder.py", line 650, in IncludeModule
    namespace = namespace)
  File "/home/vagrant/.local/lib/python3.6/site-packages/cx_Freeze/finder.py", line 309, in _ImportModule
    deferredImports, namespace = namespace)
  File "/home/vagrant/.local/lib/python3.6/site-packages/cx_Freeze/finder.py", line 402, in _InternalImportModule
    parentModule, namespace)
  File "/home/vagrant/.local/lib/python3.6/site-packages/cx_Freeze/finder.py", line 473, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "/home/vagrant/.local/lib/python3.6/site-packages/cx_Freeze/finder.py", line 561, in _ScanCode
    arguments.append(co.co_consts[opArg])
IndexError: tuple index out of range
```

I'm not sure what may be going on here, and I didn't take time to dig.  This is just a report so you know what's going on before 3.6 is officially released next week.

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/215

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anthony Tuininga (Bitbucket: [anthony_tuininga](https://bitbucket.org/anthony_tuininga), GitHub: Unknown)**:

----------------------------------------

I can confirm this is an issue and am looking into what is causing it. It is possible that the bytecode format changed in Python 3.6 but will figure out what the problem is and correct it. Thanks for the heads up!

**Comment by anthony-tuininga** [comment]
*Original comment by* **hlcd (Bitbucket: [lolo020117](https://bitbucket.org/lolo020117), GitHub: Unknown)**:

----------------------------------------

By comparing strings representing the sequence of bytecode instructions in python36 vs python35, I patched the code of finder._ScanCode. This ended up with the following slightly modified _ScanCode function that I have tested on a small project and should work as expected on any other ones, if I have made no mistake. Hope this helps.

```
#!python

    def _ScanCode(self, co, module, deferredImports, topLevel = True):
        """Scan code, looking for imported modules and keeping track of the
           constants that have been created in order to better tell which
           modules are truly missing."""
        opIndex = 0
        arguments = []
        code = co.co_code
        numOps = len(code)
        is3 = sys.version_info[0] >= 3
        is36 = sys.version_info.major >= 3 and sys.version_info.minor >= 6
        while opIndex < numOps:
            if is3:
                op = code[opIndex]
            else:
                op = ord(code[opIndex])
            opIndex += 1
            if op >= dis.HAVE_ARGUMENT:
                if is36:
                   opArg = code[opIndex]
                   opIndex += 1
                elif is3:
                    opArg = code[opIndex]  + code[opIndex + 1] * 256
                    opIndex += 2
                else:
                    opArg = ord(code[opIndex]) + ord(code[opIndex + 1]) * 256
                    opIndex += 2

            if op == LOAD_CONST:
                # Store an argument to be used later by an IMPORT_NAME operation.
                arguments.append(co.co_consts[opArg])

            elif op == IMPORT_NAME:
                name = co.co_names[opArg]
                if len(arguments) >= 2:
                    relativeImportIndex, fromList = arguments[-2:]
                else:
                    relativeImportIndex = -1
                    fromList, = arguments

                if name not in module.excludeNames:
                    # Load the imported module
                    importedModule = self._ImportModule(name, deferredImports,
                            module, relativeImportIndex)
                    if importedModule is not None:
                        if fromList and fromList != ("*",) \
                                and importedModule.path is not None:
                            self._EnsureFromList(module, importedModule,
                                    fromList, deferredImports)

            elif op == IMPORT_FROM and topLevel:
                if is36:
                    op = code[opIndex]
                    opArg = code[opIndex + 1]
                    opIndex += 2
                elif is3:
                    op = code[opIndex]
                    opArg = code[opIndex + 1]  + code[opIndex + 2] * 256
                    opIndex += 3
                else:
                    op = ord(code[opIndex])
                    opArg = ord(code[opIndex + 1]) + \
                            ord(code[opIndex + 2]) * 256
                    opIndex += 3

                if op == STORE_FAST:
                    name = co.co_varnames[opArg]
                else:
                    name = co.co_names[opArg]
                storeName = True
                if deferredImports:
                    deferredCaller, deferredPackage, deferredFromList = \
                            deferredImports[-1]
                    storeName = deferredCaller is not module
                if storeName:
                    module.globalNames[name] = None

            elif op == IMPORT_STAR and topLevel and importedModule is not None:
                module.globalNames.update(importedModule.globalNames)
                arguments = []

            elif op not in (BUILD_LIST, INPLACE_ADD):
                # The stack was used for something else, so we clear it.
                if topLevel and op in STORE_OPS:
                    name = co.co_names[opArg]
                    module.globalNames[name] = None
                arguments = []

        # Scan the code objects from function & class definitions
        for constant in co.co_consts:
            if isinstance(constant, type(co)):
                self._ScanCode(constant, module, deferredImports,
                        topLevel = False)
   
```

**Comment by anthony-tuininga** [comment]
*Original comment by* **Christopher Hoadley (Bitbucket: [hoadlck](https://bitbucket.org/hoadlck), GitHub: [hoadlck](https://github.com/hoadlck))**:

----------------------------------------

First off, thanks for looking into this and delivering a patch!

I tried the patch on my project, and the freeze process no longer errors out. I end up with a frozen executable.  However, when I try to run the program, it just executes and returns without doing any of the functionality of my program.  (I am running on Windows Vista.)

I was able to freeze the same program earlier with cx_freeze without any problems.  But, I have moved my program on to use Python 3.6 features, and can no longer use earlier versions of Python.

I am wondering if this may be some non-Python 3.6 problem I am having? This is the first time that I have used cx_freeze 5.0.

I am going to try a test where only the version of Python changes, and see if I can isolate the problem more.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Christopher Hoadley (Bitbucket: [hoadlck](https://bitbucket.org/hoadlck), GitHub: [hoadlck](https://github.com/hoadlck))**:

----------------------------------------

I found that Issue #211 is the source of why my program did not work: the patch that @lolo020117 delivered works fine for my application.  This is the first that I have used cx_freeze 5.0, so I was not aware of this problem until now.

Thanks!

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anthony Tuininga (Bitbucket: [anthony_tuininga](https://bitbucket.org/anthony_tuininga), GitHub: Unknown)**:

----------------------------------------

I just pushed my changes to correct this issue -- hopefully in a way that will require less maintenance for future releases! Please give one of the samples a try with this new code and let me know if you are still running into problems. I hope to make a new release later this week.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Christopher Hoadley (Bitbucket: [hoadlck](https://bitbucket.org/hoadlck), GitHub: [hoadlck](https://github.com/hoadlck))**:

----------------------------------------

Most excellent!

I pulled the latest changes and ran it thru my tests again. The program works in frozen mode, and I was able to remove the workaround I had to add for Issue #211.

Thank you all.

**Comment by anthony-tuininga** [comment]
*Original comment by* **hlcd (Bitbucket: [lolo020117](https://bitbucket.org/lolo020117), GitHub: Unknown)**:

----------------------------------------

The solution of Anthony (based on standard dis module) is a lot cleaner than mine, which was a quick and dirty hack to be quickly able to freeze Python 3.6 code until next cx_freeze release. Thanks.
