### ISSUE TITLE
Geopandas import error.

### ISSUE THREAD

**Issue by RybarskiDominik** [marcelotduarte/cx_Freeze#2193]
When I use "import geopandas as gpd"
in this case there is a problem in this line.
When I remove the geopandas import, the program works normally.

pyinstaller creates an exe file but it is full of false positive information about the virus.
nuitka also has a problem with creating the exe

No matter what version, I tried py 3.12 dev/cx_freeze 6.16.0.dev13 or 3.11/ cx_Freeze 6.15.12 there is the same problem.

Error:
```
---------------------------
cx_Freeze: Python error in main script
---------------------------
Traceback (most recent call last):
  File "C:\Users\Komputer\AppData\Roaming\Python\Python311\site-packages\cx_Freeze\initscripts\__startup__.py", line 124, in run
    module_init.run(name + "__main__")
  File "C:\Users\Komputer\AppData\Roaming\Python\Python311\site-packages\cx_Freeze\initscripts\console.py", line 16, in run
    exec(code, module_main.__dict__)
  File "GG.py", line 8, in <module>
  File "C:\Users\Komputer\AppData\Roaming\Python\Python311\site-packages\geopandas\__init__.py", line 3, in <module>
    from geopandas.geoseries import GeoSeries
  File "C:\Users\Komputer\AppData\Roaming\Python\Python311\site-packages\geopandas\geoseries.py", line 13, in <module>
    from pyproj import CRS
  File "C:\Users\Komputer\AppData\Roaming\Python\Python311\site-packages\pyproj\__init__.py", line 47, in <module>
    import pyproj.network
  File "C:\Users\Komputer\AppData\Roaming\Python\Python311\site-packages\pyproj\network.py", line 10, in <module>
    from pyproj._network import (  # noqa: F401 pylint: disable=unused-import
ImportError: DLL load failed while importing _network: Nie można odnaleźć określonego modułu.
```

My setup.py:
```
import sys
import os
from cx_Freeze import setup, Executable

includes = []
excludes = []
zip_include_packages = []
packages = []
include_files = []

build_exe_options = {"excludes": excludes, "includes": includes, "zip_include_packages": zip_include_packages, "include_files": include_files, "packages": packages}  # "optimize": 1, "silent_level": 3, "no_compress"

base = "Win32GUI" if sys.platform == "win32" else None

setup(
    name="GMLv1",
    version="1.0",
    description="GML",
    options={"build_exe": build_exe_options},
    executables=[Executable("GML.py", base=base)],
)
```

My Desktop:
 - Platform information : win 10
 - OS architecture :amd64
 - cx_Freeze version: 6.15.12
 - Python version: 3.11

**Comment by marcelotduarte** [comment]
You can test the patch in the latest development build:
`pip install --force --no-cache --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`
For conda-forge the command is:
`conda install -y --no-channel-priority -S -c https://marcelotduarte.github.io/packages/conda cx_Freeze`

**Comment by marcelotduarte** [comment]
[Release 6.15.13](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.15.13) is out!
