### ISSUE TITLE
RuntimeError: Failed to import transformers.models.wav2vec2.processing_wav2vec2 because of the following error (look up to see its traceback): [Errno 2] No such file or directory: 'C:\\Kunal\\build\\exe.win-amd64-3.10\\lib\\transformers\\__init__.py'

### ISSUE THREAD

**Issue by WhozKunal** [marcelotduarte/cx_Freeze#2203]
```
from cx_Freeze import setup, Executable
import sys

sys.setrecursionlimit(5000)

build_options = {
    'packages': [
        'whisperx', 'tkinter', 'threading', 'concurrent.futures', 'os', 'time', 'numpy', 'transformers', 'pyannote',
        'aiohttp', 'aiosignal', 'alembic', 'attrs',
        'audioread', 'av', 'certifi', 'cffi', 'click', 'colorama', 'coloredlogs', 'colorlog',
        'contourpy', 'ctranslate2', 'cycler', 'decorator', 'docopt', 'einops',
        'filelock', 'flatbuffers', 'frozenlist', 'fsspec', 'greenlet', 
        'humanfriendly', 'idna', 'joblib', 'julius', 'kiwisolver', 'lazy_loader', 'librosa',
        'lief', 'lightning', 'llvmlite', 'matplotlib',
        'mdurl', 'mpmath', 'msgpack', 'multidict', 'networkx', 'nltk', 'numba', 'omegaconf', 'onnxruntime',
        'optuna', 'packaging', 'pandas', 'pipdeptree', 'platformdirs', 'pooch', 'primePy',
        'pyannote.audio', 'pyannote.core', 'pyannote.database', 'pyannote.metrics', 'pyannote.pipeline',
        'pycparser', 'pyparsing', 'pyreadline3', 'pytz', 'regex', 'requests', 'rich', 'ruamel.yaml',
        'safetensors', 'scipy', 'semver', 'sentencepiece', 'shellingham', 'six', 'sortedcontainers',
        'soundfile', 'soxr', 'speechbrain', 'sympy', 'tabulate', 'tensorboardX', 'threadpoolctl',
        'tokenizers', 'torch', 'torchaudio', 'torchmetrics', 'torchvision',
        'tqdm', 'typer', 'typing_extensions', 'tzdata', 'urllib3', 'yarl', 'zstandard'
    ],

    'excludes': [],
    'include_msvcr': True,
   'include_files': [
        (r"C:\Kunal\env\Lib\site-packages\transformers", "transformers"),
        # ... other include_files entries
    ],
}

import sys
base = 'Win64GUI' if sys.platform == 'win64' else None

executables = [
    Executable('main.py', base=base)
]

setup(
    name='Pratilikha',
    version='1.0',
    description='Pratilikha',
    options={'build_exe': build_options},
    executables=executables
)


I have created the setup file using cx-freeze when i have  to run the exe then that bug comes:
Traceback (most recent call last):
  File "C:\Kunal\env\lib\site-packages\transformers\utils\import_utils.py", line 1382, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Users\sss\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Kunal\env\lib\site-packages\transformers\models\wav2vec2\processing_wav2vec2.py", line 21, in <module>
    from ...processing_utils import ProcessorMixin
  File "C:\Kunal\env\lib\site-packages\transformers\processing_utils.py", line 32, in <module>
    transformers_module = direct_transformers_import(Path(__file__).parent)
  File "C:\Kunal\env\lib\site-packages\transformers\utils\import_utils.py", line 1411, in direct_transformers_import
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Kunal\\build\\exe.win-amd64-3.10\\lib\\transformers\\__init__.py'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Kunal\env\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 124, in run
    module_init.run(name + "__main__")
  File "C:\Kunal\env\Lib\site-packages\cx_Freeze\initscripts\console.py", line 16, in run
    exec(code, module_main.__dict__)
  File "main.py", line 4, in <module>
  File "C:\Kunal\env\lib\site-packages\whisperx\__init__.py", line 1, in <module>
    from .transcribe import load_model
  File "C:\Kunal\env\lib\site-packages\whisperx\transcribe.py", line 9, in <module>
    from .alignment import align, load_align_model
  File "C:\Kunal\env\lib\site-packages\whisperx\alignment.py", line 12, in <module>
    from transformers import Wav2Vec2ForCTC, Wav2Vec2Processor
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "C:\Kunal\env\lib\site-packages\transformers\utils\import_utils.py", line 1373, in __getattr__
    value = getattr(module, name)
  File "C:\Kunal\env\lib\site-packages\transformers\utils\import_utils.py", line 1372, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Kunal\env\lib\site-packages\transformers\utils\import_utils.py", line 1384, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.wav2vec2.processing_wav2vec2 because of the following error (look up to see its traceback):
[Errno 2] No such file or directory: 'C:\\Kunal\\build\\exe.win-amd64-3.10\\lib\\transformers\\__init__.py'
```

step: 

I have check the init file it is there on the build folder 
![image](https://github.com/marcelotduarte/cx_Freeze/assets/73089776/6a490ff3-f45f-4a2d-9912-298f28dcebb7)

**Comment by marcelotduarte** [comment]
I noticed that:
1) Does not exit sys.platform == 'win64' nor base = 'Win64GUI', so, the correct is:
`base = 'Win32GUI' if sys.platform == 'win32' else None`
You can confirm using `print(sys.platform)` inside python cli.
2) copy files to lib\\transformers
```
'include_files': [
        (r"C:\Kunal\env\Lib\site-packages\transformers", "lib\\transformers"),
        # ... other include_files entries
    ],
```

**Comment by marcelotduarte** [comment]
Can I close the issue?

**Comment by WhozKunal** [comment]
Yes it is solved you can close now thanks for help
