### ISSUE TITLE
Errors freezing WeasyPrint module

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#222]
Originally reported by: **Anonymous**

----------------------------------------

I have tested the attached files for freezing the WeasyPrint module with a simple front end on both cx_Freeze 4.3.4 and 5.0 on Ubuntu 16.04 with the Anaconda Python 2.7.13 version.

For cx_Freeze 4.3.4, I had to create a hook for the pyphen module to include the "dictionaries" directory and I had to modify the pyphen module to look for the dictionaries directory next to the exe with the following patch right after the lines 48-49 in pyphen's __init__.py  

```
#!python
except ImportError:
    dictionaries_root = os.path.join(os.path.dirname(__file__), 'dictionaries')

if getattr(sys, 'frozen', False):
    # this is a frozen exe
    path = os.path.realpath(sys.executable)
    if not os.path.isdir(path):
        path = os.path.dirname(path)
    dictionaries_root = os.path.join(path, 'dictionaries')
```

On cx_Freeze 5.0, I don't think this is needed (but I have not verified).

Running the resulting frozen executable, I get the following error:

```
#!bash
./convertHTMLtoPDF
Traceback (most recent call last):
  File "/home/user/anaconda2/lib/python2.7/site-packages/cx_Freeze/initscripts/__startup__.py", line 12, in <module>
    __import__(name + "__init__")
  File "/home/user/anaconda2/lib/python2.7/site-packages/cx_Freeze/initscripts/Console.py", line 21, in <module>
    scriptModule = __import__(moduleName)
  File "./HTML_to_PDF.py", line 11, in <module>
  File "/home/user/anaconda2/lib/python2.7/site-packages/weasyprint/__init__.py", line 338, in <module>
    from .css import PARSER, preprocess_stylesheet  # noqa
  File "/home/user/anaconda2/lib/python2.7/site-packages/weasyprint/css/__init__.py", line 30, in <module>
    from . import computed_values
  File "/home/user/anaconda2/lib/python2.7/site-packages/weasyprint/css/computed_values.py", line 18, in <module>
    from .. import text
  File "/home/user/anaconda2/lib/python2.7/site-packages/weasyprint/text.py", line 201, in <module>
    ''')
  File "/home/user/anaconda2/lib/python2.7/site-packages/cffi/api.py", line 105, in cdef
    self._cdef(csource, override=override, packed=packed)
  File "/home/user/anaconda2/lib/python2.7/site-packages/cffi/api.py", line 119, in _cdef
    self._parser.parse(csource, override=override, **options)
  File "/home/user/anaconda2/lib/python2.7/site-packages/cffi/cparser.py", line 299, in parse
    self._internal_parse(csource)
  File "/home/user/anaconda2/lib/python2.7/site-packages/cffi/cparser.py", line 304, in _internal_parse
    ast, macros, csource = self._parse(csource)
  File "/home/user/anaconda2/lib/python2.7/site-packages/cffi/cparser.py", line 260, in _parse
    ast = _get_parser().parse(csource)
  File "/home/user/anaconda2/lib/python2.7/site-packages/cffi/cparser.py", line 40, in _get_parser
    _parser_cache = pycparser.CParser()
  File "/home/user/anaconda2/lib/python2.7/site-packages/pycparser/c_parser.py", line 116, in __init__
    outputdir=taboutputdir)
  File "/home/user/anaconda2/lib/python2.7/site-packages/pycparser/ply/yacc.py", line 3293, in yacc
    if pinfo.validate_all():
  File "/home/user/anaconda2/lib/python2.7/site-packages/pycparser/ply/yacc.py", line 2938, in validate_all
    self.validate_modules()
  File "/home/user/anaconda2/lib/python2.7/site-packages/pycparser/ply/yacc.py", line 2982, in validate_modules
    lines, linen = inspect.getsourcelines(module)
  File "/home/user/anaconda2/lib/python2.7/inspect.py", line 689, in getsourcelines
    lines, lnum = findsource(object)
  File "/home/user/anaconda2/lib/python2.7/inspect.py", line 528, in findsource
    raise IOError('source code not available %s' %(file, ))
IOError: source code not available ./lib/python2.7/pycparser/plyparser.pyc
```

A this point, I am stumped.  I am not certain how to get past this at the moment. In cx_Freeze 5.0, the file referenced does exist, but it is obviously not a .py source file, but it is looking for the .pyc file for some reason.

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/222

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Closing due to inactivity. 
If you had issues please re-open.
