### ISSUE TITLE
OpenCV error: AttributeError: 'ModuleFinder' object has no attribute 'cache_path'

### ISSUE THREAD

**Issue by bw7715** [marcelotduarte/cx_Freeze#2234]
**Describe the bug**
An error occurs when try to freeze a project with OpenCV:
```python
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\projects\p39_cv2\_build\venv\Scripts\cxfreeze.exe\__main__.py", line 7, in <module>
  File "C:\projects\p39_cv2\_build\venv\lib\site-packages\cx_Freeze\cli.py", line 350, in main
    freezer: Freezer = Freezer(
  File "C:\projects\p39_cv2\_build\venv\lib\site-packages\cx_Freeze\freezer.py", line 735, in __init__
    Freezer.__init__(self, *args, **kwargs)
  File "C:\projects\p39_cv2\_build\venv\lib\site-packages\cx_Freeze\freezer.py", line 122, in __init__
    self.finder: ModuleFinder = self._get_module_finder()
  File "C:\projects\p39_cv2\_build\venv\lib\site-packages\cx_Freeze\freezer.py", line 373, in _get_module_finder
    finder.include_package(name)
  File "C:\projects\p39_cv2\_build\venv\lib\site-packages\cx_Freeze\finder.py", line 760, in include_package
    module = self._import_module(name, deferred_imports)
  File "C:\projects\p39_cv2\_build\venv\lib\site-packages\cx_Freeze\finder.py", line 260, in _import_module
    module = self._internal_import_module(name, deferred_imports)
  File "C:\projects\p39_cv2\_build\venv\lib\site-packages\cx_Freeze\finder.py", line 348, in _internal_import_module
    module = self._load_module(
  File "C:\projects\p39_cv2\_build\venv\lib\site-packages\cx_Freeze\finder.py", line 415, in _load_module
    self._load_module_code(module, loader, deferred_imports)
  File "C:\projects\p39_cv2\_build\venv\lib\site-packages\cx_Freeze\finder.py", line 454, in _load_module_code
    self._run_hook("load", module.name, module)
  File "C:\projects\p39_cv2\_build\venv\lib\site-packages\cx_Freeze\finder.py", line 581, in _run_hook
    method(self, *args)
  File "C:\projects\p39_cv2\_build\venv\lib\site-packages\cx_Freeze\hooks\cv2.py", line 65, in load_cv2
    source = finder.cache_path / "cv2-config.py"
AttributeError: 'ModuleFinder' object has no attribute 'cache_path'
The system cannot find the path specified.
```

**To Reproduce**
Project file:
```python
# (project.py)
import cv2
print(cv2.__version__)
```

requirements.txt
```
cx-Freeze==6.15.13
opencv-python-headless==4.9.0.80
```

Freeze bat scripts:
```bash
echo off
set WORKSPACE=%~dp0

set BUILD_DIRPATH=%WORKSPACE%\_build
set BASE_PYTHON_DIRPATH=C:\Program Files\Python39

set VENV_DIRPATH=%BUILD_DIRPATH%\venv
set TARGET_DIR=%BUILD_DIRPATH%\out

set SCRIPTS_DIRPATH=%VENV_DIRPATH%\Scripts
set PYTHON_EXE_PATH="%SCRIPTS_DIRPATH%\python.exe"
set FREEZER_EXE_PATH="%SCRIPTS_DIRPATH%\cxfreeze.exe"

set TARGET_NAME=project_out.exe
set PROJECT_SOURCE_PY_PATH=project.py

set PACKAGES=cv2


"%BASE_PYTHON_DIRPATH%\python" -m venv "%VENV_DIRPATH%"
%PYTHON_EXE_PATH% -m pip install -r requirements.txt

rem %PYTHON_EXE_PATH% -m pip install --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze --upgrade

%FREEZER_EXE_PATH% -O -OO --include-msvcr --target-dir="%TARGET_DIR%" --target-name=%TARGET_NAME% --packages=%PACKAGES% %PROJECT_SOURCE_PY_PATH%

"%TARGET_DIR%\%TARGET_NAME%"
```

**Desktop (please complete the following information):**
 - Platform information: Windows 10 
 - OS architecture: 64bit
 - cx_Freeze version: 6.15.13
 - Python version: 3.9

**Additional context**
With cx_Freeze 6.15.12 this project works.

**Comment by marcelotduarte** [comment]
Thanks for reporting!
19841725e57eb957f867601ce125d224aba014f7

**Comment by marcelotduarte** [comment]
[Release 6.15.14](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.15.14) is out!

**Comment by bw7715** [comment]
Thank you, now works.

**Comment by Iyyappan-vw** [comment]
this issue not solved using above process

**Comment by marcelotduarte** [comment]
@Iyyappan-vw It solves for cx-Freeze>=6.15.14 and opencv-python-headless==4.9.0.80
For another version of opencv, please open a detailed issue.

**Comment by Iyyappan-vw** [comment]
Thank for quick replay I using cx-Freeze>=6.15.14 library version. It now working for me
