### ISSUE TITLE
cx_Freeze 5.0.1 do not find some modules that cx_Freeze 5.0 did

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#228]
Originally reported by: **Harald Hanöfner (Bitbucket: [HarryH](https://bitbucket.org/HarryH), GitHub: [HarryH](https://github.com/HarryH))**

----------------------------------------

Here is the error message at running the freezed program with ```cx_Freeze 5.0.1```

```
#!python

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\requests\packages\__init__.py", line 39, in <module>
    from . import idna
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\requests\packages\idna\__init__.py", line 1, in <module>
    from .core import *
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\requests\packages\idna\core.py", line 1, in <module>
    from . import idnadata
ImportError: cannot import name 'idnadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
    __import__(name + "__init__")
  File "C:\Users\Harry\Python\lib\hhCxFreezeBootInit.py", line 96, in <module>
    exec(code, m.__dict__)
  File "flickrsync.py", line 53, in <module>
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\flickrapi\__init__.py", line 52, in <module>
    from flickrapi.core import FlickrAPI
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\flickrapi\core.py", line 13, in <module>
    from . import tokencache, auth
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\flickrapi\tokencache.py", line 10, in <module>
    from flickrapi.auth import FlickrAccessToken
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\flickrapi\auth.py", line 23, in <module>
    from requests_toolbelt import MultipartEncoder
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\requests_toolbelt\__init__.py", line 12, in <module>
    from .adapters import SSLAdapter, SourceAddressAdapter
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\requests_toolbelt\adapters\__init__.py", line 12, in <module>
    from .ssl import SSLAdapter
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\requests_toolbelt\adapters\ssl.py", line 12, in <module>
    import requests
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\requests\__init__.py", line 63, in <module>
    from . import utils
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\requests\utils.py", line 24, in <module>
    from ._internal_utils import to_native_string
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\requests\_internal_utils.py", line 11, in <module>
    from .compat import is_py2, builtin_str, str
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\requests\compat.py", line 11, in <module>
    from .packages import chardet
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\requests\packages\__init__.py", line 41, in <module>
    import idna
ImportError: No module named 'idna'
```

With the previous version ```cx_Freeze 5.0``` I had no problems with the ```requests``` package. I work with Python 3.5.2 (32bit) on Windows 10.

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/228

**Comment by anthony-tuininga** [comment]
*Original comment by* **Jake Omann (Bitbucket: [jhomann](https://bitbucket.org/jhomann), GitHub: Unknown)**:

----------------------------------------

I can also confirm that `idna` does not get automatically included in Windows and Linux (Python 3.5.2 also)

As a side note can just do `packages = ['idna']` and pass that into the build options and it works fine but cx_Freeze does not automatically include it (4.3.4 and 5.0.0 did)

**Comment by sebastian3495** [comment]
@anthony-tuininga  -->  https://gyazo.com/f05b6195cd781acdb2ce3c4658b50a6c
I didn't solve the problem. 

My code (setup.py):


```
`from cx_Freeze import setup, Executable
from multiprocessing import Queue
import os, sys
os.environ['TCL_LIBRARY'] = "C:\\Program Files\\Python35\\tcl\\tcl8.6"
os.environ['TK_LIBRARY'] = "C:\\Program Files\\Python35\\tcl\\tk8.6"


if sys.platform == 'win32':
	base = 'Win32GUI'

executables = [Executable('TwitterBot.py', base=base)]
	
setup(
	name='TwitterBot',
	options = {"build_exe": {"packages":["idna","tkinter", "tweepy", "requests"]}},
	version='0.1',
	description='Parse stuff',
	executables = executables)
	`
if sys.platform == 'win32':
	base = 'Win32GUI'

executables = [Executable('TwitterBot.py', base=base)]
	
setup(
	name='TwitterBot',
	options = {"build_exe": {"packages":["idna","tkinter", "tweepy", "requests"]}},
	version='0.1',
	description='Parse stuff',
	executables = executables)
	`
```



errormsg:

`running build
running build_exe
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    executables = executables)
  File "C:\Users\sebastian\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cx_Freeze\dist.py", line 349, in setup
    distutils.core.setup(**attrs)
  File "C:\Users\sebastian\AppData\Local\Programs\Python\Python35-32\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\sebastian\AppData\Local\Programs\Python\Python35-32\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\sebastian\AppData\Local\Programs\Python\Python35-32\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\sebastian\AppData\Local\Programs\Python\Python35-32\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\Users\sebastian\AppData\Local\Programs\Python\Python35-32\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\sebastian\AppData\Local\Programs\Python\Python35-32\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\sebastian\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cx_Freeze\dist.py", line 219, in run
    freezer.Freeze()
  File "C:\Users\sebastian\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cx_Freeze\freezer.py", line 621, in Freeze
    self.finder = self._GetModuleFinder()
  File "C:\Users\sebastian\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cx_Freeze\freezer.py", line 340, in _GetModuleFinder
    finder.IncludePackage(name)
  File "C:\Users\sebastian\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cx_Freeze\finder.py", line 653, in IncludePackage
    module = self._ImportModule(name, deferredImports)
  File "C:\Users\sebastian\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cx_Freeze\finder.py", line 350, in _ImportModule
    raise ImportError("No module named %r" % name)
ImportError: No module named 'idna'`

**Comment by anthony-tuininga** [comment]
Can you provide the script that goes along with setup.py that demonstrates the problem?

**Comment by imerkle** [comment]
@`build_exe_options = {"packages": ["os", "requests"],...` fixed for me.
Looks like you have to mention all external packages youre importing.

**Comment by asanka-herath** [comment]
How did you solved it?

**Comment by bobatsar** [comment]
For 5.0.2 I also had to include "idna" to the packages as Jake Omann already wrote.

**Comment by Okhan97** [comment]
@anthony-tuininga  "As a side note can just do packages = ['idna'] and pass that into the build options and it works fine but cx_Freeze does not automatically include it (4.3.4 and 5.0.0 did)"

Can you please explain how to do this step please ? (english is not my main lenguaje ,so if you could upload images of the process I would appreciate it !)

**Comment by kalifan** [comment]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\__startup__.py", lin
e 14, in run
    module.run()
  File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26
, in run
    exec(code, m.__dict__)
  File "shell.py", line 1, in <module>
  File "<string>", line 1, in <module>
ImportError: No module named socket

someone can help me please.

**Comment by ajochope** [comment]
Importing "idna" works for me, as 'bobatsar' said, cx_Freeze==5.1 
thank you all

build_exe_options = {"packages": ["os", "idna"], "excludes": ["tkinter"], "include_files":


My setup.py file:

from cx_Freeze import setup, Executable
from multiprocessing import Queue
import os, sys

base = None
if sys.platform == "win32":
    base = "Win32GUI"
build_exe_options = {"packages": ["os", "idna"], "excludes": ["tkinter"], "include_files":["cmmedia.ico","email_tv.html","email_adms.py"]}
setup( name = "Monitorado stream radio script python",
       version = "0.1",
       description = "Monitorado stream radio script python",
       options = {"build_exe": build_exe_options},
       executables = [Executable("stream_mon.py", base=base, icon='cmmedia.ico')])

**Comment by mcl12345** [comment]
I have resolved the problem thanks to that : 

    from cx_Freeze import setup, Executable
    import sys


    #main
    exe = Executable(script="test.py", base="Win32GUI")
    buildOptions = dict(excludes = ["tkinter"], includes =["idna.idnadata"], optimize=1)
    setup(name = "instagram",version = "1.0", description = "test", executables = [exe], options =dict(build_exe = buildOptions))

**Comment by gouzenes** [comment]
I am using vmware, and the setup xx build command does not work.
-- example
-source code : 'mon_programme.py'
#coding utf-8
# langage = python 2
import sys
#import monprogramme.location_1
print (' version of python = ', sys.version_info)
def foo (x) : return [x]
if __name__ == '__main__':
    print ('foo = ', foo('C:\\unix_ssd\\test\\test_unix_python2'))
-- and the setup :
###!/usr/bin/env python
#coding utf-8
# langage = python 2
import sys
import os
import os.path
from cx_Freeze import setup, Executable
print '------------------'
print os.path.abspath('startup/startup.py')
print '------------------'
base = None
if sys.platform == "win32":
    base = "Win32GUI" # base = Win32GUI ou console ?
setup(
    name='test KM2',
    version='1.9.1',
	author = "Laurent Gouzenes",
    packages= [], #['monprogramme', 'monprogramme.test'],
	scripts = ['mon_programme.py'],
    license='Creative Commons Attribution-Noncommercial-Share Alike license',
	#options = {"build_exe": build_exe_options},
    long_description=open('README.txt').read(),
    executables = [Executable ("mon_programme.py", 
								#initScript = os.path.abspath("startup/startup.py"), 
								base = base)]  # base = Win32GUI)
2) Then the command
python setup.py build
runs properly (no error message)

3) when I execute, I get an unknown module:
I get the error message:
" ImportError: No module named __startup__"

what is wrong ?

Many thanks in advance !

**Comment by Manav1918** [comment]
I'm trying to make executable with cx_freeze.i used pymysql in my Code, so I imported this in both "packages" And "includes" . 
It's showing error while packaging

"ImportError, No module called Socket


I imported Socket too in packages and includes.

**Comment by marcelotduarte** [comment]
@Manav1918 Please use the latest version, 6.5.3 and if you have issues open a new issue
