### ISSUE TITLE
replace_paths is not working correctly

### ISSUE THREAD

**Issue by kutu** [marcelotduarte/cx_Freeze#247]
```py
buildOptions = dict(
    replace_paths = '*=',
)

executables = [
    Executable('app.py'),
]

setup(name='app',
      version = '1.0.0',
      description = 'app',
      options = dict(build_exe = buildOptions),
      executables = executables)
```
replaces paths with `=` instead of nothing
```py
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "=__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "=Console.py", line 24, in <module>
  File "=app.py", line 435, in <module>
  File "=tornado\ioloop.py", line 862, in start
  File "=tornado\platform\select.py", line 63, in poll
```

**Comment by nickvandewiele** [comment]
the following format worked for me:

`'replace_paths': [("*", "")],`

I agree, the documentation on this option could be formulated less ambiguously.
http://cx-freeze.readthedocs.io/en/latest/distutils.html#build-exe

The relevant lines in the code can be found here:
https://github.com/anthony-tuininga/cx_Freeze/blob/master/cx_Freeze/finder.py#L481
