### ISSUE TITLE
cx_freeze 5.0.1 and python 3.6.1 - bug at freezing

### ISSUE THREAD

**Issue by FreeHarry** [marcelotduarte/cx_Freeze#254]
I got a bug at the freezing my app. It appears if the code is trying to get a value from the list `arguments`, but the list is still empty.

Replace the line 561 in finder.py ...
`fromList, = arguments`

with ...
`fromList = arguments[0] if arguments else []`

does fix the bug for me.

```
running build_exe
Traceback (most recent call last):
  File "setup_cx.py", line 85, in <module>
    executables = [executable_1],
  File "C:\Users\hh16534\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\dist.py", line 349, in setup
    distutils.core.setup(**attrs)
  File "C:\Users\hh16534\AppData\Local\Programs\Python\Python36-32\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\hh16534\AppData\Local\Programs\Python\Python36-32\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\hh16534\AppData\Local\Programs\Python\Python36-32\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\hh16534\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\dist.py", line 219, in run
    freezer.Freeze()
  File "C:\Users\hh16534\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\freezer.py", line 623, in Freeze
    self._FreezeExecutable(executable)
  File "C:\Users\hh16534\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\freezer.py", line 199, in _FreezeExecutable
    finder.IncludeFile(exe.script, exe.moduleName)
  File "C:\Users\hh16534\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 633, in IncludeFile
    deferredImports)
  File "C:\Users\hh16534\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 474, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "C:\Users\hh16534\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 564, in _ScanCode
    module, relativeImportIndex)
  File "C:\Users\hh16534\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 310, in _ImportModule
    deferredImports, namespace = namespace)
  File "C:\Users\hh16534\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 403, in _InternalImportModule
    parentModule, namespace)
  File "C:\Users\hh16534\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 474, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "C:\Users\hh16534\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 564, in _ScanCode
    module, relativeImportIndex)
  File "C:\Users\hh16534\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 310, in _ImportModule
    deferredImports, namespace = namespace)
  File "C:\Users\hh16534\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 403, in _InternalImportModule
    parentModule, namespace)
  File "C:\Users\hh16534\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 416, in _LoadModule
    namespace)
  File "C:\Users\hh16534\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 485, in _LoadPackage
    self._LoadModule(name, fp, path, info, deferredImports, parent)
  File "C:\Users\hh16534\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 474, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "C:\Users\hh16534\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 564, in _ScanCode
    module, relativeImportIndex)
  File "C:\Users\hh16534\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 345, in _ImportModule
    deferredImports, namespace = namespace)
  File "C:\Users\hh16534\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 403, in _InternalImportModule
    parentModule, namespace)
  File "C:\Users\hh16534\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 474, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "C:\Users\hh16534\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 561, in _ScanCode
    fromList, = arguments
ValueError: not enough values to unpack (expected 1, got 0)
```

**Comment by jekoie** [comment]
Yes, I meet the same one

**Comment by jekoie** [comment]
I had try, and it's ok, good.

**Comment by anthony-tuininga** [comment]
I understand how the patch corrects this issue but I am wondering if we are just papering over a bigger issue. Can you provide an example that demonstrates this problem?

**Comment by FreeHarry** [comment]
What du you mean with 'a bigger issue'?

**Comment by anthony-tuininga** [comment]
What I mean is that there might be a bigger problem that should be fixed instead -- that the solution you are providing only addresses the symptoms, not the cause of the problem! Do you have an example that demonstrates the issue?

**Comment by FreeHarry** [comment]
Please see #261 for the desired example.

**Comment by anthony-tuininga** [comment]
Merge request has been merged. Thanks.
