### ISSUE TITLE
ModuleNotFoundError: No module named 'msilib'

### ISSUE THREAD

**Issue by glibg10b** [marcelotduarte/cx_Freeze#2659]
**Prerequisite**
 - Make sure no duplicated issue has already been reported. You should look for closed issues, too.
 - Make sure you are not asking us to help to solve your specific issue. GitHub issues are opened mainly for development purposes. If you want to ask someone to help to solve your problem, go to some community site like StackOverflow, etc.
 - Make sure your problem is not derived from packaging (e.g. Homebrew).

**Describe the bug**
Running `cxfreeze main.py` with Python 3.13 produces the following error because `msilib` has long been deprecated and has now been removed.

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Waldo\AppData\Local\Programs\Python\Python313\Scripts\cxfreeze.exe\__main__.py", line 4, in <module>
    from cx_Freeze.cli import main
  File "C:\Users\Waldo\AppData\Local\Programs\Python\Python313\Lib\site-packages\cx_Freeze\__init__.py", line 32, in <module>
    from cx_Freeze.command.bdist_msi import bdist_msi
  File "C:\Users\Waldo\AppData\Local\Programs\Python\Python313\Lib\site-packages\cx_Freeze\command\bdist_msi.py", line 31, in <module>
    from msilib import (  # pylint: disable=deprecated-module
    ...<15 lines>...
    )
ModuleNotFoundError: No module named 'msilib'
```

**To Reproduce**
1. Install [Python 3.13](https://www.python.org/downloads/)
2. Run `cxfreeze main.py` where cx_freeze is installed and main.py is some Python file

**Expected behavior**
cxfreeze shouldn't depend on a deprecated module.

**Screenshots**

**Desktop (please complete the following information):**
 - Platform information (e.g. Ubuntu Linux 22.04): Windows 11
 - OS architecture (e.g. amd64): amd64
 - cx_Freeze version [e.g. 6.11]: 7.2.4
 - Python version [e.g. 3.10]: 3.13

**Additional context**

**Comment by marcelotduarte** [comment]
Support for Python 3.13 in the next minor release (7.3.0).

**Comment by marcelotduarte** [comment]
You can test the PR with:
`pip install --extra-index-url https://test.pypi.org/simple/ cx-Freeze==7.3.0.2630.dev1732997903`

**Comment by marcelotduarte** [comment]
[Release 8.0](https://github.com/marcelotduarte/cx_Freeze/releases/tag/8.0.0) is out!
[Documentation](https://cx-freeze.readthedocs.io)

See also #2837
