### ISSUE TITLE
PyZMQ: ImportError: libsodium-4762836c.so.26.1.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by bw7715** [marcelotduarte/cx_Freeze#2679]
An error occurs when try to freeze a project with pyzmq module.

**Describe the bug**
```
Traceback (most recent call last):
  File "/home/user1/projects/zmq_issue/_build/venv/lib/python3.9/site-packages/cx_Freeze/initscripts/__startup__.py", line 140, in run
    module_init.run(f"__main__{name}")
  File "/home/user1/projects/zmq_issue/_build/venv/lib/python3.9/site-packages/cx_Freeze/initscripts/console.py", line 25, in run
    exec(code, main_globals)
  File "/home/user1/projects/zmq_issue/project.py", line 1, in <module>
    import zmq
  File "/home/user1/projects/zmq_issue/_build/venv/lib/python3.9/site-packages/zmq/__init__.py", line 52, in <module>
    from zmq import backend
  File "/home/user1/projects/zmq_issue/_build/venv/lib/python3.9/site-packages/zmq/backend/__init__.py", line 30, in <module>
    raise original_error from None
  File "/home/user1/projects/zmq_issue/_build/venv/lib/python3.9/site-packages/zmq/backend/__init__.py", line 25, in <module>
    _ns = select_backend(first)
  File "/home/user1/projects/zmq_issue/_build/venv/lib/python3.9/site-packages/zmq/backend/select.py", line 31, in select_backend
    mod = import_module(name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/user1/projects/zmq_issue/_build/venv/lib/python3.9/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import _zmq
ImportError: libsodium-4762836c.so.26.1.0: cannot open shared object file: No such file or directory
```

**To Reproduce**
project.py
```python
import zmq
print(zmq.__version__)
```

freeze.sh
```bash
#!/bin/bash

WORKSPACE="$(dirname "$(realpath "$0")")"

BUILD_DIRPATH="${WORKSPACE}/_build"
BASE_PYTHON_DIRPATH="/usr/bin/python3.9"
VENV_DIRPATH="${BUILD_DIRPATH}/venv"
TARGET_DIR="${BUILD_DIRPATH}/out"
SCRIPTS_DIRPATH="${VENV_DIRPATH}/bin"
PYTHON_EXE_PATH="${SCRIPTS_DIRPATH}/python"
FREEZER_EXE_PATH="${SCRIPTS_DIRPATH}/cxfreeze"
TARGET_NAME="project_out"
PROJECT_SOURCE_PY_PATH="${WORKSPACE}/project.py"

PACKAGES="zmq"

export PATH="${SCRIPTS_DIRPATH}/:$PATH"

"${BASE_PYTHON_DIRPATH}" -m venv "${VENV_DIRPATH}"
"${PYTHON_EXE_PATH}" -m pip install -r requirements.txt
if [ $? -ne 0 ]; then
    read -p "An error occurred. Press any key to continue..."
    exit 1
fi

"${FREEZER_EXE_PATH}" build -O1 -O2 --include-msvcr --build-exe="${TARGET_DIR}" --target-name="${TARGET_NAME}" --packages="${PACKAGES}" --script="${PROJECT_SOURCE_PY_PATH}"
if [ $? -ne 0 ]; then
    read -p "An error occurred. Press any key to continue..."
    exit 1
fi

"${TARGET_DIR}/${TARGET_NAME}"
if [ $? -ne 0 ]; then
    read -p "An error occurred. Press any key to continue..."
    exit 1
fi
```

requirements.txt
```
cx_Freeze==7.2.4
cx_Logging==3.2.1
pyzmq==26.2.0
```

**Desktop (please complete the following information):**
 - Platform information: Ubuntu Linux 22.04
 - OS architecture (e.g. amd64): 64bit
 - cx_Freeze version: 7.2.4
 - Python version: 3.9

**Comment by bw7715** [comment]
On Windows 10 the same project works.

**Comment by bw7715** [comment]
I tried to add `libsodium` to `requirements.txt` and cx-Freezer `packages`, but it didn't help

**Comment by bw7715** [comment]
I tried also cx-Freeze 7.2.5, but problem still exists.

**Comment by marcelotduarte** [comment]
It's working on v7.3.0-dev. You can get the wheel [here](https://github.com/marcelotduarte/cx_Freeze/actions/runs/11786951275/artifacts/2173478048).
Unfortunately, I forgot to backport it to v7.2.4. It is working for py3.10+
In 7.2.3 is it working for py3.9.

**Comment by bw7715** [comment]
Thank you, pyZMQ with 7.3.0-dev works for me.
But I found another problem: [https://github.com/marcelotduarte/cx_Freeze/issues/2682](https://github.com/marcelotduarte/cx_Freeze/issues/2682)

**Comment by marcelotduarte** [comment]
[Release 7.2.6](https://github.com/marcelotduarte/cx_Freeze/releases/tag/7.2.6) is out!
[Documentation](https://cx-freeze.readthedocs.io)
