### ISSUE TITLE
Torchmetrics: RuntimeError: Error in dlopen for library libnvrtc.so.11.2and libnvrtc-XXXXXXXX.so.11.2

### ISSUE THREAD

**Issue by bw7715** [marcelotduarte/cx_Freeze#2682]
An error occurs when try to use torchmetrics in frozen project.

**Describe the bug**
```bash
Traceback (most recent call last):
  File "/home/user1/project/_build/venv/lib/python3.9/site-packages/cx_Freeze/initscripts/__startup__.py", line 140, in run
    module_init.run(f"__main__{name}")
  File "/home/user1/project/_build/venv/lib/python3.9/site-packages/cx_Freeze/initscripts/console.py", line 25, in run
    exec(code, main_globals)
  File "/home/user1/project/project.py", line 7, in <module>
    ssim_score = TMF.image.multiscale_structural_similarity_index_measure(image1, image2)
  File "/home/user1/project/_build/venv/lib/python3.9/site-packages/torchmetrics/functional/image/ssim.py", line 525, in multiscale_structural_similarity_index_measure
    mcs_per_image = _multiscale_ssim_update(
  File "/home/user1/project/_build/venv/lib/python3.9/site-packages/torchmetrics/functional/image/ssim.py", line 424, in _multiscale_ssim_update
    return torch.prod(mcs_weighted, axis=0)  # type: ignore[call-overload]
RuntimeError: Error in dlopen for library libnvrtc.so.11.2and libnvrtc-XXXXXXXX.so.11.2
```

**To Reproduce**
project.py
```python
import torch
import torchmetrics.functional as TMF

image1 = torch.rand((1, 3, 256, 256), device='cuda')
image2 = torch.rand((1, 3, 256, 256), device='cuda')

ssim_score = TMF.image.multiscale_structural_similarity_index_measure(image1, image2)
print(f'SSIM Score: {ssim_score}')
```

requirements.txt
```
--find-links https://download.pytorch.org/whl/cu118/torch
--find-links https://download.pytorch.org/whl/cu118/torchvision

cx_Freeze==7.2.5
cx_Logging==3.2.1
torch==2.5.0+cu118
torchmetrics==1.5.2
torchvision==0.20.0+cu118
```

freeze.sh
```bash
#!/bin/bash

WORKSPACE="$(dirname "$(realpath "$0")")"

BUILD_DIRPATH="${WORKSPACE}/_build"
BASE_PYTHON_DIRPATH="/usr/bin/python3.9"
VENV_DIRPATH="${BUILD_DIRPATH}/venv"
TARGET_DIR="${BUILD_DIRPATH}/out"
SCRIPTS_DIRPATH="${VENV_DIRPATH}/bin"
PYTHON_EXE_PATH="${SCRIPTS_DIRPATH}/python"
FREEZER_EXE_PATH="${SCRIPTS_DIRPATH}/cxfreeze"
TARGET_NAME="project_out"
PROJECT_SOURCE_PY_PATH="${WORKSPACE}/project.py"

PACKAGES="torch,torchvision,torchmetrics"

export PATH="${SCRIPTS_DIRPATH}/:$PATH" 
"${BASE_PYTHON_DIRPATH}" -m venv "${VENV_DIRPATH}"
"${PYTHON_EXE_PATH}" -m pip install -r requirements.txt
if [ $? -ne 0 ]; then
    read -p "An error occurred. Press any key to continue..."
    exit 1
fi

"${FREEZER_EXE_PATH}" build -O1 -O2 --include-msvcr --build-exe="${TARGET_DIR}" --target-name="${TARGET_NAME}" --packages="${PACKAGES}" --script="${PROJECT_SOURCE_PY_PATH}"
if [ $? -ne 0 ]; then
    read -p "An error occurred. Press any key to continue..."
    exit 1
fi

"${TARGET_DIR}/${TARGET_NAME}"
if [ $? -ne 0 ]; then
    read -p "An error occurred. Press any key to continue..."
    exit 1
fi
```

**Desktop (please complete the following information):**
 - Platform information: Ubuntu Linux 22.04
 - OS architecture: 64bit
 - cx_Freeze version: 7.2.3, 7.2.5, 7.3.0-dev
 - Python version: 3.9

**Comment by bw7715** [comment]
The cx-Freeze v7.3.0-dev is from here: [link](https://github.com/marcelotduarte/cx_Freeze/actions/runs/11786951275/artifacts/2173478048)

**Comment by marcelotduarte** [comment]
I have no way to test it, since I don't have a compatible card.
`RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx`

If this issue is related to https://stackoverflow.com/questions/79114702/could-not-load-library-libnvrtc-so-12-error-libnvrtc-so-12-cannot-open-shared then the mentioned libraries are not part of torch, so I have no way to change this in cx_Freeze. However, you can indicate the location of these libraries for copying and if it does not work because they are dynamically loaded, you will probably have to copy them to some torch folder.
Check the use of [--bin-includes](https://cx-freeze.readthedocs.io/en/stable/setup_script.html#cmdoption-arg-bin_includes) or [--include-files](https://cx-freeze.readthedocs.io/en/stable/setup_script.html#cmdoption-arg-include_files) to get or copy the libraries.

**Comment by bw7715** [comment]
I tried with `--bin-includes` and `--include-files` but this doesn't work for me. 

I tried also with cx_Freeze 7.2.7 but problem still exists, and there is a new similar problem with the OpenCV module: https://github.com/marcelotduarte/cx_Freeze/issues/2729

**Comment by bw7715** [comment]
I found a fix for this issue, just add at the top of the `project.py` script this code:

```python
import ctypes
from pathlib import Path

venv_lib_path = Path(__file__).resolve().parent.parent
for lib_path in venv_lib_path.rglob("libnvrtc.so.11*"):
    ctypes.CDLL(lib_path)
```


The final `project.py` will look like this:
```python
####################### FIX START ######################
# Fix for 'RuntimeError: Error in dlopen for library libnvrtc.so.11.2and libnvrtc-XXXXXXXX.so.11.2'
import ctypes
from pathlib import Path

venv_lib_path = Path(__file__).resolve().parent.parent
for lib_path in venv_lib_path.rglob("libnvrtc.so.11*"):
    ctypes.CDLL(lib_path)
######################## FIX END #######################

import torch
import torchmetrics.functional as TMF

image1 = torch.rand((1, 3, 256, 256), device='cuda')
image2 = torch.rand((1, 3, 256, 256), device='cuda')

ssim_score = TMF.image.multiscale_structural_similarity_index_measure(image1, image2)
print(f'SSIM Score: {ssim_score}')
```

And then it works after freezing.

**Comment by marcelotduarte** [comment]
So are these files being distributed with another package? Print this path for me, i.e.:
 `print(libpath)`

Maybe it's better to print relative:
`print(libpath.relative_to(venv_lib_path))`

**Comment by bw7715** [comment]
> So are these files being distributed with another package? Print this path for me, i.e.: `print(libpath)`
> 
> Maybe it's better to print relative: `print(libpath.relative_to(venv_lib_path))`

```
nvidia/cuda_nvrtc/lib/libnvrtc.so.11.2
```

**Comment by marcelotduarte** [comment]
Based on your findings and reading the code of torch init, I hope this PR fix the issue in a generic way.
You can test the PR with:
`pip install --extra-index-url https://test.pypi.org/simple/ cx-Freeze==7.3.0.2750.dev1735014735`

**Comment by marcelotduarte** [comment]
[Release 7.2.8](https://github.com/marcelotduarte/cx_Freeze/releases/tag/7.2.8) is out!
[Documentation](https://cx-freeze.readthedocs.io)

Please give me feedback.

**Comment by bw7715** [comment]
With 7.2.8 version I get an error:
```python
Traceback (most recent call last):
  File "/home/user1/project/_build/venv/lib/python3.9/site-packages/cx_Freeze/initscripts/__startup__.py", line 140, in run
    module_init.run(f"__main__{name}")
  File "/home/user1/project/_build/venv/lib/python3.9/site-packages/cx_Freeze/initscripts/console.py", line 25, in run
    exec(code, main_globals)
  File "/home/user1/project/project.py", line 12, in <module>
    import torch
  File "/home/user1/project/_build/venv/lib/python3.9/site-packages/torch/__init__.py", line 367, in <module>
    _load_global_deps()
  File "/home/user1/project/_build/venv/lib/python3.9/site-packages/nvidia/__init__.py", line 10, in <module>
  File "/home/user1/project/_build/venv/lib/python3.9/site-packages/nvidia/__init__.py", line 9, in _cxfreeze_patch
  File "/usr/local/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/user1/project/_build/out/lib/nvidia/cusolver/lib/__init__.pyc: invalid ELF header
```

**Comment by marcelotduarte** [comment]
I'll check again later, but I would be grateful if you could test it for me tomorrow.

**Comment by bw7715** [comment]
Ok, I tried with 7.3.0.dev1736216847 but problem still exists.

**Comment by marcelotduarte** [comment]
@bw7715 Please test the fix with:
`pip install --extra-index-url https://test.pypi.org/simple/ cx-Freeze==7.3.0.2782.dev1738051574`

**Comment by bw7715** [comment]
> [@bw7715](https://github.com/bw7715) Please test the fix with: `pip install --extra-index-url https://test.pypi.org/simple/ cx-Freeze==7.3.0.2782.dev1738051574`

Thank you, the fix works for me.

**Comment by marcelotduarte** [comment]
[Release 7.2.9](https://github.com/marcelotduarte/cx_Freeze/releases/tag/7.2.9) is out!
[Documentation](https://cx-freeze.readthedocs.io)
