### ISSUE TITLE
Build failed in v7.2.6

### ISSUE THREAD

**Issue by markox92** [marcelotduarte/cx_Freeze#2701]
What has changed from version 7.2.4 ? seems it's the latest version which works for me is 7.2.4. 7.2.5 and 7.2.6 both have the same problem.
Run the command `python build.py bdist_msi` in 7.2.4 it worked fine and the build completed, but in the new versions, the output is.

```
running bdist_msi
running build
running build_exe
C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cerberus\errors.py:157: SyntaxWarning: invalid escape sequence '\*'
  """
C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cerberus\errors.py:185: SyntaxWarning: invalid escape sequence '\*'
  """
C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\winshell.py:870: SyntaxWarning: invalid escape sequence '\p'
  """Create a Windows shortcut:
Traceback (most recent call last):
  File "C:\Users\marko\Desktop\test\src\build.py", line 99, in <module>
    setup(
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cx_Freeze\__init__.py", line 66, in setup
    return setuptools.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\setuptools\__init__.py", line 117, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\setuptools\_distutils\core.py", line 183, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\setuptools\_distutils\core.py", line 199, in run_commands
    dist.run_commands()
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\setuptools\_distutils\dist.py", line 954, in run_commands
    self.run_command(cmd)
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\setuptools\dist.py", line 995, in run_command
    super().run_command(command)
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
    cmd_obj.run()
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cx_Freeze\command\bdist_msi.py", line 1115, in run
    self.run_command("build")
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\setuptools\dist.py", line 995, in run_command
    super().run_command(command)
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
    cmd_obj.run()
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\setuptools\_distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\setuptools\dist.py", line 995, in run_command
    super().run_command(command)
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
    cmd_obj.run()
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cx_Freeze\command\build_exe.py", line 303, in run
    freezer.freeze()
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cx_Freeze\freezer.py", line 755, in freeze
    self._freeze_executable(executable)
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cx_Freeze\freezer.py", line 290, in _freeze_executable
    finder.include_file_as_module(exe.main_script, exe.main_module_name)
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cx_Freeze\finder.py", line 777, in include_file_as_module
    module = self._load_module_from_file(name, path, deferred_imports)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cx_Freeze\finder.py", line 499, in _load_module_from_file
    self._load_module_code(module, loader, deferred_imports)
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cx_Freeze\finder.py", line 472, in _load_module_code
    self._scan_code(module, deferred_imports)
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cx_Freeze\finder.py", line 660, in _scan_code
    imported_module = self._import_module(
                      ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cx_Freeze\finder.py", line 268, in _import_module
    module = self._internal_import_module(name, deferred_imports)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cx_Freeze\finder.py", line 355, in _internal_import_module
    module = self._load_module(
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cx_Freeze\finder.py", line 426, in _load_module
    self._load_module_code(module, loader, deferred_imports)
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cx_Freeze\finder.py", line 472, in _load_module_code
    self._scan_code(module, deferred_imports)
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cx_Freeze\finder.py", line 660, in _scan_code
    imported_module = self._import_module(
                      ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cx_Freeze\finder.py", line 268, in _import_module
    module = self._internal_import_module(name, deferred_imports)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cx_Freeze\finder.py", line 355, in _internal_import_module
    module = self._load_module(
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cx_Freeze\finder.py", line 426, in _load_module
    self._load_module_code(module, loader, deferred_imports)
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cx_Freeze\finder.py", line 472, in _load_module_code
    self._scan_code(module, deferred_imports)
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cx_Freeze\finder.py", line 668, in _scan_code
    self._ensure_from_list(
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cx_Freeze\finder.py", line 179, in _ensure_from_list
    self._import_module(sub_module_name, deferred_imports, caller)
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cx_Freeze\finder.py", line 268, in _import_module
    module = self._internal_import_module(name, deferred_imports)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cx_Freeze\finder.py", line 355, in _internal_import_module
    module = self._load_module(
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cx_Freeze\finder.py", line 426, in _load_module
    self._load_module_code(module, loader, deferred_imports)
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cx_Freeze\finder.py", line 477, in _load_module_code
    elif module.stub_code is not None:
         ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cx_Freeze\module.py", line 257, in stub_code
    package = filename.parent.relative_to(self.root_dir)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\pathlib.py", line 682, in relative_to
    raise ValueError(f"{str(self)!r} is not in the subpath of {str(other)!r}")
ValueError: 'C:\\Users\\marko\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\win32comext\\shell' is not in the subpath of 'C:\\Users\\marko\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\win32com'
```

**Desktop (please complete the following information):**
 - Windows 11 24h2
 - amd64
 - cx_Freeze 7.2.6
 - Python 3.12.7

**Comment by HydraDragonAntivirus** [comment]
Same with https://github.com/marcelotduarte/cx_Freeze/issues/2683

**Comment by marcelotduarte** [comment]
You can test the PR with:
`pip install -i https://test.pypi.org/simple/ cx-Freeze==7.3.0.dev2708`

**Comment by markox92** [comment]
> You can test the PR with: `pip install -i https://test.pypi.org/simple/ cx-Freeze==7.3.0.dev2708`

```
pip install -i https://test.pypi.org/simple/ cx-Freeze==7.3.0.dev2708
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://test.pypi.org/simple/
Collecting cx-Freeze==7.3.0.dev2708
  Downloading https://test-files.pythonhosted.org/packages/d7/cf/0665663f1d20b4f86f0ed70820d4ecdc1d98b7667acccc344ee8b89ffa82/cx_Freeze-7.3.0.dev2708-cp312-cp312-win_amd64.whl.metadata (10 kB)
INFO: pip is looking at multiple versions of cx-freeze to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement filelock>=3.12.3 (from cx-freeze) (from versions: none)
ERROR: No matching distribution found for filelock>=3.12.3
```

**Comment by marcelotduarte** [comment]
`pip install --extra-index-url https://test.pypi.org/simple/ cx-Freeze==7.3.0.dev2708`

**Comment by markox92** [comment]
@marcelotduarte this is strange, I have built msi but now when I run the app it's back error module win32com.shell.

![Screenshot 2024-11-27 184822](https://github.com/user-attachments/assets/58756820-38a3-4fc6-a882-cd3853242fed)

**Comment by marcelotduarte** [comment]
I used this [sample](https://github.com/marcelotduarte/cx_Freeze/pull/2708/files#diff-81db0b5f4a0e2fbfba037b978eecd196b8610712d21b73981b78c0c3a13ed9a5) to test, by it does not include win32com.shell. So you can modify or make a simple code that I can use to test?

**Comment by marcelotduarte** [comment]
Do you have pywin32 installed?

**Comment by marcelotduarte** [comment]
Checking that winshell is used, I think I understand the situation. I redid the tests and the patch.
I was unable to upload the wheel to testpipy, so to test it, download the wheel from [here](https://github.com/marcelotduarte/cx_Freeze/actions/runs/12061809160/artifacts/2247768540) and install it using:
`pip uninstall cx_Freeze`
`pip install <wheel file name> --pre --no-cache`

**Comment by HydraDragonAntivirus** [comment]
I have pywin32 installed and get same issue at 7.2.6 but not at 7.2.5

**Comment by markox92** [comment]
> Checking that winshell is used, I think I understand the situation. I redid the tests and the patch. I was unable to upload the wheel to testpipy, so to test it, download the wheel from [here](https://github.com/marcelotduarte/cx_Freeze/actions/runs/12061809160/artifacts/2247768540) and install it using: `pip uninstall cx_Freeze` `pip install <wheel file name> --pre --no-cache`

Tested `cx_Freeze-7.3.0.dev2708-cp312-cp312-win_amd64.whl` and it looks like it works fine now.

**Comment by marcelotduarte** [comment]
@HydraDragonAntivirus Can you test the PR?
Download the wheel from [here](https://github.com/marcelotduarte/cx_Freeze/actions/runs/12061809160/artifacts/2247768540) and install it using:
`pip uninstall cx_Freeze`
`pip install <wheel file name> --pre --no-cache`

**Comment by HydraDragonAntivirus** [comment]
> @HydraDragonAntivirus Can you test the PR? Download the wheel from [here](https://github.com/marcelotduarte/cx_Freeze/actions/runs/12061809160/artifacts/2247768540) and install it using: `pip uninstall cx_Freeze` `pip install <wheel file name> --pre --no-cache`

It now worked on python 3.12.7 with my antivirus.py application with no errors.

**Comment by marcelotduarte** [comment]
[Release 7.2.7](https://github.com/marcelotduarte/cx_Freeze/releases/tag/7.2.7) is out!
[Documentation](https://cx-freeze.readthedocs.io)
