### ISSUE TITLE
Ubuntu OpenCV: ImportError: libswresample-2ec4394e.so.4.7.100: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by bw7715** [marcelotduarte/cx_Freeze#2729]
An error occurs when try to freeze a project with OpenCV on Linux:
```
Traceback (most recent call last):
  File "/home/user1/p39_opencv/_build/venv/lib/python3.9/site-packages/cx_Freeze/initscripts/__startup__.py", line 140, in run
    module_init.run(f"__main__{name}")
  File "/home/user1/p39_opencv/_build/venv/lib/python3.9/site-packages/cx_Freeze/initscripts/console.py", line 25, in run
    exec(code, main_globals)
  File "/home/user1/p39_opencv/project.py", line 1, in <module>
    import cv2
  File "/home/user1/p39_opencv/_build/venv/lib/python3.9/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/user1/p39_opencv/_build/venv/lib/python3.9/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libswresample-2ec4394e.so.4.7.100: cannot open shared object file: No such file or directory
```

project.py
```python
import cv2
print(cv2.__version__)
```

requirements.txt
```
cx_Freeze==7.2.7
opencv-contrib-python-headless==4.10.0.84
opencv-python-headless==4.1
```

freeze.sh
```bash
#!/bin/bash

WORKSPACE="$(dirname "$(realpath "$0")")"

BUILD_DIRPATH="${WORKSPACE}/_build"
#BASE_PYTHON_DIRPATH="/usr/local/bin/python3.9" 
BASE_PYTHON_DIRPATH="/usr/bin/python3.9"
VENV_DIRPATH="${BUILD_DIRPATH}/venv"
TARGET_DIR="${BUILD_DIRPATH}/out"
SCRIPTS_DIRPATH="${VENV_DIRPATH}/bin"
PYTHON_EXE_PATH="${SCRIPTS_DIRPATH}/python"
FREEZER_EXE_PATH="${SCRIPTS_DIRPATH}/cxfreeze"
TARGET_NAME="project_out"
PROJECT_SOURCE_PY_PATH="${WORKSPACE}/project.py"

PACKAGES="cv2"

export PATH="${SCRIPTS_DIRPATH}/:$PATH" 

"${BASE_PYTHON_DIRPATH}" -m venv "${VENV_DIRPATH}"
"${PYTHON_EXE_PATH}" -m pip install -r requirements.txt
if [ $? -ne 0 ]; then
    read -p "An error occurred. Press any key to continue..."
    exit 1
fi

"${FREEZER_EXE_PATH}" build -O1 -O2 --include-msvcr --build-exe="${TARGET_DIR}" --target-name="${TARGET_NAME}" --packages="${PACKAGES}" --script="${PROJECT_SOURCE_PY_PATH}"
if [ $? -ne 0 ]; then
    read -p "An error occurred. Press any key to continue..."
    exit 1
fi

"${TARGET_DIR}/${TARGET_NAME}"
if [ $? -ne 0 ]; then
    read -p "An error occurred. Press any key to continue..."
    exit 1
fi
```

**Desktop (please complete the following information):**
 - Platform information: Ubuntu Linux 22.04 and 24.04
 - OS architecture (e.g. amd64): 64bit
 - cx_Freeze version: 7.2.7
 - Python version: 3.9

**Comment by marcelotduarte** [comment]
You can test the PR with:
`pip install --extra-index-url https://test.pypi.org/simple/ cx-Freeze==7.3.0.2735.dev1734393177`

**Comment by bw7715** [comment]
> You can test the PR with: `pip install --extra-index-url https://test.pypi.org/simple/ cx-Freeze==7.3.0.2735.dev1734393177`

I still have the same problem.


```
python -m pip list
Package                        Version
------------------------------ ------------------------
cx_Freeze                      7.3.0.2735.dev1734393177
filelock                       3.16.1
numpy                          2.0.2
opencv-contrib-python-headless 4.10.0.84
opencv-python-headless         4.10.0.84
packaging                      24.2
patchelf                       0.17.2.1
pip                            22.0.4
setuptools                     75.6.0
tomli                          2.2.1
typing_extensions              4.12.2

```

**Comment by bw7715** [comment]
I found a fix for this (the order of missing libs is important):
```python
import ctypes
from pathlib import Path

venv_lib_path = Path(__file__).resolve().parent.parent

missing_libs = [
    "libquadmath*.so",
    "libgfortran*.so",
    "libcrypto*.so",
    "libcrypto*.so.1.1",
    "libssl*.so",
    "libssl*.so.1.1",
    "libvpx*.so",
    "libavutil*.so",
    "libswresample*.so",
]

for missing_lib in missing_libs:
    for lib_path in venv_lib_path.rglob(f"{missing_lib}*"):
        if lib_path is not None and lib_path.is_file() and 'cv2' in str(lib_path).lower():
            print(lib_path.relative_to(venv_lib_path))
            ctypes.CDLL(lib_path)
```

And the project.py look like this:
```python
####################### FIX START ######################
# Fix for 'ImportError: libswresample-2ec4394e.so.4.7.100: cannot open shared object file: No such file or directory'
import ctypes
from pathlib import Path

venv_lib_path = Path(__file__).resolve().parent.parent

missing_libs = [
    "libquadmath*.so",
    "libgfortran*.so",
    "libcrypto*.so",
    "libcrypto*.so.1.1",
    "libssl*.so",
    "libssl*.so.1.1",
    "libvpx*.so",
    "libavutil*.so",
    "libswresample*.so",
]

for missing_lib in missing_libs:
    for lib_path in venv_lib_path.rglob(f"{missing_lib}*"):
        if lib_path is not None and lib_path.is_file() and 'cv2' in str(lib_path).lower():
            print(lib_path.relative_to(venv_lib_path))
            ctypes.CDLL(lib_path)
######################## FIX END #######################

import cv2
print(cv2.__version__)
```

**Comment by bw7715** [comment]
`print(lib_path.relative_to(venv_lib_path))` output:

```
cv2/libquadmath-96973f99.so.0.0.0
cv2/libgfortran-91cc3cb1.so.3.0.0
cv2/libcrypto-337dac8b.so.1.1
cv2/libcrypto-337dac8b.so.1.1
cv2/libssl-28bef1ac.so.1.1
cv2/libssl-28bef1ac.so.1.1
cv2/libvpx-c3a7933e.so.9.0.0
cv2/libavutil-a0a0531e.so.57.28.100
cv2/libswresample-2ec4394e.so.4.7.100

```

**Comment by marcelotduarte** [comment]
So you don't help me find a definitive solution... ;-)
We have to find a solution in which you don't need to hack each program.
But from your `pip list` I realized that I had not installed opencv-contrib-python-headless. Without it the patch works. I'll investigate a little more later.
I used the sample to test: https://github.com/marcelotduarte/cx_Freeze/tree/opencv/samples/opencv

**Comment by marcelotduarte** [comment]
I updated the patch. You can test with:
`pip install --extra-index-url https://test.pypi.org/simple/ cx-Freeze==7.3.0.2735.dev1734467144 `

**Comment by bw7715** [comment]
> cx-Freeze==7.3.0.2735.dev1734467144

Thank you. With this cx-Freeze version opencv project works for me :)

**Comment by marcelotduarte** [comment]
[Release 7.2.8](https://github.com/marcelotduarte/cx_Freeze/releases/tag/7.2.8) is out!
[Documentation](https://cx-freeze.readthedocs.io)
