### ISSUE TITLE
Ubuntu Shapely: ImportError: libgeos-e4f0e0c1.so.3.11.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by bw7715** [marcelotduarte/cx_Freeze#2737]
An error occurs in project with Shapely module.

```
Traceback (most recent call last):
  File "/home/user1/p39_shapely/_build/venv/lib/python3.9/site-packages/cx_Freeze/initscripts/__startup__.py", line 140, in run
    module_init.run(f"__main__{name}")
  File "/home/user1/p39_shapely/_build/venv/lib/python3.9/site-packages/cx_Freeze/initscripts/console.py", line 25, in run
    exec(code, main_globals)
  File "/home/user1/p39_shapely/project.py", line 27, in <module>
    import shapely
  File "/home/user1/p39_shapely/_build/venv/lib/python3.9/site-packages/shapely/__init__.py", line 1, in <module>
    from shapely.lib import GEOSException  # NOQA
ImportError: libgeos-e4f0e0c1.so.3.11.4: cannot open shared object file: No such file or directory

```

project.py
```python
import shapely
print(shapely.__version__)
```

requirements.txt
```
cx_Freeze==7.2.7
shapely==2.0.6
```

freeze.sh
```bash
#!/bin/bash

WORKSPACE="$(dirname "$(realpath "$0")")"

BUILD_DIRPATH="${WORKSPACE}/_build"
#BASE_PYTHON_DIRPATH="/usr/local/bin/python3.9"
BASE_PYTHON_DIRPATH="/usr/bin/python3.9"
VENV_DIRPATH="${BUILD_DIRPATH}/venv"
TARGET_DIR="${BUILD_DIRPATH}/out"
SCRIPTS_DIRPATH="${VENV_DIRPATH}/bin"
PYTHON_EXE_PATH="${SCRIPTS_DIRPATH}/python"
FREEZER_EXE_PATH="${SCRIPTS_DIRPATH}/cxfreeze"
TARGET_NAME="project_out"
PROJECT_SOURCE_PY_PATH="${WORKSPACE}/project.py"

PACKAGES="shapely"

export PATH="${SCRIPTS_DIRPATH}/:$PATH"

"${BASE_PYTHON_DIRPATH}" -m venv "${VENV_DIRPATH}"
"${PYTHON_EXE_PATH}" -m pip install -r requirements.txt
if [ $? -ne 0 ]; then
    read -p "An error occurred. Press any key to continue..."
    exit 1
fi

"${FREEZER_EXE_PATH}" build -O1 -O2 --include-msvcr --build-exe="${TARGET_DIR}" --target-name="${TARGET_NAME}" --packages="${PACKAGES}" --script="${PROJECT_SOURCE_PY_PATH}"
if [ $? -ne 0 ]; then
    read -p "An error occurred. Press any key to continue..."
    exit 1
fi

"${TARGET_DIR}/${TARGET_NAME}"
if [ $? -ne 0 ]; then
    read -p "An error occurred. Press any key to continue..."
    exit 1
fi
```

**Desktop (please complete the following information):**
 - Platform information: Ubuntu Linux 22.04 and Ubuntu Linux 24.04
 - OS architecture (e.g. amd64): 64bit
 - cx_Freeze version: 7.2.7
 - Python version: 3.9

**Comment by marcelotduarte** [comment]
You can test the PR with:
`pip install --extra-index-url https://test.pypi.org/simple/ cx-Freeze==7.3.0.2749.dev1734972467`

**Comment by marcelotduarte** [comment]
[Release 7.2.8](https://github.com/marcelotduarte/cx_Freeze/releases/tag/7.2.8) is out!
[Documentation](https://cx-freeze.readthedocs.io)

Please give me feedback.

**Comment by bw7715** [comment]
Thank you, with cx-Freeze 7.2.8 the project with shapely workds.
