### ISSUE TITLE
Calling the app from a Windows shortcut results in crash, while calling the app directly works.

### ISSUE THREAD

**Issue by nickvandewiele** [marcelotduarte/cx_Freeze#276]
Calling the app from a Windows shortcut results in crash, while calling the app directly works.

The error trace (cf. below) points to "_DLL load failed errors_" which indicate that the app is unable to find DLLs that are located in the same folder of the app.

A solution is to fill out the "Start in:" field of the shortcut (cf. screenshot below), which can be part of an installation (as explained in https://github.com/anthony-tuininga/cx_Freeze/issues/48). However, this is a work-around solution, with limited robustness. For example, it does not work when the app is launched by clicking on files that have an file extension associated with the app, which uses a registry look-up mechanism. The "start-in" field is absent in such mechanism, afaik.  

It seems like release 5.0.1 already included a fix related to paths to app and symbolic links (cf. accc271), but this fix did not work.

**Ideally, I'd like to understand the piece of code where cx_Freeze assumes or sets the location of the DLLs of dependencies like numpy/scipy.**

```
root - ERROR - <class 'ImportError'>: DLL load failed: The specified module could not be found.
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\envX\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "C:\ProgramData\Anaconda3\envs\envX\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
	...
  File "C:\ProgramData\Anaconda3\envs\envX\lib\site-packages\scipy\stats\__init__.py", line 348, in <module>
  File "C:\ProgramData\Anaconda3\envs\envX\lib\site-packages\scipy\stats\stats.py", line 175, in <module>
  File "C:\ProgramData\Anaconda3\envs\envX\lib\site-packages\scipy\special\__init__.py", line 640, in <module>
ImportError: DLL load failed: The specified module could not be found.
```

My environment:
- Anaconda Python 3.5
- cx_Freeze 5.0.2
- Windows 10

![image](https://user-images.githubusercontent.com/242147/27229861-2e4eabe4-527b-11e7-8000-3cd353a26d11.png)

**Comment by nickvandewiele** [comment]
perhaps related #274

**Comment by marcelotduarte** [comment]
Closing due to inactivity.
