### ISSUE TITLE
When package use 'requests' cannot import the dependency files automatically

### ISSUE THREAD

**Issue by Sl0v3C** [marcelotduarte/cx_Freeze#287]
## test_file: hello.py which only 2 lines:
"import requests
print("Hello")"
## steup.py as bellow:

from cx_Freeze import setup, Executable
import sys

buildOptions = dict(packages = ['requests'], includes = [], excludes = [], p

ath= sys.path)

executables = [
    Executable('D:\hello.py'),
]

setup(name='hello',
      version = '1.0',
      description = 'Hello World',
      options = dict(build_exe = buildOptions),
      executables = executables)
## Run the hello.exe which generated by cxfreeze, it will show bellow error:
C:\Python34\Scripts\build\exe.win-amd64-3.4>C:\Python34\Scripts\build\exe.win-amd64-3.4\hello.exe
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
    module.run()
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
    exec(code, m.__dict__)
  File "D:\price_spider\LEGO_price\hello.py", line 1, in <module>
  File "C:\Python34\lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "C:\Python34\lib\site-packages\urllib3\__init__.py", line 8, in <module>
    from .connectionpool import (
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 28, in <module>
    from .packages.six.moves import queue
  File "C:\Python34\lib\site-packages\urllib3\packages\six.py", line 92, in __get__
    result = self._resolve()
  File "C:\Python34\lib\site-packages\urllib3\packages\six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "C:\Python34\lib\site-packages\urllib3\packages\six.py", line 82, in _import_module
    __import__(name)
ImportError: No module named 'queue'

**Comment by TCRserver** [comment]
My solution with cx_Freeze-5.0.2 was to add the following imports:
```
import requests
from multiprocessing import Queue
from idna import idnadata
```
but with cx_Freeze-6.0b1 my solution does not work anymore.
I get the following error message:

> Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
    module.run()
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
    exec(code, m.__dict__)
  File "C:\Users\tcr\Qsync\Projekte\g2p_pdm\test.py", line 3, in <module>
    import requests
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\requests\__init__.py", line 98, in <module>
    from . import packages
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\requests\packages.py", line 7, in <module>
    locals()[package] = __import__(package)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\idna\__init__.py", line 2, in <module>
    from .core import *
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\idna\core.py", line 1, in <module>
    from . import idnadata
ImportError: cannot import name 'idnadata'

**Comment by anthony-tuininga** [comment]
The problem is that the "queue" module is being loaded dynamically. If you include it in your "includes" directive, the problem goes away. This works for both the v5.x branch and master (6.0b1).

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
