### ISSUE TITLE
cx_freeze 5.0 build *.py using retrying module cannot run

### ISSUE THREAD

**Issue by Sl0v3C** [marcelotduarte/cx_Freeze#289]
### However it cannot be run with bellow message:
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
    module.run()
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
    exec(code, m.__dict__)
  File "Z:\Workshop\price_spider1\process.py", line 3, in <module>
    import sys, re, HTMLInfo, genHTML, time
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "Z:\Workshop\price_spider1\HTMLInfo.py", line 212, in <module>
    @retry
NameError: name 'retry' is not defined

**Comment by anthony-tuininga** [comment]
Can you provide a simple script and accompanying setup.py that can be used to demonstrate the problem?

**Comment by Sl0v3C** [comment]
Hi anthony,
I just write a simple test retrying script and generate the exe file with cx_freeze.
It can run now, I don't know why it can not be executed before.
Maybe my HTMLInfo.py has some error or setup.py not config right way.
I will close this issue.
Thanks!
