### ISSUE TITLE
Problem with bcrypt / paramiko when running frozen binary

### ISSUE THREAD

**Issue by Devligue** [marcelotduarte/cx_Freeze#313]
OS: Ubuntu 17.4
Python: 3.5
cx_Freeze:  tried both 5.0.2 and latest 5.x branch

I have frozen my python script no problem, except that I've run into an issue when running the binary file:

```
Traceback (most recent call last):
  File "/home/kd/.local/lib/python3.5/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
    module.run()
  File "/home/kd/.local/lib/python3.5/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run
    exec(code, m.__dict__)
  File "main.py", line 41, in <module>
  File "/media/sf_DBiR-SVN/Software/STERKA_UI_3/Source/3.1.0 +/app/classes.py", line 25, in <module>
    import threads
  File "/media/sf_DBiR-SVN/Software/STERKA_UI_3/Source/3.1.0 +/app/threads.py", line 16, in <module>
    import paramiko
  File "/home/kd/.local/lib/python3.5/site-packages/paramiko/__init__.py", line 31, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/home/kd/.local/lib/python3.5/site-packages/paramiko/transport.py", line 57, in <module>
    from paramiko.ed25519key import Ed25519Key
  File "/home/kd/.local/lib/python3.5/site-packages/paramiko/ed25519key.py", line 17, in <module>
    import bcrypt
  File "/home/kd/.local/lib/python3.5/site-packages/bcrypt/__init__.py", line 25, in <module>
    from bcrypt import _bcrypt
ImportError: libffi-0ded59d6.so.6.0.4: cannot open shared object file: No such file or directory
```

I had similar issue before with PIL but i solved it by adding PIL to zip_exclude_packages. I tried the same with adding bcrypt and paramiko to zip_exclude_packages but with no success. Both paramiko and bcrypt import with no error in python and work fine in my program yet something is not right when frozen. The mentioned in traceback file libffi-0ded59d6.so.6.0.4 is created in the output directory.

**Comment by klensy** [comment]
```5.x``` branch for 2.7 python, so you should try ```master``` branch for python 3.5.

**Comment by anthony-tuininga** [comment]
Can you provide some sample code that demonstrates the problem?

**Comment by Devligue** [comment]
Sure!

test.py
```
import bcrypt

print("Hello World!")
```

cxf_setup.py
```
from cx_Freeze import setup, Executable

exe = Executable(
    script="test.py",
    targetName="test",
    copyright="",
    icon="icon.ico"
)

options = {
    "build_exe": {
        "build_exe": 'builds/linux/test_app',
        "optimize": 2,
        "include_msvcr": True,
        "packages": ['bcrypt', 'cffi'],
        "zip_include_packages": "*",
        "zip_exclude_packages": ['bcrypt']
    }
}

setup(
    name="test",
    version=__version__,
    author="tester",
    description="test",
    options=options,
    executables=[exe]
)
```

Error when running resulting binary file:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
    module.run()
  File "/usr/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run
    exec(code, m.__dict__)
  File "test.py", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/bcrypt/__init__.py", line 25, in <module>
    from bcrypt import _bcrypt
ImportError: libffi-d78936b1.so.6.0.4: cannot open shared object file: No such file or directory
```

edit:
This was done on Manjaro 17.0.6 with Python 3.6.3 and cx_Freeze 5.0.2 (installed with pip)

edit2:
Here is the error that occurs if we exchange bcrypt with paramiko in the above example:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
    module.run()
  File "/usr/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run
    exec(code, m.__dict__)
  File "test.py", line 2, in <module>
  File "/usr/lib/python3.6/site-packages/paramiko/__init__.py", line 31, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/lib/python3.6/site-packages/paramiko/transport.py", line 57, in <module>
    from paramiko.ed25519key import Ed25519Key
  File "/usr/lib/python3.6/site-packages/paramiko/ed25519key.py", line 17, in <module>
    import bcrypt
  File "/usr/lib/python3.6/site-packages/bcrypt/__init__.py", line 25, in <module>
    from bcrypt import _bcrypt
  File "ExtensionLoader_bcrypt__bcrypt.py", line 22, in <module>
  File "ExtensionLoader_bcrypt__bcrypt.py", line 14, in __bootstrap__
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libffi-d78936b1.so.6.0.4: cannot open shared object file: No such file or directory
```

**Comment by anthony-tuininga** [comment]
I just tried this with the v5.x branch with python 3.6 and it worked as expected. I used bcrypt 3.1.4 and cffi 1.11.2 -- which may or may not make any difference? Can you try with either master (aka 6.0b1) or the v5.x branch and let me know if that works any better for you?

**Comment by Devligue** [comment]
With the same exact test code as presented before and:
- Manjaro 17.0.6 (freshly installed so that nothing should be broken)
- Python 3.6.2
- bcrypt 3.1.4
- cffi 1.11.2
- cx_Freeze 6.0b1 (master branch) or 5.1.1 (v5.x branch) - tried both

When running binary I get error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
    module.run()
  File "/usr/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run
    exec(code, m.__dict__)
  File "test.py", line 2, in <module>
  File "/usr/lib/python3.6/site-packages/bcrypt/__init__.py", line 25, in <module>
    from bcrypt import _bcrypt
ImportError: libffi-bce22613.so.6.0.4: cannot open shared object file: No such file or directory
```

Maybe I am missing some steps that you do? Here is how I proceed:
- `pip install bcrypt`
- `pip install "git+https://github.com/anthony-tuininga/cx_Freeze@master"` (or v5.x)
- create `test.py` and `cxf_setup.py` with content presented in previous comments
- run `test.py` just to make sure it works fine
- `python cxf_setup.py build`
- run resulting `test` binary file
- get error

**Comment by jepmarketo** [comment]
in site-packages, make sure you have the folder `.libs_cffi_backend` which contains the file it's complaining about. Because of the period, the folder may be invisible in some apps (like WinSCP, by default).

**Comment by alex-eri** [comment]
@jepmarketo how to add this folder to `build/lib` ?

there is few places for site-packages. How to find in which is it installed?

**Comment by jepmarketo** [comment]
@alex-eri sorry, don't know. I installed paramiko on EC2 / Amazon Linux using pip, then copied it to my local system using WinSCP to add it to an AWS Lambda deployment zip-file. Initially I had forgotten to copy the hidden folder so I got the error mentioned by OP

**Comment by r41d** [comment]
Have a similar problem (although with the ssdeep) package, and just have no clue where this weird filename (libffi-d78936b1.so.6.0.4) is coming from, it obviously doesn't exist, why is python looking for it...

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.

**Comment by cbedroid** [comment]
For missing .libs_cffi_backend/  folder , just uninstall cffi module and do a clean install.

#uninstall
pip uninstall  cffi # be sure to use your corresponding version of pip

#reinstalll cffi:
python -m pip install --no-cache  cffi

**Comment by sarnold** [comment]
I just got a runtime error for this one, but the answer (using 6.4.2) for me was just adding the ``cffi`` module to includes (and the platform libs dir did not start with a ``.`` in my case).  It should be enough to add the module name as long as the install pulls in the right platform wheels (with no need to manually bundle any external shared libs).
