### ISSUE TITLE
ValueError: invalid version number

### ISSUE THREAD

**Issue by kierun** [marcelotduarte/cx_Freeze#340]
I have `version = "0.1.0a"` which should be a valid version number. When I run `python setup.py dbist_msi`, I get this:

```
copying build\exe.win-amd64-3.6\top_station.exe -> build\bdist.win-amd64\msi
copying build\exe.win-amd64-3.6\VCRUNTIME140.dll -> build\bdist.win-amd64\msi
Traceback (most recent call last):
  File ".\setup.py", line 121, in <module>
    executables=executables,
  File "C:\Users\User\Documents\Projects\ook\BTTS\lib\site-packages\cx_Freeze\dist.py", line 348, in setup
    distutils.core.setup(**attrs)
  File "C:\Python36\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Python36\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Python36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\User\Documents\Projects\ook\BTTS\lib\site-packages\cx_Freeze\windist.py", line 381, in run
    distutils.version.StrictVersion(version).version
  File "C:\Python36\lib\distutils\version.py", line 40, in __init__
    self.parse(vstring)
  File "C:\Python36\lib\distutils\version.py", line 137, in parse
    raise ValueError("invalid version number '%s'" % vstring)
ValueError: invalid version number '0.1.0a'
```

**Comment by kierun** [comment]
The next version will be `0.1.0a1` and so on until `0.1.b` and `0.1.0rc` and so on…

**Comment by kierun** [comment]
As expected `0.2.0dev2` is invalid as well. ☹

**Comment by luckymls** [comment]
You can only use float numbers

**Comment by kierun** [comment]
@luckymls Yes, I figured as much. However, that is a violation of [PEP440](https://www.python.org/dev/peps/pep-0440/).

**Comment by kierun** [comment]
@anthony-tuininga Thank you for merging my changes.
