### ISSUE TITLE
LookupError: no codec search functions registered: can't find encoding

### ISSUE THREAD

**Issue by speedpacer** [marcelotduarte/cx_Freeze#341]
I believe this is related to #325.  

I cloned and installed from the v5.x branch on CentOS 7 and I'm receiving this error when running the executable created by "python setup.py build".  
`LookupError: no codec search functions registered: can't find encoding`

I also received an error while I was installing from source: 
`Installed /usr/lib64/python2.7/site-packages/cx_Freeze-5.1.1-py2.7-linux-x86_64.egg
Traceback (most recent call last):
  File "setup.py", line 212, in <module>
    package_data = {"cx_Freeze" : packageData })
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 101, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 380, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 604, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 655, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 701, in process_distribution
    distreq.project_name, distreq.specs, requirement.extras
TypeError: __init__() takes exactly 2 arguments (4 given)` 

Also, when I attempted "python setup.py bdist_rpm", I received this error:
`error: mfm.py: No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.khxrJI (%build)
RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.khxrJI (%build)
error: command rpmbuild failed with exit status 1`

After uninstalling and reinstalling just using pip, I realized that it's also 5.1.1.

Not sure if any/all of these are related but wanted to provide as much info as I could.

**Comment by grahamperrin** [comment]
Mozilla bug [1503358 - mozregression-gui crash: LookupError: no codec search functions registered: can't find encoding](https://bugzilla.mozilla.org/show_bug.cgi?id=1503358)

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
