### ISSUE TITLE
Unable to build an simple installer via bdist_msi

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#35]
Originally reported by: **sifu (Bitbucket: [sifu](https://bitbucket.org/sifu), GitHub: [sifu](https://github.com/sifu))**

----------------------------------------

Hello,

When I try to build an simple installer, I have the following error:

```
#!python

Traceback (most recent call last):
  File "setup_czfreeze.py", line 20, in <module>
    executables = [Executable( script = "bin/imageresizer"
  File "c:\Python27\lib\site-packages\cx_Freeze\dist.py", line 365, in setup
    distutils.core.setup(**attrs)
  File "c:\Python27\lib\distutils\core.py", line 152, in setup
    dist.run_commands()
  File "c:\Python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "c:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "c:\Python27\lib\site-packages\cx_Freeze\windist.py", line 390, in run
    self.add_files()
  File "c:\Python27\lib\site-packages\cx_Freeze\windist.py", line 131, in add_fi
les
    dir.add_file(file)
  File "c:\Python27\lib\msilib\__init__.py", line 337, in add_file
    sequence, logical = self.cab.append(absolute, file, logical)
  File "c:\Python27\lib\msilib\__init__.py", line 207, in append
    logical = self.gen_id(file)
  File "c:\Python27\lib\msilib\__init__.py", line 195, in gen_id
    logical = _logical = make_id(file)
  File "c:\Python27\lib\msilib\__init__.py", line 181, in make_id
    assert re.match("^[A-Za-z_][A-Za-z0-9_.]*$", str), "FILE"+str
AssertionError: FILEGMT+0

```
It seems that cz_freeze was unable to add a file with a "+" like "GMT+0".

You can find the setup.py file here https://gitorious.org/yet-another-piwigo-image-resizer/yet-another-piwigo-image-resizer/commit/e9cc0b8be3008407ac7ad65ed10d07936338d7d7

Thanks.

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/35

**Comment by anthony-tuininga** [comment]
*Original comment by* **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**:

----------------------------------------

This appears to have been a bug in Python itself - see [Issue 11696](http://bugs.python.org/issue11696). If you're using a version older than 2.7.2, try upgrading.

**Comment by anthony-tuininga** [comment]
*Original comment by* **sifu (Bitbucket: [sifu](https://bitbucket.org/sifu), GitHub: [sifu](https://github.com/sifu))**:

----------------------------------------

It's OK with the last version of Python 2.7.
Thanks alot for your help and sorry for the inconvenience.

**Comment by anthony-tuininga** [comment]
*Original comment by* **sifu (Bitbucket: [sifu](https://bitbucket.org/sifu), GitHub: [sifu](https://github.com/sifu))**:

----------------------------------------

It was due of my version of Python.
There is no issue with cx_Freeze.
