### ISSUE TITLE
sqlite3 Unable to open database file

### ISSUE THREAD

**Issue by ThomasCaio** [marcelotduarte/cx_Freeze#350]
Traceback (most recent call last):
  File "C:\Python36-32\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
    module.run()
  File "C:\Python36-32\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
    exec(code, m.__dict__)
  File "Launcher.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "E:\Estoque\CadClient.py", line 3, in <module>
    import sqlite3,time,Launcher
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "E:\Estoque\Launcher.py", line 3, in <module>
    import ContEst
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "E:\Estoque\ContEst.py", line 4, in <module>
    from contents import funcs,login,multilistbox
  File "E:\Estoque\contents\login.py", line 4, in <module>
    import ContEst, CadClient, AccManager, Launcher
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "E:\Estoque\AccManager.py", line 7, in <module>
    conn = sqlite3.connect('contents/database.db')
sqlite3.OperationalError: unable to open database file

Name: cx-Freeze
Version: 5.1.1
Summary: create standalone executables from Python scripts
Home-page: https://anthony-tuininga.github.io/cx_Freeze
Author: Anthony Tuininga
Author-email: anthony.tuininga@gmail.com
License: Python Software Foundation License
Location: c:\python36-32\lib\site-packages
Requires:

##### setup.py
```
import os,sys
os.environ['TCL_LIBRARY'] = r'C:\Python36-32\tcl\tcl8.6'
os.environ['TK_LIBRARY'] = r'C:\Python36-32\tcl\tk8.6'

from cx_Freeze import setup, Executable

include_files = [r"C:\Python36-32\DLLs\tcl86t.dll",
                 r"C:\Python36-32\DLLs\tk86t.dll"]

setup(
    name = "InfoBerthis",
    version = "0.1",
    description = "Programa Test",
    executables = [Executable("Launcher.py", base="Win32GUI")],
    options={"build_exe": {
        'include_msvcr': True, 'include_files':include_files}},
    build_exe_options = {"packages": [
        'requests', 'time', 'sys', 'sqlite3', 'datetime'], "excludes": ["tkinter"], 'include_files': [os.path.join(sys.base_prefix, 'DLLs', 'sqlite3.dll')]}
)
```

**Comment by marcelotduarte** [comment]
These issues have been resolved in version 6.0b1.
