### ISSUE TITLE
from ._ufuncs import * 'ImportError: DLL load failed' with scipy

### ISSUE THREAD

**Issue by jorgesmok** [marcelotduarte/cx_Freeze#355]
Hello guys, I'm trying to freeze an application that uses PyQt4, matplotlib, Enthought (mayavi), numpy, scipy, etc... and I've had some trouble, I've fixed a lot of import errors by using 'packages' option but now I encountered this issue related to scipy:

```
    import scipy.integrate
  File "C:\ProgramData\Anaconda3\envs\py35\lib\site-packages\scipy\integrate\__init__.py", line 55, in <module>
    from .quadrature import *
  File "C:\ProgramData\Anaconda3\envs\py35\lib\site-packages\scipy\integrate\quadrature.py", line 10, in <module>
    from scipy.special import roots_legendre
  File "C:\ProgramData\Anaconda3\envs\py35\lib\site-packages\scipy\special\__init__.py", line 640, in <module>
    from ._ufuncs import *
ImportError: DLL load failed: The specified procedure could not be found.
```
I did some research and found something quite similar in: https://github.com/anthony-tuininga/cx_Freeze/issues/43 which was not fixed, I tried a couple of workarounds mentioned there (including patching the hook function) and it didn't solve my problem. I'd really appreciate your help, thanks.

**Comment by jorgesmok** [comment]
Ok I already fixed it, I used Process Monitor to see what DLL files where missing and I found out **mkl_core.dll** and **libiomp5md.dll** were the problem. These files are located in \Anaconda3\Library\bin so I just copied them to the folder containing my frozen app, problem solved.

**Comment by cr7yash** [comment]
I am using python 3.6 and facing this error while importing seaborn or gensim. Can you explain more about how to solve this problem?

**Comment by AndreiKeino** [comment]
I have the same issue with the Anaconda3-5.2.0-Windows-x86.exe distribution on Windows 7 x86.

**Comment by datduong** [comment]
I also had the same problem. To fix it, I uninstalled scipy and then reinstalled it using pip.

**Comment by trohit920** [comment]
I am having same kind of problem. 
```
 from scipy.spatial import Distance
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\rohit\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\spatial\__init__.py", line 101, in <module>
    from ._spherical_voronoi import SphericalVoronoi
  File "C:\Users\rohit\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\spatial\_spherical_voronoi.py", line 18, in <module>
    from scipy.spatial.distance import pdist
  File "C:\Users\rohit\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\spatial\distance.py", line 126, in <module>
    from ..special import rel_entr
  File "C:\Users\rohit\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\special\__init__.py", line 641, in <module>
    from ._ufuncs import *
ImportError: DLL load failed: The specified procedure could not be found.
```
I am using Windows 10 with python 3.6 and pip  19.0.1. Any help will be appreciated.

**Comment by vedansh7788** [comment]
> Ok I already fixed it, I used Process Monitor to see what DLL files where missing and I found out **mkl_core.dll** and **libiomp5md.dll** were the problem. These files are located in \Anaconda3\Library\bin so I just copied them to the folder containing my frozen app, problem solved.

Hey, may I please know what is the frozen app?

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.

**Comment by tamarsam** [comment]
I am still having the same issue with cx-freeze 6.1 and the latest versions of scipy and numpy. Here is the output I get when running the exe generated by cx-freeze.

```
Traceback (most recent call last):
  File "C:\Users\tamar\PycharmProjects\liquidation\venv\lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "C:\Users\tamar\PycharmProjects\liquidation\venv\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Users\tamar\PycharmProjects\liquidation\venv\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tamar\PycharmProjects\liquidation\venv\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
    module.run()
  File "C:\Users\tamar\PycharmProjects\liquidation\venv\lib\site-packages\cx_Freeze\initscripts\Console.py", line 37, in run
    exec(code, {'__name__': '__main__'})
  File "liquidation.py", line 64, in <module>
    from io_tools.stock_wrapper import StockWrapper
  File "C:\Users\tamar\PycharmProjects\liquidation\io_tools\stock_wrapper.py", line 4, in <module>
    from io_tools.io_helper import *
  File "C:\Users\tamar\PycharmProjects\liquidation\io_tools\io_helper.py", line 7, in <module>
    from numpy import float_
  File "C:\Users\tamar\PycharmProjects\liquidation\venv\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\tamar\PycharmProjects\liquidation\venv\lib\site-packages\numpy\core\__init__.py", line 54, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "C:\Users\tamar\PycharmProjects\liquidation\liquidation\liquidation.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.3" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: The specified module could not be found.
```

**Comment by marcelotduarte** [comment]
@tamarsam
Please open a new issue (and include details like the numpy error sugests)
- how you installed Python (native, from python.org, anaconda, msys2) and version
- how you installed numpy
- your operating system
- if you can, provide a simple sample
