### ISSUE TITLE
ImportError: No module named 'beatifulsoup4'

### ISSUE THREAD

**Issue by maicol07** [marcelotduarte/cx_Freeze#381]
Hi,
when I build my setup:
```
import sys
from cx_Freeze import setup, Executable
import os

PYTHON_INSTALL_DIR = os.path.dirname(os.path.dirname(os.__file__))
os.environ['TCL_LIBRARY'] = "C:\\Users\Maicol\AppData\Local\Programs\Python\\Python36\\tcl\\tcl8.6"
os.environ['TK_LIBRARY'] = "C:\\Users\Maicol\AppData\Local\Programs\Python\\Python36\\tcl\\tk8.6"

# Dependencies are automatically detected, but it might need fine tuning.
build_exe_options = {"packages": ["os",
                                  "tkinter",
                                  "zipfile",
                                  "subprocess",
                                  "time",
                                  "gettext",
                                  "ctypes",
                                  "locale",
                                  "PIL.Image",
                                  "PIL.ImageTk",
                                  "webbrowser",
                                  "feedparser",
                                  "requests",
                                  "idna",
                                  "transifex.api",
                                  "polib",
                                  "bs4",
                                  "beautifulsoup4"
                                  "ttkthemes",
                                  "tkfontchooser",
                                  "lxml",
                                  "gzip"
                                  ],
                     "include-modules": ["Beautifulsoup4"],
                     # "includes":["transifex.api.requests.packages.core.idnadata"],
                     'include_files': ['LICENSE',
                                       "CHANGELOG_EN.md",
                                       "CHANGELOG_IT.md",
                                       os.path.join(PYTHON_INSTALL_DIR, 'DLLs', 'tk86t.dll'),
                                       os.path.join(PYTHON_INSTALL_DIR, 'DLLs', 'tcl86t.dll'),
                                       "images",
                                       "icons"],
                     "include_msvcr": True
                     }

# GUI applications require a different base on Windows (the default is for a
# console application).
base = None
if sys.platform == "win32":
    base = "Win32GUI"

setup(name="School Life Diary",
      version="1.0.0",
      author="maicol07",
      description="Diario scolastico sempre con te!",
      options={"build_exe": build_exe_options},
      executables=[Executable("main.py",
                              base=base,
                              icon="images/sld_icon_beta.ico",
                              shortcutName="School Life Diary",
                              shortcutDir="DesktopFolder"),
                   Executable("note.py"),
                   Executable("settings.py"),
                   Executable("subjects.py"),
                   Executable("timetable.py"),
                   Executable("voti.py"),
                   Executable("datepicker.py"),
                   Executable("wckToolTips.py")])

```
I get this error:
```
python setup.py build_exe
running build_exe
Traceback (most recent call last):
  File "setup.py", line 65, in <module>
    Executable("wckToolTips.py")])
  File "C:\Users\Maicol\AppData\Local\Programs\Python\Python36\lib\site-packages\cx_Freeze\dist.py", line 348, in setup
    distutils.core.setup(**attrs)
  File "C:\Users\Maicol\AppData\Local\Programs\Python\Python36\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\Maicol\AppData\Local\Programs\Python\Python36\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\Maicol\AppData\Local\Programs\Python\Python36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\Maicol\AppData\Local\Programs\Python\Python36\lib\site-packages\cx_Freeze\dist.py", line 219, in run
    freezer.Freeze()
  File "C:\Users\Maicol\AppData\Local\Programs\Python\Python36\lib\site-packages\cx_Freeze\freezer.py", line 617, in Freeze
    self.finder = self._GetModuleFinder()
  File "C:\Users\Maicol\AppData\Local\Programs\Python\Python36\lib\site-packages\cx_Freeze\freezer.py", line 346, in _GetModuleFinder
    finder.IncludePackage(name)
  File "C:\Users\Maicol\AppData\Local\Programs\Python\Python36\lib\site-packages\cx_Freeze\finder.py", line 621, in IncludePackage
    module = self._ImportModule(name, deferredImports)
  File "C:\Users\Maicol\AppData\Local\Programs\Python\Python36\lib\site-packages\cx_Freeze\finder.py", line 334, in _ImportModule
    raise ImportError("No module named %r" % name)
ImportError: No module named 'beatifulsoup4'
```
How to solve this?
Tested with cx_freeze 5.1.1 and 6.0.1b

**Comment by marcelotduarte** [comment]
I see some typos:
1) There is no "include-modules" option
2) In your code should have typo. Does it run directly in python? The following error seems to look for a module with a different name than what you put in packages (beautifulsoup4):
ImportError: No module named 'beatifulsoup4'
Did you get this resolved? If yes, please close the issue.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
