### ISSUE TITLE
Failing to freeze: Python 3.6.5, cx_freeze 5.1.1, Windows 7-64

### ISSUE THREAD

**Issue by mark-summerfield** [marcelotduarte/cx_Freeze#384]
I'm getting a failure with cx_freeze.
I'm using Python 3.6.5 and cx_freeze 5.1.1 on Windows 7-64.
```
Traceback (most recent call last):
  File "V:\myapp\myapp\stage\setup.py", line 76, in <module>
    shortcutName=NAME, shortcutDir='ProgramMenuFolder',
  File "C:\bin\py36\lib\site-packages\cx_Freeze\dist.py", line 349, in setup
    distutils.core.setup(**attrs)
  File "C:\bin\py36\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\bin\py36\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\bin\py36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\bin\py36\lib\site-packages\cx_Freeze\windist.py", line 389, in run
    self.add_config(fullname)
  File "C:\bin\py36\lib\site-packages\cx_Freeze\windist.py", line 43, in add_config
    self.initial_target_dir)])
  File "C:\bin\py36\lib\msilib\__init__.py", line 116, in add_data
    raise TypeError("Unsupported type %s" % field.__class__.__name__)
TypeError: Unsupported type tuple
```

**Comment by mark-summerfield** [comment]
This was due to my own mistake. I had `bdist_msi=dict(initial_target_dir=A_TUPLE))` which works fine for earlier cx_Freeze's. I changed it to be a single string and now it freezes fine. (Well, except that the resulting .exe won't run due to some problem with the tkinter libs, but I'll look into that separately.)
