### ISSUE TITLE
cx_Freeze on Windows cant get value from multiprocessing.Manager

### ISSUE THREAD

**Issue by alex-eri** [marcelotduarte/cx_Freeze#402]
Related to #231 but another error.

Python 3.6
cx_Freeze from pip

```
  File "<string>", line 2, in __getitem__
  File "C:\users\eri\Local Settings\Application Data\Programs\Python\Python36\lib\multiprocessing\managers.py", line 772, in _callmethod
multiprocessing.managers.RemoteError:
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\users\eri\Local Settings\Application Data\Programs\Python\Python36\lib\multiprocessing\managers.py", line 235, in serve_client
KeyError: '24830a48208'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\users\eri\Local Settings\Application Data\Programs\Python\Python36\lib\multiprocessing\managers.py", line 237, in serve_client
  File "C:\users\eri\Local Settings\Application Data\Programs\Python\Python36\lib\multiprocessing\managers.py", line 231, in serve_client
KeyError: '24830a48208'
```
Also this error happen then cx_freezed for linux in chroot.

**Comment by marcelotduarte** [comment]
See PR #622

**Comment by marcelotduarte** [comment]
Can you test the PR? (only if you have a C compiler)

pip install -U git+https://github.com/anthony-tuininga/cx_Freeze.git@refs/pull/622/head
