### ISSUE TITLE
Recent versions of gevent break __bootstrap__ when packaged

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#42]
Originally reported by: **Miguel Turner (Bitbucket: [dhagrow](https://bitbucket.org/dhagrow), GitHub: [dhagrow](https://github.com/dhagrow))**

----------------------------------------

If you try to package a gevent project (tested with gevent-1.0rc3 on Ubuntu 12) you will will get the following error when the package is run:

```
#!python

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cx_Freeze/initscripts/Console.py", line 27, in <module>
    exec code in m.__dict__
  File "test_thread.py", line 20, in <module>
    q = queue.Queue()
  File "/usr/local/lib/python2.7/dist-packages/gevent/queue.py", line 59, in __init__
    self.hub = get_hub()
  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 169, in get_hub
    hub = _threadlocal.hub = hubtype(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 268, in __init__
    loop_class = _import(self.loop_class)
  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 198, in _import
    return _import(path[-1])
  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 210, in _import
    x = __import__(module)
  File "ExtensionLoader_gevent_core.py", line 22, in <module>
  File "ExtensionLoader_gevent_core.py", line 9, in __bootstrap__
AttributeError: 'module' object has no attribute 'path'
```

After some investigation I found that this happens because cx_Freeze's *\_\_bootstrap\_\_* code mistakenly loads gevent's *os* module, rather than the stdlib's *os* module.

This can be worked around by changing [this line](https://bitbucket.org/anthony_tuininga/cx_freeze/src/7978ac7cca22807e87ae7e00a727fd133e226502/cx_Freeze/freezer.py?at=default#cl-25) as follows:

```
#!python

import imp, sys
os = sys.modules['os']
```

I'm not sure this is the best solution, but it works.

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/42

**Comment by anthony-tuininga** [comment]
*Original comment by* **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**:

----------------------------------------

Another solution, presumably, would be to use `from __future__ import absolute_import`. But that only works from Python 2.6, and cx_Freeze is still supporting older versions.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Rick van Hattem (Bitbucket: [WoLpH](https://bitbucket.org/WoLpH), GitHub: [WoLpH](https://github.com/WoLpH))**:

----------------------------------------

I confirm that the workaround does do the trick.

The absolute import has no effect however (on Python 2.7).

**Comment by anthony-tuininga** [comment]
*Original comment by* **Jake Omann (Bitbucket: [jhomann](https://bitbucket.org/jhomann), GitHub: Unknown)**:

----------------------------------------

The above did not work for me on Python 2.7 in windows. I ended up changing the line:

```
#!python

import os, imp, sys
```

To the following:

```
#!python

os = __import__("os")
imp = __import__("imp")
sys = __import__("sys")
```

Which is working fine for me when using gevent.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Florian Zierer (Bitbucket: [ziererf](https://bitbucket.org/ziererf), GitHub: Unknown)**:

----------------------------------------

Just wanted to say this is still an issue with gevent 1.0.1 and cx_freeze 4.3.3 like @dhagrow wrote.

The following helps here.

~~~
import imp, sys
os = sys.modules['os']
~~~

**Comment by anthony-tuininga** [comment]
*Original comment by* **Istvan Kun (Bitbucket: [kunyx](https://bitbucket.org/kunyx), GitHub: [kunyx](https://github.com/kunyx))**:

----------------------------------------

Definitely worked for me and saved me from hours (or maybe days) of searching for another solution. Thanks very much.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Brian G. Shacklett (Bitbucket: [bshacklett](https://bitbucket.org/bshacklett), GitHub: Unknown)**:

----------------------------------------

This bug affects the build of https://github.com/NagiosEnterprises/ncpa/. The solution provided by Miguel works to resolve it.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Mark Erikson (Bitbucket: [markerikson](https://bitbucket.org/markerikson), GitHub: [markerikson](https://github.com/markerikson))**:

----------------------------------------

Just running into this.  Doesn't look like the fix has been made in the repo.  Any reason why this can't be updated?

**Comment by anthony-tuininga** [comment]
*Original comment by* **Noortheen Raja  (Bitbucket: [jnoortheen](https://bitbucket.org/jnoortheen), GitHub: [jnoortheen](https://github.com/jnoortheen))**:

----------------------------------------

I have used this fix to change the imports in freezer.py but that doesn't help either. 

```
#!python

os = __import__("os")
imp = __import__("imp")
sys = __import__("sys")
```

**Comment by anthony-tuininga** [comment]
*Original comment by* **sqbing (Bitbucket: [sqbing](https://bitbucket.org/sqbing), GitHub: [sqbing](https://github.com/sqbing))**:

----------------------------------------

Same issue, same solution, thanks @Miguel Turner.
Why not fixed?
cxfreeze-4.3.4
