### ISSUE TITLE
cx_Freeze fails to find package causing a crash on execution of the build binary

### ISSUE THREAD

**Issue by golyalpha** [marcelotduarte/cx_Freeze#438]
I was able to successfully get around this issue for idna.idnadata (required by Requests) and six (required by win10toast), but I can't get it to find appdirs in pkg_resources. Here's the traceback from the built file:
```
Traceback (most recent call last):
  File "C:\Users\golya\AppData\Local\pypoetry\Cache\virtualenvs\chronogg-notifier-py3.7\lib\site-packages\cx_freeze-6.0b1-py3.7-win-amd64.egg\cx_Freeze\initscripts\__startup__.py", line 14, in run
    module.run()
  File "C:\Users\golya\AppData\Local\pypoetry\Cache\virtualenvs\chronogg-notifier-py3.7\lib\site-packages\cx_freeze-6.0b1-py3.7-win-amd64.egg\cx_Freeze\initscripts\Console.py", line 26, in run
    exec(code, m.__dict__)
  File "chronogg_notifier/__main__.py", line 1, in <module>
    from chronogg_notifier import main
  File "C:\Users\golya\git\chronogg-notifier\chronogg_notifier\__init__.py", line 9, in <module>
    import win10toast
  File "C:\Users\golya\AppData\Local\pypoetry\Cache\virtualenvs\chronogg-notifier-py3.7\lib\site-packages\win10toast\__init__.py", line 15, in <module>
    from pkg_resources import Requirement
  File "C:\Users\golya\AppData\Local\pypoetry\Cache\virtualenvs\chronogg-notifier-py3.7\lib\site-packages\pkg_resources\__init__.py", line 73, in <module>
    from pkg_resources.extern import appdirs
  File "C:\Users\golya\AppData\Local\pypoetry\Cache\virtualenvs\chronogg-notifier-py3.7\lib\site-packages\pkg_resources\extern\__init__.py", line 61, in load_module
    "distribution.".format(**locals())
ImportError: The 'appdirs' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
```

Note that the module I'm trying to build runs alright when ran directly, and trying to add "appdirs" into includes results in:
```
ImportError: No module named 'appdirs'
```

**Comment by sekrause** [comment]
It's related to issue #175, cx_Freeze can't deal with the dynamic imports from `pkg_resources._vendor`, so it doesn't include them sometimes.

The workaround is to add `'pkg_resources'` to cx_Freeze's `packages`.

**Comment by golyalpha** [comment]
I'm getting this traceback:
```
Traceback (most recent call last):
  File "C:\Users\golya\AppData\Local\pypoetry\Cache\virtualenvs\chronogg-notifier-py3.7\lib\site-packages\cx_freeze-6.0b1-py3.7-win-amd64.egg\cx_Freeze\initscripts\__startup__.py", line 14, in run
    module.run()
  File "C:\Users\golya\AppData\Local\pypoetry\Cache\virtualenvs\chronogg-notifier-py3.7\lib\site-packages\cx_freeze-6.0b1-py3.7-win-amd64.egg\cx_Freeze\initscripts\Console.py", line 26, in run
    exec(code, m.__dict__)
  File "chronogg_notifier/__main__.py", line 3, in <module>
    main()
  File "C:\Users\golya\git\chronogg-notifier\chronogg_notifier\__init__.py", line 14, in main
    notifier.show_toast("Chrono.GG Notifier", "Notifier running.")
  File "C:\Users\golya\AppData\Local\pypoetry\Cache\virtualenvs\chronogg-notifier-py3.7\lib\site-packages\win10toast\__init__.py", line 127, in show_toast
    self._show_toast(title, msg, icon_path, duration)
  File "C:\Users\golya\AppData\Local\pypoetry\Cache\virtualenvs\chronogg-notifier-py3.7\lib\site-packages\win10toast\__init__.py", line 93, in _show_toast
    icon_path =  resource_filename(Requirement.parse("win10toast"), "win10toast/data/python.ico")
  File "C:\Users\golya\AppData\Local\pypoetry\Cache\virtualenvs\chronogg-notifier-py3.7\lib\site-packages\pkg_resources\__init__.py", line 1136, in resource_filename
    return get_provider(package_or_requirement).get_resource_filename(
  File "C:\Users\golya\AppData\Local\pypoetry\Cache\virtualenvs\chronogg-notifier-py3.7\lib\site-packages\pkg_resources\__init__.py", line 344, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "C:\Users\golya\AppData\Local\pypoetry\Cache\virtualenvs\chronogg-notifier-py3.7\lib\site-packages\pkg_resources\__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Users\golya\AppData\Local\pypoetry\Cache\virtualenvs\chronogg-notifier-py3.7\lib\site-packages\pkg_resources\__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'win10toast' distribution was not found and is required by the application
```
With this in the setup.py:
```py
from cx_Freeze import Executable, setup

options = {
    "build_exe": {
        "packages": [
            "pkg_resources"
        ],
        "includes": [
            "idna.idnadata",
            "six",
            "win10toast"
        ]
    }
}

executables = [
    Executable('chronogg_notifier/__main__.py', targetName="chronogg_notifier.exe")
]

setup(
    name="chronogg-notifier",
    version="0.1.0",
    description="",
    author="golyalpha",
    author_email="golyalpha@gmail.com",
    executables=executables,
    options=options
)
```

I tried putting it in both packages and includes (as seen in the paste). Both throw the same error.
To note, the traceback is thrown after win10toast is successfully imported.

**Comment by detche** [comment]
For future reference, I had the same issue and solved it by including the missing package distribution info via 'include_files':

```python
import pkg_resources
from os.path import join, basename
from cx_Freeze import setup, Executable

def collect_dist_info(packages):
    """
    Recursively collects the path to the packages' dist-info.
    """
    if not isinstance(packages, list):
        packages = [packages]
    dirs = []
    for pkg in packages:
        distrib = pkg_resources.get_distribution(pkg)
        for req in distrib.requires():
            dirs.extend(collect_dist_info(req.key))
        dirs.append((distrib.egg_info, join('Lib', basename(distrib.egg_info))))
    return dirs

setup(
    # ...
    executables=[Executable('program.py')],
    options={
        "build_exe": {
            "packages": [
                # ...
                "pkg_resources",
            ],
            "include_files": collect_dist_info("other_package"),
        },
    },
)
```

**Comment by marcelotduarte** [comment]
The patch #481 resolves this issue, and the workaround is not necessary anymore.

**Comment by divyaksh-shukla** [comment]
```powershell
Traceback (most recent call last):
  File "C:\Users\dshukla\AppData\Local\Programs\Python\Python36\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
    module.run()
  File "C:\Users\dshukla\AppData\Local\Programs\Python\Python36\Lib\site-packages\cx_Freeze\initscripts\Console.py", line 37, in run
    exec(code, {'__name__': '__main__'})
  File "ttk_gui.py", line 8, in <module>
  File "C:\Users\dshukla\OneDrive - Itron\Documents\Coding\python_programs\simpy\build\exe.win-amd64-3.6\movie_theatre.py", line 4, in <module>
    import simpy
  File "C:\Users\dshukla\AppData\Local\Programs\Python\Python36\Lib\site-packages\simpy\__init__.py", line 65, in <module>
    __version__: str = get_distribution('simpy').version
  File "C:\Users\dshukla\AppData\Local\Programs\Python\Python36\Lib\site-packages\pkg_resources\__init__.py", line 557, in get_distribution
    dist = get_provider(dist)
  File "C:\Users\dshukla\AppData\Local\Programs\Python\Python36\Lib\site-packages\pkg_resources\__init__.py", line 431, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "C:\Users\dshukla\AppData\Local\Programs\Python\Python36\Lib\site-packages\pkg_resources\__init__.py", line 967, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Users\dshukla\AppData\Local\Programs\Python\Python36\Lib\site-packages\pkg_resources\__init__.py", line 853, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'simpy' distribution was not found and is required by the application
```

I'm still getting the same issue even after the fix. 
Here is my setup.py
```python
from cx_Freeze import setup, Executable

# Dependencies are automatically detected, but it might need
# fine tuning.
buildOptions = dict(
    packages = ["tkinter", "tkinter.font", "imp", "sys", "os", "simpy"], 
    excludes = [], 
    includes = ["simpy"],
    include_files = [".\movie_theatre.py"]
    )

import sys
base = 'Win32GUI' if sys.platform=='win32' else None

executables = [
    Executable('ttk_gui.py', base=base)
]

setup(name='Movie Theater Simulator',
      version = '1.0',
      description = 'Simple Simulation Program',
      options = dict(build_exe = buildOptions),
      executables = executables)

```

**Comment by marcelotduarte** [comment]
@divyaksh-shukla PR #608 should resolve your issue.
Can you test the PR? (only if you have a C compiler)

`pip install -U git+https://github.com/anthony-tuininga/cx_Freeze.git@refs/pull/608/head`

**Comment by divyaksh-shukla** [comment]
Thank you for the fix, this fix works on windows and linux. How come This is not standard for cx_freeze. It took me some time to setup c++ on my windows device I use for work. But, in the end it works

**Comment by marcelotduarte** [comment]
@divyaksh-shukla I believe that this feature will be in the next release.

**Comment by marcelotduarte** [comment]
@divyaksh-shukla my PR was merged and will be in the next release.
In the meantime use:
`pip install -U git+https://github.com/anthony-tuininga/cx_Freeze.git@master`

**Comment by FlyingThunder** [comment]
Hello, sorry for thread necromancy, i followed the suggestion of the last comment using `pip install -U git+https://github.com/anthony-tuininga/cx_Freeze.git@master`

but im still getting the following error:


![grafik](https://user-images.githubusercontent.com/39583733/97357022-6cd6a000-1899-11eb-8c19-db2caaa22ad7.png)

**Comment by marcelotduarte** [comment]
@FlyingThunder You can use the new cx-Freeze 6.3 version, using:
pip install -U cx-freeze

And, I think your problem is not related to this thread.

**Comment by FlyingThunder** [comment]
i already am using 6.3, i just saw that it has something to do with pkg_resources, but i dont know what that is or why it causes a problem, but i *think* as far as i understood the issue is that cx_freeze doesnt include subpackages or something? and in my case audioclipextractor also needs this pkg_resource? i dont know man, i couldnt find anything else to solve this issue and it only appears on one machine, not on the other :/

EDIT: for the poor souls who found this thread by googling like me, i solved it by `pip install --upgrade setuptools`

**Comment by marcelotduarte** [comment]
@FlyingThunder open a new issue with information about OS, pip list, etc...
