### ISSUE TITLE
cx_Freeze fails to include namespace package

### ISSUE THREAD

**Issue by MarcelBeining** [marcelotduarte/cx_Freeze#448]
When I try to include a library to a build which contains a namespace package (here discord.ext from [discord.py](https://github.com/Rapptz/discord.py) library), cx_Freeze fails to include the content of that namespace package in the build.
The way the library is set up is

```
discord/
    __init__.py
   .....
    ext/
        commands/
            __init__.py
            ......
```
So something like `from discord.ext.commands import Bot` works in Python.

In the build made by cx_Freeze the folder `lib/discord/ext/commands` exists but with no content, so the command fails in the build then.

I then tried to add `discord.ext` or `discord.ext.commands` to either `packages` or `namespace_packages` of cx_Freeze options, like this:

```
from cx_Freeze import setup, Executables
executables = [Executable("main.py", base=None)]
options = {
    'build_exe': {    
        'packages':packages,  # discord.ext or discord.ext.commands added here
        'namespace_packages': nspackages,  # or here
	},
}
setup(
    name = "program",
    options = options,
    executables = executables
)
```
But when I do this I get an import error during building: 
```
Traceback (most recent call last):
  File "setup.py", line 55, in <module>
    executables = executables
  File "C:\ProgramData\Anaconda3\lib\site-packages\cx_Freeze\dist.py", line 349, in setup
    distutils.core.setup(**attrs)
  File "C:\ProgramData\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\cx_Freeze\dist.py", line 219, in run
    freezer.Freeze()
  File "C:\ProgramData\Anaconda3\lib\site-packages\cx_Freeze\freezer.py", line 616, in Freeze
    self.finder = self._GetModuleFinder()
  File "C:\ProgramData\Anaconda3\lib\site-packages\cx_Freeze\freezer.py", line 337, in _GetModuleFinder
    package = finder.IncludeModule(name, namespace = True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\cx_Freeze\finder.py", line 651, in IncludeModule
    namespace = namespace)
  File "C:\ProgramData\Anaconda3\lib\site-packages\cx_Freeze\finder.py", line 351, in _ImportModule
    raise ImportError("No module named %r" % name)
ImportError: No module named 'discord.ext'
```

I posted this issue at discord.py ([here](https://github.com/Rapptz/discord.py/issues/1769)) but they say it is an issue with cx_Freeze as building egg etc works.
Hope you can help me with this!

**Comment by TheoMathurin** [comment]
Is the corresponding folder in your `path`? I don't know if you've provided only a portion of your code but I don't see a `path` variable passed in `options`.

I'm having a similar issue. In my case I don't have the `ImportError` when building but the package is not copied to `build/lib`, whether I add the module to `'packages'` or `'namespace_packages'`.

Does anyone have an idea?

**Comment by marcelotduarte** [comment]
https://github.com/googleapis/google-cloud-python/issues/7804#issuecomment-508652004
