### ISSUE TITLE
I am having trouble with cx_Freeze unable to find a submodule and it gives me an Importerror!

### ISSUE THREAD

**Issue by prithvidiamond1** [marcelotduarte/cx_Freeze#456]
Hi,
my problem goes as follows, when I run my cx_Freeze script I get this message in command prompt:
C:\Users\user\Desktop\Python\64-bit\PROJECTS\GAMES\CubeDASH!>python setup.py build
running build
running build_exe
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    executables=executables
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cx_Freeze\dist.py", line 349, in setup
    distutils.core.setup(**attrs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cx_Freeze\dist.py", line 219, in run
    freezer.Freeze()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cx_Freeze\freezer.py", line 624, in Freeze
    self.finder = self._GetModuleFinder()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cx_Freeze\freezer.py", line 347, in _GetModuleFinder
    finder.IncludePackage(name)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cx_Freeze\finder.py", line 661, in IncludePackage
    self._ImportAllSubModules(module, deferredImports)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cx_Freeze\finder.py", line 288, in _ImportAllSubModules
    recursive)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cx_Freeze\finder.py", line 288, in _ImportAllSubModules
    recursive)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cx_Freeze\finder.py", line 283, in _ImportAllSubModules
    raise ImportError("No module named %r" % subModuleName)
ImportError: No module named 'OpenGL.GL.SGIX.async'

But i can clearly find this file and it is located under:
C:\Users\user\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\OpenGL\GL\SGIX\async.py

So I have no idea what to do, I am newbie when it comes to this cx_Freeze stuff and all I wanted to do was show my friends who aren't into programming my new PyOpenGL game I made!

So appreciate if anybody has any solutions or suggestions to this problem.

**Comment by tamenol** [comment]
Downgrade to Python3.5. I had similar problems with import errors and not finding .dll files when using python3.7. I downgraded to 3.5 and had no more problems

**Comment by marcelotduarte** [comment]
Would you like to test the same project in Python 3.7 using the current master?

**Comment by prithvidiamond1** [comment]
sure, I will try that and let you guys know

**Comment by marcelotduarte** [comment]
@prithvidiamond1 cx_Freeeze 6 has been released. You can try it out.

**Comment by prithvidiamond1** [comment]
Oh, OK I will do that then.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
