### ISSUE TITLE
python3.7 ValueError: FCI error 1 ?

### ISSUE THREAD

**Issue by jekoie** [marcelotduarte/cx_Freeze#527]
### hi, i write a pyqt5 gui app and run it at python3.7 it run errors;my cx_freeze is version 6.0
`code sample is here:`
```python
build_exe_options = {
    'include_files': ['./app' , './config', './doc', './image', './product', './setting', './ui'],
    'excludes':['IPython', 'jupyter_client', 'ipykernel', 'jedi', 'jinjia2', 'jupyter_core', 'nbconvert',
                'ipython_genutils', 'nbformat', 'notebook', 'pandas', 'numpy', 'faker'],
    'include_msvcr': True,
    }
```
`errors:`
```
copying build\exe.win32-3.7\Motor.exe -> build\bdist.win32\msi
Traceback (most recent call last):
  File ".\setup.py", line 75, in <module>
    executables = executables,
  File "C:\Users\jekoie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cx_freeze-6.0-py3.7-win32.egg\cx_Freeze\dist.py", line 348, in setup
    distutils.core.setup(**attrs)
  File "C:\Users\jekoie\AppData\Local\Programs\Python\Python37-32\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\jekoie\AppData\Local\Programs\Python\Python37-32\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\jekoie\AppData\Local\Programs\Python\Python37-32\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\jekoie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cx_freeze-6.0-py3.7-win32.egg\cx_Freeze\windist.py", line 416, in run
    self.add_files()
  File "C:\Users\jekoie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cx_freeze-6.0-py3.7-win32.egg\cx_Freeze\windist.py", line 139, in add_files
    cab.commit(db)
  File "C:\Users\jekoie\AppData\Local\Programs\Python\Python37-32\lib\msilib\__init__.py", line 215, in commit
    FCICreate(filename, self.files)
ValueError: FCI error 1
```

**Comment by marcelotduarte** [comment]
cx_Freeze 6.5 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
