### ISSUE TITLE
Multiprocessing/Pickling Error

### ISSUE THREAD

**Issue by dakenblack** [marcelotduarte/cx_Freeze#539]
I have a simple script that runs a parallelized operation using a pool of workers as below (execute.py)
```
    from multiprocessing import Pool, freeze_support
    from functools import partial
    from itertools import repeat
    import pickle
    import dill
    
    def product(x, y):
        return x * y
    
    
    if __name__ == '__main__':
        freeze_support()
        
        pool = Pool(processes=6)
        
        # Both calls below do not work in frozen mode
        a = pool.map(partial(product, y=3), range(12))
        # a = pool.starmap(product, zip(range(12), repeat(3)))
        print(a)
        
        # pickling routines from pickle and dill also do not work when frozen
        # d = pickle.dumps(product)
        # d = dill.dumps(product)
        # print(d)
```

When I run using `python execute.py` I get the following output (as expected)
`[0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33]`

However when I try to freeze the script and run it
```
python .\setup.py build
.\build\exe.win-amd64-3.7\execute.exe
```

I get the following error:
```
Traceback (most recent call last):
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
    module.run()
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\site-packages\cx_Freeze\initscripts\Console.py", line 23, in run
    exec(code, {'__name__': '__main__'})
  File "execute.py", line 29, in <module>
    a = pool.map(partial(product, y=3), range(12))
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\multiprocessing\pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\multiprocessing\pool.py", line 431, in _handle_tasks
    put(task)
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\multiprocessing\connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function product at 0x0000024711BA7EE8>: attribute lookup product on __main__ failed
```

The starmap call from the script also yields the exact same result. Both pickling operations also do not work in the frozen application.
Here are the outputs:

```
Traceback (most recent call last):
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
    module.run()
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\site-packages\cx_Freeze\initscripts\Console.py", line 23, in run
    exec(code, {'__name__': '__main__'})
  File "execute.py", line 34, in <module>
    d = pickle.dumps(product)
_pickle.PicklingError: Can't pickle <function product at 0x0000023AE0D67EE8>: attribute lookup product on __main__ failed
```

```
Traceback (most recent call last):
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
    module.run()
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\site-packages\cx_Freeze\initscripts\Console.py", line 23, in run
    exec(code, {'__name__': '__main__'})
  File "execute.py", line 35, in <module>
    d = dill.dumps(product)
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\site-packages\dill\_dill.py", line 265, in dumps
    dump(obj, file, protocol, byref, fmode, recurse, **kwds)#, strictio)
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\site-packages\dill\_dill.py", line 259, in dump
    Pickler(file, protocol, **_kwds).dump(obj)
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\site-packages\dill\_dill.py", line 445, in dump
    StockPickler.dump(self, obj)
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\pickle.py", line 437, in dump
    self.save(obj)
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\site-packages\dill\_dill.py", line 1413, in save_function
    obj.__dict__, fkwdefaults), obj=obj)
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\pickle.py", line 638, in save_reduce
    save(args)
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\pickle.py", line 789, in save_tuple
    save(element)
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\site-packages\dill\_dill.py", line 912, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\pickle.py", line 885, in _batch_setitems
    save(v)
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\site-packages\dill\_dill.py", line 1295, in save_module
    state=_main_dict)
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\pickle.py", line 662, in save_reduce
    save(state)
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\site-packages\dill\_dill.py", line 912, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\pickle.py", line 885, in _batch_setitems
    save(v)
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\pickle.py", line 662, in save_reduce
    save(state)
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\site-packages\dill\_dill.py", line 912, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\pickle.py", line 885, in _batch_setitems
    save(v)
  File "C:\Users\jabez\AppData\Local\Continuum\miniconda3\envs\FreezeTest\lib\pickle.py", line 524, in save
    rv = reduce(self.proto)
TypeError: can't pickle zipimport.zipimporter objects
```

Here is the setup script I used:
```
from cx_Freeze import setup, Executable
import sys
from pathlib import Path
import os

# Dependencies are automatically detected, but it might need
# fine tuning.
buildOptions = dict(packages = [], excludes = ['sqlite3'])

base = 'Console'

executables = [
    Executable('execute.py', base=base)
]

setup(name='Test',
      version = '1.0',
      description = 'Test Multiprocessing',
      options = dict(build_exe = buildOptions),
      executables = executables)

# This is just to rename the Pool.pyc to pool.pyc
# https://github.com/anthony-tuininga/cx_Freeze/issues/353
if sys.argv[1] == 'build':
    BUILD_PATH_POOL = os.path.join('.','build','exe.win-amd64-3.7','lib','multiprocessing')
    Path(os.path.join(BUILD_PATH_POOL, 'Pool.pyc')).rename(os.path.join(BUILD_PATH_POOL, 'pool.pyc'))
    print(os.path.join(BUILD_PATH_POOL, 'Pool.pyc'), ' -> ', os.path.join(BUILD_PATH_POOL, 'pool.pyc'))
```

and here is all the packages I've installed in this fresh conda environment:
```
certifi==2019.11.28
cx-Freeze==6.0
dill==0.3.1.1
mkl-fft==1.0.15
mkl-random==1.1.0
mkl-service==2.3.0
numpy==1.17.4
pyreadline==2.1
six==1.13.0
wincertstore==0.2
```

I feel I've googled a lot but haven't come up with anything, any ideas would be very helpful. I'm also thinking I should post in the multiprocessing/pickle forums as well. let me know if this is not the right place.

**Comment by dakenblack** [comment]
Some more information:
```
(FreezeTest) PS C:\Users\jabez> conda --version
conda 4.8.0
(FreezeTest) PS C:\Users\jabez> python --version
Python 3.7.5
(FreezeTest) PS C:\Users\jabez>
```

Running Win10 Pro

**Comment by janM37** [comment]
Hi, 
I'm facing the exact same issue (running python 3.6.8).
The simple script :
```
import multiprocessing as mp

def f():
    print('hello world!')

if __name__ == '__main__':
    mp.freeze_support()
    try:
        mp.Process(target=f).start()
    except Exception as ex:
        print(ex)
    go = input("Press any key to exit . . .")
```
Results into : 
`Can't pickle <function f at 0x000001BF926B2F28>: attribute lookup f on __main__ failed`

The `freeze_support` function also returns : 
```
  File "C:\Users\m\AppData\Local\Programs\Python\Python36\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
    module.run()
  File "C:\Users\m\AppData\Local\Programs\Python\Python36\lib\site-packages\cx_Freeze\initscripts\Console.py", line 37, in run
    exec(code, {'__name__': '__main__'})
  File "test.py", line 7, in <module>
  File "C:\Users\m\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 149, in freeze_support
    freeze_support()
  File "C:\Users\m\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 74, in freeze_support
    spawn_main(**kwds)
  File "C:\Users\mAppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\m\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```

And of course, the code works when it is not frozen.
Did you find any solution to this?

**Comment by dakenblack** [comment]
Hi @janM37 ,
Sorry didn't realise anyone was still looking at this. A few days after I posted this, I realised that I no longer needed to freeze my application; so I stopped looking into it. 

The issue seems to be the pickling operation, but I don't know enough of python or multiprocessing to fix it or provide any further insight.

**Comment by janM37** [comment]
Hi @dakenblack ,
Thanks for your answer. I did not find a fix either, but FYI, this issue does not appear using pyInstaller. So it seems cxFreeze is involved in this somehow.

**Comment by marcelotduarte** [comment]
See PR #622, tested with the sample in https://github.com/anthony-tuininga/cx_Freeze/issues/539#issuecomment-588171794 provided by @janM37

**Comment by marcelotduarte** [comment]
Can you test the PR? (only if you have a C compiler)

`pip install -U git+https://github.com/anthony-tuininga/cx_Freeze.git@refs/pull/622/head`

**Comment by dakenblack** [comment]
@marcelotduarte
Oh thanks I'll test it out, I just have to find my old files.

**Comment by dakenblack** [comment]
I can confirm that I no longer have the issue. Thanks for the PR @marcelotduarte

**Comment by Ranjith3436** [comment]
I also faced this issue. Switched to ThreadPoolExecutor: This avoids the pickling issue that occurs with ProcessPoolExecutor.
