### ISSUE TITLE
TypeError: an integer is required (got type bytes)

### ISSUE THREAD

**Issue by Berserker66** [marcelotduarte/cx_Freeze#543]
Python 3.8.1 on Windows 10 64Bit, using as of posting this current git cx_Freeze

requirements file for the project:

```
appdirs>=1.4.3
argon2_cffi>=19.2.0
colorama>=0.4.3
cx-Freeze>=6.0
openpyxl>=3.0.2
python-dateutil>=2.8.1
screeninfo>=0.6.1
jinja2>=2.10.3
PyNaCl>=1.3.0
cython>=0.29.14
passlib>=1.7.2
psutil==5.6.7
pywin32>=227; sys_platform == 'win32'
PySide2==5.14.0
PyYAML>=5.2
colour>=0.1.5
holidays>=0.9.11
tableprint>=0.8.0
pyodbc>=4.0.27
json_tricks>=3.13.4
```

```
Outputting to: build\exe.win-amd64-3.8
running build_exe
Traceback (most recent call last):
  File "E:/ConParser/setup.py", line 110, in <module>
    cx_Freeze.setup(
  File "C:\Program Files\Python38\lib\site-packages\cx_Freeze\dist.py", line 348, in setup
    distutils.core.setup(**attrs)
  File "C:\Program Files\Python38\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Program Files\Python38\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Program Files\Python38\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Program Files\Python38\lib\site-packages\cx_Freeze\dist.py", line 219, in run
    freezer.Freeze()
  File "C:\Program Files\Python38\lib\site-packages\cx_Freeze\freezer.py", line 641, in Freeze
    self.finder = self._GetModuleFinder()
  File "C:\Program Files\Python38\lib\site-packages\cx_Freeze\freezer.py", line 362, in _GetModuleFinder
    finder = cx_Freeze.ModuleFinder(self.includeFiles, self.excludes,
  File "C:\Program Files\Python38\lib\site-packages\cx_Freeze\finder.py", line 141, in __init__
    self._AddBaseModules()
  File "C:\Program Files\Python38\lib\site-packages\cx_Freeze\finder.py", line 152, in _AddBaseModules
    self.IncludeModule("traceback")
  File "C:\Program Files\Python38\lib\site-packages\cx_Freeze\finder.py", line 616, in IncludeModule
    module = self._ImportModule(name, deferredImports,
  File "C:\Program Files\Python38\lib\site-packages\cx_Freeze\finder.py", line 296, in _ImportModule
    module = self._InternalImportModule(name,
  File "C:\Program Files\Python38\lib\site-packages\cx_Freeze\finder.py", line 389, in _InternalImportModule
    module = self._LoadModule(name, fp, path, info, deferredImports,
  File "C:\Program Files\Python38\lib\site-packages\cx_Freeze\finder.py", line 450, in _LoadModule
    module.code = self._ReplacePathsInCode(topLevelModule,
  File "C:\Program Files\Python38\lib\site-packages\cx_Freeze\finder.py", line 496, in _ReplacePathsInCode
    constants[i] = self._ReplacePathsInCode(topLevelModule, value)
  File "C:\Program Files\Python38\lib\site-packages\cx_Freeze\finder.py", line 499, in _ReplacePathsInCode
    return types.CodeType(co.co_argcount, co.co_kwonlyargcount,
TypeError: an integer is required (got type bytes)

Process finished with exit code 1

```

**Comment by marcelotduarte** [comment]
What you have in 'File "E:/ConParser/setup.py", line 110'?

**Comment by Berserker66** [comment]
```
cx_Freeze.setup(
    name="HonorarPlus",
    version=f"{buildtime.year}.{buildtime.month}.{buildtime.day}.{buildtime.hour}",
    description="HonorarPlus",
    executables=[EXE, EXE2, EXEDEBUG, EXE3, EXESTRIPPER, EXEDAK],
    options={
        "build_exe": {
            "excludes": excludes,
            "packages": packages,
            "includes": ("PySide2.QtNetwork", "PySide2.QtWebEngineCore",
                         "PySide2.QtWebChannel", "PySide2.QtPrintSupport",
                         "PySide2.QtXml"),
            "zip_include_packages": ["*"],
            "zip_exclude_packages": [],
            "include_files": [],
            "include_msvcr": True,
            "replace_paths": [("*", "")],
            "optimize": 2,
            "build_exe": buildfolder
        },
    },
)
```

It should be noted, that the same setup works under 3.7

**Comment by marcelotduarte** [comment]
workaround: build without the replace_paths.
PR #545 solve the issue.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
