### ISSUE TITLE
incompatible with aioconsole

### ISSUE THREAD

**Issue by Berserker66** [marcelotduarte/cx_Freeze#578]
```
Traceback (most recent call last):
  File "__startup__.py", line 40, in run
  File "Console.py", line 37, in run
  File "MultiClient.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "aioconsole\__init__.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "aioconsole\code.py", line 36, in <module>
  File "aioconsole\code.py", line 67, in AsynchronousConsole
NameError: name 'help' is not defined
```

Line 67 in aioconsole is:

```
    @functools.wraps(help)
    def help(self, obj):
        self.print(pydoc.render_doc(obj))
```

**Comment by marcelotduarte** [comment]
This issue is similar to #1937 
The upstream has a workaround (https://github.com/vxgmichel/aioconsole/pull/61) since v0.1.16
