### ISSUE TITLE
Python 3.3.3 + freeze_support()

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#60]
Originally reported by: **AcidWeb (Bitbucket: [AcidWeb](https://bitbucket.org/AcidWeb), GitHub: [AcidWeb](https://github.com/AcidWeb))**

----------------------------------------

Every fork on Windows (Not tested other OS) created in frozen code generate error on end of his life.

```
#!

Traceback (most recent call last):
  File "C:\Python33_64\lib\site-packages\cx_freeze-4.3.2-py3.3-win-amd64.egg\cx_Freeze\initscripts\Console3.py", line 27, in <module>
    exec(code, m.__dict__)
  File "X.py", line 155, in <module>
  File "C:\Python33_64\lib\multiprocessing\__init__.py", line 119, in freeze_support
    freeze_support()
  File "C:\Python33_64\lib\multiprocessing\forking.py", line 307, in freeze_support
    main()
  File "C:\Python33_64\lib\multiprocessing\forking.py", line 356, in main
    exitcode = self._bootstrap()
  File "C:\Python33_64\lib\multiprocessing\process.py", line 278, in _bootstrap
    sys.stdout.flush()
AttributeError: 'NoneType' object has no attribute 'flush'
```

Removing both flushes from _bootstrap from multiprocessing\process.py suppress this error.

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/60

**Comment by anthony-tuininga** [comment]
*Original comment by* **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**:

----------------------------------------

It looks like multiprocessing assumes that the process has stdout and stderr, which is not true for a Windows GUI application. It's not clear whether the problem is with multiprocessing for not handling that case, or with cx_Freeze for not providing dummy stdout/stderr objects.

You can probably work around it by setting sys.stdout and sys.stderr to some objects with no-op `flush` and `write` methods in your 'forked' processes (Windows doesn't really have fork, but multiprocessing tries to emulate it)

**Comment by anthony-tuininga** [comment]
*Original comment by* **AcidWeb (Bitbucket: [AcidWeb](https://bitbucket.org/AcidWeb), GitHub: [AcidWeb](https://github.com/AcidWeb))**:

----------------------------------------

Lack of stderr also break HTTPServer class.

I'm using ThreadingMixIn + HTTPServer started from QThread.

**Comment by anthony-tuininga** [comment]
*Original comment by* **AcidWeb (Bitbucket: [AcidWeb](https://bitbucket.org/AcidWeb), GitHub: [AcidWeb](https://github.com/AcidWeb))**:

----------------------------------------

I'm confirming that replacing *sys.stdout* and *sys.stderr* with dummy object when code run on Windows and *getattr(sys, 'frozen', False)* is working workaround for this issue.
```
#!python
class fakestd(object):
    def write(self, string):
        pass

    def flush(self):
        pass
```

**Comment by anthony-tuininga** [comment]
*Original comment by* **olutayo (Bitbucket: [olutayo](https://bitbucket.org/olutayo), GitHub: [olutayo](https://github.com/olutayo))**:

----------------------------------------

In my case as stated [here](#76/multiprocessing-module-freeze-succefully), it got freeze without error but did not work as it should be. It works well before freeezing. So the problem should be with cx_Freeze

**Comment by anthony-tuininga** [comment]
*Original comment by* **AcidWeb (Bitbucket: [AcidWeb](https://bitbucket.org/AcidWeb), GitHub: [AcidWeb](https://github.com/AcidWeb))**:

----------------------------------------

Well in my case it was not directly fault of cx_freeze but general behavior of frozen code.

**Comment by anthony-tuininga** [comment]
*Original comment by* **olutayo (Bitbucket: [olutayo](https://bitbucket.org/olutayo), GitHub: [olutayo](https://github.com/olutayo))**:

----------------------------------------

Oh, it the freezing of **multiprocessing** itself. So **freeze_support()** solved the problem.
Details [here](#76/multiprocessing-module-freeze-succefully).

Thanks

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anthony Tuininga (Bitbucket: [anthony_tuininga](https://bitbucket.org/anthony_tuininga), GitHub: Unknown)**:

----------------------------------------

As noted in the comments this issue was resolved externally in the multiprocessing module.

**Comment by anthony-tuininga** [comment]
*Original comment by* **AcidWeb (Bitbucket: [AcidWeb](https://bitbucket.org/AcidWeb), GitHub: [AcidWeb](https://github.com/AcidWeb))**:

----------------------------------------

freeze_support() don't fix this issue alone. He was talking about his error. Not tested Python 3.4 but other 3.x still need fake sys.stdout/sys.stderr on Windows.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anthony Tuininga (Bitbucket: [anthony_tuininga](https://bitbucket.org/anthony_tuininga), GitHub: Unknown)**:

----------------------------------------

Attempting to write to sys.stdout and sys.stderr with Win32GUI is a "known" issue which Microsoft has no intentions of "fixing". You can use a console application to avoid this issue or the location where the attempt to write to sys.stdout has to be adjusted to write to a different location. A workaround is indeed to create a fake stdout but I'm not sure what cx_Freeze should do in this case, if anything. What did you have in mind?

**Comment by anthony-tuininga** [comment]
*Original comment by* **AcidWeb (Bitbucket: [AcidWeb](https://bitbucket.org/AcidWeb), GitHub: [AcidWeb](https://github.com/AcidWeb))**:

----------------------------------------

I'm not saying that is cx_Freeze bug and something need to be done :-)

Just leaving a comment for anybody might reading this so they will not be confused by sadeeb response.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anthony Tuininga (Bitbucket: [anthony_tuininga](https://bitbucket.org/anthony_tuininga), GitHub: Unknown)**:

----------------------------------------

Ah, that makes sense. Thanks for the clarification.

**Comment by anthony-tuininga** [comment]
*Original comment by* **olutayo (Bitbucket: [olutayo](https://bitbucket.org/olutayo), GitHub: [olutayo](https://github.com/olutayo))**:

----------------------------------------

AcidWeb, I do not mean to confuse anybody as you stated. I only share what resolved my issue.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Boris Dayma (Bitbucket: [koushkov](https://bitbucket.org/koushkov), GitHub: Unknown)**:

----------------------------------------

Hi AcidWeb, I am having the same problem and your solution seems that it would solve it.
Could you please share the code you would use on the dummy class you provided, ie how you would implement it exactly?
Thanks
