### ISSUE TITLE
 No module named 'pkg_resources'

### ISSUE THREAD

**Issue by calendulish** [marcelotduarte/cx_Freeze#607]
After update cx_freeze to 6.1 build is not finding pkg_resources

```
running build_scripts
creating build\scripts-3.8
copying and adjusting test.py -> build\scripts-3.8
running build_exe
Traceback (most recent call last):
  File "./setup.py", line 236, in <module>
    setup(
  File "E:\msys2_64\mingw64\lib\python3.8\site-packages\cx_Freeze\dist.py", line 340, in setup
    distutils.core.setup(**attrs)
  File "E:\msys2_64\mingw64\lib\python3.8\distutils\core.py", line 148, in setup                                                                                                                                                                                         [10/9792]
    dist.run_commands()
  File "E:\msys2_64\mingw64\lib\python3.8\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "E:\msys2_64\mingw64\lib\python3.8\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "E:\msys2_64\mingw64\lib\python3.8\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "E:\msys2_64\mingw64\lib\python3.8\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "E:\msys2_64\mingw64\lib\python3.8\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "E:\msys2_64\mingw64\lib\python3.8\site-packages\cx_Freeze\dist.py", line 211, in run
    freezer.Freeze()
  File "E:\msys2_64\mingw64\lib\python3.8\site-packages\cx_Freeze\freezer.py", line 610, in Freeze
    self.finder = self._GetModuleFinder()
  File "E:\msys2_64\mingw64\lib\python3.8\site-packages\cx_Freeze\freezer.py", line 356, in _GetModuleFinder
    finder.IncludePackage(name)
  File "E:\msys2_64\mingw64\lib\python3.8\site-packages\cx_Freeze\finder.py", line 640, in IncludePackage
    module = self._ImportModule(name, deferredImports)
  File "E:\msys2_64\mingw64\lib\python3.8\site-packages\cx_Freeze\finder.py", line 348, in _ImportModule
    raise ImportError("No module named %r" % name)
ImportError: No module named 'pkg_resources'
```

The module is available

```
Python 3.8.2 (default, Feb 27 2020, 05:27:33)  [GCC 9.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pkg_resources
>>> dir(pkg_resources)
['AvailableDistributions', 'BINARY_DIST', 'CHECKOUT_DIST', 'ContextualVersionConflict', 'DEVELOP_DIST', 'DefaultProvider', 'DistInfoDistribution', 'Distribution', 'DistributionNotFound', 'EGG_DIST', 'EGG_NAME', 'EggInfoDistribution', 'EggMetadata', 'EggProvider', 'EmptyProvider', 'EntryPoint', 'Environment', 'ExtractionError', 'FileMetadata', 'IMetadataProvider', 'IResourceProvider', 'MODULE', 'MemoizedZipManifests', 'NoDists', 'NullProvider', 'PEP440Warning', 'PY_MAJOR', 'PathMetadata', 'PkgResourcesDeprecationWarning', 'Requirement', 'RequirementParseError', 'ResolutionError', 'ResourceManager', 'SOURCE_DIST', 'UnknownExtra', 'VersionConflict', 'WRITE_SUPPORT', 'WorkingSet', 'ZipManifests', 'ZipProvider', '_ReqExtras', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__getstate__', '__loader__', '__metaclass__', '__name__', '__package__', '__path__', '__setstate__', '__spec__', '_always_object', '_by_version_descending', '_bypass_ensure_directory', '_call_aside', '_cygwin_patch', '_declare_state', '_distributionImpl', '_distribution_finders', '_find_adapter', '_handle_ns', '_imp', '_initialize', '_initialize_master_working_set', '_is_egg_path', '_is_unpacked_egg', '_macosx_arch', '_macosx_vers', '_manager', '_mkstemp', '_namespace_handlers', '_namespace_packages', '_normalize_cached', '_provider_factories', '_rebuild_mod_path', '_remove_md5_fragment', '_set_parent_ns', '_sget_dict', '_sget_none', '_sget_object', '_sset_dict', '_sset_none', '_sset_object', '_state_vars', '_version_from_file', 'absolute_import', 'add_activation_listener', 'appdirs', 'cached_files', 'cleanup_resources', 'collections', 'compatible_platforms', 'darwinVersionString', 'declare_namespace', 'dist_factory', 'distributions_from_metadata', 'email', 'empty_provider', 'ensure_directory', 'errno', 'evaluate_marker', 'extraction_error', 'extraction_path', 'file_ns_handler', 'filter', 'find_distributions', 'find_eggs_in_zip', 'find_nothing', 'find_on_path', 'fixup_namespace_packages', 'functools', 'get_build_platform', 'get_cache_path', 'get_default_cache', 'get_distribution', 'get_entry_info', 'get_entry_map', 'get_importer', 'get_platform', 'get_provider', 'get_supported_platform', 'importlib_machinery', 'inspect', 'invalid_marker', 'io', 'isdir', 'issue_warning', 'iter_entry_points', 'itertools', 'load_entry_point', 'macosVersionString', 'map', 'mkdir', 'non_empty_lines', 'normalize_path', 'ntpath', 'null_ns_handler', 'operator', 'os', 'os_open', 'packaging', 'parse_requirements', 'parse_version', 'pkgutil', 'platform', 'plistlib', 'posixpath', 'postprocess', 'py2_warn', 'py31compat', 're', 'register_finder', 'register_loader_type', 'register_namespace_handler', 'rename', 'require', 'resolve_egg_link', 'resource_dir', 'resource_exists', 'resource_filename', 'resource_isdir', 'resource_listdir', 'resource_stream', 'resource_string', 'resources_stream', 'run_main', 'run_script', 'safe_extra', 'safe_listdir', 'safe_name', 'safe_version', 'set_extraction_path', 'six', 'split', 'split_sections', 'stat', 'sys', 'tempfile', 'textwrap', 'time', 'to_filename', 'types', 'unlink', 'urllib', 'utime', 'warnings', 'working_set', 'yield_lines', 'zipfile', 'zipimport']
>>> exit()
```

**Comment by marcelotduarte** [comment]
Can you test with the master?
pip install -U git+https://github.com/anthony-tuininga/cx_Freeze.git@master

**Comment by calendulish** [comment]
git version is working. Nothing to do here, thanks.
