### ISSUE TITLE
LookupError: unknown encoding: idna

### ISSUE THREAD

**Issue by mcauto** [marcelotduarte/cx_Freeze#610]
OS: python:3.7-alpine3.8 docker image

```bash
pip list | grep cx
cx-Freeze          6.1
```

```python
future: <Task finished coro=<NetworkScanner._run_in_executor() done, defined at /code/app/scanner/__init__.py:69> exception=LookupError('unknown encoding: idna')>
Traceback (most recent call last):
  File "/code/app/scanner/__init__.py", line 73, in _run_in_executor
    return await loop.run_in_executor(None, func)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/code/app/scanner/http_scanner.py", line 74, in __http_scan
    conn.request(method='GET', url='/')
  File "/usr/local/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/local/lib/python3.7/http/client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
LookupError: unknown encoding: idna
```

**Comment by mcauto** [comment]
```python
import encodings.idna
```
It works on me.
