### ISSUE TITLE
ModuleNotFoundError: No module named 'ruamel'

### ISSUE THREAD

**Issue by tgirardsidel** [marcelotduarte/cx_Freeze#612]
Hi !

First, thanks for your work !

When I want to execute the build program I have this : 

```
$ build\exe.win-amd64-3.7\upload_camera_file.exe up
Traceback (most recent call last):
  File "C:\Users\255964\AppData\Local\Programs\Python\Python37\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
    module.run()
  File "C:\Users\255964\AppData\Local\Programs\Python\Python37\lib\site-packages\cx_Freeze\initscripts\Console.py", line 37, in run
    exec(code, {'__name__': '__main__'})
  File "upload_camera_file.py", line 8, in <module>
    from ruamel.yaml import YAML
ModuleNotFoundError: No module named 'ruamel'
```

According issue #581 I add `ruamel` (or `ruamel.yaml` but same error) in include build options : 

```
from cx_Freeze import setup, Executable

# Dependencies are automatically detected, but it might need
# fine tuning.
buildOptions = dict(packages=[], excludes=[], includes=['ruamel'])

base = 'Console'

executables = [
    Executable('upload_camera_file.py', base=base)
]

setup(name='upload_camera_file',
      version='1.0',
      description='Program for upload files into the camera',
      options=dict(build_exe=buildOptions),
      executables=executables)
```

But when I build, I have this error : 
```
python setup.py build
running build
running build_exe
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    executables=executables)
  File "C:\Users\255964\AppData\Local\Programs\Python\Python37\lib\site-packages\cx_Freeze\dist.py", line 340, in setup
    distutils.core.setup(**attrs)
  File "C:\Users\255964\AppData\Local\Programs\Python\Python37\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\255964\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\255964\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\255964\AppData\Local\Programs\Python\Python37\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\Users\255964\AppData\Local\Programs\Python\Python37\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\255964\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\255964\AppData\Local\Programs\Python\Python37\lib\site-packages\cx_Freeze\dist.py", line 211, in run
    freezer.Freeze()
  File "C:\Users\255964\AppData\Local\Programs\Python\Python37\lib\site-packages\cx_Freeze\freezer.py", line 610, in Freeze
    self.finder = self._GetModuleFinder()
  File "C:\Users\255964\AppData\Local\Programs\Python\Python37\lib\site-packages\cx_Freeze\freezer.py", line 354, in _GetModuleFinder
    finder.IncludeModule(name)
  File "C:\Users\255964\AppData\Local\Programs\Python\Python37\lib\site-packages\cx_Freeze\finder.py", line 632, in IncludeModule
    namespace = namespace)
  File "C:\Users\255964\AppData\Local\Programs\Python\Python37\lib\site-packages\cx_Freeze\finder.py", line 348, in _ImportModule
    raise ImportError("No module named %r" % name)
ImportError: No module named 'ruamel'
```

My pip list : 
```
λ pip freeze                                                                         
argh==0.26.2                                                                         
argon2-cffi==19.1.0                                                                  
asn1crypto==0.24.0                                                                   
astroid==2.2.5                                                                       
attrs==19.1.0                                                                        
autobahn==19.6.2                                                                     
Automat==0.7.0                                                                       
bcrypt==3.1.6                                                                        
bitstring==3.1.5                                                                     
cbor==1.0.0                                                                          
cbor2==4.1.2                                                                         
certifi==2019.3.9                                                                    
cffi==1.12.3                                                                         
chardet==3.0.4                                                                       
Click==7.0                                                                           
clize==4.1.1                                                                         
colorama==0.4.1                                                                      
constantly==15.1.0                                                                   
crossbar==19.6.1                                                                     
cryptography==2.7                                                                    
cx-Freeze==6.1                                                                       
docutils==0.16                                                                       
flatbuffers==1.11                                                                    
h2==3.1.0                                                                            
hpack==3.0.0                                                                         
hyperframe==5.2.0                                                                    
hyperlink==19.0.0                                                                    
idna==2.5                                                                            
incremental==17.5.0                                                                  
isort==4.3.19                                                                        
Jinja2==2.10.1                                                                       
lazy-object-proxy==1.4.1                                                             
lmdb==0.94                                                                           
lz4==2.1.9                                                                           
MarkupSafe==1.1.1                                                                    
mccabe==0.6.1                                                                        
mistune==0.8.4                                                                       
msgpack==0.6.1                                                                       
netaddr==0.7.19                                                                      
Nuitka==0.6.3.1                                                                      
numpy==1.15.4                                                                        
od==1.0                                                                              
passlib==1.7.1                                                                       
pathtools==0.1.2                                                                     
pex==1.6.6                                                                           
priority==1.3.0                                                                      
psutil==5.6.2                                                                        
py-ubjson==0.13.0                                                                    
py2exe==0.9.2.2                                                                      
pyasn1==0.4.5                                                                        
pyasn1-modules==0.2.5                                                                
pycparser==2.19                                                                      
Pygments==2.4.0                                                                      
PyHamcrest==1.9.0                                                                    
pylint==2.3.1                                                                        
PyNaCl==1.3.0                                                                        
pyOpenSSL==19.0.0                                                                    
PyQRCode==1.2.1                                                                      
python-snappy==0.5.4                                                                 
PyTrie==0.3.1                                                                        
pywin32==224                                                                         
PyYAML==5.1                                                                          
requests==2.21.0                                                                     
requests-toolbelt==0.9.1                                                             
ruamel.yaml==0.16.10                                                                 
ruamel.yaml.clib==0.2.0                                                              
sdnotify==0.3.2                                                                      
service-identity==18.1.0                                                             
setproctitle==1.1.10                                                                 
sigtools==2.0.2                                                                      
six==1.12.0                                                                          
sortedcontainers==2.1.0                                                              
treq==18.6.0                                                                         
Twisted==19.2.0                                                                      
txaio==18.8.1                                                                        
txtorcon==19.0.0                                                                     
typed-ast==1.3.5                                                                     
u-msgpack-python==2.5.1                                                              
ujson==1.35                                                                          
UNKNOWN==0.0.0                                                                       
urllib3==1.24.3                                                                      
watchdog==0.9.0                                                                      
wrapt==1.11.1                                                                        
zlmdb==19.4.1                                                                        
zope.interface==4.6.0                                                                
```

Can you help me ? Thank you !

**Comment by marcelotduarte** [comment]
As far as I can see, this ruamel is a namespace package, so add it and put its module in includes.

buildOptions = dict(packages=[], excludes=[], includes=['ruamel.yaml'], namespace_packages=['ruamel'])

You will probably have other errors and should add other modules like this 'ruamel.yaml.clib' in includes.

**Comment by tgirardsidel** [comment]
It's work ! It's ok because I dont use `ruamel.yaml.clib`.

Thank you for your help :)
