### ISSUE TITLE
ModuleNotFoundError: No module named 'uvloop'

### ISSUE THREAD

**Issue by mcauto** [marcelotduarte/cx_Freeze#618]
Hello! It's so nice library. Thank you for your works.

I want to add uvloop with asyncio in python3.7.

help me plz

```python
build_exe_options:{
    'zip_include_packages': ["*"],
    'zip_exclude_packages': [],
    'includes': ['_cffi_backend', 'encodings.idna'], # add 'uvloop' is not working
    'namespace_packages': ['uvloop'] # this also..
}
```

```bash
Traceback (most recent call last):
  File "/root/projects/py/ims/.venv/lib/python3.7/site-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
    module.run()
  File "/root/projects/py/ims/.venv/lib/python3.7/site-packages/cx_Freeze/initscripts/Console.py", line 37, in run
    exec(code, {'__name__': '__main__'})
  File "app/__main__.py", line 12, in <module>
  File "/root/projects/py/ims/.venv/lib/python3.7/site-packages/uvloop/__init__.py", line 7, in <module>
    from .loop import Loop as __BaseLoop  # NOQA
  File "uvloop/loop.pyx", line 42, in init uvloop.loop
ImportError: cannot import name _noop
```

**Comment by marcelotduarte** [comment]
In 'includes' you should add the module 'uvloop._noop'.

**Comment by mcauto** [comment]
> In 'includes' you should add the module 'uvloop._noop'.

😅 Thank you!
