### ISSUE TITLE
Searching for dylibs in the wrong location

### ISSUE THREAD

**Issue by mstrater** [marcelotduarte/cx_Freeze#621]
I'm new to this whole thing, but I'm trying to upgrade to a newer version of cx_freeze and getting errors when freezing as a result. Here's the relevant part of the output I get:

```
copying /Users/max/client-delivery/3P/PYTHON/3.7.6/MAC64/Frameworks/Release/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_datetime.cpython-37m-darwin.so -> build/exe.macosx-10.9-x86_64-3.7/lib/_datetime.cpython-37m-darwin.so
copying /Users/max/client-delivery/3P/PYTHON/3.7.6/MAC64/Frameworks/Release/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_hashlib.cpython-37m-darwin.so -> build/exe.macosx-10.9-x86_64-3.7/lib/_hashlib.cpython-37m-darwin.so
error: otool returned a dependent file that could not be found: /Users/max/client-delivery/3P/PYTHON/3.7.6/MAC64/Frameworks/Release/Python.framework/Versions/3.7/bin/../../../../Python.framework/Versions/3.7/lib/Python.framework/Versions/3.7/lib/libssl.1.1.dylib
Traceback (most recent call last):
  File "BuildMacCleaner", line 144, in <module>
    CopyChangeSignApp('Fusion 360', stream)
  File "BuildMacCleaner", line 84, in CopyChangeSignApp
    shutil.copytree(path.join(builddir, 'Fusion 360 Cleaner-0.1.app'), appdir)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 309, in copytree
    names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/max/client-delivery/Core/Neutron/Streamer/src/build/Fusion 360 Cleaner-0.1.app'
```

It should be searching for:
`Users/max/client-delivery/3P/PYTHON/3.7.6/MAC64/Frameworks/Release/Python.framework/Versions/3.7/bin/../../../../Python.framework/Versions/3.7/lib/libssl.1.1.dylib`
Somehow it's injecting an extra `Python.framework/Versions/3.7/lib` in there. Do you know why this would be?

**Comment by mstrater** [comment]
oh, and this is my setup file:
```
#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys
import os
from os import path, walk

sys.path.append(path.join(os.environ['_CX_FREEZE'], 'lib'))

from cx_Freeze import setup, Executable

resources = []
base = None
if sys.platform == 'win32':
    base = 'Win32GUI'
    for (dirpath, dirnames, filenames) in walk("DLLs"):
        for f in filenames:
            srcPath = path.join(dirpath, f)
            resources.extend([(srcPath, f)])

for (dirpath, dirnames, filenames) in walk("resources"):
    for f in filenames:
        if f == 'clean_config.json':
            fileWithPath = path.join(dirpath, f)
            resources.extend([(fileWithPath, fileWithPath)])
        elif f == 'cleaner.ico' and sys.platform == 'win32':
            fileWithPath = path.join(dirpath, f)
            resources.extend([(fileWithPath, fileWithPath)])
        elif f == 'cleaner.icns' and sys.platform != 'win32':
            fileWithPath = path.join(dirpath, f)
            resources.extend([(fileWithPath, fileWithPath)])

iconPath = "resources/cleaner.icns" # Mac
if sys.platform.startswith('win'):
    iconPath = "resources/cleaner.ico"

setup(
    name="Fusion 360 Cleaner",
    version="0.1",
    description="Clean Fusion 360 related folders and files",
    options={
        'build_exe': {
            'include_files': resources,
            'include_msvcr': True,  # For windows, of course
            'namespace_packages': ['adsk']
        }
    },
    executables=[Executable("cleaner.py", base=base, icon=iconPath)])
```

**Comment by marcelotduarte** [comment]
cx_Freeze 6.2 has just been released. Please, try it out.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.3 has just been released.
Closing due to inactivity. 
If you had issues please re-open.
