### ISSUE TITLE
freezing scipy as package causes error

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#64]
Originally reported by: **Ian Bell (Bitbucket: [ibell](https://bitbucket.org/ibell), GitHub: [ibell](https://github.com/ibell))**

----------------------------------------

I made a simple example that imports scipy as a package to demonstrate the sorts of problems I have been having with cx_Freeze.  scipy is a pretty heavily used package so it would be nice to have this working

scipy 0.13.2

python 2.7

windows 7 64-bit

python 2.7.2 32-bit

# foo.py #

```
#!python
print "Hello"
```

# setup.py #

```
#!python

import sys
from cx_Freeze import setup, Executable

sys.argv += ['build']

# Dependencies are automatically detected, but it might need fine tuning.
build_exe_options = {"packages": ["scipy"]}

# GUI applications require a different base on Windows (the default is for a
# console application).
base = None
if sys.platform == "win32":
    base = "Win32GUI"

setup(  name = "foo",
        version = "0.1",
        description = "My GUI application!",
        options = {"build_exe": build_exe_options},
        executables = [Executable("foo.py", base=base)])
```

fails with 
```
>pythonw -u "setup.py"
running build
running build_exe
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    executables = [Executable("foo.py", base=base)])
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\dist.py", line 362, in setup
    distutils.core.setup(**attrs)
  File "c:\Python27\lib\distutils\core.py", line 152, in setup
    dist.run_commands()
  File "c:\Python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "c:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "c:\Python27\lib\distutils\command\build.py", line 127, in run
    self.run_command(cmd_name)
  File "c:\Python27\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "c:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\dist.py", line 232, in run
    freezer.Freeze()
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\freezer.py", line 575, in Freeze
    self.finder = self._GetModuleFinder()
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\freezer.py", line 330, in _GetModuleFinder
    finder.IncludePackage(name)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 581, in IncludePackage
    self._ImportAllSubModules(module, deferredImports)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 226, in _ImportAllSubModules
    recursive)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 220, in _ImportAllSubModules
    deferredImports)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 338, in _InternalImportModule
    parentModule, namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 395, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 494, in _ScanCode
    module, relativeImportIndex)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 248, in _ImportModule
    deferredImports, namespace = namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 338, in _InternalImportModule
    parentModule, namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 350, in _LoadModule
    namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 406, in _LoadPackage
    self._LoadModule(name, fp, path, info, deferredImports, parent)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 395, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 494, in _ScanCode
    module, relativeImportIndex)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 264, in _ImportModule
    deferredImports, namespace = namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 338, in _InternalImportModule
    parentModule, namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 350, in _LoadModule
    namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 406, in _LoadPackage
    self._LoadModule(name, fp, path, info, deferredImports, parent)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 395, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 494, in _ScanCode
    module, relativeImportIndex)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 258, in _ImportModule
    deferredImports, namespace = namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 338, in _InternalImportModule
    parentModule, namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 395, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 494, in _ScanCode
    module, relativeImportIndex)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 258, in _ImportModule
    deferredImports, namespace = namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 338, in _InternalImportModule
    parentModule, namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 395, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 494, in _ScanCode
    module, relativeImportIndex)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 264, in _ImportModule
    deferredImports, namespace = namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 338, in _InternalImportModule
    parentModule, namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 395, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 537, in _ScanCode
    topLevel = False)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 494, in _ScanCode
    module, relativeImportIndex)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 258, in _ImportModule
    deferredImports, namespace = namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 338, in _InternalImportModule
    parentModule, namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 395, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 494, in _ScanCode
    module, relativeImportIndex)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 264, in _ImportModule
    deferredImports, namespace = namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 338, in _InternalImportModule
    parentModule, namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 395, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 494, in _ScanCode
    module, relativeImportIndex)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 264, in _ImportModule
    deferredImports, namespace = namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 338, in _InternalImportModule
    parentModule, namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 395, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 537, in _ScanCode
    topLevel = False)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 537, in _ScanCode
    topLevel = False)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 537, in _ScanCode
    topLevel = False)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 494, in _ScanCode
    module, relativeImportIndex)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 264, in _ImportModule
    deferredImports, namespace = namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 321, in _InternalImportModule
    namespace = namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 338, in _InternalImportModule
    parentModule, namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 350, in _LoadModule
    namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 406, in _LoadPackage
    self._LoadModule(name, fp, path, info, deferredImports, parent)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 395, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 494, in _ScanCode
    module, relativeImportIndex)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 258, in _ImportModule
    deferredImports, namespace = namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 338, in _InternalImportModule
    parentModule, namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 395, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 537, in _ScanCode
    topLevel = False)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 494, in _ScanCode
    module, relativeImportIndex)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 264, in _ImportModule
    deferredImports, namespace = namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 338, in _InternalImportModule
    parentModule, namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 350, in _LoadModule
    namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 406, in _LoadPackage
    self._LoadModule(name, fp, path, info, deferredImports, parent)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 395, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 494, in _ScanCode
    module, relativeImportIndex)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 258, in _ImportModule
    deferredImports, namespace = namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 338, in _InternalImportModule
    parentModule, namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 350, in _LoadModule
    namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 406, in _LoadPackage
    self._LoadModule(name, fp, path, info, deferredImports, parent)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 395, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 494, in _ScanCode
    module, relativeImportIndex)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 258, in _ImportModule
    deferredImports, namespace = namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 338, in _InternalImportModule
    parentModule, namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 395, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 494, in _ScanCode
    module, relativeImportIndex)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 264, in _ImportModule
    deferredImports, namespace = namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 338, in _InternalImportModule
    parentModule, namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 395, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 494, in _ScanCode
    module, relativeImportIndex)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 258, in _ImportModule
    deferredImports, namespace = namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 338, in _InternalImportModule
    parentModule, namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 395, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 494, in _ScanCode
    module, relativeImportIndex)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 264, in _ImportModule
    deferredImports, namespace = namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 338, in _InternalImportModule
    parentModule, namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 395, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 537, in _ScanCode
    topLevel = False)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 537, in _ScanCode
    topLevel = False)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 494, in _ScanCode
    module, relativeImportIndex)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 258, in _ImportModule
    deferredImports, namespace = namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 338, in _InternalImportModule
    parentModule, namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 395, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 494, in _ScanCode
    module, relativeImportIndex)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 258, in _ImportModule
    deferredImports, namespace = namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 338, in _InternalImportModule
    parentModule, namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 395, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 494, in _ScanCode
    module, relativeImportIndex)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 258, in _ImportModule
    deferredImports, namespace = namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 338, in _InternalImportModule
    parentModule, namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 395, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 494, in _ScanCode
    module, relativeImportIndex)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 264, in _ImportModule
    deferredImports, namespace = namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 321, in _InternalImportModule
    namespace = namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 338, in _InternalImportModule
    parentModule, namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 350, in _LoadModule
    namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 406, in _LoadPackage
    self._LoadModule(name, fp, path, info, deferredImports, parent)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 395, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 494, in _ScanCode
    module, relativeImportIndex)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 283, in _ImportModule
    deferredImports, namespace = namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 338, in _InternalImportModule
    parentModule, namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 395, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 494, in _ScanCode
    module, relativeImportIndex)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 283, in _ImportModule
    deferredImports, namespace = namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 338, in _InternalImportModule
    parentModule, namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 395, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 494, in _ScanCode
    module, relativeImportIndex)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 283, in _ImportModule
    deferredImports, namespace = namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 321, in _InternalImportModule
    namespace = namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 338, in _InternalImportModule
    parentModule, namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 350, in _LoadModule
    namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 406, in _LoadPackage
    self._LoadModule(name, fp, path, info, deferredImports, parent)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 395, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 494, in _ScanCode
    module, relativeImportIndex)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 283, in _ImportModule
    deferredImports, namespace = namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 338, in _InternalImportModule
    parentModule, namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 395, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 494, in _ScanCode
    module, relativeImportIndex)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 283, in _ImportModule
    deferredImports, namespace = namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 338, in _InternalImportModule
    parentModule, namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 395, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 494, in _ScanCode
    module, relativeImportIndex)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 283, in _ImportModule
    deferredImports, namespace = namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 338, in _InternalImportModule
    parentModule, namespace)
  File "c:\Python27\lib\site-packages\cx_freeze-4.3.2-py2.7-win32.egg\cx_Freeze\finder.py", line 366, in _LoadModule
    module.code = compile(codeString, path, "exec")
  File "c:\Python27\lib\site-packages\sympy\mpmath\libmp\exec_py3.py", line 1
    exec_ = exec
               ^
```

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/64

**Comment by anthony-tuininga** [comment]
*Original comment by* **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**:

----------------------------------------

The issue here is actually with sympy, not scipy - it includes `exec_py3` and `exec_py2` modules which should only be used on their respective Python versions, and can't even be imported on the other. cx_Freeze should probably catch that, though.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**:

----------------------------------------

Pull request #44 should fix this.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Ian Bell (Bitbucket: [ibell](https://bitbucket.org/ibell), GitHub: [ibell](https://github.com/ibell))**:

----------------------------------------

Thanks for following up.  Will be great to have scipy freezing properly again.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**:

----------------------------------------

I think this can be closed now that pull request #44 has been merged.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Ian Bell (Bitbucket: [ibell](https://bitbucket.org/ibell), GitHub: [ibell](https://github.com/ibell))**:

----------------------------------------

Fine by me.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
