### ISSUE TITLE
pywintypes.error: (2, 'BeginUpdateResource', 'The system cannot find the file specified.'

### ISSUE THREAD

**Issue by ERIPECH** [marcelotduarte/cx_Freeze#676]
I do have a cx_freeze issue on python 3.7.6.4 ond Windows 10 (also tried Windows 7 - same error) - using this makeexe:

```
import sys
from cx_Freeze import setup, Executable

# Dependencies are automatically detected, but it might need fine tuning.
build_exe_options = {"packages": ["os", "sys"],
                     "include_files": ["DMCA.ico"]     # with or without this line
}

# GUI applications require a different base on Windows (the default is for a
# console application).
base = None
if sys.platform == "win32":
    base = "Win32GUI"

setup(  name = "DMCA",
        version = "0.01",
        description = "DMCA by EP",
        options = {"build_exe": build_exe_options},
        executables = [Executable("DMCA.py", base=base, icon="DMCA.ico")])
```
I do get:
```
C:\WPy64-3760\Code\09Working>makeexe

C:\WPy64-3760\Code\09Working>C:/WPy64-3760/python-3.7.6.amd64/python MakeExe.py build
running build
running build_exe
copying C:\WPy64-3760\python-3.7.6.amd64\lib\site-packages\cx_Freeze\bases\Win32GUI.exe -> build\exe.win-amd64-3.7\DMCA.exe
copying C:\WPy64-3760\python-3.7.6.amd64\python37.dll -> build\exe.win-amd64-3.7\python37.dll
copying C:\WPy64-3760\python-3.7.6.amd64\VCRUNTIME140.dll -> build\exe.win-amd64-3.7\VCRUNTIME140.dll
error: [WinError 2] Das System kann die angegebene Datei nicht finden: 'build\\exe.win-amd64-3.7\\DMCA.exe'
```
and if I use:
```
import sys
from cx_Freeze import setup, Executable

# Dependencies are automatically detected, but it might need fine tuning.
build_exe_options = {"packages": ["os", "sys"]}

# GUI applications require a different base on Windows (the default is for a
# console application).
base = None
if sys.platform == "win32":
    base = "Win32GUI"

setup(  name = "DMCA",
        version = "0.01",
        description = "DMCA by EP",
        options = {"build_exe": build_exe_options},
        executables = [Executable("DMCA.py", base=base)])
```
The error is:
```
C:\WPy64-3760\Code\09Working>makeexe

C:\WPy64-3760\Code\09Working>C:/WPy64-3760/python-3.7.6.amd64/python MakeExe.py build
running build
running build_exe
copying C:\WPy64-3760\python-3.7.6.amd64\lib\site-packages\cx_Freeze\bases\Win32GUI.exe -> build\exe.win-amd64-3.7\DMCA.exe
copying C:\WPy64-3760\python-3.7.6.amd64\python37.dll -> build\exe.win-amd64-3.7\python37.dll
copying C:\WPy64-3760\python-3.7.6.amd64\VCRUNTIME140.dll -> build\exe.win-amd64-3.7\VCRUNTIME140.dll
Traceback (most recent call last):
  File "MakeExe.py", line 21, in <module>
    executables = [Executable("DMCA.py", base=base)])
  File "C:\WPy64-3760\python-3.7.6.amd64\lib\site-packages\cx_Freeze\dist.py", line 348, in setup
    distutils.core.setup(**attrs)
  File "C:\WPy64-3760\python-3.7.6.amd64\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\WPy64-3760\python-3.7.6.amd64\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\WPy64-3760\python-3.7.6.amd64\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\WPy64-3760\python-3.7.6.amd64\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\WPy64-3760\python-3.7.6.amd64\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\WPy64-3760\python-3.7.6.amd64\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\WPy64-3760\python-3.7.6.amd64\lib\site-packages\cx_Freeze\dist.py", line 219, in run
    freezer.Freeze()
  File "C:\WPy64-3760\python-3.7.6.amd64\lib\site-packages\cx_Freeze\freezer.py", line 617, in Freeze
    self._FreezeExecutable(executable)
  File "C:\WPy64-3760\python-3.7.6.amd64\lib\site-packages\cx_Freeze\freezer.py", line 208, in _FreezeExecutable
    self._AddVersionResource(exe)
  File "C:\WPy64-3760\python-3.7.6.amd64\lib\site-packages\cx_Freeze\freezer.py", line 143, in _AddVersionResource
    stamp(fileName, versionInfo)
  File "C:\WPy64-3760\python-3.7.6.amd64\lib\site-packages\win32\lib\win32verstamp.py", line 163, in stamp
    h = BeginUpdateResource(pathname, 0)
pywintypes.error: (2, 'BeginUpdateResource', The system cannot find the file specified.)
```

The source code, which I want to freeze is larger; PyQt QmainWindow and multiple sub-files using matplotlib 3.2.1, pillow 6.2.1, scipy 1.4.1 and numpy 1.17.4+mkl, so it would overwhelm this page. I also tried to add my sub-files to build_exe_options as 'includes' and output is the same.

**Comment by marcelotduarte** [comment]
The include_files and packages shouldn't be necessary.

Executable("DMCA.py", base=base, icon="DMCA.ico")
These files are in the same path of the setup (in your case MakeExe.py)?
If not, use:
`Executable("path\\to\\DMCA.py", base=base, icon="path\\to\\DMCA.ico")`
Of course, changing `path\\to\\` to the correct path.

**Comment by ERIPECH** [comment]
@marcelotduarte - all related files are in the same directory, where I start the makeexe. For a simple test project this works, but here I don’t know how to e.g. tweak the cx_freeze file or sth. else. Also the changing behavior adding  >> icon="path\\to\\DMCA.ico" << is strange. How can I proceed?

**Comment by marcelotduarte** [comment]
Please put the output of:
python -VV
pip list or inform the versions of cx-freeze and pywin32

**Comment by ERIPECH** [comment]
python -VV is
Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)]

cx_freeze is 6.0 (installing 6.1 failed using winpython Control Pannel and pip command)  and pywin32 is 227 (update to 228 failed).


in the meantime I  I reinstalled everything and cx_freeze (now 6.1,  pywin32 vers. 277) is working properly now. The next issue is: Error No module named 'mpl_toolkits', when I execute the Application.

**Comment by marcelotduarte** [comment]
I was going to ask you if you were using anaconda, but I see that it's winpython. With versions of python compiled differently from the original version of python.org I have sometimes seen some problems with packages. Just because you can't install pywin228 and cx-freeze 6.1 already shows that.
I have used in a project of mine, python 3.7.7 with cx-freeze 6.1 or current and pywin32 updated as soon as the version came out, and compiled everything correctly.
I suggest you at least try to use the official version for testing.

**Comment by ERIPECH** [comment]
It seems, there is an issue using different packages; especially matplotlib - because this error is not longer valid, Im going to close this issue.
