### ISSUE TITLE
On running setup.exe install - "cx_Freeze.freezer.ConfigError: no initscript named Console3"

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#68]
Originally reported by: **Anonymous**

----------------------------------------

Here is a complete dump of the error:

C:\Users\...\Desktop\dist>setup.exe install
running install
running build
running build_exe
Traceback (most recent call last):
  File "C:\Python33\lib\site-packages\cx_Freeze\initscripts\Console3.py", line 27, in <module>
    exec(code, m.__dict__)
  File "setup.py", line 19, in <module>
  File "C:\Python33\lib\site-packages\cx_Freeze\dist.py", line 365, in setup
    distutils.core.setup(**attrs)
  File "C:\Python33\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Python33\lib\distutils\dist.py", line 930, in run_commands
    self.run_command(cmd)
  File "C:\Python33\lib\distutils\dist.py", line 949, in run_command
    cmd_obj.run()
  File "C:\Python33\lib\distutils\command\install.py", line 569, in run
    self.run_command('build')
  File "C:\Python33\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Python33\lib\distutils\dist.py", line 949, in run_command
    cmd_obj.run()
  File "C:\Python33\lib\distutils\command\build.py", line 126, in run
    self.run_command(cmd_name)
  File "C:\Python33\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Python33\lib\distutils\dist.py", line 949, in run_command
    cmd_obj.run()
  File "C:\Python33\lib\site-packages\cx_Freeze\dist.py", line 234, in run
    metadata = metadata)
  File "C:\Python33\lib\site-packages\cx_Freeze\freezer.py", line 108, in __init__
    self._VerifyConfiguration()
  File "C:\Python33\lib\site-packages\cx_Freeze\freezer.py", line 471, in _VerifyConfiguration
    self._GetInitScriptFileName()
  File "C:\Python33\lib\site-packages\cx_Freeze\freezer.py", line 316, in _GetInitScriptFileName
    raise ConfigError("no initscript named %s", name)
cx_Freeze.freezer.ConfigError: no initscript named Console3

C:\Users\...\Desktop\dist>

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/68

**Comment by anthony-tuininga** [comment]
*Original comment by* **Luke Jones (Bitbucket: [snowdogu77](https://bitbucket.org/snowdogu77), GitHub: [snowdogu77](https://github.com/snowdogu77))**:

----------------------------------------

![ss (2014-03-11 at 07.55.09).png](https://bitbucket.org/repo/oE5Lk/images/189809735-ss%20%282014-03-11%20at%2007.55.09%29.png)Here's a cleaner version of the full dump, sorry about the mess.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**:

----------------------------------------

Sorry, what is setup.exe? It looks like you have a frozen executable trying to create another frozen executable.

The Console3 initscript was just removed - you can use the Console initscript on Python 2 or 3 now.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anthony Tuininga (Bitbucket: [anthony_tuininga](https://bitbucket.org/anthony_tuininga), GitHub: Unknown)**:

----------------------------------------

As Thomas mentioned, Console3 is no longer shipped. And it looks like this issue is a result of something more complex in your configuration that needs to be resolved first.
