### ISSUE TITLE
cx_Freeze not working with Google Cloud SDK

### ISSUE THREAD

**Issue by tardis4500** [marcelotduarte/cx_Freeze#685]
Here is a simple test case.
google_sdk.py
```
import google.cloud.storage
print(google.cloud.storage.Client())
```
setup.py
```
from cx_Freeze import setup, Executable
setup(name='google_sdk',
      executables=[Executable('google_sdk.py')],
      options={'build_exe': {'excludes': ['Tkinter']}})
```
I have tried multiple options to  setup and build_exe including includes, packages, and namespace_packages but the frozen executable always fails with:
```
Traceback (most recent call last):
  File "C:\Users\jgs10292\AppData\Local\Programs\Python\Python38\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
    module.run()
  File "C:\Users\jgs10292\AppData\Local\Programs\Python\Python38\lib\site-packages\cx_Freeze\initscripts\Console.py", line 37, in run
    exec(code, {'__name__': '__main__'})
  File "google_sdk.py", line 1, in <module>
    import google.cloud.storage
ModuleNotFoundError: No module named 'google'
```

**Comment by tamenol** [comment]
You need to add the `google` package.


```python
from cx_Freeze import setup, Executable
setup(name='google_sdk',
      executables=[Executable('google_sdk.py')],
      options={'build_exe': {'excludes': ['Tkinter'], "packages":["google"]}})
```
or 

`"packages":["google.cloud.storage"]`

but I'm not sure if this will work. Try it out.

**Comment by tardis4500** [comment]
I already tried that as indicated in the original ticket. That results in an error during the build. The same below will happen if I specify google instead of google.cloud.storage or if I specify both.
```
running build_exe
Traceback (most recent call last):
  File ".\setup.py", line 2, in <module>
    setup(name='google_sdk',
  File "C:\Users\jgs10292\AppData\Local\Programs\Python\Python38\lib\site-packages\cx_Freeze\dist.py", line 340, in setup
    distutils.core.setup(**attrs)
  File "C:\Users\jgs10292\AppData\Local\Programs\Python\Python38\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\jgs10292\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\jgs10292\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\jgs10292\AppData\Local\Programs\Python\Python38\lib\site-packages\cx_Freeze\dist.py", line 211, in run
    freezer.Freeze()
  File "C:\Users\jgs10292\AppData\Local\Programs\Python\Python38\lib\site-packages\cx_Freeze\freezer.py", line 610, in Freeze
    self.finder = self._GetModuleFinder()
  File "C:\Users\jgs10292\AppData\Local\Programs\Python\Python38\lib\site-packages\cx_Freeze\freezer.py", line 356, in _GetModuleFinder
    finder.IncludePackage(name)
  File "C:\Users\jgs10292\AppData\Local\Programs\Python\Python38\lib\site-packages\cx_Freeze\finder.py", line 640, in IncludePackage
    module = self._ImportModule(name, deferredImports)
  File "C:\Users\jgs10292\AppData\Local\Programs\Python\Python38\lib\site-packages\cx_Freeze\finder.py", line 348, in _ImportModule
    raise ImportError("No module named %r" % name)
ImportError: No module named 'google.cloud.storage'
```

**Comment by marcelotduarte** [comment]
cx_Freeze 6.2 has just been released with namespace detection. Please, try it.

**Comment by marcelotduarte** [comment]
PR #697 and others fix this issue. I'll do more tests and in one or two days I had a plan to release a version.

**Comment by tardis4500** [comment]
It still fails with 6.2 but now it fails when the packaged executable is run rather than during the build:

`pkg_resources.DistributionNotFound: The 'google-cloud-storage' distribution was not found and is required by the application`

**Comment by marcelotduarte** [comment]
Wait a bit more, I'll release a version that needs a minimum setup for the test case.
from cx_Freeze import setup, Executable
```
setup(name='google_sdk',
      executables=[Executable('google_sdk.py')],
      options={'build_exe': {'excludes': ['tkinter']}})
```

**Comment by marcelotduarte** [comment]
@tardis4500 @tamenol 
If you have a C compiler, you can test the development version:
`pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@develop`

**Comment by marcelotduarte** [comment]
@tardis4500 @tamenol 
cx_Freeze 6.3 has just been released.
Can you check if this has been resolved?

**Comment by marcelotduarte** [comment]
Closing due to lack of response.
If you had issues please re-open.
