### ISSUE TITLE
TypeError while compiling

### ISSUE THREAD

**Issue by arnaudavot** [marcelotduarte/cx_Freeze#730]
Hi, 

I get this error when I execute `python setup.py build`
```
Traceback (most recent call last):
  File "setup.py", line 36, in <module>
    executables=[Executable("Kea_app.py", base=base, icon="icon.ico")]
  File "C:\Users\Me\PycharmProjects\MyProject\venv\lib\site-packages\cx_Freeze\dist.py", line 342, in setup
    distutils.core.setup(**attrs)
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Me\PycharmProjects\MyProject\venv\lib\site-packages\cx_Freeze\dist.py", line 217, in run
    freezer.Freeze()
  File "C:\Users\Me\PycharmProjects\MyProject\venv\lib\site-packages\cx_Freeze\freezer.py", line 645, in Freeze
    self._WriteModules(fileName, self.finder)
  File "C:\Users\Me\PycharmProjects\MyProject\venv\lib\site-packages\cx_Freeze\freezer.py", line 536, in _WriteModules
    sourcePackageDir = os.path.dirname(module.file)
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37\lib\ntpath.py", line 221, in dirname
    return split(p)[0]
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37\lib\ntpath.py", line 183, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
here my code.

```
import sys
import os
from cx_Freeze import setup, Executable

python_dir = os.path.dirname(sys.executable)
build_exe_options = {"packages": ["os"],
                      "include_files": ["icon.ico",  "UIMainWindow.ui",
                                        "config/", "HostExplorer/", "Template/",
                                        os.path.join(python_dir, "python3.dll"),
                                        os.path.join(python_dir, "vcruntime140.dll")],
                      "includes": ['atexit', 'PyQt5'],
                      "excludes": ['tkinter']}

base = None
if sys.platform == "win32":
    base = "Win32GUI"

setup(
    name='Kea',
    version='0.0.17',
    description='Toolbox',
    options={"build_exe": build_exe_options},
    executables=[Executable("Kea_app.py", base=base, icon="icon.ico")]
)
```

I work with python 3.7 and cx_freeze 6.2 (I don't think the problem comes from my code because it worked with previous version of cx_freeze...)

Can you help me?

**Comment by marcelotduarte** [comment]
In cx-freeze 6.2 some modules cause this error.
If you have a C compiler, you can test the current version:
pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@master

I'll release a new version this week.

**Comment by arnaudavot** [comment]
Ok thanks a lot, unfortunately i don't have C compiler installed.
I'll wait the new version.

**Comment by VeronicaGupta** [comment]
Hey, I have also got the same issue when I upgraded the cx-freeze, have you got any solutions yet?

Also, let me know if you got this error while opening the GUI and have solved it- 
qt.qpa.fonts: Unable to open default EUDC font: "C:\\WINDOWS\\FONTS\\EUDC.TTE"

**Comment by brummel-promed** [comment]
I also had this same trace back:
Traceback (most recent call last):
  File "setup.py", line 40, in <module>
    'bdist_msi': bdist_msi_options})
  File "C:\Users\Username\Anaconda3\lib\site-packages\cx_Freeze\dist.py", line 342, in setup
    distutils.core.setup(**attrs)
  File "C:\Users\Username\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\Username\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\Username\Anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Username\Anaconda3\lib\site-packages\cx_Freeze\windist.py", line 389, in run
    self.run_command('build')
  File "C:\Users\Username\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Username\Anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Username\Anaconda3\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\Users\Username\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Username\Anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Username\Anaconda3\lib\site-packages\cx_Freeze\dist.py", line 217, in run
    freezer.Freeze()
  File "C:\Users\Username\Anaconda3\lib\site-packages\cx_Freeze\freezer.py", line 645, in Freeze
    self._WriteModules(fileName, self.finder)
  File "C:\Users\Username\Anaconda3\lib\site-packages\cx_Freeze\freezer.py", line 536, in _WriteModules
    sourcePackageDir = os.path.dirname(module.file)
  File "C:\Users\Username\Anaconda3\lib\ntpath.py", line 221, in dirname
    return split(p)[0]
  File "C:\Users\Username\Anaconda3\lib\ntpath.py", line 183, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by marcelotduarte** [comment]
cx_Freeze 6.3 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
