### ISSUE TITLE
cx_Freeze.util.AddIcon file not found error

### ISSUE THREAD

**Issue by jnettels** [marcelotduarte/cx_Freeze#732]
In cx_freeze versions 6.1 and 6.2 on Windows I get the following error when running `python setup.py bdist_msi`

```
Traceback (most recent call last):
  File "C:\Users\Nettelstroth\anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\Nettelstroth\anaconda3\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\Nettelstroth\anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Nettelstroth\anaconda3\lib\site-packages\cx_Freeze\windist.py", line 386, in run
    self.run_command('build')
  File "C:\Users\Nettelstroth\anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Nettelstroth\anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Nettelstroth\anaconda3\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\Users\Nettelstroth\anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Nettelstroth\anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Nettelstroth\anaconda3\lib\site-packages\cx_Freeze\dist.py", line 211, in run
    freezer.Freeze()
  File "C:\Users\Nettelstroth\anaconda3\lib\site-packages\cx_Freeze\freezer.py", line 614, in Freeze
    self._FreezeExecutable(executable)
  File "C:\Users\Nettelstroth\anaconda3\lib\site-packages\cx_Freeze\freezer.py", line 205, in _FreezeExecutable
    cx_Freeze.util.AddIcon(exe.targetName, exe.icon)
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden: 'build\\exe.win-amd64-3.7\\dwd2trnsys.exe'
```

This is the seemingly relevant part of my setup() method:
```
executables=[Executable(r'lpagg/dwd2trnsys.py',
                            # base=base,  # Removes the console (use GUI only)
                            icon=r'./res/icon_d2t.ico',
                            targetName='dwd2trnsys.exe',
                            shortcutName="dwd2trnsys",
                            shortcutDir="ProgramMenuFolder",
                            )],
```

This is the line with the error (line 205 in v6.1; line 226 in v6.2)
```
                cx_Freeze.util.AddIcon(exe.targetName, exe.icon)
```
with `print(exe.targetName) = build\exe.win-amd64-3.7\dwd2trnsys.exe`

With this tiny change, the setup runs fine:
```
                cx_Freeze.util.AddIcon(os.path.abspath(exe.targetName), exe.icon)
```
I cannot help but wonder: Am I the only one with this issue?
Should I provide a pull request?

I said it runs fine.. .except... it used to run fine, but after switching between 6.1 and 6.2 now afterward I run into this
```
Traceback (most recent call last):
  File "C:\Users\Nettelstroth\Documents\07 Python\LPagg\setup_d2t_exe.py", line 232, in <module>
    '{eaedb2b8-f535-439a-af23-4797a64c53c5}',
  File "C:\Users\Nettelstroth\anaconda3\lib\site-packages\cx_Freeze\dist.py", line 340, in setup
    distutils.core.setup(**attrs)
  File "C:\Users\Nettelstroth\anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\Nettelstroth\anaconda3\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\Nettelstroth\anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Nettelstroth\anaconda3\lib\site-packages\cx_Freeze\windist.py", line 423, in run
    self.add_files()
  File "C:\Users\Nettelstroth\anaconda3\lib\site-packages\cx_Freeze\windist.py", line 143, in add_files
    cab.commit(db)
  File "C:\Users\Nettelstroth\anaconda3\lib\msilib\__init__.py", line 215, in commit
    FCICreate(filename, self.files)
ValueError: FCI error 1
```
But this should be discussed in a separate issue, and has already been reported here: https://github.com/marcelotduarte/cx_Freeze/issues/527

**Comment by marcelotduarte** [comment]
Duplicate of #693 
If you have a C compiler, you can test the current version:
pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@master

**Comment by jnettels** [comment]
Thanks for the ultra fast response. I am fine waiting for the next release.

**Comment by marcelotduarte** [comment]
@jnettels cx_Freeze 6.3 has just been released.

**Comment by jnettels** [comment]
@marcelotduarte Thanks for the info, this is much appreciated! 

I hesitated to ask, but... are you also involved with uploading cx_Freeze to conda-forge?
Over at https://github.com/conda-forge/cx_freeze-feedstock/pulls PRs exist for the update to 6.3, but some of the builds fail and there were no changes for the last two weeks. Honestly I have no clue about the error messages, so all I can say is: having conda support would be great.

**Comment by marcelotduarte** [comment]
@jnettels I only make a PR to update but not maintain it. The maintainer of conda-forge that have control over it. Please open an issue in that repository.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.5 has just been released.
