### ISSUE TITLE
error in def _WriteModules() due to module.file = None

### ISSUE THREAD

**Issue by jnettels** [marcelotduarte/cx_Freeze#733]
```
Traceback (most recent call last):
  File "C:\Users\Nettelstroth\Documents\07 Python\LPagg\setup_d2t_exe.py", line 232, in <module>
    '{eaedb2b8-f535-439a-af23-4797a64c53c5}',
  File "C:\Users\Nettelstroth\anaconda3\lib\site-packages\cx_Freeze\dist.py", line 342, in setup
    distutils.core.setup(**attrs)
  File "C:\Users\Nettelstroth\anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\Nettelstroth\anaconda3\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\Nettelstroth\anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Nettelstroth\anaconda3\lib\site-packages\cx_Freeze\windist.py", line 389, in run
    self.run_command('build')
  File "C:\Users\Nettelstroth\anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Nettelstroth\anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Nettelstroth\anaconda3\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\Users\Nettelstroth\anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Nettelstroth\anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Nettelstroth\anaconda3\lib\site-packages\cx_Freeze\dist.py", line 217, in run
    freezer.Freeze()
  File "C:\Users\Nettelstroth\anaconda3\lib\site-packages\cx_Freeze\freezer.py", line 645, in Freeze
    self._WriteModules(fileName, self.finder)
  File "C:\Users\Nettelstroth\anaconda3\lib\site-packages\cx_Freeze\freezer.py", line 536, in _WriteModules
    sourcePackageDir = os.path.dirname(module.file)
  File "C:\Users\Nettelstroth\anaconda3\lib\ntpath.py", line 221, in dirname
    return split(p)[0]
  File "C:\Users\Nettelstroth\anaconda3\lib\ntpath.py", line 183, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

This is what can be learned about the `module` that crashes the script:
```
print(module)
<Module name='numpy.random._examples', path=['C:\\Users\\Nettelstroth\\anaconda3\\lib\\site-packages\\numpy\\random\\_examples']>
print(module.path)
['C:\\Users\\Nettelstroth\\anaconda3\\lib\\site-packages\\numpy\\random\\_examples']
print(module.file)
None
```

A quick fix could be made in line 532 of freezer.py:
`if module.path is not None and includeInFileSystem:
`
change to: 
`if module.path is not None and module.file is not None and includeInFileSystem:
`
...but I cannot tell if this is the best way to deal with the issue.

A full reproduction of this issue can be found in this GitHub Action run in one of my repos:
https://github.com/jnettels/lpagg/runs/927100021?check_suite_focus=true

**Comment by marcelotduarte** [comment]
This bug already resolved in the current branch. I have a plan to release a new version soon.

If you have a C compiler, you can test the current version:
pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@master

**Comment by jnettels** [comment]
Thanks for the ultra fast response. I am fine waiting for the next release.

**Comment by marcelotduarte** [comment]
You are welcome.
