### ISSUE TITLE
can't find module 'cx_Freeze__init__'

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#74]
Originally reported by: **Yaerox (Bitbucket: [Yaerox](https://bitbucket.org/Yaerox), GitHub: [Yaerox](https://github.com/Yaerox))**

----------------------------------------

I tried to build and executable (samples/simple) **python -tt setup.py build** but I'm not able to start the .exe afterwards. I'm getting the following Error:
_________________________________________________
zipimport.ZipImportError: can't find module 'cx_Freeze__init__' (this is shown bold because there are two _ before and after init ...)
Fatal Python error: unable to locate initialization module

Current thread 0x0000618c (most recent call first):
_________________________________________________

Following my output when running the python -tt setup.py build:
_________________________________________________
C:\Python34\Lib\site-packages\cx_Freeze\samples\simple>python -tt setup.py build
running build
running build_exe
copying C:\Python34\lib\site-packages\cx_Freeze\bases\Console.exe -> build\exe.win-amd64-3.4\hello.e
xe
copying C:\Windows\system32\python34.dll -> build\exe.win-amd64-3.4\python34.dll
*** WARNING *** unable to create version resource
install pywin32 extensions first
writing zip file build\exe.win-amd64-3.4\library.zip

  Name                      File
  ----                      ----
m BUILD_CONSTANTS
m _bootlocale
m _bz2                      C:\Python34\DLLs\_bz2.pyd
m _codecs
m _codecs_cn
m _codecs_hk
m _codecs_iso2022
m _codecs_jp
m _codecs_kr
m _codecs_tw
m _collections
m _collections_abc
m _datetime
m _dummy_thread
m _functools
m _heapq
m _imp
m _io
m _locale
m _multibytecodec
m _operator
m _sre
m _stat
m _string
m _strptime
m _struct
m _thread
m _threading_local
m _warnings
m _weakref
m _weakrefset
m abc
m argparse
m array
m atexit
m base64
m binascii
m builtins
m bz2
m calendar
m codecs
P collections
m collections.abc
m contextlib
m copy
m copyreg
m cx_Freeze__init__         C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console3.py
m datetime
m dummy_threading
P encodings
m encodings.aliases
m encodings.ascii
m encodings.base64_codec
m encodings.big5
m encodings.big5hkscs
m encodings.bz2_codec
m encodings.charmap
m encodings.cp037
m encodings.cp1006
m encodings.cp1026
m encodings.cp1125
m encodings.cp1140
m encodings.cp1250
m encodings.cp1251
m encodings.cp1252
m encodings.cp1253
m encodings.cp1254
m encodings.cp1255
m encodings.cp1256
m encodings.cp1257
m encodings.cp1258
m encodings.cp273
m encodings.cp424
m encodings.cp437
m encodings.cp500
m encodings.cp65001
m encodings.cp720
m encodings.cp737
m encodings.cp775
m encodings.cp850
m encodings.cp852
m encodings.cp855
m encodings.cp856
m encodings.cp857
m encodings.cp858
m encodings.cp860
m encodings.cp861
m encodings.cp862
m encodings.cp863
m encodings.cp864
m encodings.cp865
m encodings.cp866
m encodings.cp869
m encodings.cp874
m encodings.cp875
m encodings.cp932
m encodings.cp949
m encodings.cp950
m encodings.euc_jis_2004
m encodings.euc_jisx0213
m encodings.euc_jp
m encodings.euc_kr
m encodings.gb18030
m encodings.gb2312
m encodings.gbk
m encodings.hex_codec
m encodings.hp_roman8
m encodings.hz
m encodings.idna
m encodings.iso2022_jp
m encodings.iso2022_jp_1
m encodings.iso2022_jp_2
m encodings.iso2022_jp_2004
m encodings.iso2022_jp_3
m encodings.iso2022_jp_ext
m encodings.iso2022_kr
m encodings.iso8859_1
m encodings.iso8859_10
m encodings.iso8859_11
m encodings.iso8859_13
m encodings.iso8859_14
m encodings.iso8859_15
m encodings.iso8859_16
m encodings.iso8859_2
m encodings.iso8859_3
m encodings.iso8859_4
m encodings.iso8859_5
m encodings.iso8859_6
m encodings.iso8859_7
m encodings.iso8859_8
m encodings.iso8859_9
m encodings.johab
m encodings.koi8_r
m encodings.koi8_u
m encodings.latin_1
m encodings.mac_arabic
m encodings.mac_centeuro
m encodings.mac_croatian
m encodings.mac_cyrillic
m encodings.mac_farsi
m encodings.mac_greek
m encodings.mac_iceland
m encodings.mac_latin2
m encodings.mac_roman
m encodings.mac_romanian
m encodings.mac_turkish
m encodings.mbcs
m encodings.palmos
m encodings.ptcp154
m encodings.punycode
m encodings.quopri_codec
m encodings.raw_unicode_escape
m encodings.rot_13
m encodings.shift_jis
m encodings.shift_jis_2004
m encodings.shift_jisx0213
m encodings.tis_620
m encodings.undefined
m encodings.unicode_escape
m encodings.unicode_internal
m encodings.utf_16
m encodings.utf_16_be
m encodings.utf_16_le
m encodings.utf_32
m encodings.utf_32_be
m encodings.utf_32_le
m encodings.utf_7
m encodings.utf_8
m encodings.utf_8_sig
m encodings.uu_codec
m encodings.zlib_codec
m errno
m functools
m gc
m genericpath
m gettext
m heapq
m hello__main__             hello.py
m imp
P importlib
m importlib._bootstrap
m importlib.machinery
m importlib.util
m io
m itertools
m keyword
m linecache
m locale
m math
m nt
m ntpath
m operator
m optparse
m os
m posixpath
m quopri
m re
m reprlib
m sre_compile
m sre_constants
m sre_parse
m stat
m string
m stringprep
m struct
m sys
m textwrap
m threading
m time
m token
m tokenize
m traceback
m types
m unicodedata               C:\Python34\DLLs\unicodedata.pyd
m warnings
m weakref
m zipimport
m zlib

Missing modules:
? _dummy_threading imported from dummy_threading
? ce imported from os
? doctest imported from heapq
? getopt imported from base64, quopri
? org.python.core imported from copy
? os.path imported from os
? posix imported from os
? pwd imported from posixpath
? subprocess imported from os
This is not necessarily a problem - the modules may not be needed on this platform.

copying C:\Python34\DLLs\_bz2.pyd -> build\exe.win-amd64-3.4\_bz2.pyd
copying C:\Python34\DLLs\unicodedata.pyd -> build\exe.win-amd64-3.4\unicodedata.pyd

C:\Python34\Lib\site-packages\cx_Freeze\samples\simple>
_________________________________________________

I already installed pywin32 but still this **WARNING** on top ... not sure if this could be a problem. Maybe this is something like this issue right here (#69/python-340-can-not-import-collectionsabc) ? Already edited the finder.py but in my case didn't solved the problem.

**#Edit:**
Environment:
Windows 7 Professional 64-Bit
Python 3.4 (v3.4.0:04f714765c13, Mar 16 2014, 19:25:23) 64 Bit ([MSC v.1600 64 Bit (AMD64)] on win32

**#Edit 2:**
Even after doing this https://www.mail-archive.com/cx-freeze-users@lists.sourceforge.net/msg01848.html same behaviour ... but my file was only called 'msvc9compiler.py' not 'distutils.msvc9compiler.py' ...

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/74

**Comment by anthony-tuininga** [comment]
*Original comment by* **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**:

----------------------------------------

Are you using the released version of cx_Freeze or the development version? It might already be fixed since the last release. If you're not already, can you try it with the development version ([zip download](https://bitbucket.org/anthony_tuininga/cx_freeze/get/default.zip))? Note that you'll need a C compiler to install it - I think it's VS 2010 for Python 3.4.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Yaerox (Bitbucket: [Yaerox](https://bitbucket.org/Yaerox), GitHub: [Yaerox](https://github.com/Yaerox))**:

----------------------------------------

On the weekend I had no chance to work on this. Sorry for that. Hopeful I'll be able to give it a try today. I'll reply as soon as I tried ;) Thanks already.

Edit 1: I used Version 4.3.2 Windows installers MSI Python 4.3 64 Bit. What do you mean with “Note that you'll need a C compiler to install it - I think it's VS 2010 for Python 3.4.“ ... could u give me an short introduction what to do or a link where i can read what to do?

**Comment by anthony-tuininga** [comment]
*Original comment by* **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**:

----------------------------------------

When a release is made, installer packages are made. To install the development version, you need to have a C compiler installed on your system, probably Visual Studio 2010. If you're not comfortable with this stuff, you can just wait for the next release - hopefully we'll have one soon.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Yaerox (Bitbucket: [Yaerox](https://bitbucket.org/Yaerox), GitHub: [Yaerox](https://github.com/Yaerox))**:

----------------------------------------

I know this general things, my problem is that I don't know which files I have to compile and the way you're doing this :-) In case that this would need to much time I probably have to wait till the next release, otherway I'd give it a try.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**:

----------------------------------------

Once you've got VS installed, you can just run `python setup.py install` in the source directory - it will take care of compiling the necessary files.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Yaerox (Bitbucket: [Yaerox](https://bitbucket.org/Yaerox), GitHub: [Yaerox](https://github.com/Yaerox))**:

----------------------------------------

I did ```python setup.py install``` and i got an error. Because I don't know if this can have any consequences for the installation I'll post only a couple lines to show where this error occured: 

```
copying cx_Freeze\samples\zope\setup.py -> build\lib.win-amd64-3.4\cx_Freeze\samples\zope
running build_ext
building 'cx_Freeze.util' extension
error: Unable to find vcvarsall.bat
```

I tried to compile sample\simple still same behaviour like before.

Thank you for your efforts. I really appreciate it.

#Edit:

Tried:

```
VS100COMNTOOLS="C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\"
VS110COMNTOOLS="C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\"
VS120COMNTOOLS="C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\"
VS90COMNTOOLS="C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\"
```
but no luck for me. I got VisualStudio Express 2013 Version 12. Or do I have to use the oder one?

**Comment by anthony-tuininga** [comment]
*Original comment by* **0BLACK0 (Bitbucket: [0BLACK0](https://bitbucket.org/0BLACK0), GitHub: Unknown)**:

----------------------------------------

Install VS2010
but read Issue #71 before build .

**Comment by anthony-tuininga** [comment]
*Original comment by* **Yaerox (Bitbucket: [Yaerox](https://bitbucket.org/Yaerox), GitHub: [Yaerox](https://github.com/Yaerox))**:

----------------------------------------

I installed VS2010 and tried to do it again. I got the following error when trying to install:


```
building 'cx_Freeze.util' extension
Traceback (most recent call last):
  File "setup.py", line 224, in <module>
    package_data = {"cx_Freeze" : packageData })
  File "C:\Python34\lib\distutils\core.py", line 149, in setup
    dist.run_commands()
  File "C:\Python34\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Python34\lib\site-packages\setuptools\command\install.py", line 74, in run
    self.do_egg_install()
  File "C:\Python34\lib\site-packages\setuptools\command\install.py", line 89, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Python34\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Python34\lib\site-packages\setuptools\command\bdist_egg.py", line 185, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Python34\lib\site-packages\setuptools\command\bdist_egg.py", line 171, in call_command
    self.run_command(cmdname)
  File "C:\Python34\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Python34\lib\site-packages\setuptools\command\install_lib.py", line 20, in run
    self.build()
  File "C:\Python34\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Python34\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Python34\lib\distutils\command\build_ext.py", line 348, in run
    self.build_extensions()
  File "C:\Python34\lib\distutils\command\build_ext.py", line 457, in build_extensions
    self.build_extension(ext)
  File "setup.py", line 61, in build_extension
    distutils.command.build_ext.build_ext.build_extension(self, ext)
  File "C:\Python34\lib\distutils\command\build_ext.py", line 512, in build_extension
    depends=ext.depends)
  File "C:\Python34\lib\distutils\msvc9compiler.py", line 460, in compile
    self.initialize()
  File "C:\Python34\lib\distutils\msvc9compiler.py", line 371, in initialize
    vc_env = query_vcvarsall(VERSION, plat_spec)
  File "C:\Python34\lib\distutils\msvc9compiler.py", line 287, in query_vcvarsall
    raise ValueError(str(list(result.keys())))
ValueError: ['path']
```

I tried if maybe the fix from Issue #71 could help here I gave it a try but same result.

**Comment by anthony-tuininga** [comment]
*Original comment by* **0BLACK0 (Bitbucket: [0BLACK0](https://bitbucket.org/0BLACK0), GitHub: Unknown)**:

----------------------------------------

i think it's python3.4 error

some one have the same error with numpy

[why-does-installing-matplotlib-for-python-v3-4-fail-on-windows-7-x64](http://stackoverflow.com/questions/22662811/why-does-installing-matplotlib-for-python-v3-4-fail-on-windows-7-x64)

so try python 3.3+cx_freeze 
i use it to build all my projects

**Comment by anthony-tuininga** [comment]
*Original comment by* **Yaerox (Bitbucket: [Yaerox](https://bitbucket.org/Yaerox), GitHub: [Yaerox](https://github.com/Yaerox))**:

----------------------------------------

I'll give it a try, but I can do this Thursday at the earliest. Thanks for the help. Ill reply asap.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Yaerox (Bitbucket: [Yaerox](https://bitbucket.org/Yaerox), GitHub: [Yaerox](https://github.com/Yaerox))**:

----------------------------------------

Tried Python 3.3.0 and Python 3.3.3 on both same error ...

**Comment by marcelotduarte** [comment]
Closing due to inactivity. 
cx_Freeze 6.1 has just been released.
