### ISSUE TITLE
cx_Freeze with pydantic on windows

### ISSUE THREAD

**Issue by abrade** [marcelotduarte/cx_Freeze#753]
Hi,
we are trying to create a executable of our application with pydantic as a dependency. I have created a small example for reproduction on windows:
setup.py:
```
from cx_Freeze import setup, Executable

build_exe_options = {
    "zip_include_packages": ["*"],
    "zip_exclude_packages": [],
    "packages": ["pydantic"],
    "includes": ["json", "ipaddress", "uuid", "colorsys"],
}

my_executable = Executable('pydantic_test.py', base='Console')

setup(
    name='pydantic_freeze',
    install_requires=[
        'pydantic',
        'cx_Freeze==6.0.0'
    ],
    options={'build_exe': build_exe_options},
    executables=[
        my_executable
    ],
)
```

pydantic_test.py:
```
# -*- coding: utf-8 -*-

from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, BaseConfig


class User(BaseModel):
    id: int
    name = 'John Doe'
    signup_ts: Optional[datetime] = None
    friends: List[int] = []


if __name__ == '__main__':
    external_data = {
        'id': '123',
        'signup_ts': '2019-06-01 12:22',
        'friends': [1, 2, '3'],
    }
    user = User(**external_data)
    print(user.id)
    # > 123
    print(repr(user.signup_ts))
    # > datetime.datetime(2019, 6, 1, 12, 22)
    print(user.friends)
    # > [1, 2, 3]
    print(user.dict())
```

and we get the following error when we execute the binary:
```
Traceback (most recent call last):
  File "C:\Users\....\.virtualenvs\pydantic_freeze\lib\site-packages\cx_freeze-6.0-py3.7-win-amd64.egg\cx_Freeze\initscripts\__startup__.py", line 40, in run
    module.run()
  File "C:\Users\...\.virtualenvs\pydantic_freeze\lib\site-packages\cx_freeze-6.0-py3.7-win-amd64.egg\cx_Freeze\initscripts\Console.py", line 23, in run
    exec(code, {'__name__': '__main__'})
  File "pydantic_test.py", line 5, in <module>
ModuleNotFoundError: No module named 'pydantic'
```

This was tested with cx-Freeze version 6.0 and 6.2 and it happen in both versions.

**Comment by marcelotduarte** [comment]
Please see issue #745, specialy from https://github.com/marcelotduarte/cx_Freeze/issues/745#issuecomment-669614916 to the end.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.3 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
