### ISSUE TITLE
cv2 failed to import

### ISSUE THREAD

**Issue by Mastermind0100** [marcelotduarte/cx_Freeze#761]
import cv2
img = cv2.imread('t1.png')
cv2.imshow('frame',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

I was testing cxfreeze to check if it worked on opencv as shown. 
The error I got:
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "c:\users\atharva\appdata\local\programs\python\python36\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
    module.run()
  File "c:\users\atharva\appdata\local\programs\python\python36\lib\site-packages\cx_Freeze\initscripts\Console.py", line 33, in run
    exec(code,  m.__dict__)
  File "hello.py", line 1, in <module>
  File "c:\users\atharva\appdata\local\programs\python\python36\lib\site-packages\cv2\__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: numpy.core.multiarray failed to import

**Comment by marcelotduarte** [comment]
cx_Freeze 6.3 has just been released.
Assuming this has been resolved.
If you had issues please re-open.

**Comment by Mastermind0100** [comment]
Please guide me to the appropriate way to handle this issue and the
resolution as I cannot find it

Thank you

**Comment by marcelotduarte** [comment]
What version of opencv you're using, please post more information.
It's installed by pip?
