### ISSUE TITLE
pandas plot with matplotlib backend

### ISSUE THREAD

**Issue by Lois31** [marcelotduarte/cx_Freeze#778]
Hello team,

I have a problem when I try to generate a chart bar with pandas/matplotlib once the executable is frozen.
Here is a sample code that reproduces the problem: [pandas_cxfreeze.zip](https://github.com/marcelotduarte/cx_Freeze/files/5509856/pandas_cxfreeze.zip)

After correcting the following issue by following the ticket #653 :
```
Traceback (most recent call last):
  File "/home/ioland/DEV/COTS/PYTHON/V3.8.3/BINARIES/Linux/lib/python3.8/site-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
    module.run()
  File "/home/ioland/DEV/COTS/PYTHON/V3.8.3/BINARIES/Linux/lib/python3.8/site-packages/cx_Freeze/initscripts/Console.py", line 37, in run
    exec(code, {'__name__': '__main__'})
  File "/home/to104437/dev/INSTRUMENTATION_BUS/benchmark/analyzer/pandas_plot.py", line 8, in <module>
    import pandas
  File "/home/ioland/DEV/COTS/PYTHON/V3.8.3/BINARIES/Linux/lib/python3.8/site-packages/pandas/__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "/home/to104437/dev/INSTRUMENTATION_BUS/binaries/linux_x86_64/python3/pandas_plot"
  * The NumPy version is: "1.18.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libopenblasp-r0-34a18dc3.3.7.so: cannot open shared object file: No such file or directory
```

I came across the following error
```
/home/ioland/DEV/COTS/PYTHON/V3.8.3/BINARIES/Linux/lib/python3.8/site-packages/pandas/plotting/_matplotlib/boxplot.py:4: MatplotlibDeprecationWarning: 
The MATPLOTLIBDATA environment variable was deprecated in Matplotlib 3.1 and will be removed in 3.3.
  from matplotlib.artist import setp
Traceback (most recent call last):
  File "/home/ioland/DEV/COTS/PYTHON/V3.8.3/BINARIES/Linux/lib/python3.8/site-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
    module.run()
  File "/home/ioland/DEV/COTS/PYTHON/V3.8.3/BINARIES/Linux/lib/python3.8/site-packages/cx_Freeze/initscripts/Console.py", line 37, in run
    exec(code, {'__name__': '__main__'})
  File "/home/to104437/dev/INSTRUMENTATION_BUS/benchmark/analyzer/pandas_plot.py", line 17, in <module>
    ax = data.plot(kind='bar', title='Example')
  File "/home/ioland/DEV/COTS/PYTHON/V3.8.3/BINARIES/Linux/lib/python3.8/site-packages/pandas/plotting/_core.py", line 847, in __call__
    return plot_backend.plot(data, kind=kind, **kwargs)
  File "/home/ioland/DEV/COTS/PYTHON/V3.8.3/BINARIES/Linux/lib/python3.8/site-packages/pandas/plotting/_matplotlib/__init__.py", line 52, in plot
    import matplotlib.pyplot as plt
  File "/home/ioland/DEV/COTS/PYTHON/V3.8.3/BINARIES/Linux/lib/python3.8/site-packages/matplotlib/pyplot.py", line 40, in <module>
    from matplotlib.figure import Figure, figaspect
  File "/home/ioland/DEV/COTS/PYTHON/V3.8.3/BINARIES/Linux/lib/python3.8/site-packages/matplotlib/figure.py", line 20, in <module>
    from matplotlib import backends, docstring, projections
  File "/home/ioland/DEV/COTS/PYTHON/V3.8.3/BINARIES/Linux/lib/python3.8/site-packages/matplotlib/projections/__init__.py", line 4, in <module>
    from mpl_toolkits.mplot3d import Axes3D
ModuleNotFoundError: No module named 'mpl_toolkits'
```

In order to run my example correctly, I had to add the following folders in the include_files variable as follows:
```
includefiles = []
if sys.platform == 'linux':
    import numpy
    site_package_path = os.path.dirname(os.path.dirname(numpy.__file__))
    includefiles = [(os.path.join(site_package_path, 'numpy.libs'),      os.path.join('lib', 'numpy.libs')),
                    (os.path.join(site_package_path, 'mpl_toolkits'),    os.path.join('lib', 'mpl_toolkits')),
                    (os.path.join(site_package_path, 'matplotlib.libs'), os.path.join('lib', 'matplotlib.libs')),
                    (os.path.join(site_package_path, 'Pillow.libs'),     os.path.join('lib', 'Pillow.libs'))]
```

Platform configuration:

- Linux RHEL 7 x86_64
- Python V3.8.3
- cx_Freeze 6.1
- numpy 1.18.5
- pandas 1.0.4

**Comment by Lois31** [comment]
For information, this problem is fully corrected by cx_Freeze 6.3.

You can close this ticket.
