### ISSUE TITLE
Exception on metadata.version()

### ISSUE THREAD

**Issue by Lois31** [marcelotduarte/cx_Freeze#814]
Hello Team,

I am having problems with two modules: _jira (v2.0.0)_ and _jsonschema (v3.2.0)_.
In both cases, an exception is thrown in the ___init__.py_ file on the following instructions:

**jsonschema**
````
__version__ = metadata.version("jsonschema")
````

**jira**
````
_v = VersionInfo('jira').semantic_version()
__version__ = _v.release_string()
version_info = _v.version_tuple()
````

I use Python v3.8.3

**Comment by marcelotduarte** [comment]
PR #817 is for jira issue
for now you can use --includes=cffi
python setup.py build_exe --includes=cffi

**Comment by marcelotduarte** [comment]
For me jsonschema do not throw exception. Can you put a traceback?

**Comment by marcelotduarte** [comment]
cx_Freeze 6.4.2 has just been released.
Can you check if this has been resolved?

**Comment by marcelotduarte** [comment]
@Lois31 ping

**Comment by Lois31** [comment]
> For me jsonschema do not throw exception. Can you put a traceback?

Sorry for the latency ...

```
Traceback (most recent call last):
  File "/home/ioland/DEV/COTS/PYTHON/V3.8.3/BINARIES/Linux/lib/python3.8/site-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
    module.run()
  File "/home/ioland/DEV/COTS/PYTHON/V3.8.3/BINARIES/Linux/lib/python3.8/site-packages/cx_Freeze/initscripts/Console.py", line 37, in run
    exec(code, {'__name__': '__main__'})
  File "/home/to104437/dev/NETAPI_CODEGEN/src/codegen.py", line 20, in <module>
    from jsonschema import validate
  File "/home/ioland/DEV/COTS/PYTHON/V3.8.3/BINARIES/Linux/lib/python3.8/site-packages/jsonschema/__init__.py", line 34, in <module>
    __version__ = metadata.version("jsonschema")
  File "/home/ioland/DEV/COTS/PYTHON/V3.8.3/BINARIES/Linux/lib/python3.8/importlib/metadata.py", line 531, in version
    return distribution(distribution_name).version
  File "/home/ioland/DEV/COTS/PYTHON/V3.8.3/BINARIES/Linux/lib/python3.8/importlib/metadata.py", line 504, in distribution
    return Distribution.from_name(distribution_name)
  File "/home/ioland/DEV/COTS/PYTHON/V3.8.3/BINARIES/Linux/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: jsonschema
```
I will test with the latest version of cx_Freeze

**Comment by marcelotduarte** [comment]
@Lois31 Please test with the lasted version, 6.4.2, because this can be the error on imporlib.metadata

**Comment by Lois31** [comment]
It's works with cx_Freeze 6.4.2.

I will test with the _Jira_ module.

**Comment by Lois31** [comment]
It also works with the _Jira_ module.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.5 has just been released.
