### ISSUE TITLE
ImportError: No module named 'http.cookies' in Django 1.7b4 after freezing

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#85]
Originally reported by: **keelung yang (Bitbucket: [csoapy](https://bitbucket.org/csoapy), GitHub: Unknown)**

----------------------------------------

following code works in python 3.4.1 before freeze:

```
#!python

import os
import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "DiagnosticOnline.settings")
django.setup()

from django.utils.six.moves import http_cookies
print(http_cookies.SimpleCookie().value_encode(';'))

```
but after freeze it by cx_freeze 4.3.3:

```
#!python

from cx_Freeze import setup, Executable

buildOptions = dict(
    create_shared_zip = False,
    append_script_to_exe = False,
    packages = [],
    includes = [],
    excludes = []
    )

executables = [
    Executable('test.py', base='Console', targetName='Feedback.exe')
]

setup(name='Feedback',
      version = '1.0',
      description = '',
      options = dict(build_exe = buildOptions),
      executables = executables
      )

```
i got:

```
#!bat

D:\work\DPP\Scripts\Python\DiagnosticOnline\build\exe.win32-3.4>Feedback.exe
Traceback (most recent call last):
  File "D:\dev\Python\lib\site-packages\cx_Freeze\initscripts\Console.py", line
27, in <module>
    exec(code, m.__dict__)
  File "test.py", line 5, in <module>
  File "D:\dev\Python\lib\site-packages\django-1.7b4-py3.4.egg\django\__init__.p
y", line 18, in setup
    from django.utils.log import configure_logging
  File "X:\Python34-x32\lib\importlib\_bootstrap.py", line 2237, in _find_and_lo
ad
  File "X:\Python34-x32\lib\importlib\_bootstrap.py", line 2226, in _find_and_lo
ad_unlocked
  File "X:\Python34-x32\lib\importlib\_bootstrap.py", line 1191, in _load_unlock
ed
  File "X:\Python34-x32\lib\importlib\_bootstrap.py", line 1161, in _load_backwa
rd_compatible
  File "D:\dev\Python\lib\site-packages\django-1.7b4-py3.4.egg\django\utils\log.
py", line 10, in <module>
    from django.views.debug import ExceptionReporter, get_exception_reporter_fil
ter
  File "X:\Python34-x32\lib\importlib\_bootstrap.py", line 2237, in _find_and_lo
ad
  File "X:\Python34-x32\lib\importlib\_bootstrap.py", line 2226, in _find_and_lo
ad_unlocked
  File "X:\Python34-x32\lib\importlib\_bootstrap.py", line 1191, in _load_unlock
ed
  File "X:\Python34-x32\lib\importlib\_bootstrap.py", line 1161, in _load_backwa
rd_compatible
  File "D:\dev\Python\lib\site-packages\django-1.7b4-py3.4.egg\django\views\debu
g.py", line 10, in <module>
    from django.http import (HttpResponse, HttpResponseServerError,
  File "X:\Python34-x32\lib\importlib\_bootstrap.py", line 2237, in _find_and_lo
ad
  File "X:\Python34-x32\lib\importlib\_bootstrap.py", line 2226, in _find_and_lo
ad_unlocked
  File "X:\Python34-x32\lib\importlib\_bootstrap.py", line 1191, in _load_unlock
ed
  File "X:\Python34-x32\lib\importlib\_bootstrap.py", line 1161, in _load_backwa
rd_compatible
  File "D:\dev\Python\lib\site-packages\django-1.7b4-py3.4.egg\django\http\__ini
t__.py", line 1, in <module>
    from django.http.cookie import SimpleCookie, parse_cookie
  File "X:\Python34-x32\lib\importlib\_bootstrap.py", line 2237, in _find_and_lo
ad
  File "X:\Python34-x32\lib\importlib\_bootstrap.py", line 2226, in _find_and_lo
ad_unlocked
  File "X:\Python34-x32\lib\importlib\_bootstrap.py", line 1191, in _load_unlock
ed
  File "X:\Python34-x32\lib\importlib\_bootstrap.py", line 1161, in _load_backwa
rd_compatible
  File "D:\dev\Python\lib\site-packages\django-1.7b4-py3.4.egg\django\http\cooki
e.py", line 5, in <module>
    from django.utils.six.moves import http_cookies
  File "X:\Python34-x32\lib\importlib\_bootstrap.py", line 2281, in _handle_from
list
  File "D:\dev\Python\lib\site-packages\django-1.7b4-py3.4.egg\django\utils\six.
py", line 91, in __get__
    result = self._resolve()
  File "D:\dev\Python\lib\site-packages\django-1.7b4-py3.4.egg\django\utils\six.
py", line 110, in _resolve
    return _import_module(self.mod)
  File "D:\dev\Python\lib\site-packages\django-1.7b4-py3.4.egg\django\utils\six.
py", line 76, in _import_module
    __import__(name)
  File "X:\Python34-x32\lib\importlib\_bootstrap.py", line 2237, in _find_and_lo
ad
  File "X:\Python34-x32\lib\importlib\_bootstrap.py", line 2224, in _find_and_lo
ad_unlocked
ImportError: No module named 'http.cookies'

D:\work\DPP\Scripts\Python\DiagnosticOnline\build\exe.win32-3.4>

```

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/85

**Comment by anthony-tuininga** [comment]
*Original comment by* **keelung yang (Bitbucket: [csoapy](https://bitbucket.org/csoapy), GitHub: Unknown)**:

----------------------------------------

after importing http.cookies & html.parser in my test.py or put them into buildOptions, it workd!

**Comment by anthony-tuininga** [comment]
*Original comment by* **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**:

----------------------------------------

I suspect that cx_Freeze won't be able to automatically detect any imports that are loaded by `six.moves`.

**Comment by anthony-tuininga** [comment]
*Original comment by* **ravi p (Bitbucket: [master1988](https://bitbucket.org/master1988), GitHub: Unknown)**:

----------------------------------------

@keelung yang: Is there any other solution for this? For me, even import http.cookies and html.parser fails as well.
ImportError: No module named http.cookies
ImportError: No module named html.parser

using freeze.py with Python 2.7.6. Any help would be very appreciated.

Thanks.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**:

----------------------------------------

@master1988 `http.cookies` and `html.parser` are the Python 3 names. If you're using Python 2, you should use the Python 2 names for those modules. Look at the table here: http://pythonhosted.org/six/#module-six.moves

**Comment by marcelotduarte** [comment]
Closing due to inactivity. 
cx_Freeze 6.1 has just been released.
