### ISSUE TITLE
Pygments freeze fail when using lexers or formatters

### ISSUE THREAD

**Issue by lexa** [marcelotduarte/cx_Freeze#862]
When using the following example from pygments documentation cx_Freeze misses imports for pygment.lexers.* and pygments.formatters.*

    from pygments import highlight
    from pygments.lexers import PythonLexer
    from pygments.formatters import HtmlFormatter
    
    code = 'print "Hello World"'
    print(highlight(code, PythonLexer(), HtmlFormatter()))

Frozen packages fails on import:

    Traceback (most recent call last):
      File "/home/aleksei/.linuxbrew/opt/python@3.8/lib/python3.8/site-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
        module.run()
      File "/home/aleksei/.linuxbrew/opt/python@3.8/lib/python3.8/site-packages/cx_Freeze/initscripts/Console.py", line 33, in run
        exec(code,  m.__dict__)
      File "1.py", line 2, in <module>
        from pygments.lexers import PythonLexer
      File "/home/aleksei/.local/lib/python3.8/site-packages/pygments/lexers/__init__.py", line 329, in __getattr__
        _load_lexers(info[0])
      File "/home/aleksei/.local/lib/python3.8/site-packages/pygments/lexers/__init__.py", line 45, in _load_lexers
        mod = __import__(module_name, None, None, ['__all__'])
    ModuleNotFoundError: No module named 'pygments.lexers.python'

**Comment by marcelotduarte** [comment]
cx_Freeze 6.5 has just been released.
