### ISSUE TITLE
PyQt4 + Python Installation using cx_freeze

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#88]
Originally reported by: **ramas sami (Bitbucket: [ramas09](https://bitbucket.org/ramas09), GitHub: Unknown)**

----------------------------------------

Hi Anthony,

I have created GUI using PyQt4 and linked with Python code using PyDev interpreters on the Eclipse environment now I want to create a executable of the project

Code:
----------------------------------------------------
from cx_Freeze import setup,Executable

includefiles = ['README.txt', 'CompanyLogo.jpg', 'Plot.py']
includes = []
excludes = ['Tkinter']

setup(
    name = 'MONTHLY REPORT',
    version = '0.1',
    description = 'A general enhancement utility',
    author = 'lenin',
    author_email = 'le...@null.com',
    options = {'build_exe': {'excludes':excludes,'include_files':includefiles}}, 
    executables = [Executable('Main.py')])
---------------------------------------------------------------------

It seems creating the build but when I click the Main.exe doesn't want to open, please help me fix this.

Thank you so much.

Ramas

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/88

**Comment by anthony-tuininga** [comment]
*Original comment by* **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**:

----------------------------------------

Try running the exe from a command prompt - there might be an error message that you don't see when double clicking it.

**Comment by anthony-tuininga** [comment]
*Original comment by* **ramas sami (Bitbucket: [ramas09](https://bitbucket.org/ramas09), GitHub: Unknown)**:

----------------------------------------

Thanks Thomas,
Will get back to you after trying your comments.
Thanks you so much...

Best Regards--Ramas

**Comment by anthony-tuininga** [comment]
*Original comment by* **ramas sami (Bitbucket: [ramas09](https://bitbucket.org/ramas09), GitHub: Unknown)**:

----------------------------------------

C:\Python33\build\exe.win-amd64-3.3>Main.exe
Traceback (most recent call last):
  File "c:\python33\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27
, in <module>
    exec(code, m.__dict__)
  File "Main.py", line 8, in <module>
  File "c:\Python\64-bit\3.3\lib\importlib\_bootstrap.py", line 1567, in _find_a
nd_load
  File "c:\Python\64-bit\3.3\lib\importlib\_bootstrap.py", line 1534, in _find_a
nd_load_unlocked
  File "c:\python33\lib\site-packages\numpy\__init__.py", line 168, in <module>
    from . import add_newdocs
  File "c:\Python\64-bit\3.3\lib\importlib\_bootstrap.py", line 1616, in _handle
_fromlist
  File "c:\Python\64-bit\3.3\lib\importlib\_bootstrap.py", line 313, in _call_wi
th_frames_removed
  File "c:\Python\64-bit\3.3\lib\importlib\_bootstrap.py", line 1567, in _find_a
nd_load
  File "c:\Python\64-bit\3.3\lib\importlib\_bootstrap.py", line 1534, in _find_a
nd_load_unlocked
  File "c:\python33\lib\site-packages\numpy\add_newdocs.py", line 13, in <module
>
    from numpy.lib import add_newdoc
  File "c:\Python\64-bit\3.3\lib\importlib\_bootstrap.py", line 1567, in _find_a
nd_load
  File "c:\Python\64-bit\3.3\lib\importlib\_bootstrap.py", line 1534, in _find_a
nd_load_unlocked
  File "c:\python33\lib\site-packages\numpy\lib\__init__.py", line 8, in <module
>
    from .type_check import *
  File "c:\Python\64-bit\3.3\lib\importlib\_bootstrap.py", line 1567, in _find_a
nd_load
  File "c:\Python\64-bit\3.3\lib\importlib\_bootstrap.py", line 1534, in _find_a
nd_load_unlocked
  File "c:\python33\lib\site-packages\numpy\lib\type_check.py", line 11, in <mod
ule>
    import numpy.core.numeric as _nx
  File "c:\Python\64-bit\3.3\lib\importlib\_bootstrap.py", line 1567, in _find_a
nd_load
  File "c:\Python\64-bit\3.3\lib\importlib\_bootstrap.py", line 1514, in _find_a
nd_load_unlocked
  File "c:\Python\64-bit\3.3\lib\importlib\_bootstrap.py", line 313, in _call_wi
th_frames_removed
  File "c:\Python\64-bit\3.3\lib\importlib\_bootstrap.py", line 1567, in _find_a
nd_load
  File "c:\Python\64-bit\3.3\lib\importlib\_bootstrap.py", line 1534, in _find_a
nd_load_unlocked
  File "c:\python33\lib\site-packages\numpy\core\__init__.py", line 6, in <modul
e>
    from . import multiarray
  File "c:\Python\64-bit\3.3\lib\importlib\_bootstrap.py", line 1616, in _handle
_fromlist
  File "c:\Python\64-bit\3.3\lib\importlib\_bootstrap.py", line 313, in _call_wi
th_frames_removed
  File "c:\Python\64-bit\3.3\lib\importlib\_bootstrap.py", line 1567, in _find_a
nd_load
  File "c:\Python\64-bit\3.3\lib\importlib\_bootstrap.py", line 1534, in _find_a
nd_load_unlocked
  File "ExtensionLoader_numpy_core_multiarray.py", line 22, in <module>
  File "ExtensionLoader_numpy_core_multiarray.py", line 21, in __bootstrap__
ImportError: No module named None

C:\Python33\build\exe.win-amd64-3.3>

**Comment by anthony-tuininga** [comment]
*Original comment by* **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**:

----------------------------------------

Sorry, I can't think what would be causing that. Are you using the latest cx_Freeze (4.3.3)?

**Comment by anthony-tuininga** [comment]
*Original comment by* **ramas sami (Bitbucket: [ramas09](https://bitbucket.org/ramas09), GitHub: Unknown)**:

----------------------------------------

Hi Thomas,
Good morning,
Yes I am using the latest version of cx_freeze, any suggestions on who would give me a solution.
Thanks

Best Regards
--Ramas07574896485

**Comment by anthony-tuininga** [comment]
*Original comment by* **ramas sami (Bitbucket: [ramas09](https://bitbucket.org/ramas09), GitHub: Unknown)**:

----------------------------------------

Hi Thomas,
This is the code have used it....
from cx_Freeze import setup, Executable
executables = [    Executable('Main.py')]
includes = ["zmq", "zmq.utils.garbage", "zmq.backend.cython"]
setup(name='test',      version='0.1',      description='Test',      options = {"build_exe" : {"includes" : includes }},      executables=executables      )

Please spot any mistakes in there...Thanks

Best RegardsRamas

**Comment by anthony-tuininga** [comment]
*Original comment by* **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**:

----------------------------------------

I can't see any mistakes there, but try adding a `"packages": ["numpy"]` field to the dict where "includes" already is. "packages" works like includes, but it includes all submodules and packages as well.

**Comment by anthony-tuininga** [comment]
*Original comment by* **ramas sami (Bitbucket: [ramas09](https://bitbucket.org/ramas09), GitHub: Unknown)**:

----------------------------------------

Thanks for the reply Thomas,
I did include packages but still it throws up same error (checked line by line with the previous error)
I have using PyQt4, does it make any difference in building executables.
I may send all the files which I have used (trying) to create the executables.
Please give your precious time to fix this error, coz I have stuck in this for very long time.   
Thank you so much.
from cx_Freeze import setup, Executable
executables = [Executable('Main.py')]packages = ["numpy","reportlab","matplotlib"]
#includes = ["zmq", "zmq.utils.garbage", "zmq.backend.cython"]includes = []
setup(name='test',      version='0.1',      description='Test',      options = {"build_exe" : {"includes" : includes,"packages":packages }},      executables=executables      )
Best Regards--Ramas

**Comment by anthony-tuininga** [comment]
*Original comment by* **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**:

----------------------------------------

Can you post the output that's shown when you freeze it? It will be long, so stick it in a pastebin and post the link here.

**Comment by anthony-tuininga** [comment]
*Original comment by* **ramas sami (Bitbucket: [ramas09](https://bitbucket.org/ramas09), GitHub: Unknown)**:

----------------------------------------

Hi Thomas,
Thanks for the reply,
It took nearly 1 and half hours to copy the build process (I didn't know that is such a big process)....
The link....
http://pastebin.com/ThnxdyH7
Please give me a positive solution after verifying the process.....
Thanks again...

Best Regards,Ramas.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**:

----------------------------------------

OK, I think I see the bug. Can you try editing the file `c:\python33\lib\site-packages\cx_Freeze\freezer.py`? At line 263, you should see this:

```python
dependentFiles = cx_Freeze.util.GetDependentFiles(path)
```

Wrap a try/except around it, so it looks like this:

```python
try:
    dependentFiles = cx_Freeze.util.GetDependentFiles(path)
except cx_Freeze.util.BindError:
    dependentFiles = []
```

Then try freezing again.

**Comment by anthony-tuininga** [comment]
*Original comment by* **ramas sami (Bitbucket: [ramas09](https://bitbucket.org/ramas09), GitHub: Unknown)**:

----------------------------------------

Hi Thomas,
You are diamond!!!
With your instructions  successfully created the executables and have tested in other systems as well, works fine.
Thank you so much for your time, effort, help... 
Best Regards,Ramas.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**:

----------------------------------------

OK, great. So the issue is that when it can't read a module as Python code (in this case, because it's not valid syntax for the version of Python you're using), it assumes that it must be a compiled library. I think that can only cause a problem on Windows, because of the different way we handle compiled libraries. I'll make a PR with that change.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**:

----------------------------------------

See pull request #56

**Comment by anthony-tuininga** [comment]
*Original comment by* **Mark Grandi (Bitbucket: [mgrandi](https://bitbucket.org/mgrandi), GitHub: [mgrandi](https://github.com/mgrandi))**:

----------------------------------------

Adding onto this issue, I just had an issue where i was getting this error , because i hadn't compiled a super bleeding edge version of cx_freeze, and i had a syntax error in one of python files, which lead it to try and compile it as a windows dll, and then failing

shouldn't there be an error if it can't read the file and it knows its meant to be a python file (ends in .py)? Now with this behavior it basically ignores the file entirely rather then telling the user they forgot a comma somewhere or something.

**Comment by marcelotduarte** [comment]
Closing due to inactivity. 
cx_Freeze 6.1 has just been released.
