### ISSUE TITLE
Regression in 6.5+  `ImportError: No module named 'cxbugbin__main__'`

### ISSUE THREAD

**Issue by spaam** [marcelotduarte/cx_Freeze#891]
This was working in 6.4.2 and started to fail from version 6.5+
using Python 3.9.1  from brew macOS

**traceback:**
```
xprmnt dev/cxbug » python3 setup.py build_exe
running build_exe
Traceback (most recent call last):
  File "/Users/johan/dev/cxbug/setup.py", line 7, in <module>
    setup(  name = "guifoo",
  File "/usr/local/lib/python3.9/site-packages/cx_Freeze/dist.py", line 392, in setup
    distutils.core.setup(**attrs)
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.9/site-packages/cx_Freeze/dist.py", line 260, in run
    freezer.Freeze()
  File "/usr/local/lib/python3.9/site-packages/cx_Freeze/freezer.py", line 754, in Freeze
    self._FreezeExecutable(executable)
  File "/usr/local/lib/python3.9/site-packages/cx_Freeze/freezer.py", line 227, in _FreezeExecutable
    finder.IncludeFile(exe.main_script, exe.main_module_name)
  File "/usr/local/lib/python3.9/site-packages/cx_Freeze/finder.py", line 618, in IncludeFile
    module = self._load_module(name, path, deferred_imports)
  File "/usr/local/lib/python3.9/site-packages/cx_Freeze/finder.py", line 371, in _load_module
    raise ImportError(f"No module named {name!r}", name=name)
ImportError: No module named 'cxbugbin__main__'
xprmnt dev/cxbug »
```

**test case:**
`setup.py`
```
import sys
from cx_Freeze import setup, Executable
build_exe_options = {"packages": ["os"], "excludes": ["tkinter"]}
setup(  name = "guifoo",
        version = "0.1",
        description = "My GUI application!",
        options = {"build_exe": build_exe_options},
        executables = [Executable("bin/cxbugbin", base=None)])
```
`bin/cxbugbin`
```
import cxbug

if __name__ == "__main__":
    cxbug.main()
```
`cxbug/__init__.py`
```
def main():
    print("hello world")
```
`cxbug/__main__.py`
```
import sys

if __package__ is None and not hasattr(sys, "frozen"):
    import os.path
    sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import cxbug
if __name__ == "__main__":
    cxbug.main()
```

**Comment by nilslindemann** [comment]
Can confirm. cx-Freeze seems not to find the Python standard libs. I get a `missing __main__.py` error.

The operating system is Windows v 7, Python is v 3.8.2, cx-Freeze is v 6.5.2.

The PATH contains `(...);C:\run\Python-3.8\Scripts;C:\run\Python-3.8;(...)`, sys.path is `['', 'C:\\run\\Python-3.8\\python38.zip', 'C:\\run\\Python-3.8\\DLLs', 'C:\\run\\Python-3.8\\lib', 'C:\\run\\Python-3.8', 'C:\\run\\Python-3.8\\lib\\site-packages']` (notice, there is no `python38.zip` in `C:\run\Python-3.8`). Also tried adding these to the PYTHONPATH variable.

The python file to be frozen contains `print('Hello World')`.

This is what I do:

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Alle Rechte vorbehalten.

C:\run\code\My_Project>cd C:\

C:\>C:\run\Python-3.8\Scripts\cxfreeze.exe C:\run\code\My_Project\helloworld.py --target-dir C:\run\code\My_Project\build
copying c:\run\python-3.8\vcruntime140.dll -> C:\run\code\My_Project\build\vcruntime140.dll
copying c:\run\python-3.8\python3.dll -> C:\run\code\My_Project\build\python3.dll
copying c:\run\python-3.8\python38.dll -> C:\run\code\My_Project\build\python38.dll
copying c:\run\python-3.8\lib\site-packages\cx_Freeze\bases\Console.exe -> C:\run\code\My_Project\build\helloworld.exe
Traceback (most recent call last):
  File "c:\run\python-3.8\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\run\python-3.8\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\run\Python-3.8\Scripts\cxfreeze.exe\__main__.py", line 7, in <module>
  File "c:\run\python-3.8\lib\site-packages\cx_Freeze\main.py", line 255, in main
    freezer.Freeze()
  File "c:\run\python-3.8\lib\site-packages\cx_Freeze\freezer.py", line 765, in Freeze
    self._WriteModules(fileName, self.finder)
  File "c:\run\python-3.8\lib\site-packages\cx_Freeze\freezer.py", line 592, in _WriteModules
    self.constantsModule.Create(finder)
  File "c:\run\python-3.8\lib\site-packages\cx_Freeze\freezer.py", line 956, in Create
    raise ConfigError(
cx_Freeze.common.ConfigError: No file named C:\run\Python-3.8\Scripts\cxfreeze.exe\__main__.py (for module __main__)

C:\>cd C:\run\code\My_Project\build

C:\run\code\My_Project\build>helloworld.exe
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'C:\run\code\My_Project\build\helloworld.exe'
  isolated = 0
  environment = 0
  user site = 1
  import site = 0
  sys._base_executable = 'C:\\run\\code\\My_Project\\build\\helloworld.exe'
  sys.base_prefix = ''
  sys.base_exec_prefix = ''
  sys.executable = 'C:\\run\\code\\My_Project\\build\\helloworld.exe'
  sys.prefix = ''
  sys.exec_prefix = ''
  sys.path = [
    'C:\\run\\code\\My_Project\\build\\lib\\library.zip',
    'C:\\run\\code\\My_Project\\build\\lib',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00001880 (most recent call first):
<no Python frame>

C:\run\code\My_Project\build>
```

cx-Freeze creates `helloworld.exe`, `vcruntime140.dll`, `python3.dll` and `python38.dll` in the `build` dir, but not the `lib` folder and not `lib\library.zip`.

**Comment by marcelotduarte** [comment]
@nilslindemann Put the contents of your setup.py.

**Comment by nilslindemann** [comment]
@marcelotduarte I do not use a setup.py, as the [docs](https://cx-freeze.readthedocs.io/en/latest/script.html#script) say that is not necessary, is it?

I just tried downgrading to v6.4.2 (`pip install --upgrade cx-Freeze==6.4.2`) according to [this SO answer](https://stackoverflow.com/a/65777173). Then it works. It creates the lib folder in the `build` dir, and the standard libs inside of it.

**Comment by marcelotduarte** [comment]
@nilslindemann Sorry, you used cxfreeze command line.
Can you try cxfreeze 6.5.1 or 6.5?

**Comment by nilslindemann** [comment]
@marcelotduarte Both 6.5 and 6.5.1 give the same error.

**Comment by marcelotduarte** [comment]
Tomorrow I will check these errors and correct them.

**Comment by hefischer** [comment]
I got this error on a python entry named .pyw, and cx_freeze started cooperating when removing the w from the suffix.

**Comment by spaam** [comment]
if i changed the name of the file like what @hefischer said. but from `bin/cxbugbin` to `bin/cxbugbin.py` it works.  hopefully it will narrow it down where the issue is :)

**Comment by marcelotduarte** [comment]
In my virtual machine a simple hello.py works, but in a Github Actions VM, don't. The difference is that I use the 'wheel' package to publish cx_Freeze. 
Here are 2 issues:
1) reported by @spaam - using setup build - if you use `'cxbug/__main__.py'` in the Executable() probably works (I do not test your sample yet - but tested a hello sample without an extension)
2) reported by @nilslindemann - using cxfreeze command line - where the wheel goes wrong.

**Comment by marcelotduarte** [comment]
#893 fix the first regression

**Comment by spaam** [comment]
@marcelotduarte, the fix in master works for me. thank you for fixing this ❤️

**Comment by nilslindemann** [comment]
@marcelotduarte Sorry when I mixed up issues. I thought they were the same (both are about missing `__main__.py`'s).

**Comment by marcelotduarte** [comment]
#894 fix the second issue
cx_Freeze 6.5.3 has just been released.
cc @nilslindemann @hefischer @spaam

**Comment by nilslindemann** [comment]
Thanks a ton @marcelotduarte it works!
