### ISSUE TITLE
ImportError: No module named 'mitmproxy.io.proto' with 6.5.3 (no errors with 6.4.2)

### ISSUE THREAD

**Issue by sarnold** [marcelotduarte/cx_Freeze#900]
I'm still trying to get my first "frozen" app working (so far so good with 6.4.2 running frozen Linux app) across the 3 main platforms, but I could not use the latest release to get anywhere.  After dropping back to 6.4.2 things seem to work as expected, at least I could see the obvious missing imports and start adding them to my freeze.py script.

AFAICT the errors had nothing to do with what I was packaging, rather, the above errors happened several times (but with different python deps, eg, ``importlib_resources``).  Now when I go back to 6.5.3 (with a working freeze.py from 6.4.2) I get more import errors on my own deps *that are included in the freeze script* via ``'packages'``.  Here's what I have so far: https://github.com/freepn/freepn-proxy/tree/pkg-clean  but I have no idea how to proceed (except pinning the version of cx_freeze in my build environment).

**Comment by marcelotduarte** [comment]
Put some details about the Linux, python version, python distributed with Linux ou conda, etc.
Maybe is an issue with importlib-metadata, try to uninstall it and cx-freeze then install cx-freeze only (cx-freeze will install it as a dependent).
importlib-metadata should be installed with py39 too because of a bug in importlib.metadata.

**Comment by sarnold** [comment]
Using virtualenvwrapper and python 3.8; my own github CI uses python3_{6..9}.  More build system info:

```
$  eselect python list
Available Python interpreters, in order of preference:
  [1]   python3.8
  [2]   python3.7
  [3]   python3.9 (fallback)

$  emerge --info 
Portage 3.0.12 (python 3.8.7-candidate-1, default/linux/amd64/17.1/desktop/gnome, gcc-10.2.0, glibc-2.32-r5, 5.9.8-gentoo x86_64)
=================================================================
System uname: Linux-5.9.8-gentoo-x86_64-Intel-R-_Core-TM-_i7-4600U_CPU_@_2.10GHz-with-glibc2.2.5
KiB Mem:     8031448 total,    655952 free
KiB Swap:   12021752 total,   8235000 free
Timestamp of repository gentoo: Mon, 21 Dec 2020 17:00:01 +0000
Head commit of repository gentoo: 903d72e8d5ff6e1b7d3ac83c1d232879f242f3df
Head commit of repository sakaki-tools: 571e34870d665e98677caecbd56cf0d399ee4b3c

sh bash 5.1_p4
ld GNU gold (Gentoo 2.35.1 p2 2.35.1) 1.16
app-shells/bash:          5.1_p4::gentoo
dev-java/java-config:     2.3.1::gentoo
dev-lang/perl:            5.30.3-r1::gentoo
dev-lang/python:          3.7.9-r1::gentoo, 3.8.7_rc1::gentoo, 3.9.1::gentoo
dev-util/cmake:           3.19.2::gentoo
sys-apps/baselayout:      2.7-r1::gentoo
sys-apps/openrc:          0.42.1::gentoo
sys-apps/sandbox:         2.20::gentoo
sys-devel/autoconf:       2.13-r1::gentoo, 2.69-r5::gentoo
sys-devel/automake:       1.16.3-r1::gentoo
sys-devel/binutils:       2.35.1-r1::gentoo
sys-devel/gcc:            10.2.0-r4::gentoo
sys-devel/gcc-config:     2.3.2-r1::gentoo
sys-devel/libtool:        2.4.6-r6::gentoo
sys-devel/make:           4.3::gentoo
sys-kernel/linux-headers: 5.10::gentoo (virtual/os-headers)
sys-libs/glibc:           2.32-r5::gentoo
Repositories:

gentoo
    location: /usr/portage
    sync-type: rsync
    sync-umask: 022
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    sync-user: portage:portage
    priority: -1000
    sync-rsync-extra-opts: 
    sync-rsync-verify-metamanifest: yes
    sync-rsync-verify-max-age: 24
    sync-rsync-verify-jobs: 1

cross-armv7
    location: /usr/local/portage/cross-armv7
    sync-umask: 022
    sync-user: portage:portage
    masters: gentoo

nerdboy
    location: /usr/local/portage/nerdboy
    masters: gentoo
    priority: 0
```

**Comment by sarnold** [comment]
I tried uninstalling cx_freeze but now I'm confused between importlibs - cx_freeze depends on importlib-metadata (so I removed both) and my app depends on importlib-resources (for less than py39).  I uninstalled all of that, reinstalled cx_freeze:

```
Successfully installed cx-freeze-6.5.3 importlib-metadata-3.4.0
```

and pip installed from local checkout:

```
Successfully installed freepn-proxy-0.0.1 importlib-resources-5.1.0
```

but with no change in the outcome; the errors are all on multiple nested imports already included in ``packages``.

```
$ python setup_freeze.py build
running build
running build_py
running egg_info
writing freepn_proxy.egg-info/PKG-INFO
writing dependency_links to freepn_proxy.egg-info/dependency_links.txt
writing entry points to freepn_proxy.egg-info/entry_points.txt
writing requirements to freepn_proxy.egg-info/requires.txt
writing top-level names to freepn_proxy.egg-info/top_level.txt
reading manifest file 'freepn_proxy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*.py[cod]' found anywhere in distribution
warning: no previously-included files matching '__pycache__' found anywhere in distribution
writing manifest file 'freepn_proxy.egg-info/SOURCES.txt'
running build_exe
Traceback (most recent call last):
  File "setup_freeze.py", line 52, in <module>
    setup(
  File "/home/nerdboy/.virtualenvs/proxy-bld/lib/python3.8/site-packages/cx_Freeze/dist.py", line 392, in setup
    distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/nerdboy/.virtualenvs/proxy-bld/lib/python3.8/site-packages/cx_Freeze/dist.py", line 260, in run
    freezer.Freeze()
  File "/home/nerdboy/.virtualenvs/proxy-bld/lib/python3.8/site-packages/cx_Freeze/freezer.py", line 758, in Freeze
    self.finder = self._GetModuleFinder()
  File "/home/nerdboy/.virtualenvs/proxy-bld/lib/python3.8/site-packages/cx_Freeze/freezer.py", line 465, in _GetModuleFinder
    finder.IncludePackage(name)
  File "/home/nerdboy/.virtualenvs/proxy-bld/lib/python3.8/site-packages/cx_Freeze/finder.py", line 647, in IncludePackage
    module = self._import_module(name, deferred_imports)
  File "/home/nerdboy/.virtualenvs/proxy-bld/lib/python3.8/site-packages/cx_Freeze/finder.py", line 291, in _import_module
    raise ImportError(f"No module named {name!r}")
ImportError: No module named 'mitmproxy.io.proto'
```

**Comment by marcelotduarte** [comment]
importlib-metadata is a backport of importlib.metadata, and I use the former because a bug in the standard library.
importlib-resources is a backport of importlib.resources
 
try to build with the command:
python setup_freeze.py build_exe

because I see confusion in the logs:
```
running build_py
running egg_info
writing freepn_proxy.egg-info/PKG-INFO
```

**Comment by sarnold** [comment]
What exactly is the difference between ``build`` and ``build_exe``?

Also, same error:

```
  File "/home/nerdboy/.virtualenvs/proxy-bld/lib/python3.8/site-packages/cx_Freeze/finder.py", line 291, in _import_module
    raise ImportError(f"No module named {name!r}")
ImportError: No module named 'mitmproxy.io.proto'
```

**Comment by marcelotduarte** [comment]
cx_Frreze uses a distutils interface, and extend it with build_exe, then build calls build_py, .... and build_exe
if you use build_exe you will go directly to the point.

A package/subpackage needs a  `__init__`, and  `mitmproxy.io.proto` hasn't. I'll investigate how to fix this.

**Comment by marcelotduarte** [comment]
@sarnold PR #906 fix this issue

If you have a C compiler, you can test the PR:
`pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@refs/pull/906/head`

The __pycache__ warning is not from cx_Freeze, is from build_py

To optimize your build, 'excludes': unwanted_packages should contain 'tkinter' (Tkinter is from py2 and is excluded by cx_Freeze)

**Comment by sarnold** [comment]
using #906 

```
Installing collected packages: cx-Freeze
  Attempting uninstall: cx-Freeze
    Found existing installation: cx-Freeze 6.4.2
    Uninstalling cx-Freeze-6.4.2:
      Successfully uninstalled cx-Freeze-6.4.2
Successfully installed cx-Freeze-6.6.dev0
```
and:
```
$ ls build/exe.linux-x86_64-3.8/
freepn  freepn_proxy  lib
```
equals success, Thanks!

**Comment by marcelotduarte** [comment]
cx_Freeze 6.6 has just been released.
Assuming this has been resolved.
If you had issues please open a new issue.
