### ISSUE TITLE
Colored Text Crashing CX freeze

### ISSUE THREAD

**Issue by hourlyfish** [marcelotduarte/cx_Freeze#939]
Hi, I have found a crash when I'm trying to export my little game project using CX Freeze. I don't know if this is fixable, or worth fixing, but whenever I run it through console I get a long error.

"D:\Python\Python382\Programs\TextGame\dist>main.exe
Traceback (most recent call last):
  File "d:\python\python382\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 74, in run
    module.run()
  File "d:\python\python382\lib\site-packages\cx_Freeze\initscripts\Console.py", line 36, in run
    exec(code, m.__dict__)
  File "Main.py", line 1, in <module>
  File "\<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "\<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "\<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "\<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "\<frozen zipimport>", line 259, in load_module
  File "D:\Python\Python382\Programs\TextGame\Army.py", line 1, in <module>
    from Color import *
  File "\<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "\<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "\<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "\<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "\<frozen zipimport>", line 259, in load_module
  File "D:\Python\Python382\Programs\TextGame\Color.py", line 23, in <module>
    printColored("E","green")
  File "D:\Python\Python382\Programs\TextGame\Color.py", line 21, in printColored
    stdout.shell.write(str(text),colorList[color])
AttributeError: '_io.TextIOWrapper' object has no attribute 'shell' "

I put the offending file as a txt, but it should run in IDLE just fine. I'm relatively new to programming, so not sure if this is a bug or more just a feature that is purposefully not implemented for some technical reason. If you have any alternative solutions, please feel free to let me know.

[color.txt](https://github.com/marcelotduarte/cx_Freeze/files/6045438/color.txt)

**Comment by marcelotduarte** [comment]
This color.txt doesn't run for me. Same error in python:
python3 color.py
Traceback (most recent call last):
  File "color.py", line 23, in <module>
    printColored("EEEE","green")
  File "color.py", line 21, in printColored
    stdout.shell.write(str(text),colorList[color])
AttributeError: '_io.TextIOWrapper' object has no attribute 'shell'

**Comment by hourlyfish** [comment]
Interesting! Is stdout.shell.write an IDLE-specific thing? I swear it works for me. It may be that I have a different version or something?
![image](https://user-images.githubusercontent.com/49924974/109211284-a51cbb00-7773-11eb-8236-c2d16eb367c9.png)

**Comment by marcelotduarte** [comment]
As far I know, stdout hasn't an attribute shell.
I'm using python 3.8.6 on Linux, but I think that the API is the same on windows.
If it is IDLE-specific thing, you should import the package that monkey patch the stdout to freeze it.

**Comment by marcelotduarte** [comment]
For reference: https://docs.python.org/3/library/idle.html#user-output-in-shell
