### ISSUE TITLE
Packaging error with recursive naming

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#94]
Originally reported by: **Anonymous**

----------------------------------------

I have tried to come up with a more minimal example, but I can't seem to.  The problem is this:  I have a simple package that used to package fine with an older version of cx_freeze, but hasn't worked for quite some time.  I have a top-level package called CoolProp, and a cython extension also called CoolProp inside the top-level package (not good style, but now we are stuck with it).  This seems to confuse cx_freeze, and I get the following output for the stripped down setup.py and demo.py files attached.

A quick pip install CoolProp will get you CoolProp.

I tried to dig into the source code to figure out if I could fix it, but I got horribly lost and made little progress after several hours of work.

When I run the setup.py script, I get the following behavior:
```
C:\Users\Belli\Desktop\failing_cx_freeze>python setup.py build
running build
running build_exe
creating directory demo
copying C:\Miniconda\lib\site-packages\cx_Freeze\bases\Win32GUI.exe -> demo\demo.exe
Stamped: demo\demo.exe
writing zip file demo\demo.zip

  Name                      File
  ----                      ----
m __main__                  demo.py
m cx_Freeze__init__         C:\Miniconda\lib\site-packages\cx_Freeze\initscripts\Console.py

Traceback (most recent call last):
  File "setup.py", line 47, in <module>
    executables = [GUI2Exe_Target_1]
  File "C:\Miniconda\lib\site-packages\cx_Freeze\dist.py", line 362, in setup
    distutils.core.setup(**attrs)
  File "C:\Miniconda\lib\distutils\core.py", line 152, in setup
    dist.run_commands()
  File "C:\Miniconda\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Miniconda\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Miniconda\lib\distutils\command\build.py", line 127, in run
    self.run_command(cmd_name)
  File "C:\Miniconda\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "C:\Miniconda\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Miniconda\lib\site-packages\cx_Freeze\dist.py", line 232, in run
    freezer.Freeze()
  File "C:\Miniconda\lib\site-packages\cx_Freeze\freezer.py", line 610, in Freeze
    self.compress, self.copyDependentFiles)
  File "C:\Miniconda\lib\site-packages\cx_Freeze\freezer.py", line 510, in _WriteModules
    module.Create(finder)
  File "C:\Miniconda\lib\site-packages\cx_Freeze\freezer.py", line 746, in Create
    module.file, module.name)
cx_Freeze.freezer.ConfigError: no file named sys (for module CoolProp.CoolProp.sys)
```

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/94

**Comment by anthony-tuininga** [comment]
*Original comment by* **Ian Bell (Bitbucket: [ibell](https://bitbucket.org/ibell), GitHub: [ibell](https://github.com/ibell))**:

----------------------------------------

This example works in 4.1.2.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Ian Bell (Bitbucket: [ibell](https://bitbucket.org/ibell), GitHub: [ibell](https://github.com/ibell))**:

----------------------------------------

This is caused by a bug in the handling of imports in cx_Freeze between python 2.7 and python 3.x.  It worked in 4.1.2 and I can't localize the regression.  But many projects are broken on py2.7 right now.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Ian Bell (Bitbucket: [ibell](https://bitbucket.org/ibell), GitHub: [ibell](https://github.com/ibell))**:

----------------------------------------

A second version with the import of Ph function

**Comment by anthony-tuininga** [comment]
*Original comment by* **Ian Bell (Bitbucket: [ibell](https://bitbucket.org/ibell), GitHub: [ibell](https://github.com/ibell))**:

----------------------------------------

The first one seems to work in the below environment, the second attached example does definitely not work and demonstrates the issue I have.  Everything is up to date.

```
[py27cx] C:\Users\Belli\Desktop\failing2>conda list -n py27cx
# packages in environment at C:\Miniconda\envs\py27cx:
#
coolprop                  4.2.3                     <pip>
cx-freeze                 4.3.3                     <pip>
numpy                     1.8.1                    py27_0
pip                       1.5.6                    py27_0
python                    2.7.8                         0
scipy                     0.14.0               np18py27_0
setuptools                3.6                      py27_0
wsgiref                   0.1.2                     <pip>
```

**Comment by anthony-tuininga** [comment]
*Original comment by* **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**:

----------------------------------------

I'm still investigating the actual error, but I've found a workaround, at least for this simple case: remove CoolProp from packages in the setup.py file. cx_Freeze automatically detects dependencies from imports - you should only need to specify them when the automatic detection fails.

You also have to remove the targetdir option from the Executable definition, or it puts the exe in a separate place from its associated libraries. That's a confusing option which I'm getting rid of for the next version of cx_Freeze.

I've attached a working version of setup.py.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**:

----------------------------------------

I think I found the issue - when `CoolProp.Plots.Common` imports `CoolProp.CoolProp`, on Python 2 that's handled as an implicit relative import. cx_Freeze sees that, and tries to walk up the package structure to find `CoolProp`. It finds it as the extension module in the `CoolProp` package, so it winds up thinking that `CoolProp.CoolProp.CoolProp` is a thing, and then the problems seem to multiply.

Pull request #59 fixes that. I suspect there may have been other bugs involved here, but... `bugs -= 1`.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Ian Bell (Bitbucket: [ibell](https://bitbucket.org/ibell), GitHub: [ibell](https://github.com/ibell))**:

----------------------------------------

That is pretty much what I was able to deduce from my debugging, but I wasn't able to figure out how to correct cx_Freeze's absolute/relative import confusion.  I'll try the PR and see what happens, and report on the result.  But I think you probably hit the nail on the head.

**Comment by marcelotduarte** [comment]
Closing due to inactivity. 
cx_Freeze 6.1 has just been released.
