### ISSUE TITLE
AttributeError: 'ModuleFinder' object has no attribute 'dist_cachedir' 

### ISSUE THREAD

**Issue by alphasierra59** [marcelotduarte/cx_Freeze#963]
Hello, I'm trying to build an application with the 6.6.dev0 build. I'm using the dev build because I encountered #919. 

Traceback end: 
```python
File "c:\users\XXX\appdata\local\programs\python\python39\lib\site-packages\cx_Freeze\freezer.py", line 719, in _WriteModules
    dist_cachedir = finder.dist_cachedir.name
AttributeError: 'ModuleFinder' object has no attribute 'dist_cachedir' 
```

<details>
<summary>Full Traceback</summary>

```python
Traceback (most recent call last):
  File "C:\Users\XXX\setup.py", line 14, in <module>
    setup(name='compiled_program',
  File "c:\users\XXX\appdata\local\programs\python\python39\lib\site-packages\cx_Freeze\dist.py", line 392, in setup
    distutils.core.setup(**attrs)
  File "c:\users\XXX\appdata\local\programs\python\python39\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "c:\users\XXX\appdata\local\programs\python\python39\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "c:\users\XXX\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "c:\users\XXX\appdata\local\programs\python\python39\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "c:\users\XXX\appdata\local\programs\python\python39\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "c:\users\XXX\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "c:\users\XXX\appdata\local\programs\python\python39\lib\site-packages\cx_Freeze\dist.py", line 260, in run
    freezer.Freeze()
  File "c:\users\XXX\appdata\local\programs\python\python39\lib\site-packages\cx_Freeze\freezer.py", line 776, in Freeze
    self._WriteModules(fileName, self.finder)
  File "c:\users\XXX\appdata\local\programs\python\python39\lib\site-packages\cx_Freeze\freezer.py", line 719, in _WriteModules
    dist_cachedir = finder.dist_cachedir.name
AttributeError: 'ModuleFinder' object has no attribute 'dist_cachedir' 
```
</details>

<details>
<summary>Package List</summary>

```
Package                   Version
------------------------- ---------
altgraph                  0.17
argon2-cffi               20.1.0
astroid                   2.4.2
async-generator           1.10
attrs                     20.3.0
backcall                  0.2.0
bleach                    3.3.0
cffi                      1.14.5
colorama                  0.4.4
cx-Freeze                 6.6.dev0
cycler                    0.10.0
decorator                 4.4.2
defusedxml                0.6.0
entrypoints               0.3
future                    0.18.2
importlib-metadata        3.7.0
ipykernel                 5.4.3
ipython                   7.20.0
ipython-genutils          0.2.0
ipywidgets                7.6.3
isort                     5.7.0
jedi                      0.18.0
Jinja2                    2.11.3
jsonschema                3.2.0
jupyter                   1.0.0
jupyter-client            6.1.11
jupyter-console           6.2.0
jupyter-core              4.7.1
jupyterlab-pygments       0.1.2
jupyterlab-widgets        1.0.0
kiwisolver                1.3.1
lazy-object-proxy         1.4.3
MarkupSafe                1.1.1
matplotlib                3.3.3
mccabe                    0.6.1
mistune                   0.8.4
nbclient                  0.5.2
nbconvert                 6.0.7
nbformat                  5.1.2
nest-asyncio              1.5.1
notebook                  6.2.0
numpy                     1.19.5
packaging                 20.9
pandas                    1.2.0
pandocfilters             1.4.3
parso                     0.8.1
pefile                    2019.4.18
pickleshare               0.7.5
Pillow                    8.1.0
pip                       21.0.1
prometheus-client         0.9.0
prompt-toolkit            3.0.16
pycparser                 2.20
Pygments                  2.8.0
pyinstaller               4.2
pyinstaller-hooks-contrib 2020.11
pylint                    2.6.0
pyparsing                 2.4.7
pyrsistent                0.17.3
pyserial                  3.5
python-dateutil           2.8.1
pythoncrc                 1.21
pytz                      2020.5
PyVISA                    1.11.3
pywin32                   300
pywin32-ctypes            0.2.0
pywinpty                  0.5.7
pyzmq                     22.0.3
qtconsole                 5.0.2
QtPy                      1.9.0
scipy                     1.6.0
Send2Trash                1.5.0
setuptools                49.2.1
six                       1.15.0
terminado                 0.9.2
testpath                  0.4.4
toml                      0.10.2
tornado                   6.1
traitlets                 5.0.5
typing-extensions         3.7.4.3
wcwidth                   0.2.5
webencodings              0.5.1
wheel                     0.36.2
widgetsnbextension        3.5.1
wrapt                     1.12.1
wxPython                  4.1.1
zipp                      3.4.1 
```

</details>

**Comment by marcelotduarte** [comment]
You're using git clone or installing direct from pip? What command?

If you have a C compiler, you can test the main version:
`pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@main`

**Comment by alphasierra59** [comment]
From [this](https://stackoverflow.com/questions/66080643/cx-freeze-throws-an-error-when-building-if-packages-are-involved) stackoverflow post:
``python -m pip install git+https://github.com/marcelotduarte/cx_Freeze.git``

**Comment by marcelotduarte** [comment]
Try to uninstall and install again, and close the issue if you get success.

**Comment by alphasierra59** [comment]
It was able to build a working executable this time. Was a change made or did the command I used grab the wrong branch?

**Comment by marcelotduarte** [comment]
Sometimes I see strange behavior in pip if you have an installed version from wheel and install from the source without cleanup.

**Comment by alphasierra59** [comment]
Cool, thanks for the prompt response! I just found cx_freeze but it seems to be working quite well so far.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.6 has just been released.
