### ISSUE TITLE
Why do I get "AttributeError: 'DarwinFile' object has no attribute 'machOReferenceDict'" when running cx_freeze script?

### ISSUE THREAD

**Issue by GrantDrinnen** [marcelotduarte/cx_Freeze#988]
Ive updated my cx_Freeze directory with all the updates added through today, 3/18/21 at 3:00PM. Im running Python 3.8, on a Mac M1.

When running the cx_freeze script to create the .exe file (python3.8 setup.py bdist_mac), the output shows the following error:  

```
File "/Users/grantdrinnen/opt/anaconda3/lib/python3.8/site-packages/cx_Freeze/macdist.py", line 309, in setRelativeReferencePaths
    for path, machORef in darwinFile.machOReferenceDict.items():
AttributeError: 'DarwinFile' object has no attribute 'machOReferenceDict'
```

The script does result in a non-functional .app file and build directory. When running the created distme unix executable file from within the build directory, I get the following errors: 

```
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'python3'
  isolated = 0
  environment = 0
  user site = 1
  import site = 0
  sys._base_executable = '/Users/grantdrinnen/Documents/Mail Merge App v1/build/exe.macosx-10.9-x86_64-3.8/distme'
  sys.base_prefix = ''
  sys.base_exec_prefix = ''
  sys.executable = '/Users/grantdrinnen/Documents/Mail Merge App v1/build/exe.macosx-10.9-x86_64-3.8/distme'
  sys.prefix = ''
  sys.exec_prefix = ''
  sys.path = [
    '/Users/grantdrinnen/Documents/Mail Merge App v1/build/exe.macosx-10.9-x86_64-3.8/lib/library.zip',
    '/Users/grantdrinnen/Documents/Mail Merge App v1/build/exe.macosx-10.9-x86_64-3.8/lib',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
Traceback (most recent call last):
  File "<frozen zipimport>", line 520, in _get_decompress_func
ImportError: dlopen(/Users/grantdrinnen/Documents/Employment/Professional Development/Python/Python Practice/Python Notebooks/Pay Summary Mail Merge Tool/Mail Merge App v1/build/exe.macosx-10.9-x86_64-3.8/lib/zlib.cpython-38-darwin.so, 2): Symbol not found: _PyExc_MemoryError
  Referenced from: /Users/grantdrinnen/Documents/Mail Merge App v1/build/exe.macosx-10.9-x86_64-3.8/lib/zlib.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/grantdrinnen/Documents/Mail Merge App v1/build/exe.macosx-10.9-x86_64-3.8/lib/zlib.cpython-38-darwin.so

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen zipimport>", line 568, in _get_data
  File "<frozen zipimport>", line 523, in _get_decompress_func
zipimport.ZipImportError: can't decompress data; zlib not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/grantdrinnen/opt/anaconda3/lib/python3.8/encodings/__init__.py", line 31, in <module>
  File "<frozen zipimport>", line 241, in load_module
  File "<frozen zipimport>", line 709, in _get_module_code
  File "<frozen zipimport>", line 570, in _get_data
zipimport.ZipImportError: can't decompress data; zlib not available
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

**Comment by marcelotduarte** [comment]
cx_Freeze 6.6 has just been released.
Can you check if this has been resolved?

**Comment by marcelotduarte** [comment]
cx_Freeze 6.7b2 has just been released.
pip install cx-Freeze==6.7b2

**Comment by marcelotduarte** [comment]
Closing due to lack of response.
If you had issues please open a new issue.
